### ISSUE TITLE
ShapefileDataReader cannot read encoding from Streams in some cases

### ISSUE THREAD

**Issue by senritsu** [NetTopologySuite/NetTopologySuite#104]
**Status quo**
Currently the `ShapefileDataReader` takes a `IStreamProviderRegistry`, which in turn only supports the 3 `StreamTypes` of `Shape`, `Data` and `Index`. The `DbaseFileHeader` later reads the encoding from the dbf header and tries to find a .cpg file as a fallback if the provided streams are `FileStream`s. 

**Problem**
While the ShapefileDataReader currently works fine with MemoryStreams with some manual work (or the patch supplied in #91), there is no way to specify the encoding if it isn't set in the dbf header directly. QGIS for example sets the header byte to `0x00` and writes the encoding to the .cpg by default. It is currently not possible to supply a .cpg `Stream` to the `ShapefileDataReader`, so the input files will be read as UTF8 no matter what the actual encoding is.

For `FileStream`s this is not an issue, as the `DbaseFileHeader` tries to find the .cpg file on the filesystem, which fails for `MemoryStream`s for obvious reasons.

**Possible solutions**

- Add the encoding as an additional parameter to the `ShapefileDataReader` constructor. Setting it after construction has no effect because the read streams are opened in the constructor with the encoding set at the time. The field names are also read as soon as the `DbaseFileHeader` initially reads the header from the dbf stream.
- Expand the IStreamProviderRegistry to support .cpg streams (.prj might also be a good idea, but a different matter)

*Option 1a*
The first option would be fairly straightforward. An optional encoding parameter would be added to `ShapefileDataReader.ctor`, `DbaseFileReader.GetHeader` and `DbaseFileHeader.ReadHeader` and passed through to the latter. Inside of `DbaseFileHeader.ReadHeader` the part where it tries to read the encoding from the .dbf or .cpg would be changed to accommodate the encoding parameter if one is supplied. Passing through the parameter is not the prettiest solution, but the execution flow at the moment makes it hard to get in the encoding any other way, at least if it should be in time for the reading of the field names. 

*Option 1b, ignore field names*
When disregarding field names (which are often ascii abbreviations anyways due to the severe limit on length), setting the encoding directly in the `ShapefileDataReader` after the header is retrieved might be enough. This would reduce the number of changes to one additional ctor parameter for `ShapefileDataReader` and 2 lines of checking if the parameter is supplied and subsequently setting the encoding of the header.

*Option 2*
The second option would probably require a number of changes to the way the dbf file is read, and is therefore less desirable without some very good reasons.

**Comment by FObermaier** [comment]
Is this issue resolved?

**Comment by senritsu** [comment]
From the looks of the commit it should be, but i didn't have an opportunity to test it yet in our application.
