### ISSUE TITLE
DotSpatial integration

### ISSUE THREAD

**Issue by mogikanin** [NetTopologySuite/NetTopologySuite#107]
Hi guys,

recently we moved DotSpatial into [github](https://github.com/DotSpatial/DotSpatial) too.
And we decided to switch to nts\geoapi instead of using dotspatial.topology.
At the moment we simply forked NTS & GeoAPI repos. But in fact there are a very little changes which needed for DS. 
https://github.com/DotSpatial/GeoAPI/commit/9b63fe8ef802f8d81edc78ffaa51ac45f3ccd17b and
https://github.com/DotSpatial/NetTopologySuite/commit/ddfa534bd8b5f3615c19d78509842219d08aee2c

It would be great if you include these changes into official NTS repo. In this case we simply add reference to latest NTS and everything will be fine. Otherwise we have to update these 2 forks on every NTS release. This really not hard for us, but this might confuse users, since these forks also be on nuget with ids DotSpatial.GeoAPI\NTS, and I'm sure also will be some problems in projects where used both DotSpatial and original NTS.

What do you think?

**Comment by DGuidi** [comment]
I take a quick look and looks DotSpatial uses XYZM ordinates as default.
This can be a not-so-little change for NTS, at least for performaces purposes. 
No problem for additional methods.
My2Cents.

**Comment by mogikanin** [comment]
yes, main change is in adding 4-d ordinate M. 
performance leak will be only in creation a lot of Coordinates. It's about +30% per time, and +8 bytes 
per each instance. I've created a simple test to verify it. http://pastebin.com/NMHytp5f
On my old PC it's 1.7s vs 2.5s for 1e7 coordinates.
Other operations like iterating items will take mostly the same time since Coordinate is class.

So, the difference will be tangible when user creates more than 1e7 elements at once, and anyways for such cases better to use structs.

**Comment by DGuidi** [comment]
@mogikanin maybe the default xyzm can be handled using specific coordinatesequecefactory?
@FObermaier what do you think about?

**Comment by mogikanin** [comment]
can you explain idea with coordinatesequecefactory?

**Comment by airbreather** [comment]
If I were doing something big that required XYZM, I'd start by making a subclass of [Coordinate](https://github.com/NetTopologySuite/GeoAPI/blob/master/GeoAPI/Geometries/Coordinate.cs) that adds the storage for M, implement [ICoordinateSequenceFactory](https://github.com/NetTopologySuite/GeoAPI/blob/master/GeoAPI/Geometries/ICoordinateSequenceFactory.cs) / [ICoordinateSequence](https://github.com/NetTopologySuite/GeoAPI/blob/master/GeoAPI/Geometries/ICoordinateSequence.cs) and make that the [default](https://github.com/NetTopologySuite/GeoAPI/blob/330e437feb166d2e066c19bebf330cd5400a9beb/GeoAPI/IGeometryServices.cs#L26-L29).

I wouldn't be surprised to find something in NTS / GeoAPI that loses the extra data where it "shouldn't", but I would look at them on a case-by-case basis as they come up.  The JTS mailing list occasionally gets some traffic along these lines, so maybe Martin might be able to speak to this more.

I would **not** change the built-in default types in NTS / GeoAPI, for two reasons:

1. JTS doesn't do it like this; it would be potentially an ongoing maintenance nightmare to have NTS differ from JTS in this fundamental way.
2. Existing things using NTS / GeoAPI would take a significant performance hit when upgrading to this.  Those most affected by this change are using a Coordinate array sequence and probably "ought to" look into switching to a packed coordinate sequence type or a custom one of some sort, but I'm concerned about those applications where it's borderline "good enough" / "OK" as-is, but increasing the size of Coordinate by a factor of one-third would hurt.  Even for those who currently use other sequence types, if they're not careful, it's [very possible](https://github.com/NetTopologySuite/NetTopologySuite/blob/51deaa362bdf737e9622de52ea52ac41eca8ca61/NetTopologySuite/Algorithm/Locate/IndexedPointInAreaLocator.cs#L106-L112) for Coordinate instances to [sneak](https://github.com/NetTopologySuite/NetTopologySuite/blob/51deaa362bdf737e9622de52ea52ac41eca8ca61/NetTopologySuite/Geometries/Prepared/PreparedPolygon.cs#L64) into your heap and stick around for longer than the scope of an operation.

**Comment by FObermaier** [comment]
There already is an ICoordinateSequence/ICoordinateSequenceFactory implementation that plays nicely with DotSpatial shapes:
https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite/Geometries/Implementation/DotSpatialAffineCoordinateSequence.cs
https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite/Geometries/Implementation/DotSpatialAffineCoordinateSequenceFactory.cs

Ugly names but IIRC they have a lower memory footprint and performed a little better than default `CoordinateSequence`. Like @airbreather I'm not in favor of changing `Coordinate` class as long as JTS does not do it.

**Comment by DGuidi** [comment]
> JTS doesn't do it like this; it would be potentially an ongoing maintenance nightmare to have NTS differ from JTS in this fundamental way.

to me, this is the main issue with this request. I'd like to have NTS as close as possible with JTS, so I perfectly agree with you

**Comment by mogikanin** [comment]
Ok, thanks for explanation. For now, we decided to use & maintain own forks of NTS\GeoAPI. This is a simplest solution for us.

**Comment by FObermaier** [comment]
> Ok, thanks for explanation. For now, we decided to use & maintain own forks of NTS\GeoAPI. This is a simplest solution for us.

I doubt that this is the best and fastest way to go. Anyhow, be sure to 
- notice where the original work was done and what your "extensions" are. The currently provided `DotSpatial.Topology` lacks that information.
- report issues and fixes.

**Comment by DGuidi** [comment]
@mogikanin so I can close this issue?

**Comment by mogikanin** [comment]
Yes
