### ISSUE TITLE
Integrate latest JTS changes

### ISSUE THREAD

**Issue by DGuidi** [NetTopologySuite/NetTopologySuite#108]
Check [svn repo](https://sourceforge.net/p/jts-topo-suite/code/HEAD/tree/trunk/) and [git repo](https://github.com/dr-jts/jts/commits/master), then integrate changes.
Note that JTS changes after [JTS rev.1087](https://github.com/NetTopologySuite/NetTopologySuite/commit/a7831571ca9afd340d0d05ada07f084ab9657ef9) should be integrated too

**Comment by FObermaier** [comment]
Duplicate with #35
