### ISSUE TITLE
Strong Assembly Name

### ISSUE THREAD

**Issue by tlaguz** [NetTopologySuite/NetTopologySuite#109]
Can NetTopologySuite be signed with strong assembly name?
This would allow libraries referencing it to be strong named as well.

I have found this related issue:
http://forums.devart.com/viewtopic.php?f=1&t=32705

**Comment by DGuidi** [comment]
Happy to see some products using NTS, like Devart.Data.Oracle.Entity.Spatials.
String Naming is an annoying thing, actually: in the past NTS was a signed assembly, but this kind of support was removed.
I don't remember the exact problems we have occurred: maybe you can try to build your own signed assembly, for PCL stuff as example.

**Comment by tlaguz** [comment]
@DGuidi thanks for fast response!

I asked because weak named assemblies prevent msbuild from copying references with library which referenced them.
When for example Database assembly references NetTopologySuite, then all tests libraries that reference Database have to reference NetTopologySuite, because NTS is not copied automatically to test bin directory.

I can sign assembly on my own and publish it to private nuget server in our company, but won't I break yours license terms then?

**Comment by DGuidi** [comment]
> but won't I break yours license terms then?

I don't think this can be a problem, LGPL terms allow this, I suppose.
Anyway, why simply you don't add a MSBuild/Copy operation that copy all references to outpath?
