### ISSUE TITLE
WpfGeometryReader Creates Self-Intersecting Polygons

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#11]
Not sure how high a priority NetTopologySuite.Windows.Media is to you guys, or even how complete it's supposed to be at this point considering that it doesn't go out to NuGet, but I was browsing the code and was interested to see how NTS handled the problem of creating topologically valid geometries when [PathFigure.FillRule](http://msdn.microsoft.com/en-us/library/system.windows.media.pathgeometry.fillrule(v=vs.110).aspx) is EvenOdd.

Turns out it doesn't, and so WpfGeometryReader can easily create self-intersecting polygons which are not topologically valid.

When working on something similar for our application (JTS using J#, not NTS, sorry), I stumbled upon [this post](http://sourceforge.net/p/jts-topo-suite/mailman/message/32589557/) ([gist](https://gist.github.com/dbaston/d3f8f873f8b9e10569e3)) that happened to solve the fundamental problem on the JTS side.  Porting the Java to C# and optimizing it a little, this seemed to work as expected (at least on [this sample](https://gist.github.com/airbreather/f3a63abc8464fda34d6b), where the LINESTRING is the screen coordinates of a particularly complex figure I drew with a prototype version of our lasso tool).

Obviously, if FillRule was NonZero, then the solution would be much simpler: just combine all the polygons from the Polygonizer.

Hope this helps.  Feel free to close this if that assembly isn't something anyone's supposed to bother looking at right now.

Update: realized I didn't post a link to [this](http://sourceforge.net/p/jts-topo-suite/mailman/message/27724837/), which was what started me on "how do I apply the Even/Odd rule to the output of Polygonizer?".

**Comment by DGuidi** [comment]
@airbreather sorry, are you working on this?

**Comment by airbreather** [comment]
@DGuidi no, not right now.

**Comment by FObermaier** [comment]
@airbreather, please have a look at [this] (https://github.com/NetTopologySuite/NetTopologySuite/blob/10a2a5cf354863eebd3e91dc550e108d4980a1ea/NetTopologySuite.Windows.Forms/Test/BasicTestMedia.cs#L46) test and tell me if the results are what you expect.

**Comment by airbreather** [comment]
@FObermaier: the results do seem to be as expected.  As an aside, the test might be more useful if you were to pick a few points and ensure that the WPF geometry's FillContains predicate matches up with the NTS geometry's Covers predicate.

It might look something like this:

    Assert.AreEqual(pathGeometry.FillContains(new WpfPoint(25, 50)), geomNonzero.Covers(Geometries.GeometryFactory.Default.CreatePoint(new Coordinate(25, 50))));

**Comment by airbreather** [comment]
For quick reference, the inputs and outputs of the test are as follows, for quick copy/pasting into OpenJUMP which is how I verified.

Input
----

    LINESTRING(15 0,50 100,85 0,0 65,100 65,15 0)

EvenOdd Output
----

    MULTIPOLYGON (((37.75 65, 29.77958237 42.22737819, 0 65, 37.75 65)), ((15 0, 29.77958237 42.22737819, 50 26.76470588, 15 0)), ((37.75 65, 50 100, 62.25 65, 37.75 65)), ((70.22041763 42.22737819, 85 0, 50 26.76470588, 70.22041763 42.22737819)), ((70.22041763 42.22737819, 62.25 65, 100 65, 70.22041763 42.22737819)))

NonZero Output
----

    POLYGON ((15 0, 29.77958237 42.22737819, 0 65, 37.75 65, 50 100, 62.25 65, 100 65, 70.22041763 42.22737819, 85 0, 50 26.76470588, 15 0))
