### ISSUE TITLE
Exception thrown, MultiLineHandler.cs, Ln133

### ISSUE THREAD

**Issue by Git2263** [NetTopologySuite/NetTopologySuite#111]
MultiLineHandler.cs, Ln133:
IMultiLineString multi;
if (geometry is IGeometryCollection)
multi = (IMultiLineString)geometry;
else
multi = factory.CreateMultiLineString(new[] { (ILineString)geometry });
Debug ----------------------------------------------
Exception thrown: 'System.InvalidCastException' in NetTopologySuite.IO.GeoTools.dll
An unhandled exception of type 'System.InvalidCastException' occurred in NetTopologySuite.IO.GeoTools.dll

Unable to cast object of type 'NetTopologySuite.Geometries.GeometryCollection' to type 'GeoAPI.Geometries.IMultiLineString'

**Comment by DGuidi** [comment]
can you post some sample code that throws the error?
actually, the code should be ok because IMultiLineString implements IGeometryCollection, and this code should be called only when you have a IMultiLineString or a ILineString...
so I'm interested to see when this exception is actually thrown.

**Comment by Git2263** [comment]
var shapeFileType = Shapefile.GetShapeType(geometries);
var sfw = new ShapefileWriter(Path.GetFileNameWithoutExtension(shapepath), shapeFileType);
sfw.Write(geometries);

**Comment by DGuidi** [comment]
@Git2263 ok this is clear, but I suspect that problem lies in data into shapefile. 
can you post a link where I can download shapefile?

**Comment by FObermaier** [comment]
@DGuidi: He wants to write some Shapefile. I think he has some geometries, one of which is not a `MultiLineString` but a plain `GeometryCollection`, Maybe `GEOMETRYCOLLECTION EMPTY`?
That is why the shapefile handler is failing.

**Comment by DGuidi** [comment]
@FObermaier yep, you're right. my bad, I can try to build a unit test soon.

**Comment by DGuidi** [comment]
@FObermaier the problem, to me, lies in [ShapeFile.GetNonEmptyGeometry](https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite.IO/NetTopologySuite.IO.GeoTools/Shapefile.cs#L124) that tests only the first geom of a collection. Make sense to check all geometries, at least for consistency?
