### ISSUE TITLE
Reading shape files

### ISSUE THREAD

**Issue by trailway** [NetTopologySuite/NetTopologySuite#112]
I recently encountered some shape files which the reader does not handle.  It can be debated whether the files are correct but they do work in ArcMap!  What happens is that the content length does not include M content which is present (although it's presence is benign because the value says that it is not meaningful).  This makes the reader fail because it walks through shape geometry using content length, i.e. it expects the next element to begin at the location just after the location where the previous element ended.  This  works in ArcMap because they use the shape index.  I think that using the shape index (which is a required file) is a more stable approach.

**Comment by DGuidi** [comment]
can you post some sample data that actually show this failure?

**Comment by trailway** [comment]
Sample data:

[Matt.zip](https://github.com/NetTopologySuite/NetTopologySuite/files/378760/Matt.zip)

**Comment by DGuidi** [comment]
Thanks for sharing this :)
 Hope to take a look as soon as possible.

----- Messaggio originale -----
Da: "trailway" <notifications@github.com>
Inviato: ‎22/‎07/‎2016 19:22
A: "NetTopologySuite/NetTopologySuite" <NetTopologySuite@noreply.github.com>
Cc: "Diego Guidi" <diegoguidi@gmail.com>; "Comment" <comment@noreply.github.com>
Oggetto: Re: [NetTopologySuite/NetTopologySuite] Reading shape files (#112)

Sample data:
Matt.zip

**Comment by airbreather** [comment]
This issue was moved to NetTopologySuite/NetTopologySuite.IO.ShapeFile#5
