### ISSUE TITLE
Point.M not supported

### ISSUE THREAD

**Issue by becio** [NetTopologySuite/NetTopologySuite#113]
I found out that Point.M is not supported, it always returns NaN, why ?

**Comment by DGuidi** [comment]
yep, [this code](https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite/Geometries/Point.cs#L392) looks wrong... try using Point.Coordinate.M directly

**Comment by becio** [comment]
Nope, Coordinate does not support it either https://github.com/NetTopologySuite/GeoAPI/blob/master/GeoAPI/Geometries/Coordinate.cs#L429

**Comment by DGuidi** [comment]
try check a sample like 'ExtractLinestringByMeasure'
