### ISSUE TITLE
Census TIGER shapefiles cannot be read with Shapefile.CreateDataTable

### ISSUE THREAD

**Issue by JoelFeiner** [NetTopologySuite/NetTopologySuite#115]
The issue seems to be small one.

Using the files contained in this zipfile as a test: [ftp://ftp2.census.gov/geo/tiger/TIGER2015/TRACT/tl_2015_01_tract.zip](ftp://ftp2.census.gov/geo/tiger/TIGER2015/TRACT/tl_2015_01_tract.zip)

I get an exception in ShapefileDataReader.GetValues(). The array passed in is one larger than the number of columns in the data reader. The reason for this seems to be that the data reader considers the geometry object to be one of the columns, but of course the _columnValues array does not contain it. It only contains data for the other columns in the shapefile. I dealt with this by making my own version of CreateDataTable, that looks like this:

```
public static DataTable CreateDataTable(string filename, string tableName, GeometryFactory geometryFactory) {
    if(filename == null)
        throw new ArgumentNullException("filename");
    if(tableName == null)
        throw new ArgumentNullException("tableName");
    if(geometryFactory == null)
        throw new ArgumentNullException("geometryFactory");
    ShapefileDataReader shapefileDataReader = new ShapefileDataReader(filename, geometryFactory);
    DataTable dataTable = new DataTable(tableName);
    IEnumerator enumerator = shapefileDataReader.GetEnumerator();
    enumerator.MoveNext();
    foreach(object property in ((ICustomTypeDescriptor)enumerator.Current).GetProperties()) {
        Type propertyType = property.GetProperty<Type>("PropertyType");
        DataColumn column = new DataColumn(property.GetProperty<string>("Name"), propertyType);
        if(propertyType == typeof(string))
            column.MaxLength = property.GetProperty<int>("Length");
        dataTable.Columns.Add(column);
    }
    // this section is changed from the original
    int num = 0;
    object[] values = new object[shapefileDataReader.FieldCount - 1];
    object[] allValues = new object[shapefileDataReader.FieldCount];
    do {
        ++num;
        shapefileDataReader.GetValues(values);
        // place geometry object into first column to match schema of data table
        allValues[0] = shapefileDataReader.Geometry.AsBinary();
        Array.Copy(values, 0, allValues, 1, values.Length);
        dataTable.Rows.Add(allValues);
    }
    while(enumerator.MoveNext());
    return dataTable;
}
```

Note that `GetProperty<>()` is an extension method I have that can get the value of a property by name via reflection. This was needed because the actual object type returned by `GetProperties()` is an internal class.

I don't know what the right answer is here, so I don't want to propose a solution. But there is a bug somewhere, one way or another.

**Comment by FObermaier** [comment]
I must admit I have not used this functionality at all. To me there are a couple of questions to resolve:
* What is the expected behavior?
  * Do you need the geometry definition in the data table at all?
  * If you need it, do you need the geometry, its `WellKnown[Text|Binary]` or sth else,
  * is the geometry column at index 0 the right position?
* The record id is not returned at all, isn't that important, too?

**Comment by JoelFeiner** [comment]
The expected behavior is not to get an array out of bounds exception. That is, I should be able to call CreateDataTable() without error. So that bug needs to be fixed.

It would seem to me that the data table should return all columns in the shapefile, including the geometry/geography column. It appears that that is the intent, but the structure of ShapefileReader is to have the geometry object stored separately from the other columns. These are not combined into a single row of data when it's time for that to happen.

More specific answers to your questions:
* I do think the geometry data should be included. The shapefile isn't useful without it.
* I don't know that I care what format it is stored in. The existing code creates a byte[] column, so that would imply WKB. The actual geometry instance (whatever class implements IGeometry) would also make sense, and then it could be converted as needed by the user.
* It should be either at the start or the end. I can't think of a justification for putting it in the middle.
* I'm not sure what the record ID is in this case. I don't see why it shouldn't be included, though.

**Comment by airbreather** [comment]
@JoelFeiner have you tried this again after the series of commits that @FObermaier made around September 12, 2016?

**Comment by airbreather** [comment]
The following code outputs meaningful values without throwing any exceptions on the latest prerelease packages available on MyGet, and I haven't gotten any response to my previous inquiry, so I'm closing this.

```csharp
using System;

using GeoAPI.Geometries;
using NetTopologySuite.Geometries;
using NetTopologySuite.IO;

namespace ConsoleApp1
{
    internal static class Test
    {
        private static void Main()
        {
            using (var reader = new ShapefileDataReader(@"C:\Temp\tl_2015_01_tract\tl_2015_01_tract.shp", GeometryFactory.Default))
            {
                object[] values = new object[reader.FieldCount];
                while (reader.Read())
                {
                    reader.GetValues(values);
                    Console.WriteLine(((IGeometry)values[0]).NumPoints);
                }
            }
        }
    }
}
```
