### ISSUE TITLE
Any example how to work with sanp

### ISSUE THREAD

**Issue by am2222** [NetTopologySuite/NetTopologySuite#116]
Hi,
I am working on a way to perform snapping on windows application,I saw this functions `https://github.com/NetTopologySuite/NetTopologySuite/tree/master/NetTopologySuite/Operation/Overlay/Snap` so..How can I use these functions?Does it even helps me?

thanks

**Comment by FObermaier** [comment]
This is a utility class for overlay operations. I'm almost sure it won't help you.

**Comment by am2222** [comment]
thank so much for your help.So what is its usage?Is there any hints how can I do snapping?any algorithms or ideas..I am currently using sharpmap..I thought I can manage to do that using this algorithms
