### ISSUE TITLE
Roundtrip Serializing/Deserializing a Feature fails

### ISSUE THREAD

**Issue by DustinReagan** [NetTopologySuite/NetTopologySuite#120]
See this StackOverflow [link ](http://stackoverflow.com/questions/39155975/serializing-deserializing-a-roundtrip-with-nettopologysuites-io-library-for-geo) for details.

**Comment by DGuidi** [comment]
the presence of `\"properties\":null` looks the cause of the bug.

**Comment by DGuidi** [comment]
fixed. can you check if this fix resolve your issues?
anyway, thanks for reporting this :)

**Comment by FObermaier** [comment]
@DGuidi: The question is where does `"properties":null` come from in the first place? Was that created by the GeoJsonWriter and if so, does that conform to the json/geojson standard.

**Comment by DGuidi** [comment]
@FObermaier heres' my thoughts

1. good question: issue doesn't provide initial feature object used in with GeoJSONWriter, but I can make some additional checks.

2. [GeoJSON specs](http://geojson.org/geojson-spec.html#feature-objects) explicitly allows `null`

> a feature object must have a member with the name "properties". The value of the properties member is an object (any JSON object or a **JSON null value**).

**Comment by DGuidi** [comment]
@DustinReagan can you provide a sample code that generates a GeoJSON with `\"properties\":null`?
I've made some checks and I'm unable to generate a similar json using GeoJSONWriter

**Comment by DustinReagan** [comment]
> @DustinReagan can you provide a sample code that generates a GeoJSON with \"properties\":null?
I've made some checks and I'm unable to generate a similar json using GeoJSONWriter

@DGuidi Sure:

`Geometry geometry = SomeMethodThatCreatesAGeometry();
Feature feature = new Feature(geometry, null);`

Thanks for looking into this bug.  For now, I've just resolved my issue by doing:

`Feature feature = new Feature(geometry, new AttributeTable());`

**Comment by DGuidi** [comment]
Tried code like this but geojson writer doesn't produce a json string but throws exception, at least using latest master.
I give some other checks soon. Thanks again.

----- Messaggio originale -----
Da: "Dustin Reagan" <notifications@github.com>
Inviato: ‎26/‎08/‎2016 21:18
A: "NetTopologySuite/NetTopologySuite" <NetTopologySuite@noreply.github.com>
Cc: "Diego Guidi" <diegoguidi@gmail.com>; "Mention" <mention@noreply.github.com>
Oggetto: Re: [NetTopologySuite/NetTopologySuite] RoundtripSerializing/Deserializing a Feature fails (#120)

@DustinReagan can you provide a sample code that generates a GeoJSON with \"properties\":null?
I've made some checks and I'm unable to generate a similar json using GeoJSONWriter
@DGuidi Sure:
Geometry geometry = SomeMethodThatCreatesAGeometry();
Feature feature = new Feature(geometry, null);
Thanks for looking into this bug. For now, I've just resolved my issue by doing:
Feature feature = new Feature(geometry, new AttributeTable());

**Comment by FObermaier** [comment]
With 243ede3e9e6d8f52e87f2aedf476e8a3fc802e93 the following improvements have been made to the converter objects:
- when serializing, they obey to `JsonSerializer.NullValueHandling`
- when deserializing, they don't fail when encountering null tokens.
