### ISSUE TITLE
Open a shapefile which contains faulty data

### ISSUE THREAD

**Issue by laetitiamh** [NetTopologySuite/NetTopologySuite#121]
Hi!

I am trying to open a shapefile that contains building outlines using NetTopologySuite.IO.ShapefileReader.
I only get around 700 of the 5000+ buildings as a result as the reading stops early because of a faulty linear ring "Number of points must be 0 or >3". This shapefile is automatically generated and contains some errors. I can open the same file in a tool like http://mapshaper.org/ and I can see all the outlines.

The ShapefileEnumerator::MoveNext will return false when it encounters such an exception and as a result the ShapeFileReader::ReadAll will abort the foreach loop.
Could we specifiy as an option to the ShapefileReader to continue reading until the end of the file even when it finds faulty geometries? 

Thank you very much!

**Comment by laetitiamh** [comment]
Any comment on this issue? Thanks!

**Comment by axmand** [comment]
I have the same problem, the source code like below:
https://github.com/synhershko/nettopologysuite/blob/2440df92a2705755b4fd25e5124ac0781df324b9/NetTopologySuite/Geometries/LinearRing.cs#L52
```
new LineRing(points)
```
will be call ValidateConstruction funciton ,then throw this error.i think this problem can be resolve by add a property such as "ForceIgnoreValidateConstruction:true".

**Comment by airbreather** [comment]
This issue was moved to NetTopologySuite/NetTopologySuite.IO.ShapeFile#6
