### ISSUE TITLE
polygon intersection error

### ISSUE THREAD

**Issue by sendreams** [NetTopologySuite/NetTopologySuite#122]
Steps to reproduce

two polygon, coordates is below: {LINEARRING (0.0000000000000000 -6.1026585365860800, 3.8000000000000000 -5.7690000000000000, 7.9000000000000000 -5.4090000000000000, 12.0000000000000000 -5.3690000000000000, 16.1000000000000000 -5.0990000000000000, 20.3000000000000000 -5.1390000000000000, 24.5000000000000000 -4.9090000000000000, 28.5000000000000000 -4.6390000000000000, 32.6000000000000000 -4.1890000000000000, 36.6000000000000000 -3.2890000000000000, 40.8000000000000000 -3.1890000000000000, 44.8000000000000000 -2.9490000000000000, 49.0000000000000000 -2.8200000000000000, 53.3000000000000000 -2.3600000000000000, 57.3000000000000000 -2.1400000000000000, 61.3000000000000000 -1.5200000000000000, 65.5000000000000000 -1.3900000000000000, 69.6000000000000000 -1.1700000000000000, 73.6000000000000000 -1.0100000000000000, 77.9000000000000000 -0.9700000000000000, 82.0000000000000000 -0.8000000000000000, 86.2000000000000000 -0.7400000000000000, 90.2000000000000000 -0.6700000000000000, 94.5000000000000000 -0.6000000000000000, 98.6000000000000000 -0.5000000000000000, 102.6000000000000000 -0.3900000000000000, 106.9000000000000000 -0.2400000000000000, 111.1000000000000000 -0.1500000000000000, 115.1000000000000000 -0.1510000000000000, 119.2000000000000000 -0.1510000000000000, 123.1000000000000000 -0.0510000000000000, 127.2000000000000000 0.0590000000000000, 131.2000000000000000 0.2090000000000000, 132.2000000000000000 1.0250000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 0.5000000000000000, 128.6000000000000000 0.5000000000000000, 106.2000000000000000 -2.3000000000000000, 49.9000000000000000 -2.3000000000000000, 31.0000000000000000 -5.4500000000000000, 0.0000000000000000 -5.4500000000000000, 0.0000000000000000 -6.1026585365860800)}
{LINEARRING (0.0000000000000000 2.6400000000000000, 0.0000000000000000 -6.0030697674418800, 0.3200000000000000 -5.9800000000000000, 4.6200000000000000 -5.6700000000000000, 8.8100000000000000 -5.1600000000000000, 13.1000000000000000 -5.2100000000000000, 17.1200000000000000 -4.8400000000000000, 21.2800000000000000 -5.1700000000000000, 25.5000000000000000 -5.1600000000000000, 29.7100000000000000 -4.6700000000000000, 34.1300000000000000 -3.9000000000000000, 38.2800000000000000 -3.4800000000000000, 42.6400000000000000 -3.3000000000000000, 46.9800000000000000 -3.2600000000000000, 51.1600000000000000 -2.8900000000000000, 55.3200000000000000 -2.8300000000000000, 59.3000000000000000 -2.9200000000000000, 63.6800000000000000 -2.3600000000000000, 67.4800000000000000 -2.5700000000000000, 70.8900000000000000 -2.4800000000000000, 74.8900000000000000 -2.5500000000000000, 78.8800000000000000 -2.6900000000000000, 82.4400000000000000 -2.4600000000000000, 87.5300000000000000 -2.8100000000000000, 91.6200000000000000 -2.7500000000000000, 95.9000000000000000 -2.1000000000000000, 100.2200000000000000 -2.2100000000000000, 104.4400000000000000 -2.3000000000000000, 109.1500000000000000 -1.9500000000000000, 113.2400000000000000 -2.8200000000000000, 117.2400000000000000 -1.9600000000000000, 120.9400000000000000 -1.3000000000000000, 125.0300000000000000 -0.8200000000000000, 126.6800000000000000 0.1300000000000000, 132.5500000000000000 1.5400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 0.0000000000000000 2.6400000000000000)}
2. invoke polygon's intersection function, will throw exception
3. the exception stack & message: 
found non-noded intersection between LINESTRING(3.8 -5.769, 7.9 -5.409) and LINESTRING(31 -5.45, 6.4274509803921562 -5.45) [ (7.4330555555555522, -5.45, NaN, NaN) ]

在 NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.GetResultGeometry(SpatialFunction opCode)
在 NetTopologySuite.Geometries.Geometry.Intersection(IGeometry other)
在 Ware4u.Geomatics.Section.DotSpatialTest.Clip(GeoRegion region1, GeoRegion region2) 位置 C:\Users\hong\Documents\Visual Studio 2015\Projects\Ware4u.Geomatics\Ware4u.Geomatics.Section\DotSpatialTest.cs:行号 23

DotSpatial version: 1.9

Expected behaviour

the intersection of two polygon, may be one or more ploygons.

Actual behaviour

throw exception.

net framework 4.0,
win10 ent 64. 
vs2015,

**Comment by FObermaier** [comment]
Not valid with current source:
![tmp1595](https://cloud.githubusercontent.com/assets/2065346/18386207/b4715180-7695-11e6-831b-ca61c77a9b26.png)

Note: You are not intersecting two polygons, you are intersecting two linear rings, thus your result cannot be a polygon, your result may consist of lines and points. in this case it is:
`GEOMETRYCOLLECTION (POINT (6.4274509803921562 -5.45), POINT (20.648577770189519 -5.1199112173467647), POINT (32.2515 -4.2272500000000006), POINT (33.042227171492208 -4.0894988864142539), POINT (43.973756097560972 -3.2877073170731705), POINT (94.583076923076931 -2.3), POINT (104.44 -2.3), POINT (108.78010471204188 -1.977486910994765), POINT (126.52524168574122 0.04089672815403271), POINT (127.80842883548985 0.40105360443623261), POINT (132.31348298854311 1.4831875662428937), POINT (132.6 2.64), LINESTRING (0 -5.45, 0 -6.00306976744188))`

**Comment by sendreams** [comment]
@FObermaier can you please tell me what the diff between linear rings and polygon, i have confused about them.
another question: in your snap picture, how can you render the geometries ? use SharpMap or any other?

**Comment by sendreams** [comment]
my really point is get the intersect region between two polygon, like this picture.
<img width="329" alt="snap2" src="https://cloud.githubusercontent.com/assets/4160051/18392822/d6598c22-76e5-11e6-8a9b-b182e0ea1f63.png">
how can i do it?

**Comment by FObermaier** [comment]
A `LINEARRING` is a special form of a `LINESTRING`. It is lineal, closed and has at least 4 coordinates or, when empty, 0. A `POLYGON` is an aereal geometry. The exterior ring of a `POLYGON` is made up of a 'LINEARRING'.

**Comment by DGuidi** [comment]
some useful resources [here](https://en.wikipedia.org/wiki/Simple_Features)

**Comment by sendreams** [comment]
@FObermaier  do you know any open source library can intersection two polygon? i need the polygon result. thanks.

**Comment by FObermaier** [comment]
You are using the __right library__ but the __wrong geometries__:
Try intersecting 
```
POLYGON ((0.0000000000000000 -6.1026585365860800, 3.8000000000000000 -5.7690000000000000, 7.9000000000000000 -5.4090000000000000, 12.0000000000000000 -5.3690000000000000, 16.1000000000000000 -5.0990000000000000, 20.3000000000000000 -5.1390000000000000, 24.5000000000000000 -4.9090000000000000, 28.5000000000000000 -4.6390000000000000, 32.6000000000000000 -4.1890000000000000, 36.6000000000000000 -3.2890000000000000, 40.8000000000000000 -3.1890000000000000, 44.8000000000000000 -2.9490000000000000, 49.0000000000000000 -2.8200000000000000, 53.3000000000000000 -2.3600000000000000, 57.3000000000000000 -2.1400000000000000, 61.3000000000000000 -1.5200000000000000, 65.5000000000000000 -1.3900000000000000, 69.6000000000000000 -1.1700000000000000, 73.6000000000000000 -1.0100000000000000, 77.9000000000000000 -0.9700000000000000, 82.0000000000000000 -0.8000000000000000, 86.2000000000000000 -0.7400000000000000, 90.2000000000000000 -0.6700000000000000, 94.5000000000000000 -0.6000000000000000, 98.6000000000000000 -0.5000000000000000, 102.6000000000000000 -0.3900000000000000, 106.9000000000000000 -0.2400000000000000, 111.1000000000000000 -0.1500000000000000, 115.1000000000000000 -0.1510000000000000, 119.2000000000000000 -0.1510000000000000, 123.1000000000000000 -0.0510000000000000, 127.2000000000000000 0.0590000000000000, 131.2000000000000000 0.2090000000000000, 132.2000000000000000 1.0250000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 0.5000000000000000, 128.6000000000000000 0.5000000000000000, 106.2000000000000000 -2.3000000000000000, 49.9000000000000000 -2.3000000000000000, 31.0000000000000000 -5.4500000000000000, 0.0000000000000000 -5.4500000000000000, 0.0000000000000000 -6.1026585365860800))
``` 
and
```
POLYGON ((0.0000000000000000 2.6400000000000000, 0.0000000000000000 -6.0030697674418800, 0.3200000000000000 -5.9800000000000000, 4.6200000000000000 -5.6700000000000000, 8.8100000000000000 -5.1600000000000000, 13.1000000000000000 -5.2100000000000000, 17.1200000000000000 -4.8400000000000000, 21.2800000000000000 -5.1700000000000000, 25.5000000000000000 -5.1600000000000000, 29.7100000000000000 -4.6700000000000000, 34.1300000000000000 -3.9000000000000000, 38.2800000000000000 -3.4800000000000000, 42.6400000000000000 -3.3000000000000000, 46.9800000000000000 -3.2600000000000000, 51.1600000000000000 -2.8900000000000000, 55.3200000000000000 -2.8300000000000000, 59.3000000000000000 -2.9200000000000000, 63.6800000000000000 -2.3600000000000000, 67.4800000000000000 -2.5700000000000000, 70.8900000000000000 -2.4800000000000000, 74.8900000000000000 -2.5500000000000000, 78.8800000000000000 -2.6900000000000000, 82.4400000000000000 -2.4600000000000000, 87.5300000000000000 -2.8100000000000000, 91.6200000000000000 -2.7500000000000000, 95.9000000000000000 -2.1000000000000000, 100.2200000000000000 -2.2100000000000000, 104.4400000000000000 -2.3000000000000000, 109.1500000000000000 -1.9500000000000000, 113.2400000000000000 -2.8200000000000000, 117.2400000000000000 -1.9600000000000000, 120.9400000000000000 -1.3000000000000000, 125.0300000000000000 -0.8200000000000000, 126.6800000000000000 0.1300000000000000, 132.5500000000000000 1.5400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 0.0000000000000000 2.6400000000000000))
```

**Comment by sendreams** [comment]
@FObermaier  thank you very much for you reply, i'm a newer for NetTopologySuite, i use your simple data for test, but never successed. my test code is below, is any wrong?
string r1 = "0.0000000000000000 -6.1026585365860800, 3.8000000000000000 -5.7690000000000000, 7.9000000000000000 -5.4090000000000000, 12.0000000000000000 -5.3690000000000000, 16.1000000000000000 -5.0990000000000000, 20.3000000000000000 -5.1390000000000000, 24.5000000000000000 -4.9090000000000000, 28.5000000000000000 -4.6390000000000000, 32.6000000000000000 -4.1890000000000000, 36.6000000000000000 -3.2890000000000000, 40.8000000000000000 -3.1890000000000000, 44.8000000000000000 -2.9490000000000000, 49.0000000000000000 -2.8200000000000000, 53.3000000000000000 -2.3600000000000000, 57.3000000000000000 -2.1400000000000000, 61.3000000000000000 -1.5200000000000000, 65.5000000000000000 -1.3900000000000000, 69.6000000000000000 -1.1700000000000000, 73.6000000000000000 -1.0100000000000000, 77.9000000000000000 -0.9700000000000000, 82.0000000000000000 -0.8000000000000000, 86.2000000000000000 -0.7400000000000000, 90.2000000000000000 -0.6700000000000000, 94.5000000000000000 -0.6000000000000000, 98.6000000000000000 -0.5000000000000000, 102.6000000000000000 -0.3900000000000000, 106.9000000000000000 -0.2400000000000000, 111.1000000000000000 -0.1500000000000000, 115.1000000000000000 -0.1510000000000000, 119.2000000000000000 -0.1510000000000000, 123.1000000000000000 -0.0510000000000000, 127.2000000000000000 0.0590000000000000, 131.2000000000000000 0.2090000000000000, 132.2000000000000000 1.0250000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 0.5000000000000000, 128.6000000000000000 0.5000000000000000, 106.2000000000000000 -2.3000000000000000, 49.9000000000000000 -2.3000000000000000, 31.0000000000000000 -5.4500000000000000, 0.0000000000000000 -5.4500000000000000, 0.0000000000000000 -6.10265853658608000";
Polygon region = NtsHelper.ParseFromString(r1);
string r2 = "0.0000000000000000 2.6400000000000000, 0.0000000000000000 -6.0030697674418800, 0.3200000000000000 -5.9800000000000000, 4.6200000000000000 -5.6700000000000000, 8.8100000000000000 -5.1600000000000000, 13.1000000000000000 -5.2100000000000000, 17.1200000000000000 -4.8400000000000000, 21.2800000000000000 -5.1700000000000000, 25.5000000000000000 -5.1600000000000000, 29.7100000000000000 -4.6700000000000000, 34.1300000000000000 -3.9000000000000000, 38.2800000000000000 -3.4800000000000000, 42.6400000000000000 -3.3000000000000000, 46.9800000000000000 -3.2600000000000000, 51.1600000000000000 -2.8900000000000000, 55.3200000000000000 -2.8300000000000000, 59.3000000000000000 -2.9200000000000000, 63.6800000000000000 -2.3600000000000000, 67.4800000000000000 -2.5700000000000000, 70.8900000000000000 -2.4800000000000000, 74.8900000000000000 -2.5500000000000000, 78.8800000000000000 -2.6900000000000000, 82.4400000000000000 -2.4600000000000000, 87.5300000000000000 -2.8100000000000000, 91.6200000000000000 -2.7500000000000000, 95.9000000000000000 -2.1000000000000000, 100.2200000000000000 -2.2100000000000000, 104.4400000000000000 -2.3000000000000000, 109.1500000000000000 -1.9500000000000000, 113.2400000000000000 -2.8200000000000000, 117.2400000000000000 -1.9600000000000000, 120.9400000000000000 -1.3000000000000000, 125.0300000000000000 -0.8200000000000000, 126.6800000000000000 0.1300000000000000, 132.5500000000000000 1.5400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 0.0000000000000000 2.6400000000000000";
Polygon clipRegion = NtsHelper.ParseFromString(r2);
Polygon innerRegion = region.Intersection(clipRegion) as Polygon;   // this will throw exception.

`public static Polygon ParseFromString(string str) {
            string[] tmp = str.Split(',');
            List<Coordinate> coords = new List<Coordinate>();
            foreach (string item in tmp) {
                string[] xy = item.Split(new string[] { " "}, StringSplitOptions.RemoveEmptyEntries);
                coords.Add(new Coordinate(double.Parse(xy[0]), double.Parse(xy[1])));
            }
            LinearRing lr = new LinearRing(coords.ToArray());
            return new Polygon(lr);
        }`

**Comment by FObermaier** [comment]
1. Look in wikipedia for "Well known text"
2. Try this snipplet
```C#
var wktReader = new NetTopologySuite.IO.WKTReader();

var poly1 = wktReader.Read(<WKT POLYGON TEXT GOES HERE>);
var poly2 = wktReader.Read(<WKT POLYGON TEXT GOES HERE>);
var intersection = poly1.Intersection(poly2);
System.Console.Writeline(intersection.AsText());
```

**Comment by sendreams** [comment]
@FObermaier i have download the latest code and test your code, it going to failed. 
`        [TestAttribute]
        public void TestPolgyonIntersection() {
            IGeometry a = rdr.Read("POLYGON ((0.0000000000000000 -6.1026585365860800, 3.8000000000000000 -5.7690000000000000, 7.9000000000000000 -5.4090000000000000, 12.0000000000000000 -5.3690000000000000, 16.1000000000000000 -5.0990000000000000, 20.3000000000000000 -5.1390000000000000, 24.5000000000000000 -4.9090000000000000, 28.5000000000000000 -4.6390000000000000, 32.6000000000000000 -4.1890000000000000, 36.6000000000000000 -3.2890000000000000, 40.8000000000000000 -3.1890000000000000, 44.8000000000000000 -2.9490000000000000, 49.0000000000000000 -2.8200000000000000, 53.3000000000000000 -2.3600000000000000, 57.3000000000000000 -2.1400000000000000, 61.3000000000000000 -1.5200000000000000, 65.5000000000000000 -1.3900000000000000, 69.6000000000000000 -1.1700000000000000, 73.6000000000000000 -1.0100000000000000, 77.9000000000000000 -0.9700000000000000, 82.0000000000000000 -0.8000000000000000, 86.2000000000000000 -0.7400000000000000, 90.2000000000000000 -0.6700000000000000, 94.5000000000000000 -0.6000000000000000, 98.6000000000000000 -0.5000000000000000, 102.6000000000000000 -0.3900000000000000, 106.9000000000000000 -0.2400000000000000, 111.1000000000000000 -0.1500000000000000, 115.1000000000000000 -0.1510000000000000, 119.2000000000000000 -0.1510000000000000, 123.1000000000000000 -0.0510000000000000, 127.2000000000000000 0.0590000000000000, 131.2000000000000000 0.2090000000000000, 132.2000000000000000 1.0250000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 0.5000000000000000, 128.6000000000000000 0.5000000000000000, 106.2000000000000000 -2.3000000000000000, 49.9000000000000000 -2.3000000000000000, 31.0000000000000000 -5.4500000000000000, 0.0000000000000000 -5.4500000000000000, 0.0000000000000000 -6.1026585365860800))");
            IGeometry b = rdr.Read("POLYGON ((0.0000000000000000 2.6400000000000000, 0.0000000000000000 -6.0030697674418800, 0.3200000000000000 -5.9800000000000000, 4.6200000000000000 -5.6700000000000000, 8.8100000000000000 -5.1600000000000000, 13.1000000000000000 -5.2100000000000000, 17.1200000000000000 -4.8400000000000000, 21.2800000000000000 -5.1700000000000000, 25.5000000000000000 -5.1600000000000000, 29.7100000000000000 -4.6700000000000000, 34.1300000000000000 -3.9000000000000000, 38.2800000000000000 -3.4800000000000000, 42.6400000000000000 -3.3000000000000000, 46.9800000000000000 -3.2600000000000000, 51.1600000000000000 -2.8900000000000000, 55.3200000000000000 -2.8300000000000000, 59.3000000000000000 -2.9200000000000000, 63.6800000000000000 -2.3600000000000000, 67.4800000000000000 -2.5700000000000000, 70.8900000000000000 -2.4800000000000000, 74.8900000000000000 -2.5500000000000000, 78.8800000000000000 -2.6900000000000000, 82.4400000000000000 -2.4600000000000000, 87.5300000000000000 -2.8100000000000000, 91.6200000000000000 -2.7500000000000000, 95.9000000000000000 -2.1000000000000000, 100.2200000000000000 -2.2100000000000000, 104.4400000000000000 -2.3000000000000000, 109.1500000000000000 -1.9500000000000000, 113.2400000000000000 -2.8200000000000000, 117.2400000000000000 -1.9600000000000000, 120.9400000000000000 -1.3000000000000000, 125.0300000000000000 -0.8200000000000000, 126.6800000000000000 0.1300000000000000, 132.5500000000000000 1.5400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 132.6000000000000000 2.6400000000000000, 0.0000000000000000 2.6400000000000000))");
            IGeometry c = a.Intersection(b);
        }`
<img width="541" alt="snap1" src="https://cloud.githubusercontent.com/assets/4160051/18422377/bf285a86-78cc-11e6-93f1-2caea19c6a45.png">

**Comment by sendreams** [comment]
Additional information: found non-noded intersection between LINESTRING(3.8 -5.769, 7.9 -5.409) and LINESTRING(31 -5.45, 6.4274509803921562 -5.45) [ (7.4330555555555522, -5.45, NaN) ]
stacktrace:
   在 NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.GetResultGeometry(SpatialFunction opCode) 位置 D:\test\NetTopologySuite-master\NetTopologySuite\Operation\Overlay\Snap\SnapIfNeededOverlayOp.cs:行号 82
   在 NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.Overlay(IGeometry g0, IGeometry g1, SpatialFunction opCode) 位置 D:\test\NetTopologySuite-master\NetTopologySuite\Operation\Overlay\Snap\SnapIfNeededOverlayOp.cs:行号 21
   在 NetTopologySuite.Geometries.Geometry.Intersection(IGeometry other) 位置 D:\test\NetTopologySuite-master\NetTopologySuite\Geometries\Geometry.cs:行号 1613
   在 NetTopologySuite.Tests.NUnit.Operation.Overlay.FixedPrecisionSnappingTest.TestPolgyonIntersection() 位置 D:\test\NetTopologySuite-master\NetTopologySuite.Tests.NUnit\Operation\Overlay\FixedPrecisionSnappingTest.cs:行号 36

**Comment by sendreams** [comment]
<img width="690" alt="snap2" src="https://cloud.githubusercontent.com/assets/4160051/18422584/a677d8a6-78cf-11e6-9f6e-d3485c673f24.png">

**Comment by FObermaier** [comment]
The `LINEARRING` that makes up the first `POLYGON` is self-intersecting. By the definition of a `POLYGON` in the _[Simple Feature Access - Part 1: Common Architecture](http://www.opengeospatial.org/standards/sfa)_ this is invalid, and NTS (sometimes) fails to correctly handle that. You can fix the self-intersection by assigning `a = a.Buffer(0);`.

**Comment by sendreams** [comment]
@FObermaier thank you very much, it can work now. another question: is any way to check a polygon is Self-intersection?

**Comment by FObermaier** [comment]
```C'
if (!a.IsValid) 
{
    // ... 
}
``` 
or 
```C#
var isValidOp = new NetTopologySuite.Operation.Valid..IsValidOp(a);
if (!isValidOp.IsValid) 
{
    System.Diagnostics.Debug.WriteLine("Geometry is not valid: {0}", isValidOp.ValidationError);
   // ...
}
```
