### ISSUE TITLE
LineString Intersection with Polygon return null 

### ISSUE THREAD

**Issue by sendreams** [NetTopologySuite/NetTopologySuite#123]
Steps to reproduce

1.a lineString with:
{LINESTRING (0 -5.15, 30 -5.15, 48.9 -2, 105.2 -2, 127.6 0.8, 132.6 0.8)}
2. Intersection with a rectangle polygon with 
{LINEARRING (15.325555555555553 0.8, 42.309375 0.8, 42.309375 -5.15, 15.325555555555553 -5.15, 15.325555555555553 0.8)}
3. return null

Expected behaviour

should return a LineString

Actual behaviour

return null

use the latest code.

**Comment by FObermaier** [comment]
![tmpf1ce](https://cloud.githubusercontent.com/assets/2065346/18386073/b623f2f4-7694-11e6-94cd-69d4592bc4c2.png)
