### ISSUE TITLE
polygon buffer retun empty

### ISSUE THREAD

**Issue by sendreams** [NetTopologySuite/NetTopologySuite#124]
some self-intersection polygon do buffer action will return empty polygon.

POLYGON ((1.4749999999994841 -5.15, 30 -5.15, 48.9 -2, 108.1997 -2, 130.25148787313435 0.75647348414179227, 130.25148787313435 0.75647348414179161, 130 0.75, 126.3 0.72, 122.9 0.7, 119.2 0.42, 115.2 0.45, 111 0.29, 106.9 0.23, 102.8 0.2, 98.8 0.12, 94.8 0.04, 90.7 -0.08, 86.5 -0.2, 82.4 -0.42, 78.3 -0.57, 74.1 -0.69, 69.9 -0.78, 65.8 -0.87, 61.7 -1.07, 57.7 -1.09, 53.7 -1.229, 49.5 -1.289, 45.3 -1.369, 41.2 -1.719, 37 -2.409, 32.8 -3.219, 28.6 -3.769, 24.5 -4.089, 20.4 -4.429, 16.3 -4.599, 12.1 -4.759, 8 -4.889, 4 -5.049, 1.4749999999994841 -5.15))

do geometry.buffer(0) will return empty polygon.

**Comment by sendreams** [comment]
[TestAttribute]
        public void TestBuffer() {
            WKTReader rdr = new WKTReader();
            IGeometry a = rdr.Read("POLYGON ((1.4749999999994841 -5.15, 30 -5.15, 48.9 -2, 108.1997 -2, 130.25148787313435 0.75647348414179227, 130.25148787313435 0.75647348414179161, 130 0.75, 126.3 0.72, 122.9 0.7, 119.2 0.42, 115.2 0.45, 111 0.29, 106.9 0.23, 102.8 0.2, 98.8 0.12, 94.8 0.04, 90.7 -0.08, 86.5 -0.2, 82.4 -0.42, 78.3 -0.57, 74.1 -0.69, 69.9 -0.78, 65.8 -0.87, 61.7 -1.07, 57.7 -1.09, 53.7 -1.229, 49.5 -1.289, 45.3 -1.369, 41.2 -1.719, 37 -2.409, 32.8 -3.219, 28.6 -3.769, 24.5 -4.089, 20.4 -4.429, 16.3 -4.599, 12.1 -4.759, 8 -4.889, 4 -5.049, 1.4749999999994841 -5.15))");
            a = a.Buffer(0);
        }

**Comment by sendreams** [comment]
![Uploading 无标题.png…]()

**Comment by sendreams** [comment]
<img width="380" alt="debug" src="https://cloud.githubusercontent.com/assets/4160051/18498500/6ad5bad4-7a69-11e6-9e07-9ca65e1d06b1.png">

**Comment by FObermaier** [comment]
Calling `geometry.Buffer(0)` does not work in all cases.
Another way is to use `NetTopologySuite.Precision.GeometryPrecisionReducer`:
```C#
var pm = new NetTopologySuite.Geometries.PrecisionModel(1e10);
geom = new NetTopologySuite.Precision.GeometryPrecisionReducer(pm).Reduce(geom);
```

In your case this leads to the slightly different `POLYGON`:
```
POLYGON ((1.475 -5.15, 30 -5.15, 48.9 -2, 108.1997 -2, 130.2514878731 0.7564734841, 130 0.75,
126.3 0.72, 122.9 0.7, 119.2 0.42, 115.2 0.45, 111 0.29, 106.9 0.23, 102.8 0.2, 98.8 0.12, 94.8 0.04, 
90.7 -0.08, 86.5 -0.2, 82.4 -0.42, 78.3 -0.57, 74.1 -0.69, 69.9 -0.78, 65.8 -0.87, 61.7 -1.07, 57.7 -1.09,
53.7 -1.229, 49.5 -1.289, 45.3 -1.369, 41.2 -1.719, 37 -2.409, 32.8 -3.219, 28.6 -3.769, 24.5 -4.089, 
20.4 -4.429, 16.3 -4.599, 12.1 -4.759, 8 -4.889, 4 -5.049, 1.475 -5.15))
```

**Comment by sendreams** [comment]
“Calling geometry.Buffer(0) does not work in all cases.”, i dont understand your mean,  i have useed buffer(0) in another many situation, it can work perfect in most time except in this case.

**Comment by FObermaier** [comment]
If I'm not mistaken, you are attempting to fix an invalid polygon by calling `geom.Buffer(0)`. While this works in most of the cases, it does not always. In your case it appearantly does not.

**Comment by sendreams** [comment]
@FObermaier , can you please toll me the reason, why buffer(0) cann't be working in some case?

**Comment by DGuidi** [comment]
@sendreams algorithm stuff

**Comment by FObermaier** [comment]
From [JTS-FAQ](http://tsusiatsoftware.net/jts/jts-faq/jts-faq.html)
> ... in some situations the computed result may not be what is desired (i.e. the buffer operation may be "confused" by certain topologies, and fail to produce a result which is close to the original. An example where this can happen is a "bow-tie: or __"figure-8" polygon, with one very small lobe and one large one__. Depending on the orientations of the lobes, the buffer(0) operation may keep the small lobe and discard the "valid" large lobe).
