### ISSUE TITLE
GeometryFactory.CreatePoint does not return a point that supports M

### ISSUE THREAD

**Issue by becio** [NetTopologySuite/NetTopologySuite#126]
The title can be misleading, the long story is that what I have done is instantiating a custom NtsGeometryServices providing the DotSpatialAffineCoordinateSequenceFactory which supports the use of M, then I obtained the IGeometryFactory and invoked the method CreatePoint(Coordinate) to create a point, well this point does NOT support the property M.

Under the hood I noticed that this is because the construct of **DotSpatialAffineCoordinateSequence(IList<Coordinate>)**, invoked by the factory, **does NOT initialize the _m field** !

In my opinion since I have set the DotSpatialAffineCoordinateSequenceFactory, the GeometryFactory.CreatePoint should return a proper point, the fix should be to initialize the field or the factory should invoke a different construct which enables M.

**Comment by FObermaier** [comment]
Becio, you expect a `DotSpatialAffineCoordinateSequenceFactory` to create 3DM coordinate sequences, no matter what?
