### ISSUE TITLE
Any secure way to reproject a shape file.

### ISSUE THREAD

**Issue by am2222** [NetTopologySuite/NetTopologySuite#127]
Hi, I dont know if my question is related into this project or not, I want to find a secure way to reprojection shape files, My main SRID code is 900913 and I must perform a re-projection on each shape file which I want to add on those layer automaticly. I have used sharp map to reproject layers but It has some problems. In some cases it broke data,
I want to know if there is any way to perform reprojection on shape file data using NettopologySuit?

**Comment by DGuidi** [comment]
please use [Google Group](https://groups.google.com/forum/#!forum/nettopologysuite) for this kind of questions
