### ISSUE TITLE
How do you manage to split a polygon (flowchart)

### ISSUE THREAD

**Issue by am2222** [NetTopologySuite/NetTopologySuite#128]
Hi,
This question is not related into this project, I would thank you if you halp me,
I have a polygon, I want to split it into three equile parts, I have a senario as bellow,
1- user must select a vertex on polygon
2- user must add direction to start split on
3- based on the node and direction we must select a line segment on polygon
4-??????

I have no idea how to go farther and then do what to split that line segment.In fact here there is some problems,
1- how we can find if the line segment is devidable into for example 3 parts?how we van determine the lenght of each segments on line to divide?
2- if line segment changes its direction what will happen?

Can some one give me some hints how to reach a flowchart on his?
thanks

**Comment by DGuidi** [comment]
please use [Google Group](https://groups.google.com/forum/#!forum/nettopologysuite) for this kind of questions
