### ISSUE TITLE
"side location conflict" undescriptive exception

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#129]
I'm trying to use this suite to manipulate geo data before inserting it to elastic search database.
The manipulations is uses GeoJson Feature and tests if one feature is inside the other.
I'm getting the following exception:
"side location conflict" with some coordinates.
How can I tell why I'm getting this error and how to modify the feature in order to solve it?

**Comment by FObermaier** [comment]
There are two possible reasons that you are getting this exception:

1. Most likely you have invalid geometries to start with. You can test geometries for validity by either checking `feature.Geometry.IsValid` property or by using the `NetTopologySuite.Operation.Valid.IsValidOp` class. The later gives you the location where the validation test failed.
If this is the case you can attempt to fix the geometry by assigning `feature.Geometry = feature.Geometry.Buffer(0);`. While this works for most of the cases, it is not guaranteed to do so. An example where this might not work is a "bow-tie: or "figure-8" polygon, with one very small lobe and one large one. Depending on the orientations of the lobes, the `Buffer(0)` operation may keep the small lobe and discard the "valid" large lobe.
2. It can also happen during operations on geometries due to some subtle kinds of cross-geometry 
topology, such as two line segments being almost but not quite coincident. This can be avoided by using the `NetTopologySuite.Precision.GeometryPrecisionReducer`.

I would need to see the geometries to tell more.

**Comment by HarelM** [comment]
I'm converting all the OSM elements that have a name in Israel from OSM to GeoJson then try and add the name of the containing element to each one that is a line or a point.
The following OSM items have some issues when I try to test if they contain other elements.
While some are easy to see the issue that they intercept themselves other are not.  
http://www.openstreetmap.org/relation/1638059
http://www.openstreetmap.org/relation/4759745
http://www.openstreetmap.org/relation/1641096
http://www.openstreetmap.org/relation/1638658
http://www.openstreetmap.org/relation/1638370
http://www.openstreetmap.org/relation/1637861
http://www.openstreetmap.org/relation/5909627
http://www.openstreetmap.org/relation/1637981
http://www.openstreetmap.org/relation/1649748
http://www.openstreetmap.org/relation/1637869
http://www.openstreetmap.org/way/383762151
When I test for invalidity for all the elements I get a lot more results than the above - 243 to be exact, but those do not throw an exception when trying to test for "contain".
My main question is how do I know what exactly is wrong? is it possible to generate a more user friendly exception so I can go and check what's wrong with this element?
Since Net Topology is working on GeoJson Elements and not OSM (As far as I can tell) it might be that the converter I wrote is not written properly and I would like to know that too.

**Comment by FObermaier** [comment]
When you use `IsValidOp` you get the reason and the location of the first invalid item in the geometry.
```C#
var isValidOp = new NetTopologySuite.Operation.Valid.IsValidOp(feature.Geometry);
if (!isValidOp.IsValid)
{
    Debug.WriteLine("feature.Geometry is not valid:" + isValidOp.ValidationError.Message);
    switch (isValidOp.ValidationError.ErrorType)
    {
        // handle error types.
    }
}
```

I got the first relation using (Overpass API, exported GeoJson)[https://gist.github.com/anonymous/78271eac2b5938576e8cafb04b3de68b] and put that in the current version of the GeoJsonSerializer. The feature's geometry is perfectly valid and a `Contains` on it does not throw an exception. Either your converter has an issue or the data passed by the overpass api is somewhat different from the data you have at hand.

**Comment by HarelM** [comment]
Thanks, I now am able to see the error: "Self-intersection" at  X: 35.1588432 Y: 32.795140700000005.
Which in the above case is a point where the inner and the outer polygon of the multi-polygon meet, which might be a problem with my converter.
Is it possible to get this error in the exception instead of writing this code in the ```catch``` statement?
Also, since the geometry has a ```IsValid``` method I think it should also have a ```GetValidationErrorMessage``` or something similar. this way developers like me would be able to find it using intellisense instead of digging through the documentation (and opening this issue here when they can't find it...).

**Comment by HarelM** [comment]
Please see if I didn't understand something, see the following gist:
https://gist.github.com/HarelM/1377f7cb9b86cea452155a7920d32c61
running this test fails:
```
        [TestMethod]
        public void Test()
        {
            using (var outputStream = new FileStream(@"/Path/To/InvalidExample.geojson", FileMode.OpenOrCreate))
            {
                var reader = new StreamReader(outputStream);
                var jsonWriter = new JsonTextReader(reader);
                var serializer = new GeoJsonSerializer();
                var feature = serializer.Deserialize<FeatureCollection>(jsonWriter);
                var isValidOp = new NetTopologySuite.Operation.Valid.IsValidOp(feature.Features.First().Geometry);
                Assert.IsTrue(isValidOp.IsValid);
            }
        }
```

**Comment by FObermaier** [comment]
This test fails on my machine as well.

**Comment by HarelM** [comment]
But the shape is valid, right? It's just an inner shape touching the outer shape but it's a valid multi-polygon...?

**Comment by FObermaier** [comment]
No, the shape is __not__ valid

**Comment by HarelM** [comment]
Can you elaborate a bit please? why do you consider this shape as invalid?

**Comment by FObermaier** [comment]
That is not the geometry you have defined in your gist. Your geometry looks like this:
![image](https://cloud.githubusercontent.com/assets/2065346/19034357/45267932-8963-11e6-99e4-2bcb25f4701f.png)
Note: the hole in your picture is not defined as a hole in the GeoJson

**Comment by HarelM** [comment]
How does one define a hole in multi-polygon GeoJson? I couldn't fully understand the [spec](http://geojson.org/geojson-spec.html).
If I'm to read it again in-light of what you just wrote then I need to create a polygon with two linear rings and add this polygon to the multi-polygon?
So how does one convert OSM (which has only inner and outer members for multipolygone) to GeoJson? by looking into all the outer and find all the inner inside them and group them to a single plygone?
Your help is much appreciated. 
> 2.1.6. Polygon
> For type "Polygon", the "coordinates" member must be an array of LinearRing coordinate arrays. For Polygons with multiple rings, the first must be the exterior ring and any others must be interior rings or holes.
> 2.1.7. MultiPolygon
> For type "MultiPolygon", the "coordinates" member must be an array of Polygon coordinate arrays.

**Comment by FObermaier** [comment]
> If I'm to read it again in-light of what you just wrote then I need to create a polygon with two linear rings and add this polygon to the multi-polygon?

Yes.

**Comment by FObermaier** [comment]
As we don't want to diverge from the JTS source, we currently will neither supply an `IsValidReason()` function nor change the logic of the predicate and operation classes.

As for `IsValidReason`, this can easily be achieved using extension classes. Furthermore it is the responsibility of the client of this API to provide valid input.

**Comment by HarelM** [comment]
I'm not sure I understand this statement:
> As we don't want to diverge from the JTS source, we currently will neither supply an IsValidReason() function nor change the logic of the predicate and operation classes.

In another issue I open you said that this library is open to pull requests. the above statement feels like it is contradicting it if I'm planning to create a pull request only for the .Net code (this is what I feel comfortable with), doesn't it? 

The original reason I opened this issue is due to an unclear exception - there are workaround to understand why I got this exception (obvious from this thread) but the bottom line is that I needed your help in order to understand it. I think it terms of time consuming, you can better use your time instead of answering "dumb" developers like me by making this framework more developer friendly. 

> Furthermore it is the responsibility of the client of this API to provide valid input.

It's true that the client should supply valid input but this can only happen in a Utopian world. I use the user input (which is far from valid in some cases) and pass it to this framework, I except this framework to provide me with the required answers, or better tell me when something went wrong when it did.
