### ISSUE TITLE
GeoJson Attributes property enhancments

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#130]
This property is not developer friendly.
As a framework I would expect this property to be more like a dictionary.
for example this should work:
`feature.Attributes["new_key"] = "123"` inserted I get an exception that `new_key` not exists (with a grammar mistake).
a required API capability would be to merge between attributes from two features.

```
f1.Attributes.MergeWith(f2.Attributes);
```

Another capability would be to be able to initialize it using initialization list much like dictionary.

```
f1.Attributes = new AttributesTable { { "key", "value" }, { "key2", "value2" }}
```

**Comment by FObermaier** [comment]
We accept pull requests.

**Comment by HarelM** [comment]
Would love to help. do you have any guidelines? thing you think should be there and are not? developing guidelines are to where the tests are? are all the classes fully covered? are there any other type of geometry that this library is using and should look similar or have a similar API?

**Comment by FObermaier** [comment]
Currently there are no "official" guidelines. I invite @NetTopologySuite/developer to create a wiki page for that.

**Comment by FObermaier** [comment]
How about this:
```C#
        /// <summary>
        /// Creates an instance of this class using the provided enumeration of key/value pairs
        /// </summary>
        /// <exception cref="ArgumentException">If the enumeration contains objects</exception>
        public AttributesTable(IEnumerable<object[]> objects) : this()
        {
            foreach (var obj in objects)
            {
                if (obj == null)
                    continue;
                if (obj.Length != 2)
                    throw new ArgumentException("objects");

                if (!(obj[0] is string))
                    throw new ArgumentException("objects");

                AddAttribute((string)obj[0], obj[1]);
            }
        }
        /// <summary>
        /// Gets or sets a value indicating if setting <see cref="this[string]"/> with a 
        /// nonexistant index will throw an exception or if the attribute/value pair will 
        /// silently be added.
        /// </summary>
        public static bool AddAttributeWithIndexer { get; set; }

        /// <summary>
        /// Set the value of the specified attribute.
        /// </summary>
        /// <param name="attributeName"></param>
        /// <param name="attributeValue"></param>
        protected void SetValue(string attributeName, object attributeValue)
        {
            if (!Exists(attributeName))
            {
                if (!AddAttributeWithIndexer)
                    throw new ArgumentException("Attribute " + attributeName + " not exists!");
                AddAttribute(attributeName, attributeValue);
                return;
            }
            _attributes[attributeName] = attributeValue;
        }
        /// <summary>
        /// Method to merge this attribute table with another attribute table
        /// </summary>
        /// <param name="other">The other attribute table</param>
        /// <param name="preferThis">A value indicating if values in this attribute table are preferable 
        /// over those in <paramref name="other"/>.  The default is <value>true</value>.
        /// </param>
        public void MergeWith(IAttributesTable other, bool preferThis = true)
        {
            foreach (var name in other.GetNames())
            {
                if (!Exists(name))
                    AddAttribute(name, other[name]);
                else
                {
                    if (!preferThis)
                        this[name] = other[name];
                }
            }
        }
```

**Comment by HarelM** [comment]
Not sure why the default behavior should be to throw when adding, but I don't want to be nitpicking.
The MergeWith look good :-).
The constructor with object array is not very informative in terms of what went wrong (exception raised). 
```obejct[]``` in terms of API doesn't help you understand when you write the code what should be sent to this constructor, Why not use ```IEnumerable<KeyValuePair<string, object>>``` or even a dictionary?
I think that if you change the name of the method "AddAttribute" to just "Add" the above requirement of initializing constructor with a list of objects will be possible without creating this odd constructor.
See C# Language Specification - 7.5.10.3 Collection Initializers
And this stackoverflow question:
http://stackoverflow.com/questions/2495791/custom-collection-initializers

**Comment by HarelM** [comment]
Thanks! :-) Keep up the good work!
