### ISSUE TITLE
GeoJson desirializer gets stuck

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#131]
Hi again, sorry for nagging.
I have accidentally created an invalid GeoJson file. when I try to desirialize it the process gets stuck instead of throwing an exception or returning null:
https://gist.github.com/HarelM/03edf767ef6cab60ee7ce7888a9138a1#file-gets_stuck-geojson
Test:
```
        [TestMethod]
        public void Stucks()
        {
            using (var stream = new FileStream(@"/path/to/file.geojson", FileMode.Open, FileAccess.Read))
            {
                var serializer = new GeoJsonSerializer();
                using (var streamReader = new StreamReader(stream))
                using (var jsonTextReader = new JsonTextReader(streamReader))
                {
                    var a = serializer.Deserialize<FeatureCollection>(jsonTextReader);
                    Assert.IsNull(a);
                }
            }
        }
```

**Comment by FObermaier** [comment]
To validate your GeoJson you can use http://geojsonlint.com/
With this json string there are at least two issues:
- key values need to be in quotes ("features")
- a FeatureCollection contains features not geometries.

**Comment by HarelM** [comment]
Please re-open.
I know there are issues with this geojson. nevertheless, the fact is that the code gets stuck (!) when it shouldn't.

**Comment by FObermaier** [comment]
Code as is throws "ArgumentException" when trying to parse the first feature in the collection.

**Comment by HarelM** [comment]
I'm using version suite 1.14, Newtonsoft.Json 9.0.1 from NuGet on windows 10 with VS 2015 community.
The above test never finishes...
