### ISSUE TITLE
WpfGeometryReader generates invalid geometry

### ISSUE THREAD

**Issue by koffmoff** [NetTopologySuite/NetTopologySuite#134]
Amazingly fast response on #133 and #132, thanks! Here's another one. The input is taken from a production case, hence the weird coordinates. I've tried to simplify the input as much as possible, but this is about as far as I come. The input looks ok to me, but generates an invalid geometry.

Here's a visualisation of the WPF geometry:

![image](https://cloud.githubusercontent.com/assets/2835896/19548815/09bd5a14-96a1-11e6-9f2a-e93d7704cddb.png)

And here's the test case to expose the bug:

```
        [Test]
        public void InvalidPolygon()
        {
            var wpfGeom = Geometry.Parse("M12.6206216812134, 50.9294242858887L11.5450315475464, 49.8538360595703 10.4694414138794, 50.9294242858887 11.5450315475464, 52.0050163269043 12.6206216812134, 50.9294242858887z M11.5870275497437, 55.99609375L10.0783662796021, 54.487434387207 8.56970500946045, 55.99609375 10.0783662796021, 57.5047569274902 11.5870275497437, 55.99609375z M5.77836227416992, 54.9871711730957L3.80277156829834, 56.962760925293 5.77836227416992, 58.9383506774902 7.7539529800415, 56.962760925293 5.77836227416992, 54.9871711730957z M5.51891326904297, 51.7981262207031L5.5027756690979, 51.99609375 6.71169662475586, 53.2050170898438 7.92061805725098, 51.99609375 6.74462604522705, 50.7876129150391 6.88728761672974, 50.0960960388184 5.14503145217896, 48.3538398742676 3.40277552604675, 50.0960960388184 5.14503145217896, 51.8383522033691 5.51891326904297, 51.7981262207031z M8.37836647033691, 45.7541007995605L6.53637409210205, 47.5960960388184 8.37836647033691, 49.4380874633789 10.2203578948975, 47.5960960388184 8.37836647033691, 45.7541007995605z M1.5868661403656, 45.6459007263184L1.5868661403656, 76.6044692993164 37.3742637634277, 76.6044692993164 37.3742637634277, 45.6459007263184 1.5868661403656, 45.6459007263184z");
            WpfGeometryToImage(wpfGeom, "out.png");
            var ntsGeom = WpfGeometryReader.Read(wpfGeom, Geometries.GeometryFactory.Default);
            Assert.IsTrue(ntsGeom.IsValid);
            Assert.AreEqual(wpfGeom.GetArea(), ntsGeom.Area, 1e-4);
        }

```

**Comment by FObermaier** [comment]
The problem is, that the framing polygon is not the first one defined. Thus the parsed WpfGeometry looks like this:
![image](https://cloud.githubusercontent.com/assets/2065346/19550298/2edf6cb2-96a9-11e6-81e6-3ed176ec23af.png)

**Comment by koffmoff** [comment]
Oh I see. That's a problemsince WPF has no concept of "framing polygon". Two overlapping squares make a perfectly valid shape:

![image](https://cloud.githubusercontent.com/assets/2835896/19551496/bfde564a-96ab-11e6-9aae-0ab92766a704.png)

```
var wpfGeom = Geometry.Parse("M0,5 L0,15 10,15 10,5 0,5 M5,0 L5,10 15,10 15,0 5,0");
var ntsGeom = WpfGeometryReader.Read(wpfGeom, Geometries.GeometryFactory.Default);
```

The above give me OutOfMemoryException.

Any ideas on how to work around this?

**Comment by FObermaier** [comment]
What happens if you put a plain line between the two polygons?

**Comment by koffmoff** [comment]
Sorry, don't know what you mean by "between". There really is no between,
since they're overlapping.

**Comment by FObermaier** [comment]
If you put a line of some sort between the definition of the rectangles.
`"M0,5 L0,15 10,15 10,5 0,5 <HERE THE LINE> M5,0 L5,10 15,10 15,0 5,0"`
I'm not familiar with the syntax, otherwise I would do it myself.

**Comment by koffmoff** [comment]
You mean like this?

`var wpfGeom = Geometry.Parse("M0,5 L0,15 10,15 10,5 0,5 M0,0 L15,15 M5,0 L5,10 15,10 15,0 5,0");`


![image](https://cloud.githubusercontent.com/assets/2835896/19552763/84ebc440-96b1-11e6-8949-93fe6701b7fd.png)

Same result. OutOfMemoryException.

**Comment by FObermaier** [comment]
@koffmoff can we close this issue?

**Comment by koffmoff** [comment]
Yes, just re-ran my tests and they work! Thanks!
