### ISSUE TITLE
Is the angle calculation incorrect?

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#136]
I'm running the following code:
```
var lineString1 = new LineString(new [] { new Coordinate(1, 1), new Coordinate(2, 2)});
var lineString2 = new LineString(new[] { new Coordinate(2, 2), new Coordinate(1, 1)});
``` 
I think I should get a different values for ```Angle``` for the above lines, am I missing something? I'm getting ~45 degrees for both.
Note that they have a different direction although they are compiled from the same points.

**Comment by HarelM** [comment]
Any updates on this?

**Comment by DGuidi** [comment]
angle is an old addition from MonoGIS team, and ignores direction so result is the same for buth geometries; probably this was the MonoGIS desired result...
Anyway, probably the best move should be to mark as deprecated the Angle property entirely.

**Comment by HarelM** [comment]
So if I want to calculate the angle between two lines I should use ```LineSegment```?

**Comment by DGuidi** [comment]
try with AngleUtility

**Comment by HarelM** [comment]
Thanks! I will.
