### ISSUE TITLE
How to merge many polygons by use  NetTopologySuite?

### ISSUE THREAD

**Issue by pucx** [NetTopologySuite/NetTopologySuite#139]
Is there a method to merge many polygons by use  NetTopologySuite?Thanks.

**Comment by FObermaier** [comment]
Use [`NetTopologySuite.Operation.Union.CascadedPolygonUnion`](https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite/Operation/Union/CascadedPolygonUnion.cs) class
