### ISSUE TITLE
Feature suggestion: RadialDistanceSiplifier

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#142]
A very simple but powerful simplifier, here is a short code I wrote, might need better support for other geometries and unhappy cases.
Written partially like D-P-Simplifier in terms of API.
```cs
    public class RadialDistanceSimplifier
    {
        private readonly IGeometry _geometry;
        public double DistanceTolerance { get; set; }

        public RadialDistanceSimplifier(IGeometry geometry)
        {
            _geometry = geometry;
        }

        public ILineString GetResultGeometry()
        {
            var coordinates = _geometry.Coordinates;
            if (coordinates.Length == 0)
            {
                // throw?
                return null;
            }
            var simplified = new List<Coordinate> {coordinates.First()};
            foreach (var coordinate in coordinates.Skip(1))
            {
                if (coordinate.Distance(simplified.Last()) > DistanceTolerance)
                {
                    simplified.Add(coordinate);
                }
            }
            return simplified.Count <= 1 ? null : new LineString(simplified.ToArray());
        }
    }
```

**Comment by DGuidi** [comment]
thanks for the code posted here

**Comment by HarelM** [comment]
I looked at the code of the D-P simplifier and understood I wasn't close to how it's written (with the coordinates transformer etc.), the idea is relevant never-the-less and it's fairly simple.
I'm not sure what will be the purpose and the value of posting it in the forum...?

**Comment by DGuidi** [comment]
> I'm not sure what will be the purpose and the value of posting it in the forum...?

that anyone can read and use this code if they need.

**Comment by HarelM** [comment]
Done: https://groups.google.com/forum/#!topic/nettopologysuite/m2Eyct-kLjE
Thanks for the quick response. keep up the good work.
I eventually used a modified version of this simplifier that is also angle dependant to remove GPS bad measurements, I think it's pretty specific to my needs but if anyone is interested the code can be found here:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Services/RadialDistanceByAngleSimplifier.cs

**Comment by DGuidi** [comment]
> Thanks for the quick response

You welcome. Thanks to you for your suggestions.

**Comment by HarelM** [comment]
So you are not planning on adding it? kinda disappointing...

**Comment by FObermaier** [comment]
@HarelM, I'm trying to prepare your code for JTS. Could you provide some settings along with  input and expected output?

**Comment by HarelM** [comment]
Sure, can you elaborate what exactly you need and how to provide it?
Also note that I think the first and last point should remain similarly to D-P.
Which code are you planning to use? the one here or the one I referenced to in my github project?

**Comment by FObermaier** [comment]
The one in your github project.
I'd like to know constructor arguments, property settings and the "expected" result.

**Comment by HarelM** [comment]
The following test class describe the main usages:
I published some corrections lately including some comments to describe the algorithm itself.
https://github.com/IsraelHikingMap/Site/blob/master/Tests/IsraelHiking.API.Tests/Services/RadialDistanceByAngleSimplifierTests.cs
Do you need anything besides that?
