### ISSUE TITLE
Release tag for NetTopologySuite 1.14

### ISSUE THREAD

**Issue by russcam** [NetTopologySuite/NetTopologySuite#143]
Looking through the branches and releases, there doesn't seem to be a tag for [1.14 that's up on Nuget](https://www.nuget.org/packages/NetTopologySuite/1.14.0).

Going through the history, it looks like https://github.com/NetTopologySuite/NetTopologySuite/tree/ebc10cfc5f7c14b6bbbd656e64e49c4d05bbc2dd is the last commit before 1.14 is released. 

Would it be possible to tag this commit? I was looking through the tags while tracking down a bug reported in https://github.com/elastic/elasticsearch-net/issues/2444, which looks to be fixed in `master`, but it wasn't straightforward to find where 1.14 was cut.

Thank you for putting out such a great library and making the best GIS solution for .NET 🥇

**Comment by FObermaier** [comment]
https://github.com/NetTopologySuite/NetTopologySuite/releases/tag/v1.14
