### ISSUE TITLE
Can't deserialize GeoJson from OSM boundary files

### ISSUE THREAD

**Issue by PaulvonGitHub** [NetTopologySuite/NetTopologySuite#145]
Hi guys,

Im trying to deserialize the GeoJson into a FeatureCollection but it always returns "Expected token '{' not found." 

I got the geojson from: https://osm.wno-edv-service.de/boundaries/

When i try to deserialize these files with GeoJson.net it's no problem.

**Comment by DGuidi** [comment]
can you post the a sample geojson? or even better a minimal sample (data+code) that fails? service looks down, and btw a sample to test can be useful.

**Comment by PaulvonGitHub** [comment]
```

            using (var stream = new FileStream(jsonFileName, FileMode.Open, FileAccess.Read))
            {
                var serializer = new GeoJsonSerializer(); 

                using (var streamReader = new StreamReader(stream))
                using (var jsonTextReader = new JsonTextReader(streamReader))
                {
                    var a = serializer.Deserialize<FeatureCollection>(jsonTextReader);
                    Console.WriteLine(a.Count);
                }
            }
```


[World_AL6.GeoJson.zip](https://github.com/NetTopologySuite/NetTopologySuite/files/693929/World_AL6.GeoJson.zip)

**Comment by DGuidi** [comment]
tets doesn't fail using master

**Comment by PaulvonGitHub** [comment]
Thanks for the test. I'll check out the master and try again.

**Comment by PaulvonGitHub** [comment]
Pulled the master and it worked. Would be nice if nuget package gets updated. Thanks again.
