### ISSUE TITLE
Mapping voronoi cells to their sites

### ISSUE THREAD

**Issue by manuschiller** [NetTopologySuite/NetTopologySuite#148]
I am creating a voronoi diagram using [NetTopologySuite's Voronoi Diagram Builder][1].

Everything works as expected, but the cell information (polygon coords, area and so on) is not mapped to my sites (`Coords`) anymore.

I need to store the information for each site in a Database like this:

    point     | voroni_cell            | area
    Coords[x] | VoronoiCell.ToString() | VoronoiCell.Area

How can I map the cells to the corresponding sites?
---

Here is my sample code:

    public static void Main(string[] args)
    		{
    			var bmp = new Bitmap(1000, 650);
    			var gr = Graphics.FromImage(bmp);
    			Pen blackPen = new Pen(Color.Black, 3);
    
    			Coordinate[] Coords = new Coordinate[5];
    			Coords[0] = new Coordinate(200, 200);
    			Coords[1] = new Coordinate(400, 400);
    			Coords[2] = new Coordinate(600, 600);
    			Coords[3] = new Coordinate(800, 300);
    			Coords[4] = new Coordinate(430, 200);
    
    			VoronoiDiagramBuilder VoronoiDiagram = new VoronoiDiagramBuilder();
    			VoronoiDiagram.SetSites(Coords);
    
    			var ResultingDiagram = VoronoiDiagram.GetDiagram(new GeometryFactory());
    
    			// draw cells
    			foreach (var VoronoiCell in ResultingDiagram.Geometries)
    			{
    				List<System.Drawing.Point> Points = new List<System.Drawing.Point>();
    				foreach (var Coordinate in VoronoiCell.Coordinates)
    				{
    					Points.Add(new System.Drawing.Point((int)Coordinate.X, (int)Coordinate.Y));
    				}
    
    				gr.DrawPolygon(blackPen, Points.ToArray());
    			}
    
    			// draw sites
    			foreach (Coordinate C in Coords)
    			{
    				gr.FillEllipse(new SolidBrush(Color.BlueViolet), (float)C.X, (float)C.Y, 20, 20);
    			}
    
    			bmp.Save(Path.Combine("/Users/me/Downloads/","image.png"));
    				
    		}

And the resulting image:
[![Sample voronoi diagram][2]][2]

  [1]: http://nettopologysuite.github.io/html/class_net_topology_suite_1_1_triangulate_1_1_voronoi_diagram_builder.html
  [2]: https://i.stack.imgur.com/inr07.png

**Comment by manuschiller** [comment]
Here is a hacky solution to manually map the cells to their original sites - but can this done more elegant?

```
// draw cells
			Dictionary<Coordinate, IGeometry> MappedCoords = new Dictionary<Coordinate, IGeometry>();

			foreach (var VoronoiCell in ResultingDiagram.Geometries)
			{
				List<System.Drawing.Point> Points = new List<System.Drawing.Point>();
				foreach (var Coordinate in VoronoiCell.Coordinates)
				{
					Points.Add(new System.Drawing.Point((int)Coordinate.X, (int)Coordinate.Y));
				}

				foreach (var Coord in Coords)
				{
					if (VoronoiCell.Contains(new NetTopologySuite.Geometries.Point(Coord)))
					{
						MappedCoords.Add(Coord, VoronoiCell);
					}
				}

				Console.WriteLine("Successfully mapped {0} coords to their cells", MappedCoords.Count);

				gr.DrawPolygon(blackPen, Points.ToArray());
			}
```

**Comment by FObermaier** [comment]
Have you checked `VoronoiCell.UserData`? If I'm not mistaken, it gives you the coordinate it belongs to.
