### ISSUE TITLE
TopoJSON reader/writer

### ISSUE THREAD

**Issue by DGuidi** [NetTopologySuite/NetTopologySuite#15]
Copied from Google Code [Issue 166](https://code.google.com/p/nettopologysuite/issues/detail?id=166)

**Comment by Walt-D-Cat** [comment]
Hey, Is there any working being done on this part?  Currently the tests all fail for me in the runtime with:

    Newtonsoft.Json.JsonWriterException : Token StartObject in state Object would result in an invalid JSON object. Path 'objects.data'.

Cheers,

:w

**Comment by DGuidi** [comment]
all develop is stopped now, sorry.
any help would be appreciated.

**Comment by Walt-D-Cat** [comment]
That's what i suspected looking at the activity logs.  I've not actually
contributed to an OS project before.  Any pointers?

I've forked nettopologysuite and got it mostly building the (the PCL
libraries are not liking me).



On Wed, Jan 13, 2016 at 4:45 AM, Diego Guidi <notifications@github.com>
wrote:

> all develop is stopped now, sorry.
> any help would be appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NetTopologySuite/NetTopologySuite/issues/15#issuecomment-171233479>
> .
>



-- 
"Time is spatial"
[C. Stockdale and C. Possin (1998) Spatial Relations and Learning
<http://impactofspecialneeds.weebly.com/uploads/3/4/1/9/3419723/spatial.pdf>
]
<http://secretgeek.net/NoVS.asp>

**Comment by DGuidi** [comment]
TopoJSON reader/writer was a feature I'd like to add but it's incomplete now. 
At least, in some form reader is working, but writer isn't implemented at all.
A way to start is to take a look at [specifications](https://github.com/mbostock/topojson-specification/blob/master/README.md) and try to made unit tests work as expected, in your fork.
then you can create a [pull request](https://help.github.com/articles/using-pull-requests/).

**Comment by DGuidi** [comment]
Looks a valid first step.
