### ISSUE TITLE
GeometryFactory.BuildGeometry creates unnecessary GeometryCollection

### ISSUE THREAD

**Issue by koffmoff** [NetTopologySuite/NetTopologySuite#150]
Feeding a single MultiPolygon into GeometryFactory.BuildGeometry returns the same MultiPolygon wrapped in an unnecessary GeometryCollection. Would be more natural to return the input unchanged.

Example:

```C#
Console.WriteLine(
    GeometryFactory.Default.BuildGeometry(new[] {
        new WKTReader().Read("MULTIPOLYGON (((0 0, 10 0, 10 10, 0 10, 0 0)), ((20 0, 30 0, 30 10, 20 10, 20 0)))")
    }));

// Output:
// GEOMETRYCOLLECTION (MULTIPOLYGON (((0 0, 10 0, 10 10, 0 10, 0 0)), ((20 0, 30 0, 30 10, 20 10, 20 0))))
```

**Comment by DGuidi** [comment]
this is a design decision, documented in c# code comments too:
" 
Note that this method does not "flatten" Geometries in the input, and hence if any MultiGeometries are contained in the input a GeometryCollection containing them will be returned.
"
your suggestion seems legit, but this is a JTS (and then NTS) implementation, so I won't fix this behavior.
thanks anyway for the suggestion.
