### ISSUE TITLE
GeoJson Reader is depenant on the ordering of the fields in the GeoJson

### ISSUE THREAD

**Issue by lawrencegripper** [NetTopologySuite/NetTopologySuite#152]
https://github.com/NetTopologySuite/NetTopologySuite/blob/d6a27c2995ecc2c51286cc620463b492bd6f6a4b/NetTopologySuite.IO/NetTopologySuite.IO.GeoJSON/Converters/FeatureConverter.cs#L87

If you have a valid geojson object like this, which doesn't list the type property first, the reader will fail:

```json
{"geometry":{"coordinates":[-90.0,-3.0000000000000004],"type":"Point"},"properties":{},"type":"Feature"}
```

Would you to happy to accept a pull request from me to fix this up?

**Comment by DGuidi** [comment]
yep, but try first if error happens also with current (master) version

**Comment by lawrencegripper** [comment]
Ah thank you, it has indeed already been fixed!

**Comment by DGuidi** [comment]
so I can close this issue, right?
