### ISSUE TITLE
Crosses and intersection

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#153]
Hi, I'm guessing the following issue is related to decimal point issues but I just want to make sure I'm not doing anything wrong:
I have the following test which fails.
Basically what it does is tries to find the projection of a point on a line and then make sure that combining this point to create a new line wont cross the original line.
This fails... :-(
In order to workaround it I use the ```intersection``` method.
Should I be using this workaround or is there something else I should do?
Is this a bug or a limitation?

```cs
        [TestMethod]
        public void CrossAndIntersectionTest()
        {
            var closestCoordinate = new Coordinate(152608, 594957);
            var closestLine = new LineString(new []
            {
                new Coordinate(152348, 595130),
                new Coordinate(152421, 595061),
                new Coordinate(152455, 595033),
                new Coordinate(152524, 595001),
                new Coordinate(152593, 594973),
                new Coordinate(152622, 594946),
                new Coordinate(152634, 594930),
                new Coordinate(152641, 594921),
                new Coordinate(152649, 594910),
                new Coordinate(152863, 594623),
                new Coordinate(152873, 594607)
            });
            var indexedLine = new LengthIndexedLine(closestLine);
            var projectedIndex = indexedLine.Project(closestCoordinate);
            var coordinateToAdd = indexedLine.ExtractPoint(projectedIndex);
            var line = new LineString(new[] { new Coordinate(152503,594904), coordinateToAdd });

            // Both assert fails...
            Assert.AreEqual(coordinateToAdd, line.Intersection(closestLine).Coordinate);
            Assert.IsFalse(line.Crosses(closestLine));
        }
```
Thanks.

**Comment by FObermaier** [comment]
You are right, the failing assertions are due to limitations of floating point arithmatic.
You have two choices:
1. Use a precisionmodel to make the `coordinateToAdd` and `line.Intersection(closestLine).Coordinate` precise and compare those points afterwards.
2. Add `coordinateToAdd` to both `line` and `closestLine`

**Comment by HarelM** [comment]
Thanks for the quick response!
How would I go about using ```crosses``` with ```PrecisionModel```? do I need to convert all the coordinates using the precision model on ```closestLine``` and then test crosses? 
note that all the coordinates on ```closestLine`` are integer values so I'm not sure I understand how this will work...?

**Comment by FObermaier** [comment]
But the intersection point is not an integer value. The `Crosses` predicate will not work unless you add `coordinateToAdd` to the `closestLine` as well.
[See example code](https://github.com/NetTopologySuite/NetTopologySuite/commit/e0b99def2af3637e19c961dd8fab4923efc79604).

**Comment by HarelM** [comment]
I'm confused. In the case you added to the tests the only way to make crosses work correctly is to add the relevant point to the line? that's the same as saying that crosses doesn't work correctly I think, or I'm misunderstanding something...
I'll describe my use-case and maybe you can explain what I did wrong:
What I want to do is to prolong a line string along a GPS trace.
I have a point (let's say in the middle of this GPS trace) and now I continue iterating over the GPS trace until I get to a predefined distance from an existing line.
What I want to do is to connect the GPS partial trace to the existing line but I want to make sure I don't cross any other lines including the line I want to connect to.
Here is an image I hope will help explain better - Black are exiting lines, red are the GPS recording points, Blue is the GPS line.
![image](https://cloud.githubusercontent.com/assets/3269297/23073305/ae04afdc-f53d-11e6-97a7-a4d7b134bf85.png)
The right most point is the closest to any existing line but if I connect the left GPS point to it I will end up crossing the other two lines.
In order to avoid that I try and project the right red point on each line and test if it crosses any other line. if it doesn't then I can be sure that I can use this GPS part.
Not sure I made myself clear enough... :-/
Here is the relevant code in case you are interested:
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.API/Executors/GpxProlongerExecutor.cs

**Comment by FObermaier** [comment]
What do you intend to do with the remaining LineString?

**Comment by HarelM** [comment]
Not sure which line you are referring to, the GPS trace will be presented to the user so he'll be able to add it to OSM database.
The rest of the existing lines are readonly and should not be manipulated since they are used to test against other GPS lines.
Also consider this case for crossing test:
![image](https://cloud.githubusercontent.com/assets/3269297/23117768/ea9c5e18-f759-11e6-9941-75300567cd03.png)
The intersection and crosses function must be aligned for this to work as for the above case I'll need to go over all intersection points and test if using them causes the new line to cross any existing lines.

**Comment by FObermaier** [comment]
I was just wondering if you do sth. with the remaining GPS trace, or not. Seems not.
In that case you can compute the intersection points of all the GPS trace with the present (fix) geometries (have a look at `PreparedGeometry`).
When you then use `LengthIndexedLine` and project those intersection points on it, the point with the least projection index is the one you are looking for.

I have found a fix for RelateOp when using a fixed/scaled precision model. I have issued a [pull request](https://github.com/locationtech/jts/pull/77), lets see what happens.

**Comment by HarelM** [comment]
Please let me know if and when this gets into NTS.
