### ISSUE TITLE
Shapefile writer performance improvements?

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/NetTopologySuite#154]
I'm working on a tool for a client of mine converting OSM data into a shapefile that can easily consumed for routing and analytics.

Basically I have 2 steps:

1. Building a routerdb with [Itinero](https://github.com/itinero/routing).
2. Writing the result as a shapefile.

Now Itinero can handle the entire world, the planet OSM file, and build a database for the entire world. I don't think it's even possible to attempt writing this to a shapefile but I am having performance issues, for example for a country like germany it takes about 10 hours (!) to write a shapefile with all german roads. Doing this in Itinero-only takes about 30 mins.

I have checked and the bottleneck clearly is the shapefile writer.

So I'm wondering, is it possible to improve the performance of writing a shapefile? Can anyone give me some pointers on where to get started? For example, why does it iterate twice over the source? Any way to compress the result? Germany now give me a shapefile of 70GB (!).

I'm more than willing to contribute the improvements to NTS as usual, but any help getting started would be appreciated.

**Comment by DGuidi** [comment]
> Any way to compress the result? Germany now give me a shapefile of 70GB (!).

My2Cents: shapefile is a binary format with a well defined standard, so size of file is directly related to size of data. maybe you can (I think):

1. simplify your geometries
2. create your own "ShapefileZipWriter" that directly generates a zipped archive of a shapefile (if possible)

**Comment by airbreather** [comment]
Oh... does [BigEndianBinaryWriter](https://github.com/NetTopologySuite/NetTopologySuite/blob/817b88ba4681437d3b5bd0561994e5b42d2fb831/NetTopologySuite.IO/NetTopologySuite.IO.GeoTools/BigEndianBinaryWriter.cs) need the same performance improvement I did in c6d2ccd?  I see some calls to that class's naive WriteIntBE method.  Maybe the [corresponding reader](https://github.com/NetTopologySuite/NetTopologySuite/blob/817b88ba4681437d3b5bd0561994e5b42d2fb831/NetTopologySuite.IO/NetTopologySuite.IO.GeoTools/BigEndianBinaryReader.cs) too...

**Comment by airbreather** [comment]
If that doesn't help, could you please provide sample code and maybe a sample serialized RouterDb file so we can look at the same thing?  I've got an old serialized routerdb file, but it dates back to the times when Itinero was part of OsmSharp, and I'm guessing you've changed stuff since then, and I really don't want to dedicate CPU time to rerun odp assuming it's still as slow as it was back then.

If I can just get that little bit of help, I'd love to spend time agonizing over this one.

**Comment by xivk** [comment]
I'll try and build a sample application and do some profiling too, stay tuned. :-)

**Comment by airbreather** [comment]
This issue was moved to NetTopologySuite/NetTopologySuite.IO.ShapeFile#2
