### ISSUE TITLE
GeometryCollection.Count value does not match number of elements returned by iterating GeometryCollection.GetEnumerator()

### ISSUE THREAD

**Issue by jamesra** [NetTopologySuite/NetTopologySuite#155]
Hello, I was debugging today and traced my troubles back to a behavior different than every other library I've used in C#.

In short, enumerating a GeometryCollection creates an enumerator which will include the GeometryCollection object itself.  The GeometryCollection's Count property returns only the number of geometries in the collection.

At a minimum the count of the collection should return the actual number of elements in an enumerator of the same collection.  This is a stripped down version of how I encountered the bug:

````
DelaunayTriangulationBuilder builder = new NetTopologySuite.Triangulate.DelaunayTriangulationBuilder();
Coordinate[] coords = Verticies.Select(p => new Coordinate(p.X, p.Y)).ToArray();
builder.SetSites(coords);
GeometryFactory factory = new GeometryFactory();
IGeometryCollection triangles = builder.GetTriangles(factory);

int numLoops = 0;
foreach (IGeometry tri in triangles)
{
    numLoops++;
}

//This assertion will fail
System.Diagnostics.Debug.Assert(numLoops == triangles.Count);
````

Intuitively the default enumerator of a collection should iterate only the collection.  I suggest making the GetEnumerator function be consistent with the behavior seen throughout C#.  The specialized enumerator should be returned from a separate function with a clearer name.

The source is here:
[GeometryCollectionEnumerator.cs](https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite/Geometries/GeometryCollectionEnumerator.cs)
[GeometryCollection](https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite/Geometries/GeometryCollection.cs
)

Thank You

**Comment by DGuidi** [comment]
what you're describing it's the default (and documented) jts behavior, so I wan't fix this.
Anyway, you're correctly pointed me to **GeometryCollection's Count** property, a later addiction from MonoGIS old project but part of **IGeometryCollection** interface.
Makes sense to me to modify "Count" to return  "NumGeometries + 1", but this looks a breaking change...

> Intuitively the default enumerator of a collection should iterate only the collection. 

Yey, you're right: more intuitive but not what JTS api does.

**Comment by DGuidi** [comment]
or maybe a better xml doc that explain what count returns
