### ISSUE TITLE
Newly created Shapefiles have invalid Last Update Date in header

### ISSUE THREAD

**Issue by NimbleKelly** [NetTopologySuite/NetTopologySuite#159]
The LastUpdateDate property for DbaseFileHeader does not have a setter and no way to initialize it other than reading it from an existing file.  As a result, it is initialized with a default date of 01/01/0001.  When it is written out in the header, 1900 is subtracted from it.  This causes an invalid year, month, and day to be written and no way to specify any other value.

**Comment by airbreather** [comment]
Can this be closed?
