### ISSUE TITLE
Unable to update NetTopologySuite.IO.GeoJSON to pre-release version

### ISSUE THREAD

**Issue by peetw** [NetTopologySuite/NetTopologySuite#161]
Hi, I'd like to upgrade to the `1.15.0-pre3` version, but it looks like the dependencies have been incorrectly specified as I get the following error:

    PM> Update-Package NetTopologySuite.IO.GeoJSON -Version 1.15.0-pre3

    Attempting to gather dependency information for multiple packages with respect to project 'ProjName', targeting '.NETFramework,Version=v4.6.2'
    Gathering dependency information took 1.16 sec
    Attempting to resolve dependencies for multiple packages.
    One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'NetTopologySuite.IO.GeoJSON 1.14.0'
    Update-Package : Unable to find a version of 'Newtonsoft.Json' that is compatible with 'NetTopologySuite.IO.GeoJSON 1.15.0-pre3 constraint: Newtonsoft.Json (= 9.0.0)'.
    At line:1 char:1
    + Update-Package NetTopologySuite.IO.GeoJSON -Version 1.15.0-pre3
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
        + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
     
    Time Elapsed: 00:00:01.1980621

As far as I'm aware, there isn't a `9.0.0` release for Newtonsoft.Json (the only 9.x release is 9.0.1). Therefore I believe that the dependency should either be `>= 9.0.0` or `= 9.0.1` - which would be preferred if I make a PR?

**Comment by FObermaier** [comment]
I'd prefer `= 9.0.1`

**Comment by peetw** [comment]
Whilst I'm changing the nuspec file, should I also update the NTS dependency to be `>= $version$` rather than `= $version$`, to match the nuspec files for the other NTS.IO.* packages?

**Comment by peetw** [comment]
I also note that the version of Newtonsoft.Json currently used by the projects in the NTS solution is `7.0.1` - is there any reason it can't be updated to `9.0.1`?
