### ISSUE TITLE
Serialization issue with GeoJson Point

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#162]
The following test throws exceptions:
```
        [Test]
        public void SerializationTest()
        {
            var featureCollection = new FeatureCollection { Features = { new Feature(new Point(new Coordinate(1, 2, 3)), new AttributesTable()) } };
            using (var outputStream = new MemoryStream())
            {
                var writer = new StreamWriter(outputStream);
                var jsonWriter = new JsonTextWriter(writer);
                var serializer = GeoJsonSerializer.Create();
                serializer.Serialize(jsonWriter, featureCollection);
                jsonWriter.Flush();
                Assert.IsNotNull(outputStream.ToArray());
            }
        }
```
The following is the exception:
```
Newtonsoft.Json.JsonSerializationException : Self referencing loop detected for property 'CoordinateValue' with type 'GeoAPI.Geometries.Coordinate'. Path 'Features[0].Geometry.Coordinates[0]'.
   at ...
```

This is the code I previously used to change feature collection to string and then to bytes...
Not sure If I should do something else since this is .Net Core...?
Happens on net_refactoring branch, haven't tested stable version.

**Comment by HarelM** [comment]
I now understand what is causing this error:
![image](https://cloud.githubusercontent.com/assets/3269297/24124352/f5f50f20-0dcb-11e7-89f0-7423394ce1fa.png)
```GeoJsonSerializer.Create()``` is calling the ```JsonSerializer.Create()``` which is what's causing the above bug... 
A better message here would've avoided this issue...

**Comment by DGuidi** [comment]
what message you're suggesting?

**Comment by HarelM** [comment]
Use GeojsonSerializer.CreateDefault() or other overloads which receive parameters.
I don't know... There should be a way to prevent future developers from using the incorrect static method...

**Comment by DGuidi** [comment]
so you suggesto to add a deprecate attribute to GeoJsonSerializer.Create() ?

**Comment by HarelM** [comment]
I don't think you can since this is a static method derived from the parent class, this is what confused me... :-/

**Comment by airbreather** [comment]
This issue was moved to NetTopologySuite/NetTopologySuite.IO.GeoJSON#4
