### ISSUE TITLE
create polygon by coordinate with hole

### ISSUE THREAD

**Issue by sendreams** [NetTopologySuite/NetTopologySuite#163]
coordinates:
116.404595, 36.534432;116.406205, 36.577365;116.41287, 36.585614;116.41884, 36.607899;116.417584, 36.620766;116.410142, 36.630537;116.417533, 36.66282;116.413105, 36.670589;116.413657, 36.712957;116.405428, 36.715675;116.391886, 36.731949;116.411816, 36.757145;116.405951, 36.763872;116.406696, 36.778644;116.393349, 36.801346;116.420364, 36.861317;116.424712, 36.867912;116.433941, 36.871425;116.424583, 36.889059;116.426619, 36.90705;116.43328, 36.91149;116.439948, 36.911914;116.447854, 36.909557;116.459176, 36.899707;116.45653, 36.907382;116.459746, 36.911725;116.453639, 36.921774;116.449372, 36.922979;116.449127, 36.929227;116.45175, 36.935866;116.473372, 36.949401;116.445557, 36.978567;116.436113, 36.98365;116.402557, 36.982329;116.383898, 36.97202;116.337438, 36.975638;116.303774, 37.004035;116.232048, 37.028784;116.237175, 37.021193;116.233779, 37.003018;116.222069, 36.99139;116.214404, 36.971647;116.19131, 36.968397;116.179602, 36.954016;116.176492, 36.92756;116.152867, 36.917035;116.132552, 36.898653;116.117826, 36.90035;116.098317, 36.889617;116.032349, 36.899871;116.012312, 36.892519;115.984327, 36.895317;115.960688, 36.890799;115.950363, 36.898489;115.922599, 36.897881;115.905247, 36.910252;115.892263, 36.914025;115.865078, 36.909463;115.854471, 36.917815;115.783658, 36.918526;115.765237, 36.922335;115.745856, 36.909768;115.740903, 36.903196;115.730569, 36.898485;115.717805, 36.886201;115.710823, 36.868859;115.696138, 36.852555;115.697344, 36.834805;115.689436, 36.820182;115.665974, 36.816842;115.628378, 36.798991;115.596029, 36.789424;115.582745, 36.781421;115.56086, 36.782166;115.543273, 36.778269;115.53798, 36.780316;115.533401, 36.778056;115.532789, 36.76896;115.511645, 36.775076;115.497244, 36.766268;115.485107, 36.763361;115.484208, 36.753554;115.457731, 36.720735;115.451085, 36.700874;115.423081, 36.690191;115.413848, 36.670547;115.395199, 36.661631;115.39173, 36.648447;115.383825, 36.637733;115.347262, 36.605975;115.347928, 36.601518;115.357042, 36.600905;115.355326, 36.590486;115.352258, 36.587257;115.341896, 36.587733;115.333069, 36.553335;115.302025, 36.527136;115.301716, 36.511096;115.288542, 36.493387;115.288193, 36.485213;115.299499, 36.47984;115.296108, 36.474778;115.299564, 36.465813;115.306495, 36.470349;115.312817, 36.467846;115.30929, 36.462842;115.316821, 36.438815;115.301019, 36.418094;115.348917, 36.404681;115.351881, 36.367203;115.356226, 36.358704;115.368252, 36.351434;115.381128, 36.33409;115.363629, 36.324874;115.363225, 36.315316;115.376838, 36.314095;115.385038, 36.324691;115.397992, 36.324788;115.410932, 36.331356;115.426062, 36.329234;115.430881, 36.321079;115.434347, 36.290179;115.4748, 36.26794;115.484002, 36.247965;115.482389, 36.226675;115.485502, 36.207798;115.482482, 36.197579;115.491835, 36.145451;115.489609, 36.122436;115.464119, 36.0729;115.456347, 36.065368;115.456471, 36.029641;115.45347, 36.017432;115.416682, 36.006176;115.400214, 35.995504;115.393891, 35.980173;115.373662, 35.979764;115.369039, 35.976545;115.35991, 35.945128;115.373618, 35.929027;115.371589, 35.90245;115.365128, 35.889462;115.346964, 35.873165;115.345388, 35.853687;115.350604, 35.843362;115.342336, 35.820929;115.341479, 35.802957;115.369789, 35.784982;115.37839, 35.796328;115.384685, 35.797264;115.414079, 35.815234;115.424841, 35.831379;115.435815, 35.837976;115.458511, 35.867032;115.478174, 35.873924;115.489007, 35.88261;115.523426, 35.893589;115.547692, 35.897861;115.592428, 35.925631;115.6152, 35.929942;115.648802, 35.924597;115.654451, 35.926581;115.66042, 35.934164;115.674694, 35.933167;115.698467, 35.939003;115.707463, 35.953703;115.738899, 35.952801;115.774951, 35.965346;115.790976, 35.983071;115.784829, 35.990803;115.790344, 35.993428;115.794629, 35.990972;115.799035, 35.992463;115.815835, 36.014838;115.843072, 36.017212;115.854862, 36.009427;115.868183, 36.008744;115.874661, 36.019868;115.897121, 36.0301;115.906003, 36.032318;115.92514, 36.024876;115.943355, 36.037931;115.956756, 36.043146;115.999365, 36.051657;116.030863, 36.074222;116.064, 36.111153;116.097, 36.118315;116.106229, 36.117689;116.118963, 36.125142;116.124693, 36.138147;116.131543, 36.143126;116.167785, 36.146553;116.173983, 36.15684;116.17315, 36.178062;116.22872, 36.175659;116.264307, 36.215474;116.287313, 36.233988;116.291969, 36.247026;116.314428, 36.269405;116.334181, 36.298365;116.354602, 36.302959;116.41256, 36.328233;116.444515, 36.326913;116.458133, 36.347972;116.490108, 36.3461;116.492467, 36.35568;116.50323, 36.364891;116.509276, 36.381026;116.534897, 36.396627;116.552106, 36.414619;116.550656, 36.423527;116.519869, 36.431738;116.51761, 36.442985;116.510357, 36.450525;116.462189, 36.459565;116.461275, 36.467665;116.468016, 36.48582;116.455082, 36.492019;116.449497, 36.503561;116.441516, 36.506462;116.433159, 36.515639;116.404595, 36.534432,115.506625, 35.9227;115.512617, 35.923937;115.514418, 35.910699;115.505309, 35.900817;115.497888, 35.903;115.491419, 35.911838;115.495619, 35.917374;115.506625, 35.9227

![image](https://cloud.githubusercontent.com/assets/4160051/24131182/fe4bd0e4-0e27-11e7-9a34-dfd8d743cff1.png)

use below code will throw exception: points must form a closed linestring
ILinearRing ring = new LinearRing(coords.ToArray());
return new Polygon(ring);
// new GeometryFactory().CreatePolygon(coordinateArray) // not working too

is any way to create a Polygon with hole?

**Comment by DGuidi** [comment]
you can use IGeometryFactory.CreatePolygon(ILinearRing shell, ILinearRing[] holes)

**Comment by sendreams** [comment]
@DGuidi i know this api, but the real problem is how to finding the hole from coordinates.

**Comment by sendreams** [comment]
the third party api just giving me some coordinates, i don't know which of them will contains hole. so i need to finding the hole before createing Polygon. thanks.

**Comment by DGuidi** [comment]
have you tried with [PolygonBuilder](https://goo.gl/r73LPz)?

**Comment by sendreams** [comment]
not yet, i don't familiar with this class, i will try late. can you show me some code snippet?

**Comment by sendreams** [comment]
not yet, i don't familiar with this class, i will try late. can you show me some code snippet?

**Comment by sendreams** [comment]
i have found the hole which just beginning at "116.404595, 36.534432,115.506625, 35.9227" which has 2 coordinate.

**Comment by DGuidi** [comment]
hole should be a linearring, so at least with 4 coordinates (first and last are the same)
