### ISSUE TITLE
NetTopologySuites Linear Referencing Length Indexed Line

### ISSUE THREAD

**Issue by alejandropadillav1** [NetTopologySuite/NetTopologySuite#168]
Hi to all. 

We are using the NTS in C#, i'm working about the Linear Referencing, but I have one guestion.

In this LinearReferencing is possible to set the StartIndex?. for example.

The line's distance is 200, the start Index should start from 20 and the EndIndex should be 220. it is possible?, if yes, could you help me?.

I have created all the Coordinates point, then I create the Line using LineString, with the M parameters. so I create new a LengthInexedLine and implemented the LineString geometry, but in this LengthIndexedLine always has a startIndex = 0 and the endIndex the distance of the Line, isn't right?.

What do I do to solve this issues?

Regards.

**Comment by FObermaier** [comment]
This is by design. I don't see the use case for this.
