### ISSUE TITLE
.NET 2.0 and 3.5 Builds Are Broken

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#169]
Steps to reproduce:
1. Clone latest `master` (c65a7ba at the time of writing).
2. `msbuild TeamCity.targets /t:BuildRelease20`

Expected: .NET 2.0 build succeeds.
Actual: failure, details look something like:

      Index\KdTree\KdTreeExtensions.cs(16,52): error CS1110: Cannot define a new extension method because the compiler required type 'System.Runtime.CompilerServices.ExtensionAttribute' cannot be found. Are you missing a reference to System.Core.dll?

Suggested fix: pull in [ExtensionAttribute.cs](https://github.com/dotnet/coreclr/blob/1413d462631f0d9bfc4c3df3cb5371e23bcbd8d9/src/mscorlib/shared/System/Runtime/CompilerServices/ExtensionAttribute.cs) and put it under Utilities/FrameworkReplacements/Runtime/CompilerServices

Doing that and rebuilding gets us another error:

    IO\Streams\ByteStreamProvider.cs(94,23): error CS1061: 'Stream' does not contain a definition for 'CopyTo' and no extension method 'CopyTo' accepting a first argument of type 'Stream' could be found (are you missing a using directive or an assembly reference?)

Suggested fix: semi-inline:

```cs
// 81920: largest multiple of 4096 that doesn't go on the LOH.
// 4096 is a common internal buffer size.
byte[] array = new byte[81920];
int count;
while ((count = input.Read(array, 0, array.Length)) != 0)
{
    ms.Write(array, 0, count);
}

return ms.ToArray();
```

However, after fixing that, both `BuildRelease20` and `BuildRelease35` fail to build NetTopologySuite.IO.GeoJSON with 112 errors.  A sample:

    Converters\AttributesTableConverter.cs(5,7): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)

I do not have a suggested fix for this off the top of my head.

**Comment by airbreather** [comment]
I came across this when working on #110... I spent a little too long trying to figure out why a unified multi-targeted single NetTopologySuite project was failing on the `net20` target framework.

**Comment by DGuidi** [comment]
maybe referenced Newtonsoft.Json dll doesn't targets .net20?

**Comment by airbreather** [comment]
9.0.1 does target .NET 2.0.  I'm guessing the problem has to do with the HintPath changes from ee51f24.

It used to be:

    <HintPath>..\..\packages\Newtonsoft.Json.7.0.1\lib\$(JSON)\Newtonsoft.Json.dll</HintPath>

Now it's:

    <HintPath>..\..\packages\Newtonsoft.Json.9.0.1\lib\net40\Newtonsoft.Json.dll</HintPath>

Maybe the fix would be to just bring back `$(JSON)` in there?

**Comment by FObermaier** [comment]
If you want to experiment/work on #110, @airbreather , there has a lot of work been done in the branch `Refactor_for_NETStandard` 

Nonetheless, bringing back `$(JSON)` in the hint path seems to be the right fix for `master`.

**Comment by airbreather** [comment]
@FObermaier: I did see that, but noticed that it uses the old preview tooling's `project.json` style, so the majority of the changes would have to be revisited anyway for it to work nicely with newer versions of Visual Studio starting with VS2017.
