### ISSUE TITLE
Polygonizer fails splitting a triangle vertically

### ISSUE THREAD

**Issue by ConPac** [NetTopologySuite/NetTopologySuite#171]
Hi,
Using NTS 1.14.0 (and 1.15.0-pre2) with GeoAPI 1.7.4 (and 1.7.5-pre2)

1. Given this geomList:
Count = 2
    [0]: {LINESTRING (0 0, 1 1, 2 0, 0 0)}
    [1]: {LINESTRING (1 2, 1 -1)}

1. Testing this code:
```
var pz = new Polygonizer();
pz.Add(geomList);
var ps = pz.GetPolygons();
```

3. Expected result is ``ps.Count == 2`` but ps has this:
Count = 1
    [0]: {POLYGON ((0 0, 1 1, 2 0, 0 0))}

Am I missing something?

**Comment by FObermaier** [comment]
This is not a bug, it is a feature.
Unioning two adjacent polygons whose borders touch partially will result in one polygon as well.

**Comment by ConPac** [comment]
Well, it seems I oversimplifized my input data.
Processing the input geometries through a LineMerger, I have this new test case:

1. Given this geomList:
Count = 5
    [0]: {LINESTRING (1 0, 1 -1)}
    [1]: {LINESTRING (1 1, 2 0, 1 0)}
    [2]: {LINESTRING (1 1, 1 0)}
    [3]: {LINESTRING (1 0, 0 0, 1 1)}
    [4]: {LINESTRING (1 2, 1 1)}

1. Testing this code:
```
var pz = new Polygonizer();
pz.Add(geomList);
var ps = pz.GetPolygons();
```

3. Expected result is ps.Count == 2 but ps has this:
Count = 1
    [0]: {POLYGON ((1 1, 1 0, 0 0, 1 1))}

Tested with
* NTS 1.9.0
* NTS 1.12.0, GeoAPI 1.6.0
* NTS 1.13.3.2, GeoAPI 1.7.3.1

Gives the expected result in ps:
Count = 2
    [0]: {POLYGON ((1 1, 2 0, 1 0, 1 1))}
    [1]: {POLYGON ((1 1, 1 0, 0 0, 1 1))}

**Comment by FObermaier** [comment]
Does
```C#
var pz = new Polygonizer(true);
pz.Add(geomList);
var ps = pz.GetPolygons();
```
yield the desired result? There (used ?) to be an error in the initialization code. The default constructor should have set `_extractOnlyPolygonal` to true, but it did not.

What are you trying to achieve anyway? For splitting a polygon in by a linestring see [this](https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite.Samples.Console/Operation/Polygonize/SplitPolygonExample.cs).

**Comment by ConPac** [comment]
Hi Felix,

Using the overloaded constructor doesn't give the desired result, which is the same result as previous versions.

And yes, the method where I encountered this error splits a multipolygon by a linestring. I'll give a try to the linked example.

Thanks for your support.
