### ISSUE TITLE
the userData prop can not be reserved in OverlayOp

### ISSUE THREAD

**Issue by sendreams** [NetTopologySuite/NetTopologySuite#174]
```csharp
Point pt1 = new Point(c1);
Point pt2 = new Point(c2);
pt1.UserData = "index1";
pt2.UserData = "index2";
MultiPoint mp = new MultiPoint(new IPoint[] { pt1 , pt2 });
LineString line = new LineString(new Coordinate[] { c1, c2 });
IGeometry geo = OverlayOp.Overlay(mp, line, SpatialFunction.Intersection);
```

the except result will be a multiPoint geometry, but each Point in multiPoint is a new object which is not the original object. if can resolve the source Point object will be nice.

**Comment by airbreather** [comment]
I've reformatted the code and made no other changes.

What's the use case for this?  I assume JTS doesn't preserve user-data here either, and core NTS is very hesitant to deviate from JTS, so you might have more luck if you can convince JTS to support this.

**Comment by DGuidi** [comment]
> core NTS is very hesitant to deviate from JTS

yep, so maybe this issue should be marked as "won't fix"
