### ISSUE TITLE
GeometryTransform modifies source geometry

### ISSUE THREAD

**Issue by terribletim** [NetTopologySuite/NetTopologySuite#175]
In the following snippet, GeometryTransform unexpectedly modifies the **source** coord (GeoAPI.Geometries.Coordinate):

`rw = NetTopologySuite.CoordinateSystems.Transformations.GeometryTransform.TransformPoint(gf, new Point(coord), trans)`

I can clone the input geometry/coordinate to ensure the source coordinate is not modified, although I thought creating a new point would also achieve this. I have looked at the GeoApi and NTS code and still can't see how/why this is happening.... please could an enlightened person explain?

**Comment by airbreather** [comment]
I suspect that it's actually `trans` that's altering the input sequence.  Can you please share a more complete sample?

**Comment by kshahar** [comment]
Not sure if @terribletim is using ProjNet, but I am experiencing the same issue and the problem appears to be in the `MathTransform` object (i.e. in ProjNet, not NTS).  For more details: [MathTransform.Transform modifies the original ICoordinateSequence #26](https://github.com/NetTopologySuite/ProjNet4GeoAPI/issues/26).

**Comment by terribletim** [comment]
@FObermaier sorry for dropping the ball on this one

@kshahar Thanks for pointing this out - yes, I am also using ProjNet and I can now see it is actually ProjNet that is modifying the input geometry. 

I will close this thread and let discussion / explanation continue under ProjNet.
