### ISSUE TITLE
SnapRoundOverlayFunctions

### ISSUE THREAD

**Issue by Kortdag** [NetTopologySuite/NetTopologySuite#177]
Hi

There is a casting error in method EditGeometryCollection in GeometryEditorEx

In the latest release v1.14 the following cast throws an error

```csharp
if (collectionForType is IMultiPoint)
{
    return _targetFactory.CreateMultiPoint((IPoint[])geometries.ToArray());
}
if (collectionForType is IMultiLineString)
{
    return _targetFactory.CreateMultiLineString((ILineString[])geometries.ToArray());
}
if (collectionForType is IMultiPolygon)
{
    return _targetFactory.CreateMultiPolygon((IPolygon[])geometries.ToArray());
}
```

---------------------------------------------------
Changing it using LINQ seems to do the trick

```csharp
if (collectionForType is IMultiPoint)
{
    return _targetFactory.CreateMultiPoint(geometries.Cast<IPoint>().ToArray());
}
if (collectionForType is IMultiLineString)
{
    return _targetFactory.CreateMultiLineString(geometries.Cast<ILineString>().ToArray());
}
if (collectionForType is IMultiPolygon)
{
    return _targetFactory.CreateMultiPolygon(geometries.Cast<IPolygon>().ToArray());
}
```
----------------------------------------------------

**Comment by FObermaier** [comment]
Could you provide a sample test case to prove your point.

**Comment by Kortdag** [comment]
Sure. 
E.g. for the multipolygon case - same for the other geometry types.


[Test]
        public void Test()
        {
            var reader = new WKTReader();
            var g1 = reader.Read("MULTIPOLYGON (((30 20, 45 40, 10 40, 30 20)),((15 5, 40 10, 10 20, 5 10, 15 5)))");
            var g2 = reader.Read("MULTIPOLYGON (((40 40, 20 45, 45 30, 40 40)),((20 35, 10 30, 10 10, 30 5, 45 20, 20 35),(30 20, 20 15, 20 25, 30 20)))");
            SnapRoundOverlayFunctions.SnappedIntersection(g1, g2, 0.1);
        }


Partially stacktrace


System.InvalidCastException : Unable to cast object of type 'GeoAPI.Geometries.IGeometry[]' to type 'GeoAPI.Geometries.IPolygon[]'.
   at NetTopologySuite.Geometries.Utilities.GeometryEditorEx.EditGeometryCollection(IGeometryCollection collection) in c:\NetTopologySuite\NetTopologySuite.Lab\Geometries\Utilities\GeometryEditorEx.cs:line 290
   at

**Comment by airbreather** [comment]
Looks like this has been fixed, can it be closed?

**Comment by FObermaier** [comment]
`SnapRoundOverlay` functions superceeded by `OverlayNG`
