### ISSUE TITLE
Parsing GeoJSON issue related to Bounding Box

### ISSUE THREAD

**Issue by mstauber** [NetTopologySuite/NetTopologySuite#178]
https://gist.github.com/anonymous/9af101825f6e2bbf8b88bf6b0d711f04

```JSON
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "bbox": [
          -105.46875,
          38.788345355085625,
          -102.98583984374999,
          40.27952566881291
        ],
        "coordinates": [
          [
            [
              -105.46875,
              38.788345355085625
            ],
            [
              -102.98583984374999,
              38.788345355085625
            ],
            [
              -102.98583984374999,
              40.27952566881291
            ],
            [
              -105.46875,
              40.27952566881291
            ],
            [
              -105.46875,
              38.788345355085625
            ]
          ]
        ]
      }
    }
  ]
}
```

Parsing this GeoJSON results in the first Feature in the collection to have a null geometry. Was able to fix this instance by commenting out line 51 in EnvelopeConverter (bounding box) which was commented as advancing the token reader past the end of the array; which was likely already taken care of by the JArray deserialization above it.

**Comment by FObermaier** [comment]
The fix you propose may work for you, but doing so you break the case where the `bbox` is a property of the `feature` or `featurecollection`.

8dd60e1 should do.
