### ISSUE TITLE
Changes to the packages publishing and branching

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/NetTopologySuite#179]
I wanted to ask some feedback from the other maintainers here. I just setup a build in teamcity on the Itinero server. I've done this in a way very similar to what's happening in Itinero:

There are now two branches:
- master: should contain latest stable release.
- develop: the current prerelease version.

I have setup the build that it builds *and* publishes packages so it's now one push of a button to publish new packages. I also automated this so we can even publish after each commit with an increasing prerelease #.

So I wanted to ask some feedback:

- Is it ok to change the default branch to develop and use master only for the stable releases.
- Is it ok to publish a package after every commit to develop? This would be prerelease packages.

Releasing would be as simple as merging to master and pushing, every fix will be testable by using the prerelease nuget packages.

**Comment by DGuidi** [comment]
+1 for me, if you feel comfortable with this.

take a look also to travis ci [build](https://travis-ci.org/NetTopologySuite/NetTopologySuite)

**Comment by xivk** [comment]
Yes, travis is the way to go, and we should keep it, but with a 'private' CI system we can publish the packages automatically...

**Comment by FObermaier** [comment]
@xivk 
Merging from develop or any other branch into master will lead to a new stable release package on nuget?
I'm not sure if I would second that. Getting prerelease packages automatically off a develop branch is fine with me.    
Do we have to review the privileges for that, I mean who can merge pull-requests and shouldn't or vice versa..

**Comment by xivk** [comment]
I would merge pull-requests into develop and only a core group can merge with master. Look at it like this:

- development on develop -> prereleases.
- releases are on master -> we merge when we are confident develop is stable

Doesn't really change the process and we still have to actively push a button (merge with master) to create a release. This also implies changing the default branch to 'develop'. I would do this after @airbreather merges his changes.

Just to be clear, for now I only setup the prerelease build I wanted to make sure we agree more or less on the most important change, changing the default branch to develop.

**Comment by airbreather** [comment]
> I would do this after @airbreather merges his changes.

Merged.

I like the idea of having changes pushed to `develop` automatically kicking off a process that results in a new suite of pre-release packages (NTS plus all the NTS.IO.* ones) getting pushed to NuGet.  Before setting that up, I'd advise revisiting the package version numbering scheme (suggestion: start appending strings to the end maybe in the format "YYYYMMDD-####" where #### is a number that counts up from 0001 and increases for each subsequent build that day) as well as the assembly versioning scheme (suggestion: start using the 4th integer in the assembly version number as a number that just goes up by 1 every time another build is done) for the sake of making it easier to resolve future issues that come in on GitHub... it seems like it would suck to have a zillion different versions out there where any given user might reasonably be using, and then have to diagnose a problem with it.

**Comment by xivk** [comment]
I'm not really in favor of adding dates.

We can always match a version # to commit if we want really to. We can have read-only access to the builds where everyone can see. But I don't think that will be necessary because using the prerelease packages, and submitting issues should always have the advice 'please update to the latest prerelease' because it may have been fixed already.

So issues on the prerelease packages will always be in sync with the latest state of develop, even issues on master should be reproduced against the latest prerelease.

**Comment by xivk** [comment]
**The automatic build from develop is now setup and active**

Just a small addition to the previous comment, we need leading zero's in the packages otherwise 10 < 9, check the packages list (I just published pre10):

https://www.nuget.org/packages/NetTopologySuite

I suggest: 
- [ ] Hiding packages pre1-pre9 (the packages are still there, just not visible, searchable anymore but restoring them still works. Just saying this won't break anyones projects)
  **I don't have access to do this, who does?** @DGuidi @FObermaier 
- [x] Republish starting from 011, already active.

**Comment by DGuidi** [comment]
> Hiding packages pre1-pre9 

looks I can only delete packages...

**Comment by xivk** [comment]
Perfect for https://www.nuget.org/packages/NetTopologySuite 👍 

But this also needs to be done for all the other packages... :-)

**Comment by airbreather** [comment]
> But this also needs to be done for all the other packages... :-)

Done.

**Comment by DGuidi** [comment]
yep. I forget other nuget packages... thanks @airbreather

**Comment by airbreather** [comment]
I've gone through and unlisted the -pre10 NetTopologySuite.* packages, since they had the same problem after the auto-published -pre0xx packages.

Hopefully after doing the same for any auto-built GeoAPI / ProjNet4GeoAPI packages, that should be the last time we need to do manual intervention on this.

**Comment by airbreather** [comment]
@xivk did you ever get around to setting up that 'private' CI system to automatically publish packages after pushes to `develop`, or is it still a manual thing?

**Comment by xivk** [comment]
That was up-and-running but something seems to be wrong with my teamcity instance.

**Comment by airbreather** [comment]
OK.  Would I mess up TeamCity's ordering if I pushed a manual package with the #186 fix?

**Comment by xivk** [comment]
Shouldn't be that big of an issue if you publish manually. The next build will just fail... 

I got it back up now, for some reason the DB didn't start. Fixed now. Will check if it's building now... did you merge with develop?

**Comment by airbreather** [comment]
Yes, the fix is in `develop`.

**Comment by xivk** [comment]
Should have run now...

**Comment by xivk** [comment]
BTW: I'll give the maintainers here access to the server here, I just need to configure some stuff before I do so.

**Comment by xivk** [comment]
The rest of this issue is being discussed in https://github.com/NetTopologySuite/NetTopologySuite/issues/199
