### ISSUE TITLE
LineString intersection return empty

### ISSUE THREAD

**Issue by sendreams** [NetTopologySuite/NetTopologySuite#180]
have two line and one of them is extended to another in autocad. so i think these two line will be has intersection point. but just finding empty by NTS. is any error here?

```csharp
private void TestFindIntersection() {
    const string ls1Wkt = @"LINESTRING (500252.36136968032 3268279.9946693764, 500197.63371806522 3268255.4002767489)";
    const string ls2Wkt = @"LINESTRING (499815.091 3269179.8250000011, 500224.99754436983 3268267.6974732862)";

    IGeometryFactory factory = GeometryFactory.Default;
    WKTReader reader = new WKTReader(factory);
    IGeometry ls1 = reader.Read(ls1Wkt);

    IGeometry ls2= reader.Read(ls2Wkt);
    IGeometry pt = ls1.Intersection(ls2);    // return empty LINESTRING
}
```

<img width="858" alt="snap1" src="https://user-images.githubusercontent.com/4160051/28775264-a21c39f8-7623-11e7-8449-9adc39d7eca0.png">

**Comment by airbreather** [comment]
Reformatted the code above and made no other changes.

What does JTS do?  I suspect it's the same...

**Comment by sendreams** [comment]
@airbreather thank you for you reply. how can i found the touch point?

**Comment by DGuidi** [comment]
@sendreams are you sure lines are actually touching?

**Comment by DGuidi** [comment]
this test is ok with latest JTS code
```
public void testFindIntersection() throws Exception {
    String ls1Wkt = "LINESTRING (500252.36136968032 3268279.9946693764, 500197.63371806522 3268255.4002767489)";
    String ls2Wkt = "LINESTRING (499815.091 3269179.8250000011, 500224.99754436983 3268267.6974732862)";

    GeometryFactory factory = new GeometryFactory();
    WKTReader reader = new WKTReader(factory);
    Geometry ls1 = reader.read(ls1Wkt);
    Assert.assertNotNull(ls1);

    Geometry ls2 = reader.read(ls2Wkt);
    Assert.assertNotNull(ls2);
    
    Geometry ls = ls1.intersection(ls2); 	    
    Assert.assertNotNull(ls);
    Assert.assertEquals(LineString.class, ls.getClass());
    Assert.assertEquals("LINESTRING EMPTY", ls.toText());
}
```

**Comment by FObermaier** [comment]
This is a *precision issue*:
```C#
private void TestFindIntersection() {
    const string ls1Wkt = @"LINESTRING (500252.36136968032 3268279.9946693764, 500197.63371806522 3268255.4002767489)";
    const string ls2Wkt = @"LINESTRING (499815.091 3269179.8250000011, 500224.99754436983 3268267.6974732862)";

    IGeometryFactory factory = new GeometryFactory(new PrecisionModel(1000));
    WKTReader reader = new WKTReader(factory);
    IGeometry ls1 = reader.Read(ls1Wkt);

    IGeometry ls2= reader.Read(ls2Wkt);
    IGeometry pt = ls1.Intersection(ls2);    // returns non-empty point
}
```

**Comment by sendreams** [comment]
@FObermaier the original point sets is from autocad dwg file, these two line is drawing and extending by autocad, i think it really touching each other. in your test the precision change to 1000, its a good idea, but the precision is not enouth for me, if i change to 10000 will returning empty LineString too.

**Comment by FObermaier** [comment]
You can use the `SnapRound`ing part of the `NetTopologySuite.Lab` project:
```
var pt = ls1.SnappedIntersection(ls2, 1000000);
```
You have to [grab the relevant parts of the source yourself](https://github.com/NetTopologySuite/NetTopologySuite/tree/develop/NetTopologySuite.Lab/SnapRound) and include it in your project. There is no package for it at the moment.    
Unfortunately that isn't working in all cases either:
![image](https://user-images.githubusercontent.com/2065346/29570704-80fb1696-8757-11e7-80eb-d1a08de26b66.png)

**Comment by sendreams** [comment]
@FObermaier think you very much. it is not very perfect but is a another way.
