### ISSUE TITLE
ShapefileDataReader isn't available in 1.14

### ISSUE THREAD

**Issue by jdege** [NetTopologySuite/NetTopologySuite#182]
Latest version of NTS - Topology Suite - GeoTools in NuGet is 1.13.2.
Latest version of NTS - Topology Suite is 1.14.0.1.

They will not work together. GeoTools requires an older version of GeoAPI.

If you need to import shapefiles, you'll have to roll NTS back to 1.13.2.

**Comment by xivk** [comment]
You should be able to use these package together:

- NetTopologySuite 1.14.0
- NetTopologySuite.IO 1.14.0.1

**Comment by DGuidi** [comment]
can we close this now?

**Comment by airbreather** [comment]
A bit more details, @jdedge, you should **not** be using the [`NetTopologySuite.IO.GeoTools package`](https://www.nuget.org/packages/NetTopologySuite.IO.GeoTools).

The `NetTopologySuite.IO.GeoTools` project that you see in this repository is distributed in the [`NetTopologySuite.IO`](https://www.nuget.org/packages/NetTopologySuite.IO) package, along with others that do not require special dependencies.

**Comment by xivk** [comment]
We should fix this... :-) see #184, with that issue open, I think we can close this one.
