### ISSUE TITLE
Please update dependency of Newton.Json for IO.GeoJson

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#186]
Can you please update the dependency of NTS.IO.GeoJSON to version 10.x and above?
It conflicts with other package I have...

**Comment by airbreather** [comment]
I think the nuspec should probably just change to allow higher versions of the package to satisfy the dependency.

**Comment by HarelM** [comment]
Provably...

**Comment by airbreather** [comment]
Does this problem still happen with version 2.0.0 of the .NET Core SDK?

If you're not sure which version you have, check the output of `dotnet --info` or `dotnet --version`.

**Comment by airbreather** [comment]
I'm unable to reproduce any problems using [this](https://gist.github.com/airbreather/6d7421c95896d821e32f6c7aa46ef484), so I ask because SDK 2.0.0 might have fixed that issue.

**Comment by HarelM** [comment]
I'm haven't migrated to 2.0 yet. I use 1.3.

**Comment by HarelM** [comment]
I saw that there was a release 7 days ago but json version is still (=9.0.1).
This is evident here:
https://www.nuget.org/packages/NetTopologySuite.IO.GeoJSON/1.15.0-pre017
Can this please be changed to (>=9.0.1)?
![image](https://user-images.githubusercontent.com/3269297/30333640-0f4ed074-97e6-11e7-9c0c-514446889443.png)

**Comment by HarelM** [comment]
Pretty please?

**Comment by airbreather** [comment]
I just pushed a commit that should probably fix it... we'll see in a few minutes when the auto-build finishes whether or not that did the trick (I'll reopen if it didn't).

I kinda figured that upgrading your tools to version 2.0.0 would make this go away for you or I'd have done it earlier.

**Comment by airbreather** [comment]
Latest packages now show up with the dependency as `>=` 9.0.1.
