### ISSUE TITLE
.NET Core no ShapefileReader and ShapefileDataReader

### ISSUE THREAD

**Issue by thinking-aloud** [NetTopologySuite/NetTopologySuite#187]
Thanks to @airbreather (#110 #183) NTS can be installed with NuGet in .NET Core.

I tried version 1.15.0-pre013 and realized inside NetTopologySuite.IO there is no **ShapefileReader** and **ShapefileDataReader**.
I have the same code with the same Nuget packets inside Mono and it works fine.

**Comment by airbreather** [comment]
Duplicate of #184 (see the second checkbox on that one).
