### ISSUE TITLE
Update GitHub wiki

### ISSUE THREAD

**Issue by DGuidi** [NetTopologySuite/NetTopologySuite#188]
When #110 is consolidated, github pages should be updated.
A list of things to do:
1. Update build page
1. Specific info for .net core, like [this stuff](https://github.com/NetTopologySuite/NetTopologySuite/issues/110#issuecomment-323555706)
1. ~~Update/Remove CI docs~~ Travis CI now looks [ok](https://travis-ci.org/NetTopologySuite/NetTopologySuite) :)
1. other?

**Comment by mhosman** [comment]
I can't find any docs. I don't know how to start with this library at all !!!

**Comment by DGuidi** [comment]
I suggest you to checkout the source and start from the [samples](https://github.com/NetTopologySuite/NetTopologySuite/tree/develop/NetTopologySuite.Samples.Console)

**Comment by mhosman** [comment]
Hey, @DGuidi thanks for the resources. Anyway, it could be great to have clear documentation for each case, centralized in one place. For example, this is the only friendly documentation that I found to start using this library: [https://docs.microsoft.com/en-us/ef/core/modeling/spatial](https://docs.microsoft.com/en-us/ef/core/modeling/spatial)

It could be great to have friendly step by step documentation like this one for every use case (for example how to convert a GeoJSON input to save it into the database).

**Comment by FObermaier** [comment]
Getting Started page added
