### ISSUE TITLE
IGeometryCollection.Union() method always throw "found non-noded intersection between LineA and LineB"

### ISSUE THREAD

**Issue by pucx** [NetTopologySuite/NetTopologySuite#195]
IGeometryCollection.Union() method always throw "found non-noded intersection between LineA and LineB",how to solve this problem? In fact,the two lines are intersect at a point. Or before to use Union() method ,need to call another method?Thanks.

**Comment by FObermaier** [comment]
Your input geometries are probably not valid. Set up a unit test to prove your point and make it available here.

**Comment by pucx** [comment]
The code,
`            var reader = new WKTReader();
            var g1 = reader.Read("LINESTRING (1906.5777217955911 3761.4006028729491 0, 1820.1198459579609 3839.2176014268771 0, 1724.1829042970785 3732.6277258992195 0, 1836.47005638876 3633.8642786028795 0, 1909.5549402346369 3727.4293504389934 0, 1906.5777217955911 3761.4006028729491 0, 1906.5777217955911 3761.4006028729491 0)");
            var g2 = reader.Read("LINESTRING (1772.4700756329694 3551.9299238938838 0, 1909.5549402347533 3727.4293504399247 0)");
            var g3 = reader.Read("LINESTRING (1836.47005638876 3633.8642786028795 0, 1909.5549402346369 3727.4293504389934 0)");
            var g4 = reader.Read("LINESTRING (1909.5549402347533 3727.4293504399247 0, 1906.5777217960572 3761.4006028729491 0, 1906.5777217960567 3761.4006028729491 0, 1759.2550748434733 3893.9993521915749 0, 1736.1762532913126 3908.717300510034 0, 1716.5827331371838 3926.352581448853 0, 1674.1569754525553 3924.0594879835844 0, 1674.1569754525553 3924.0594879835844 0, 1644.2142616524936 3889.674056951887 0, 1644.2142616524943 3889.6740569518879 0, 1614.9895297663172 3862.202278373763 0, 1564.1978788769925 3796.101987561211 0, 1564.197878876992 3796.101987561211 0, 1528.8682874125661 3747.0869175335392 0, 1534.7378848842927 3705.9028060180135 0, 1534.7378848842927 3705.9028060180135 0, 1737.3787323110737 3547.6174276559614 0, 1772.4700756353559 3551.9299238980748 0, 1772.4700756353559 3551.9299238980748 0, 1909.5549402347533 3727.4293504399247 0)");
            var g5 = reader.Read("LINESTRING (1772.4700756329694 3551.9299238938838 0, 1909.5549402347533 3727.4293504399247 0)");
            var geos = new List<IGeometry>();
            geos.Add(g1);
            geos.Add(g2);
            geos.Add(g3);
            geos.Add(g4);
            geos.Add(g5);

            GeometryFactory fact = new GeometryFactory();
            IGeometryCollection cols = fact.CreateGeometryCollection(geos.ToArray());
            var res = cols.Union();//throw error`
The error message is "NetTopologySuite.Geometries.TopologyException: found non-noded intersection between LINESTRING(1836.4700563882036 3633.8642786033688, 1909.5549402346369 3727.4293504389934) and LINESTRING(1836.470056388484 3633.8642786031223, 1909.5549402347533 3727.4293504399247) [ (1868.3541644227532, 3674.683100521946, NaN) ]".
How to solve this? Thanks.

**Comment by FObermaier** [comment]
The example does not throw any exception with the current codebase.
