### ISSUE TITLE
NuGet changes

### ISSUE THREAD

**Issue by DGuidi** [NetTopologySuite/NetTopologySuite#197]
I've received this email yesterday

"
Hello NuGet.org package author,   

NuGet.org has been growing fast. It is important to us and the NuGet community that developers can trust the packages submitted to NuGet.org. We are taking a series of steps to enhance security of the publishing process to NuGet.org that you can read more about on our [blog post](https://blog.nuget.org/20170809/NuGet-Fall-2017-Roadmap.html?utm_source=hs_email&utm_medium=email&utm_content=57264167&_hsenc=p2ANqtz-8ca7_xR-p-mqmtl-fS6OYNiNicTb7XuHl2EqS8O8yN5uSpUHsWLOsfbBQCp7rDh1uoSxO0mkMBBAqerySZWT0lYY2q2w&_hsmi=57264167). 

As a part of our roadmap, starting November 10th 2017, we will require package authors to use the latest version of the free NuGet client to push packages to NuGet.org. You can download and use the latest client (v4.1.0 or above) from [here](http://landinghub.visualstudio.com/e1t/c/*W6QkfMJ7txrNhW7FlPlm5cDW2b0/*W8Ljjc-2k_NmbN4YjtGJX5Zn30/5/f18dQhb0Smh-8YXMpvW8Xlp2N2qwv2rW4c9t_t2sC12yMf5bcbXD6prW7cmS1s8pCQ6vW4s18M11mZpqpW8yGqFy8nNzQrW50FdQH61SSZmW7dDxTN7mWsnXW7dzcsS51vDDWW56vHg569NG1wW6Pr3nq1TcntwW1njMtB6H5LfSW53X_Zp52YlfxW3_8mpl9fgwMTW4gDYD-84G36-W6wrLD39dChH8W2SbjqT2S9Y9SW5p2_j06ybRcNN6wPnK8mMSMzV6vy2F75SY2TW2MjPCJ2S0HQXW7rLZPP1gKjCfW4yDSFb7M1xm0W85Qh4C5pmq83W8Xq0Wf2r-ktWW7sNLz_11MynNW3MYtL84HrzTgN45Ly2MkwRN4W8b607B2PyX2VW2MlV4M7mvqVbW1Cr-RQ7GYMrrN3xxDzVJgtZZW9k6W4292B8SNW3NnNwM9c9yYGN6lL5YZVFKrdW6JyP9b6lRJl1w3xWwfq9Hxf38RdGV02). 

You can continue to consume packages published to NuGet.org using whatever clients you might already be using. You can also use any third-party client that you might already be using to push packages, but they will need to be updated to comply with our latest protocol as documented [here](http://landinghub.visualstudio.com/e1t/c/*W6QkfMJ7txrNhW7FlPlm5cDW2b0/*W4_1yQN6HKXlTW2lPBSM27r5p00/5/f18dQhb0S1Xm2WsJr2Sp6_5n6gDHW4TZwNv5grHTMW8nqWZm5Rds-_VpVxT957G0fKW3G1C5087GV7GF8NH7WVdnm2W36KRSr2fPXzMW87hvKm94hC3wW7hK8675j-TBDW4V9CM47tzQ3hW1pcZvG2KdFh-W4qSxqq3fH8bdW8bHBJr3-ZG4FW94lLCX13T6QQW7DhhMT47qS2XW716QP96bL1VqW4vJkrS5Y7gy7W3Mr-F93gd1L0N1mSFBy1pR2jW6bBZp01M3JRJW6C8pYH6gzlTkW7rHKWK3jfp5rW1bRLK98z76bkW7Gf0X-5LD7fcVQChkj8FGrbKW5VC1_8949q51W4L0F582-ldmNN40lhzndp2CsW8KkLQS7DJRr3W7gy6gM7PzbGxW7wVVJw6_bLcrW8MRzhr69RrHFW6Jt3Hs7TD6jJW7vjxQj2XW7LyN3H7cFFlyz39W6Z6vM44W7GDrW9d6JPK16tK99N7dmxl3KJ4SMN65_Qn_y0twzW3gGcL_271zyqf2nfYbH04). 

If you have additional questions, see this announcement on our GitHub repository or feel free to reach out to us at [support@nuget.org](mailto:support@nuget.org). 

Thanks, 
The NuGet Team 
"

Checked briefly, but I haven't see any "uploader" client...

**Comment by airbreather** [comment]
I've been using 4.3.0.4406.  @xivk is your CI instance up-to-date?  If so, then we should be good.

**Comment by xivk** [comment]
I don't think it's up-to-date but will be soon, I publish all my packages via that server so I will have to update, no worries.

Leaving this issue open until I can confirm.

**Comment by xivk** [comment]
This is done!
