### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/NetTopologySuite#199]
This is a call to the core project mainainers, can we agree on a way to manage stable releases? When do we publish, how do we decide this? How do we validate packages? What package do we publish?

Anyone have more experience with this? What I do in Itinero is as follows:

- Publish prerelease packages and encourage some people to use them for a while.
- Lock features and define a roadmap for what improvements go in the next release and what has to wait. Keep these increments small.
- Publish stables once confident the feature-locked prereleases work as advertised. Sometimes I remove stuff I'm not confident about just to be able to make a stable release.
- Quickfixes that are very critical are done right away when they don't incur breaking changes.

I think our release cycle should be shorter and we should have a roadmap, it again encourages usage and contributions and inspires confidence. Things are clear to everyone once we define this.

Another question is, should we always publish stables for all packages in this repo with the same version #? Wouldn't it be better to split off the IO projects for example into individual projects with their own version # and roadmap?

My suggestions are:

- Publish the prerelease packages as we do now.
- Define a milestone for each future release and add issues (bugs or new features) we want fixed/added before the next stable release, I think this is also being done.
- We discuss at what we want in or out together.
- Quickfixes that are very critical are done right away when they don't incur breaking changes (extremely rare).
- We document all this for contributors to find, and something we can point to when there are questions.

We try to release often so the dicussions on what to include or not is about months not years. Breaking changes take longer, new features can move fast.

I would split off all IO projects into seperate repos each with a dependency on the latest stable NTS release. If we release fast that shouldn't be a problem and the IO packages can also be maintained easier. If there is for example a new SQL server release or a new postgis version we should be able to update quickly.

**Comment by FObermaier** [comment]
As the core of this project is a port of JTS the aim has been to stay -version and functionality wise- in sync with  it, at least for the core library. I think this is a goal that should be persued for the *core* functionality.

Unfortuantly we are currently behind in terms of functionality, so I'd say there is no v1.15 release until we are up to date. If I'm not mistaken the folks at locationtech are about to release JTS v1.15 shortly, so, we'd have to catch up.

As for extensions to the project, that are not part of JTS, I'd propose to keep those in seperate projects until an equivalent/a port has made it into the JTS Core library. I support @xivk suggestion to seperate extension/io projects into seperate repositories

**Comment by xivk** [comment]
Thanks for your comment @FObermaier, we seem to be completely in sync on this. Just to mention them here (and I should have commented there sorry) here are the related issues:

https://github.com/NetTopologySuite/NetTopologySuite/issues/191 => issue to split out into seperate repos and keep core here.

https://github.com/NetTopologySuite/NetTopologySuite/issues/35 => guessing this is the one to update the core project to align with NTS.

So basically this means we have to update NTS to align with JTS, but that still leaves the discussion open about when we release stables. New suggestions:

- Publish the prerelease packages as we do now.
- Define a milestone for each JTS version, I think this is also being done.
- ~~We discuss at what we want in or out together.~~ => this is taken from JTS and we're keeping only that code here in the main repo, we release when they do or soon after.
- Quickfixes that are very critical are done right away when they don't incur breaking changes (extremely rare).
- We document all this for contributors to find, and something we can point to when there are questions.

**Comment by airbreather** [comment]
Can this be closed?
