### ISSUE TITLE
Pre-release NTS build against signed .netstandard GeoAPI

### ISSUE THREAD

**Issue by JoeRobich** [NetTopologySuite/NetTopologySuite#201]
Now that the pre-release GeoAPI has fixed it's .netstandard signing issue, It would be nice to have a new pre-release .netstandard NTS that is built using the signed GeoAPI dll. 

Currently I get errors that I need to reference a build of GeoAPI where PublicToken is null when using the latest versions of both.

**Comment by airbreather** [comment]
Sorry about that.  Should be fixed now, if you reference the latest versions of everything.

**Comment by JoeRobich** [comment]
That has indeed fixed my issue. The .NetStandard support is a great addition. Thanks for you hard work on these libraries!
