### ISSUE TITLE
ShapeFileDataReader Unable to parse shape file properly

### ISSUE THREAD

**Issue by Labbe21** [NetTopologySuite/NetTopologySuite#202]
I have a shape file generated with QGIS as a zip with dbf, prj, shp and shx files within it.

That file decoding is fine with QGIS Tool and https://mygeodata.cloud/converter/

However, ShapefileDataReader is not able to read all columns as expected.
Most of columns are parsed as ""\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0" with various number of occurences of "\0" while some columns are ok.

There is the file I'm trying to parse: https://ufile.io/p0zl3

I am using the last version of NetTopologySuite.

Could someone please help me with this issue, I'm running out of ideas to fix this problem.

**Comment by xivk** [comment]
What packages are you using exactly?

**Comment by airbreather** [comment]
This issue was moved to NetTopologySuite/NetTopologySuite.IO.ShapeFile#7
