### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by brennanfee** [NetTopologySuite/NetTopologySuite#207]
It looks like your intent was to license this with LGPL.  However, no licensing information is provided.  Add a license to be explicit in your choice.

**Comment by DGuidi** [comment]
see #196

**Comment by airbreather** [comment]
Are you suggesting that we move [`License.txt`](https://github.com/NetTopologySuite/NetTopologySuite/blob/2c0f950c7deb77ab780b28396cb11d63dc250a1d/NetTopologySuite/License.txt) somewhere higher up than where it is right now?  I'd support that...

**Comment by brennanfee** [comment]
Yes, that would definitely be better.  The "non-standard" standard forming on Github these days is to have a LICENSE file at the root of the project that clearly delineates the license.  It saves people having to hunt around or worse not following your wishes.

**Comment by FObermaier** [comment]
Please follow #196
