### ISSUE TITLE
Accessing GeometryConverter in NetTopologySuite.Converter.DotSpatial

### ISSUE THREAD

**Issue by abrousseau001** [NetTopologySuite/NetTopologySuite#208]
I have a test that I am converting from GeoApi geometries and DotSpatial geometries. I have pulled the NetTopologySuite.Converter.DotSpatial nuget package and installed it to my project's solution. I am unable to access the ToDotSpatial static method in order to complete my test. 

Is the namespace GeoApi.Geometries? I don't see the GeometryConverter. 

Any help with this issue would be most appreciated.

Thanks,
Adam Brousseau

**Comment by FObermaier** [comment]
The converter will only work up to DS 1.9.
For DS 2.0 the converter is obsolete.
