### ISSUE TITLE
found non-noded intersection between LINESTRING error merging geometries

### ISSUE THREAD

**Issue by lucamorelli** [NetTopologySuite/NetTopologySuite#209]
Hi, I'm trying to merge a few shape files that contains a single polygon, so I open a few shape files, load the geometries and try to merge them using something like 

`
geometrie[i] = NetTopologySuite.Operation.Overlay.OverlayOp.Overlay(
  geometrie[i],
  geometrie[i2],
  NetTopologySuite.Operation.Overlay.SpatialFunction.Union);
`
and 
`      var resulting = NetTopologySuite.Operation.Union.CascadedPolygonUnion.Union(geometrie);
`
often works, but sometimes when I try to merge some of these shape I obtain this error

`found non-noded intersection between LINESTRING(12.448591764796777 41.972860890341124, 12.448731325430401 41.972841479998927) and LINESTRING(12.449 41.973, 12.448695198462875 41.972831837041554) [ (12.448716431340822, 41.972843551495508, NaN) ]`

How can I fix this error?

**Comment by FObermaier** [comment]
To help you with this kind of question we need to see the input geometries that produce the error.
A unit test would be great.
