### ISSUE TITLE
ShapeGeometryType.LineStringZ

### ISSUE THREAD

**Issue by kladess** [NetTopologySuite/NetTopologySuite#210]
hi guys,

I want to create shapefile for my LineStringZ geometry features .

unlike other cases, like LineString or LineStringM , ... ,  i couldn't save LineStringZ to shapefile.

```C#
public static bool newShapefileFromOtherSchema(String existShpFile, String targetFolderPath, String targetName, List<IFeature> lsFeature)
{
    using (ShapefileDataReader existShapefileReader = 
                    new ShapefileDataReader(existShpFile, GeometryFactory.Default))
    {
        var fields = new DbaseFieldDescriptor[existShapefileReader.DbaseHeader.Fields.Length];
        var filepath = System.IO.Path.Combine(targetFolderPath, targetName);
        WriteFeatures(filepath, lsFeature, fields, ShapeGeometryType.LineStringZ, Encoding.UTF8);                   
        return true;
    }
}
```

so, i found comment line at below URL, why `ShapeGeometryType.LineStringZ ` is commented?

https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite.IO/NetTopologySuite.IO.GeoTools/Handlers/ShapeHandler.cs#L381

**Comment by FObermaier** [comment]
This is a naming issue
According to the [ESRI Shapefile Technical Description](https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf) there is no shapefile that contains just x-,y- and z-ordinate values. If you want to have z-ordinate values you get m-ordinate values, too. Please look at the geometry specification.

If `ShapeGeometryType.LineStringZ` is not marked obsolete, it should. This applies to the others as well.

**Comment by kladess** [comment]
@FObermaier Thank you for comment.  It is different from the topic.. Are you GDAL nuget repository owner. isn't it? 
please update  newer version gdal repository.
