### ISSUE TITLE
Question: Support for circles

### ISSUE THREAD

**Issue by pauldendulk** [NetTopologySuite/NetTopologySuite#212]
Just a question. In Mapsui I get frequent request for circles with a radius specified in meters. Since it is in meters, not map units, it would need a transformation to calculate intersections and other spatial operations. One way to go about this is to create a circular polygon with some helper method that takes the projection as argument. Is there any other functionality in NTS to support circles? Any suggestions on how to go about this?

**Comment by FObermaier** [comment]
There is no special support for circles.
Your approach is valid. You may want to consider [`PreparedGeometry`](https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/NetTopologySuite.Samples.Console/Features/UseOfIndexAndPreparedGeometry.cs)s as they offer better performance for one against many searches.

**Comment by pauldendulk** [comment]
Thank you very much.
