### ISSUE TITLE
NUnit Assert.AreEquals does not work for Multi* geometries

### ISSUE THREAD

**Issue by joriswit** [NetTopologySuite/NetTopologySuite#218]
### Description
When I create two MultiPoint geometries from the same WKT string, the NUnit AreEqual method fails.

The message is: Expected and actual are both <NetTopologySuite.Geometries.MultiPoint>
  Values differ at index [0]
  Expected: <POINT (20.564 46.3493254)>
  But was:  <POINT (20.564 46.3493254)>

I'm not sure if this is a NTS problem, a NUnit problem, or if it is as designed.

I found this problem because of the failing SharpMap test UnitTests.Converters.SqlServer2008.ConvertAndBack(). But since this is not really a SharpMap problem, I post it here.

### Steps to Reproduce
            const string Multipoint = "MULTIPOINT (20.564 46.3493254, 45 32, 23 54)";
            IGeometry p1 = new NetTopologySuite.IO.WKTReader().Read(Multipoint);
            IGeometry p2 = new NetTopologySuite.IO.WKTReader().Read(Multipoint);

            Assert.That(object.Equals(p1, p2)); // Succeeds
            Assert.That(p1, Is.EqualTo(p2)); // Fails
            Assert.AreEqual(p1, p2); // Fails

### System Configuration
I use the latest code from GitHub
Windows 10, Visual Studio 2017, NUnit 2 Test Adapter

**Comment by FObermaier** [comment]
Is this a new problem, I mean the same test with 1.14 did work out ok?

**Comment by joriswit** [comment]
I initially found the issue running from the SharpMap project, which references 1.14, so the problem is not new. The last change to the failing test is from 2012, so it possibly worked back then.

**Comment by FObermaier** [comment]
I assume the issue is within the `GeometryCollectionIterator`. It modifies `IEnumerator.Current` value on the getter.

**Comment by joriswit** [comment]
The Using works better, but now I'm getting a `StackOverflowException` when the two are not identical.
```cs
const string Multipoint = "MULTIPOINT (20.564 46.3493254, 45 32, 23 54)";
const string Point = "POINT (20.564 46.3493254)";
IGeometry p1 = new NetTopologySuite.IO.WKTReader().Read(Multipoint);
IGeometry p2 = new NetTopologySuite.IO.WKTReader().Read(Point);

Assert.That(p1, Is.EqualTo(p2).Using(new System.Comparison<IGeometry>((u, v) => u.Equals(v) ? 0 : 1)));
```

**Comment by FObermaier** [comment]
This is mainly a problem with NUnit, not with NetTopologySuite.

For types implementing `IEnumerable` but not `IEquatable` NUnit iterates over each item in the enumeration and does the comparison. Since all `GeometryCollection` classes implement IEnumerable this applies for `MultiPoint`s, too.

Unfortunately includes the `GeometryCollectionIterator` the aggregate geometry in the result as well. That is why we get a `StackOverflow`
