### ISSUE TITLE
Difference between WKB and PostGIS readers/writers

### ISSUE THREAD

**Issue by YohDeadfall** [NetTopologySuite/NetTopologySuite#220]
What is a difference between WKB and PostGIS readers/writers? What implementation should be used? They are mostly the same, except that WKB version isn't finished yet:

https://github.com/NetTopologySuite/NetTopologySuite/blob/543b56b20c8c83df9d7ae12cf2ac3a15590c349f/NetTopologySuite/IO/WKBWriter.cs#L330-L331

**Comment by FObermaier** [comment]
WKBReader reads Well-Known-Binary
PostGisReader reads PostGis extended Well-Known-Binary (EWKB), especially SRID-flag and value as well as  and z- and m-ordinate flags. Look at the way the [PostGisWriter writes the geometry header](https://github.com/NetTopologySuite/NetTopologySuite/blob/543b56b20c8c83df9d7ae12cf2ac3a15590c349f/NetTopologySuite.IO/NetTopologySuite.IO.PostGis/PostGisWriter.cs#L134)

Whichever you use, __DON'T__ use the Read or Write functions that return or use a `Coordinate`, I strongly assume that the method you point to is not used within the writer at all. Make sure you use a `ICoordinateSequenceFactory` class that can handle m-ordinate values (`PackedCoordinateSequenceFactory.Double` or `DotSpatialAffineCoordinateSequenceFactory`).

**Comment by YohDeadfall** [comment]
Does this mean that `WKBWriter` and ` WKBReader` aren't symmetric? The first one supports EWKB.
