### ISSUE TITLE
MyGet feed for prerelease packages

### ISSUE THREAD

**Issue by roji** [NetTopologySuite/NetTopologySuite#222]
It seems that NTS is currently [publishing prerelease packages to nuget.org](https://www.nuget.org/packages/NetTopologySuite). I'd just like to suggest setting up a myget feed and publishing there - this seems to be the standard practice nowadays. IMHO it still makes sense to publish preview/beta/RC packages to nuget.org, but to keep packages such as `pre063` on myget only. This is better than using nuget.org because:
* Packages can't be deleted from nuget.org, only delisted (and there's no reason to retain these prerelease packages)
* Users have to explicitly opt into cutting edge `pre063` packages by adding a NuGet.Config file referencing the myget feed. But they still have access to more stable prerelease packages (preview/beta).
* It makes it much easier to understand the package history on nuget.org, the current situation is a little "polluted".

I'd be happy to offer any help if it's needed (although this is quite simple).

**Comment by FObermaier** [comment]
I'd support that, @xivk is it a big hustle to change that on the build server?

**Comment by xivk** [comment]
No I can change this... I imagine it works exactly the same so it's just changing the API URL. 

Do we need to make a useraccount on myget? Because that's perhaps something for you to do @FObermaier ? It would be even better if a couple of us could manage these accounts together but I'm not sure how to do that.

**Comment by FObermaier** [comment]
The feeds on myget are:

| Type   |   URL   |
| --- | --- |
| nuget v3   |   https://www.myget.org/F/nettopologysuite/api/v3/index.json   |
| nuget v2   |   https://www.myget.org/F/nettopologysuite/api/v2   |

**Comment by YohDeadfall** [comment]
Thanks!

**Comment by roji** [comment]
Thank you very much for this, Npgsql now depends on 1.15.0-pre066 where #221 was fixed, and reading works great!
