### ISSUE TITLE
GeoJSON parser fails to parse properties

### ISSUE THREAD

**Issue by dmytro-gokun** [NetTopologySuite/NetTopologySuite#224]
Hi,

i have this piece of GeoJSON:

`
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [
      12.5851472,
      55.68323837
    ]
  },
  "crs": {
    "type": "name",
    "properties": {
      "name": "EPSG:4326"
    }
  },
  "properties": {
    "id": "0a3f507a-b2e6-32b8-e044-0003ba298018",
    "status": 1,
    "vejkode": "4112",
    "vejnavn": "Landgreven",
    "adresseringsvejnavn": "Landgreven",
    "husnr": "10",
    "supplerendebynavn": null,
    "postnr": "1301",
    "postnrnavn": "København K",
    "kommunekode": "0101"
  }
}
`

I use this code to parse it:

`
var feature = new GeoJsonReader().Read<Feature>(json);
`

The resulting "feature" object contains just 1 element in it's "Attributes" property. One named "name" with value of "EPSG:4326". Instead, I expect it to contain "id", "status", "vejkode" and so on. Obviously, the parser is fooled by "properties" nested inside of "crs".

Thanks in advance,
Dmytro.

**Comment by airbreather** [comment]
This issue was moved to NetTopologySuite/NetTopologySuite.IO.GeoJSON#7
