### ISSUE TITLE
NetTopologySuite.IO.GeoJson NU1602 NuGet Warning

### ISSUE THREAD

**Issue by dfaivre** [NetTopologySuite/NetTopologySuite#225]
### Description
I get NU1602 (NuGet) warning on compile: `Warning	NU1602	NetTopologySuite.IO.GeoJSON 1.14.0 does not provide an inclusive lower bound for dependency Newtonsoft.Json. An approximate best match of Newtonsoft.Json 3.5.8 was resolved`

I'd be happy to help contribute a fix for this.  Also, should I be posting this issue here (https://github.com/NetTopologySuite/NetTopologySuite.IO.GeoJSON)?

### Steps to Reproduce
- Reference NetTopologySuite.IO.GeoJSON 1.14.0
- Build
- Check Warnings

![image](https://user-images.githubusercontent.com/1211772/38334275-78a9c698-3820-11e8-8bb5-afba21f58dba.png)

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 1.14.0
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on): Windows, Visual Studio 2017 (+Resharper 2017.3)
- .NET Framework version: 4.7
- Additional information:

**Comment by airbreather** [comment]
This issue was moved to NetTopologySuite/NetTopologySuite.IO.GeoJSON#8
