### ISSUE TITLE
DbaseFileWriter DBF write DateTime Attribute issue with the Year.

### ISSUE THREAD

**Issue by tdyen** [NetTopologySuite/NetTopologySuite#226]
In DbaseFileWriter.cs if you Write a DateTime attribute for DateTime.MinValue then the year is 1 so it writes 1 char not 4 and you get this code triggered
    
       // Check if the correct amount of bytes was written
            if (bytesWritten != recordLength)
                throw new ShapefileException("Error writing Dbase record");

So this method here 

      private void Write(DateTime date)
        {
            foreach (var c in date.Year.ToString(NumberFormatInfo.InvariantInfo))
                _writer.Write(c);

ought to be something like this, though I haven't tested it

      private void Write(DateTime date)
        {
            foreach (var c in date.ToString("yyyy", NumberFormatInfo.InvariantInfo))
                _writer.Write(c);

**Comment by airbreather** [comment]
This issue was moved to NetTopologySuite/NetTopologySuite.IO.ShapeFile#9
