### ISSUE TITLE
CI Builds not getting published to NuGet

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#231]
Neither 4d99b0c nor 540a325 seem to have corresponding packages on [NuGet](https://www.nuget.org/packages/NetTopologySuite/).

@xivk was this intentional?  I'd have at least expected to see something for 4d99b0c, since it was before all the IO projects were moved out...

**Comment by FObermaier** [comment]
@airbreather , the prerelease packages are on myget:

Type | URL
-- | --
nuget v3 | https://www.myget.org/F/nettopologysuite/api/v3/index.json
nuget v2 | https://www.myget.org/F/nettopologysuite/api/v2
