### ISSUE TITLE
ConformingDelaunayTriangulationBuilder Fails On Closed Polygon Constraint

### ISSUE THREAD

**Issue by jhaverkost** [NetTopologySuite/NetTopologySuite#234]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Attempting to use ConformingDelaunayTriangulationBuilder.GetTriangles while using a closed polygon for a constraint results in an ArgumentException due to a duplicate key in _constraintVertexMap (see below).

```
ArgumentException: The key was already present in the dictionary.
Parameter name: key
Wintellect.PowerCollections.OrderedDictionary`2[GeoAPI.Geometries.Coordinate,NetTopologySuite.Triangulate.QuadEdge.Vertex].Add (GeoAPI.Geometries.Coordinate key, NetTopologySuite.Triangulate.QuadEdge.Vertex value)
NetTopologySuite.Triangulate.ConformingDelaunayTriangulationBuilder.CreateVertices (IGeometry geom)
NetTopologySuite.Triangulate.ConformingDelaunayTriangulationBuilder.Create ()
NetTopologySuite.Triangulate.ConformingDelaunayTriangulationBuilder.GetTriangles (IGeometryFactory geomFact)
...
```

This is inconsistent with the JTS implementation (https://github.com/locationtech/jts/blob/eca80edf196bfbb5613466a3c98d4c69b614917b/modules/core/src/main/java/org/locationtech/jts/triangulate/ConformingDelaunayTriangulationBuilder.java#L137). Instead of using Add on the map, the indexer should be used.

### Steps to Reproduce
1. Create a ConformingDelaunayTriangulationBuilder
2. Set the sites to a polygon with a hole
3. Set the constraints to the closed polygon matching the hole (easily done by using polygon.GetInteriorRingN(i))
4. Call GetTriangles on the builder (should result in the exception)

### System Configuration
- NetTopologySuite version: 1.14
- Environment (Operating system, version and so on): Windows 10 Pro x64
- Additional information: Running  via Mono 2.0 (used by Unity3D)

**Comment by FObermaier** [comment]
Do you need this fixed for NTS 1.14 or could you live with NTS 1.15
