### ISSUE TITLE
Consider requiring a CLA to make future license changes easier.

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#237]
In order to help make future changes to projects' licenses, I understand that some projects require that contributors sign what's called a CLA (Contributor License Agreement) before accepting contributions.

I'm not sure if this makes sense for NTS, but I figured I'd bring it up anyway.

**Comment by FObermaier** [comment]
* Which one could we use, is there a sample?
* Is there a way to enforce it?

**Comment by xivk** [comment]
AFAIK it's not about enforcement, just don't accept contributions from people who don't 'sign'. I use the one in the Itinero contributor guidelines:

https://github.com/itinero/routing/blob/develop/CONTRIBUTING.md

But it's possible you need a legal entity somewhere to make this happen (not 100% sure), that's why I suggested to join the .NET foundation. They have all this stuff ready I guess.

**Comment by FObermaier** [comment]
>  just don't accept contributions from people who don't 'sign'
That is what I mean by enforcing. Maybe https://cla-assistant.io/?

**Comment by xivk** [comment]
Ah looks good, will investigate for Itinero too. :+1:

**Comment by FObermaier** [comment]
Anotherone would be https://www.clahub.com

**Comment by airbreather** [comment]
> I suggested to join the .NET foundation

One reservation I have about this move is that joining the .NET Foundation requires adopting [their Code of Conduct](https://dotnetfoundation.org/code-of-conduct), which contains the following lines:

> Project maintainers who do not follow or enforce the Code of Conduct may be permanently removed from the project team.
> 
> This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community.

As far as I can tell, that means that the .NET Foundation could, at their sole judgement, determine that a project maintainer is acting unethically and remove that maintainer's privileges on this project, even if that person was out and about, just because the .NET Foundation arbitrarily deemed that the person was "representing the project or its community" at the time.

Not that I'm completely against it or anything, I just don't see enough benefit at this point in time.

**Comment by FObermaier** [comment]
I have added  https://cla-assistant.io/ with a CLA based on @xivk's itinero template:
https://gist.github.com/FObermaier/2db0402438d23227ed66de0d2d4fbe78
