### ISSUE TITLE
Spatial index implementation - questions

### ISSUE THREAD

**Issue by thomasfrisko** [NetTopologySuite/NetTopologySuite#241]
Hello I have a question regarding your implementation of spatial indexes. I'm wondering why you only have read-only R trees? I do not know if it is a common need but at least in my case I would like to dynamically add or remove elements. 

I have another question regarding your Kd trees. Why do you only store the first object inserted if there is another object at the exact same location? Would it be possible to make a data structure that supports storing multiple objects at the exact same location?

**Comment by airbreather** [comment]
For the most part, NTS is just a strict port of [JTS](https://github.com/locationtech/jts), so the design decisions from that project tend to be reflected here.

> I'm wondering why you only have read-only R trees? I do not know if it is a common need but at least in my case I would like to dynamically add or remove elements.

Although `STRtree<T>` is read-only after being built, `NetTopologySuite.Index.Quadtree.Quadtree<T>` can be edited on-the-fly, in theory at the expense of it being slower.

> I have another question regarding your Kd trees.

Someone else will have to chime in about Kd trees, I don't know a thing about those.

**Comment by FObermaier** [comment]
As for `KdTree<T>` you should be able to define it as `KdTree<List<object>>`.
This way you can call 
```C#
// create the tree with zero tolerance
var kdtree = new KdTree<List<object>>();

// first item
var item = new List<object>(new [] { new object() })
var n1 = kdtree.Insert(new Coordinate(1, 1), item)

// second item at the same spot
var item = new List<object>(new [] { new object() })
var n2 = kdtree.Insert(new Coordinate(1, 1), item)

// Check if we have a new node in the tree
if (n2.Count > 1) // no new item, only reference counter has been incremented.
    n2.Data.AddRange(n2.Data);
```

**Comment by airbreather** [comment]
Can this be closed?

**Comment by thomasfrisko** [comment]
Yes you answered my questions, thanks :)
