### ISSUE TITLE
ConformingDelaunayTriangulationBuilder does not generate a closed mesh

### ISSUE THREAD

**Issue by andry-tino** [NetTopologySuite/NetTopologySuite#248]
### Description
I need to calculate the [Triangulation](http://nettopologysuite.github.io/html/class_net_topology_suite_1_1_triangulate_1_1_conforming_delaunay_triangulation_builder.html) of a set of points. More specifically: I want a **3D** triangulation of a set of points in the 3D space which is also **closed** (the final mesh must be closed: not an open surface).

### Steps to Reproduce
Following the API doc, I have written this simple program:

    var builder = new NTS.Triangulate.ConformingDelaunayTriangulationBuilder();
    
    builder.SetSites(new NTS.Geometries.MultiPoint(new[] { // A (square) pyramid
        new NTS.Geometries.Point(0, 0, 0),
        new NTS.Geometries.Point(2, 0, 0),
        new NTS.Geometries.Point(0, 2, 0),
        new NTS.Geometries.Point(2, 2, 0),
        new NTS.Geometries.Point(1, 1, 2)
    }));
    
    var triangles = builder.GetTriangles(new NTS.Geometries.GeometryFactory());
    Console.WriteLine("Triangles: " + triangles.ToString());

Which returns:

    (0 2 0, 0 0 0, 1 1 2, 0 2 0), 
    (0 2 0, 1 1 2, 2 2 0, 0 2 0), 
    (2 2 0, 1 1 2, 2 0 0, 2 2 0), 
    (0 0 0, 2 0 0, 1 1 2, 0 0 0)

Which is correct but it has generated **only 4 faces**. I was **expecting 6 triangles** (the base of the pyramid should have been included). I get an open mesh basically. I was expecting these 2 additional triangles:

    (0 0 0, 2 0 0, 0 2 0, 0 0 0),
    (0 2 0, 2 0 0, 2 2 0, 0 2 0)

Why does the algorithm generate an open mesh?

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 1.14
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.7.1

**Comment by andry-tino** [comment]
It is a possibility that the Triangulator is not meant to create closed surfaces out of points. This seems very strange to me but I realize now that my mindset might be very focused on the application I need to implement (basically I need to develop interactive scenarios in Unity, and need closed shapes).

If the Triangulator is not supposed to create closed shapes, how can I achieve this? It is unfortunate that the doc lacks examples because just by the code doc and signatures of methods, it is not very easy to know hoe things should be done.

**Comment by airbreather** [comment]
NTS is a port of JTS, which does not support 3D operations.  It calls itself [a "2.5D" library](https://locationtech.github.io/jts/jts-faq.html#B4) since you can still provide Z, but Z is rarely observed by the algorithms in this library, including this one.

**Comment by andry-tino** [comment]
@airbreather: I see. That is unfortunate I guess. I had kind of a feeling that what I was doing was not entirely correct, however the algorithm basically works in a certain way. It does return a valid triangulation, it is just that the final result is an open surface, which makes kind of sense considering your comments.

So my question is the following. Can I get the boundary of the surface and run again the triangulation to generate that missing surface? It should be a valid approach right?

**Comment by airbreather** [comment]
I'm not sure what you mean by this.  NTS just doesn't "see" 3D.

I've made a bit of a cube in Paint 3D, rotated it (the white thing on the left is the plane at Z=0), and labeled some triangles along the faces of the cube... it looks like what you're trying to get is this (plus triangles on the hidden faces):
![image](https://user-images.githubusercontent.com/3792815/42129357-9b972be6-7c90-11e8-88a4-b66f762fe0d6.png)

NTS doesn't actually "see it" that way, though.  In effect, it acts as if all the vertices had Z=0, then does the triangulation on those points, and then just carries through whatever Z value the vertices initially had.  I can't quite reproduce this in Paint 3D, but imagine if the camera were looking straight down at that Z=0 plane and the cube were translucent so you could see all the vertices highlighted... it would do the triangulation based on what *the camera* sees, not the "true" 3D shape of the figure.

It feels like this will give you a completely different result than what you're trying to do.

**Comment by andry-tino** [comment]
I see. Thanks @airbreather for taking time to explain this, you have been very helpful!
