### ISSUE TITLE
Stable release of NetTopologySuite.IO packages?

### ISSUE THREAD

**Issue by peetw** [NetTopologySuite/NetTopologySuite#250]
With the "full" release of NetTopologySuite 1.15.0, are there plans to release stable versions of the NetTopologySuite.IO NuGet packages? The latest versions are still marked as pre-release (1.15.0-pre63) and the latest stable versions (1.14) obviously reference the old 1.14 versions of NetTopologySuite, which makes it a bit awkward to upgrade cleanly

**Comment by peetw** [comment]
Looking at this closer, the types that I'm primarily interested in (`PostGisReader` / `PostGisWriter`) have been moved from the `NetTopologySuite` project to the `NetTopologySuite.IO.PostGis` project as part of the larger IO project refactoring. However, the latest version of the `NetTopologySuite.IO.PostGis` NuGet package is 1.13 (there's not even a pre-release version available atm) - I assume the intention is to release a 1.15 version of that package soon(TM)?

**Comment by FObermaier** [comment]
We are publishing pre-release packages to our myget stream. Please try this one:
https://www.myget.org/feed/nettopologysuite/package/nuget/NetTopologySuite.IO.PostGis

**Comment by peetw** [comment]
@FObermaier thanks! The version on MyGet appears to be a full (non pre-release) version? Does this mean that we can expect a full release on the main NuGet gallery soon too?

We're currently in the process of updating all our NuGet package dependencies for the NHibernate.Spatial project with the aim of supporting .NET Standard, so any idea of rough timelines would be really helpful :) If there's anything I/we can do to help with the IO.PostGis project, let us know!

**Comment by FObermaier** [comment]
@peetw, if the IO packages are ok in terms of functionality, dependency, ... we will be pushing them to the nuget stream as well.

**Comment by FObermaier** [comment]
NetTopologySuite.IO.PostGis has been published to the nuget stream: https://www.nuget.org/packages/NetTopologySuite.IO.PostGis/
