### ISSUE TITLE
Request to port H2GIS MakeValidOp method to NTS for cleaning geometry

### ISSUE THREAD

**Issue by donnyv** [NetTopologySuite/NetTopologySuite#254]
I ran across this method while researching something else. It's completely built with JTS and would be a handy method to have for cleaning up data.
https://github.com/orbisgis/h2gis/blob/22c16ce4844ee1b4b59301128f90fd57f1300fc7/h2gis-functions/src/main/java/org/h2gis/functions/spatial/clean/MakeValidOp.java

**Comment by FObermaier** [comment]
Please see/join discussion on https://gitter.im/locationtech/jts

**Comment by FObermaier** [comment]
This functionality is now (v2.4.2) available via
```C#
var fixedGeom = NetTopologySuite.Geometries.Utilities.GeometryFixer.Fix(invalidGeometry);
```
