### ISSUE TITLE
NetTopologySuite dedicated documentation

### ISSUE THREAD

**Issue by Deilan** [NetTopologySuite/NetTopologySuite#256]
On the wiki introduction page it's mentioned that NTS is a port of JTS. Looks like one should go for JTS documentation to get familiar with NTS. Nonetheless it would be more convenient to have a dedicated NTS documentation.

**Comment by bricelam** [comment]
@airbreather I recommend taking a look at [DocFX](https://dotnet.github.io/docfx/) for this.

**Comment by airbreather** [comment]
> @airbreather I recommend taking a look at [DocFX](https://dotnet.github.io/docfx/) for this.

Agreed -- I used it for the GPX I/O module and it [turned out all right](https://nettopologysuite.github.io/NetTopologySuite.IO.GPX/index.html) 😁.

The challenge is going through and actually making sure the xmldoc is up to snuff, since it's really all over the place right now IMO.

**Comment by bricelam** [comment]
Nice!

We [enable](https://github.com/aspnet/EntityFrameworkCore/blob/469177a49d251bb81184b42ce4cd2ffe623b345a/src/Microsoft.Data.Sqlite.Core/Microsoft.Data.Sqlite.Core.ruleset#L133-L145) a few [StyleCop rules](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DocumentationRules.md) (and disable the rest) on EF Core to help catch missing docs.

**Comment by SamuelEnglard** [comment]
Any update on this? I'm using DocFx and would love to be able to have cross references to NTS docs work properly.

**Comment by airbreather** [comment]
> Any update on this? I'm using DocFx and would love to be able to have cross references to NTS docs work properly.

Sorry about the wait.  Started this: https://nettopologysuite.github.io/NetTopologySuite

**Comment by joshuawootonn** [comment]
FWIW, I predominately learn by example and I am really struggling were to start right now. Does anyone have good example repos to reference usage? Bonus points for one using Dapper!!
