### ISSUE TITLE
Invalid polygon should be valid?

### ISSUE THREAD

**Issue by ArneD** [NetTopologySuite/NetTopologySuite#259]
### Description
I have a polygon which is invalid in NTS, but valid according to SqlServer.
I cloned NTS and wrote a test to see where it fails. It fails at `CheckNoSelfIntersectingRings`.

The polygon:
![image](https://user-images.githubusercontent.com/8726691/45672952-c2bcb380-bb29-11e8-8777-c54134f102a1.png)

### Steps to Reproduce
```POLYGON ((188973.5849981904 174632.64530731365, 188974.74775019288 174631.17509930953, 188973.49629419297 174630.22725931183, 188974.90890219063 174628.25081130862, 188976.18723819405 174629.35481131077, 188979.83139819652 174624.74693930522, 189000.76669421047 174640.85573931783, 188994.73213420808 174648.88031532243, 188994.30640620738 174649.44633132219, 188994.49123820662 174649.60300332308, 188993.28279020637 174651.27519532666, 188993.47530220449 174651.43186732382, 188992.24151020497 174653.35967532545, 188998.0812542066 174660.8594513312, 188990.15741420537 174666.99474733695, 188969.869286187 174639.69849131629, 188972.99274218827 174637.35980331525, 188974.3000061959 174639.15884331614, 188978.20579819381 174636.19282731414, 188984.90711019933 174645.60121132061, 188987.15095020086 174643.06002731994, 188978.20579819381 174636.19282731414, 188973.5849981904 174632.64530731365))```

If we remove the last occurrence of `188978.20579819381 174636.19282731414`, then it becomes valid.
Possible bug?

**Comment by FObermaier** [comment]
The polygon is **not valid** because its shell (exterior ring) is a self intersecting `LinearRing`.
If the omission were defined as a hole (interior ring), the polygon were valid:
```
POLYGON ((188973.5849981904 174632.64530731365, 188978.20579819381 174636.19282731414, 
188974.3000061959 174639.15884331614, 188972.99274218827 174637.35980331525, 
188969.869286187 174639.69849131629, 188990.15741420537 174666.99474733695, 
188998.0812542066 174660.8594513312, 188992.24151020497 174653.35967532545, 
188993.47530220449 174651.43186732382, 188993.28279020637 174651.27519532666, 
188994.49123820662 174649.60300332308, 188994.30640620738 174649.44633132219, 
188994.73213420808 174648.88031532243, 189000.76669421047 174640.85573931783, 
188979.83139819652 174624.74693930522, 188976.18723819405 174629.35481131077, 
188974.90890219063 174628.25081130862, 188973.49629419297 174630.22725931183, 
188974.74775019288 174631.17509930953, 188973.5849981904 174632.64530731365), 
(188978.20579819381 174636.19282731414, 188987.15095020086 174643.06002731994, 
188984.90711019933 174645.60121132061, 188978.20579819381 174636.19282731414))
```

**Comment by ArneD** [comment]
Thank you for the feedback!
The use and configuration of `IsValidOp` will solve our legacy problem.

**Comment by CumpsD** [comment]
@FObermaier is there any way to make NTS write a SQL Server geometry type which is valid? When you explicitly tell the IsValidOp it's ok.
