### ISSUE TITLE
Determine whether a polygon contains a point

### ISSUE THREAD

**Issue by corstian** [NetTopologySuite/NetTopologySuite#264]
Using NTS 1.15.1 it occured to me that the `.Contains()` method on a `Polygon` is too slow for my use case. My goal is to figure out what `Coordinate` or `Point` is within said polygon.

After fiddling around for a bit I figured out that the ray casting method as used [here](https://stackoverflow.com/a/39857727/1720761) is significantly (10 to 15 times) faster, for determining whether a point is in a polygon.

Is there place in this library for such specialized (performant) method, or am I overlooking anything?

**Comment by FObermaier** [comment]
For fast 1:N predicate test, use `NetTopologySuite.Geometries.Prepared.PreparedGeometry` and its members.

**Comment by corstian** [comment]
Ah that's an oversight on my part! Thanks for the pointers :)

**Comment by airbreather** [comment]
+1 for `NetTopologySuite.Algorithm.Locate.IndexedPointInAreaLocator`.  I've got some research notes at work that show this being the fastest option available in JTS / NTS.

**Comment by Guided-Highest** [comment]
Hi, every on,
I am new in Geo-Location. and I am working on a Geo-Location based attendance System. I get the Kml file from google earth and want to verify if the lat-log of an employee is in the polygon data in kml file.  Can anyone tell me how to accomplish

**Comment by corstian** [comment]
@Guided-Highest Depends on how far you are in the process. You'll need to decode the KML file, extract the coordinates, create a polygon in memory, and check whether a coordinate is within. Playing around with the code I figured you might be able to achieve it by doing something like this (this is untested code);

```csharp
var geoFactory = new NetTopologySuite.Geometries.Prepared.PreparedGeometryFactory();
var preparedGeometry = geoFactory.Create(
        Geometry.DefaultFactory.CreatePolygon(new [] {
            new Coordinate(1, 2)
            /* You'll probably extract the coordinates using a linq query */
        })
);

var isInside = preparedGeometry.Contains(Geometry.DefaultFactory.CreatePoint(new Coordinate(1, 2)));
```

As for the `IndexedPointInAreaLocator` you might try the following;

```csharp
var pointLocator = new NetTopologySuite.Algorithm.Locate.IndexedPointInAreaLocator(
    Geometry.DefaultFactory.CreatePolygon(new[] {
        new Coordinate(1, 2)
    })
);

var location = pointLocator.Locate(new Coordinate(1, 2));

var isInside = !location.HasFlag(Location.Exterior);
```

@airbreather Still thanks for the suggestion! I'll get back to spatial analysis in a short while, and it'll surely will save me a bit of time. :)
