### ISSUE TITLE
RobustLineIntersector.ComputeIntersect failes with NullReferenceException if lines intersect in point.

### ISSUE THREAD

**Issue by oleo65** [NetTopologySuite/NetTopologySuite#269]
### Description
I use [NetTopologySuite.Algorithm.RobustLineIntersector](https://github.com/NetTopologySuite/NetTopologySuite/blob/c94898f6a6282f6d8bb4fa65062ac59324108b85/NetTopologySuite/Algorithm/RobustLineIntersector.cs#L36) to compute intersections and collinear geometries.

Under some circumstances the algorithm fails with a NullReferenceException despite providing valid coordinates. 

- If the two lines are collinear -> ok
- If the two lines do not intersect at all -> ok
- If the two lines intersect in one point -> NullReferenceException

I used the Test2Lines unit test to successfully reproduce the error as provided below. It seems like the protected Coordinate[][] [InputLines](https://github.com/NetTopologySuite/NetTopologySuite/blob/c94898f6a6282f6d8bb4fa65062ac59324108b85/NetTopologySuite/Algorithm/LineIntersector.cs#L132) is not set while using this method

### Steps to Reproduce

```csharp
        [Test]
        public void Test2Lines()
        {
            var i = new NetTopologySuite.Algorithm.RobustLineIntersector();
            var p1 = new GeoAPI.Geometries.Coordinate(10, 10);
            var p2 = new GeoAPI.Geometries.Coordinate(20, 20);
            var q1 = new GeoAPI.Geometries.Coordinate(20, 10);
            var q2 = new GeoAPI.Geometries.Coordinate(10, 20);
            var x = new GeoAPI.Geometries.Coordinate(15, 15);
            int result = i.ComputeIntersect(p1, p2, q1, q2);
            Assert.AreEqual(NetTopologySuite.Algorithm.LineIntersector.PointIntersection, result);
        }
```

### System Configuration
I am using the most current NTS version from nuget 1.15.1 with .Net Framework 4.6.2

Thanks alot for your support.

**Comment by FObermaier** [comment]
You should not be using `RobustLineIntersector.ComputeIntersect`. This function should carry the `protected` modifier. Use `RobustLineIntersector.ComputeIntersection` instead.

**Comment by oleo65** [comment]
Thank you for the clarification.

**Comment by airbreather** [comment]
Should we update this issue to something along the lines of "hide `LineIntersector.ComputeIntersect`" and take the breaking change for 2.0?
