### ISSUE TITLE
How to use GeoJsonReader/Writer with latest version

### ISSUE THREAD

**Issue by OsamaShabrez** [NetTopologySuite/NetTopologySuite#272]
### Description
After updating to the latest NetTopologySuite 1.15.1 VS complained about missing an assembly reference for Features and GeoJsonWriter. I have installed the standalone lib for Features and also tried to install NetTopologySuite.IO for GeoJsonWriter to no avail. 

Has it been moved to another module? how to fix?

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 1.15.1
- Other NetTopologySuite packages and versions: NetTopologySuite.Features 1.15.0, NetTopologySuite.IO 1.14.0.1
- Environment (Operating system, version and so on): Windows 10 1803
- .NET Framework version: 4.5
- Additional information: -

**Comment by FObermaier** [comment]
> Other NetTopologySuite packages and versions: NetTopologySuite.Features 1.15.0, NetTopologySuite.IO 1.14.0.1

These don't match.

You need to install the latest `NetTopologySuite.IO.GeoJSON` package

**Comment by OsamaShabrez** [comment]
Issue resolved after installing NetTopologySuite.IO.GeoJSON 1.15.0
