### ISSUE TITLE
Default coordinate sequence does not support M values

### ISSUE THREAD

**Issue by loth0** [NetTopologySuite/NetTopologySuite#273]
When fetching data from sql server using EF Core the M values are neglected since the default coordinate sequence does not support it. I'd like to be able to fetch the geometries including the M-values stored in the database.

**Comment by bricelam** [comment]
``` csharp
// Create geometry services with a 4D coordinate sequence
var geometryServices = new NtsGeometryServices(
    new PackedCoordinateSequenceFactory(
        PackedCoordinateSequenceFactory.PackedType.Double,
        dimension: 4),
    new PrecisionModel(PrecisionModels.Floating),
    srid: -1);

// Inside Startup.ConfigureServices()
services
    // Register your custom geometry services
    .AddSingleton<IGeometryServices>(geometryServices)
    .AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(connectionString, x => x.UseNetTopologySuite));
```

**Comment by airbreather** [comment]
Thanks Brice for showing how to do this for the time being.

I think that #265 is likely to take care of the default case; at the moment, that one's blocked on a combination of getting the necessary updates into GeoAPI.NET (this one is particularly tricky), and finding the time to actually do the rest of the porting.

**Comment by airbreather** [comment]
As of 91cd26e, the default coordinate sequence factory supports all of XY, XYZ, XYM, and XYZM.
