### ISSUE TITLE
Fast find if set of points belong to polygon

### ISSUE THREAD

**Issue by Pcinja** [NetTopologySuite/NetTopologySuite#274]
### Question
Is there an efficient way to find points of type NetTopologySuite.Geometries.Point that are inside given polygon of type NetTopologySuite.Geometries.PointPolygon using .net core 2.2. I tried following the documentation below, but no luck: https://nettopologysuite.github.io/html/class_net_topology_suite_1_1_algorithm_1_1_locate_1_1_indexed_point_in_area_locator.html#ad28b305b77c52327b7787ca8016c0fd7. 

### System Configuration
Tell us about the environment where you are experiencing the bug:
- Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 2.2.0
- Operating system Win 10 Pro
- .NET Framework version: .net core 2.2
- Additional information: C#

Thanks.

**Comment by DGuidi** [comment]
If I understand correctly, you have a point with a given coordinate and you wanna test if this point is inside a polygon, right?
tried with `polygon.Contains(point)`

**Comment by Pcinja** [comment]
I'd like to check if set of Points are inside polygon. Do I have to use foreach or there is a better approach? I need fast solution.
Thanks.

**Comment by FObermaier** [comment]
For one against many use the `GeoAPI.Geometries.Prepared.IPreparedGeometry`.
You can create one using the `NetTopologySuite.Geometries.Prepared.PreparedGeometryFactory`.

**Comment by Pcinja** [comment]
Thank you, this works for me.
