### ISSUE TITLE
LineSegment.LineIntersection return error

### ISSUE THREAD

**Issue by sendreams** [NetTopologySuite/NetTopologySuite#276]
### Prerequisites

- [ ] version 1.15.1

### Description
linesegment has two interface: Intersection & LineIntersection,  
I think the direct difference between the two is whether the line will be extended or not.
If it's the same as I imagined, the LineIntersection return the error result.

### Steps to Reproduce
the first linesegment:     
P0: {(35613471.6165017, 4257145.3061322933, 1108.411)}
P1: {(35613477.7705378, 4257160.5282227108, 1108.293)}
the second linesegment:
P0: {(35613477.775057241, 4257160.5396535359, 1108.293)}
P1: {(35613479.856073894, 4257165.9236917039, 1108.263)}
the real intersection is:
{(35613477.772841461, 4257160.5339209242, NaN)}
but the LineIntersection result is:
{(35613477.774291642, 4257160.5403661141, NaN)}

plz check it. thanks.

**Comment by airbreather** [comment]
When I see a *lot* of digits of precision (and values very close to one another, like we have here), my mind immediately jumps to [this section of the JTS FAQ](https://locationtech.github.io/jts/jts-faq.html#robustness) (NTS is a direct port of JTS).  

I have been very busy lately, so I don't currently have the time to check to see if that applies to this particular case.  Do you get a closer result after subtracting, say, 35613470 from both X values and 4257140 from both Y values, doing the intersection, and then adding those offsets back to the result at the end?
