### ISSUE TITLE
Exception while fetching Interior Point - NetTopologySuite.Geometries.TopologyException

### ISSUE THREAD

**Issue by VarunGargCivilGeo** [NetTopologySuite/NetTopologySuite#282]
After upgradation of NetTopologySuite to latest version i.e **1.15.1** I am facing the following issues:
1. 
I am unable to find the **Interior Point** for the polygon if the polygon is similar to the one in attached image
![nettopologysuiteissue](https://user-images.githubusercontent.com/47634311/52790583-ee1ddd00-308c-11e9-892b-941d5cb421c1.png)

**Exception**  : {"found non-noded intersection between LINESTRING(-85.362787588886718 40.204679913541511, -85.364123291467237 40.204679913541511) and LINESTRING(-85.364123291467237 40.204679913541511, -85.364123291467237 40.204550643022017) [ (-85.364123291467237, 40.204679913541511, 0) ]"}   NetTopologySuite.Geometries.TopologyException

**Wkt of the polygon:**
POLYGON ((-85.36378573155713 40.205612290198054, -85.36345619668108 40.205612290198054, -85.36345619668108 40.20520564752508, -85.36310727740059 40.20520564752508, -85.36310727740059 40.20494187930476, -85.36275835812008 40.20494187930476, -85.36275835812008 40.204683606255706, -85.36277774252454 40.204683606255706, -85.36413465083763 40.204683606255706, -85.36413465083763 40.20494187930476, -85.36481310499417 40.20494187930476, -85.36481310499417 40.204683606255706, -85.36413465083763 40.204683606255706, -85.36413465083763 40.20441983803539, -85.36378573155713 40.20441983803539, -85.36378573155713 40.204156069815085, -85.36345619668108 40.204156069815085, -85.36345619668108 40.20441983803539, -85.36310727740059 40.20441983803539, -85.36310727740059 40.20389779676603, -85.36312666180505 40.20389779676603, -85.36345619668108 40.20389779676603, -85.36345619668108 40.203634028545714, -85.36448357011814 40.203634028545714, -85.36448357011814 40.20389779676603, -85.36549155915071 40.20389779676603, -85.36549155915071 40.204156069815085, -85.36518140867915 40.204156069815085, -85.36516202427468 40.204156069815085, -85.36516202427468 40.204683606255706, -85.36549155915071 40.204683606255706, -85.36549155915071 40.20494187930476, -85.36518140867915 40.20494187930476, -85.36516202427468 40.20494187930476, -85.36516202427468 40.20520564752508, -85.3638051159616 40.20520564752508, -85.36378573155713 40.20520564752508, -85.36378573155713 40.205612290198054))

2. The **center point** in such cases appears to be incorrect.

Note that both the reported issues worked fine in **Version 1.14.0**

**Comment by gktval** [comment]
I also am finding that interior point is often failing in this version of NetTopologySuite. Same reason also, "non-noded intersection". If you need another WKT:
"POLYGON ((666249.69 5260265.72, 666249.69 5260267.72, 666251.69 5260267.72, 666251.69 5260265.72, 666251.69 5260263.72, 666251.69 5260261.72, 666251.69 5260259.72, 666251.69 5260257.72, 666251.69 5260255.72, 666251.69 5260253.72, 666251.69 5260251.72, 666251.69 5260249.72, 666251.69 5260247.72, 666253.69 5260247.72, 666253.69 5260245.72, 666253.69 5260243.72, 666253.69 5260241.72, 666251.69 5260241.72, 666251.69 5260239.72, 666253.69 5260239.72, 666253.69 5260237.72, 666253.69 5260235.72, 666255.69 5260235.72, 666255.69 5260233.72, 666257.69 5260233.72, 666257.69 5260231.72, 666259.69 5260231.72, 666259.69 5260229.72, 666259.69 5260227.72, 666259.69 5260225.72, 666257.69 5260225.72, 666257.69 5260223.72, 666259.69 5260223.72, 666259.69 5260225.72, 666261.69 5260225.72, 666261.69 5260227.72, 666263.69 5260227.72, 666265.69 5260227.72, 666267.69 5260227.72, 666269.69 5260227.72, 666271.69 5260227.72, 666273.69 5260227.72, 666275.69 5260227.72, 666277.69 5260227.72, 666277.69 5260225.72, 666277.69 5260223.72, 666277.69 5260221.72, 666277.69 5260219.72, 666277.69 5260217.72, 666277.69 5260215.72, 666277.69 5260213.72, 666277.69 5260211.72, 666277.69 5260209.72, 666277.69 5260207.72, 666277.69 5260205.72, 666277.69 5260203.72, 666277.69 5260201.72, 666277.69 5260199.72, 666277.69 5260197.72, 666277.69 5260195.72, 666277.69 5260193.72, 666277.69 5260191.72, 666277.69 5260189.72, 666277.69 5260187.72, 666277.69 5260185.72, 666277.69 5260183.72, 666277.69 5260181.72, 666277.69 5260179.72, 666277.69 5260177.72, 666277.69 5260175.72, 666277.69 5260173.72, 666277.69 5260171.72, 666277.69 5260169.72, 666277.69 5260167.72, 666277.69 5260165.72, 666277.69 5260163.72, 666277.69 5260161.72, 666277.69 5260159.72, 666277.69 5260157.72, 666277.69 5260155.72, 666277.69 5260153.72, 666277.69 5260151.72, 666275.69 5260151.72, 666273.69 5260151.72, 666271.69 5260151.72, 666271.69 5260149.72, 666269.69 5260149.72, 666267.69 5260149.72, 666267.69 5260147.72, 666265.69 5260147.72, 666265.69 5260145.72, 666263.69 5260145.72, 666263.69 5260143.72, 666261.69 5260143.72, 666259.69 5260143.72, 666257.69 5260143.72, 666257.69 5260141.72, 666257.69 5260139.72, 666257.69 5260137.72, 666257.69 5260135.72, 666257.69 5260133.72, 666257.69 5260131.72, 666257.69 5260129.72, 666257.69 5260127.72, 666257.69 5260125.72, 666257.69 5260123.72, 666255.69 5260123.72, 666255.69 5260121.72, 666255.69 5260119.72, 666255.69 5260117.72, 666255.69 5260115.72, 666255.69 5260113.72, 666255.69 5260111.72, 666255.69 5260109.72, 666255.69 5260107.72, 666255.69 5260105.72, 666255.69 5260103.72, 666255.69 5260101.72, 666257.69 5260101.72, 666257.69 5260099.72, 666257.69 5260097.72, 666259.69 5260097.72, 666259.69 5260095.72, 666261.69 5260095.72, 666261.69 5260093.72, 666261.69 5260091.72, 666259.69 5260091.72, 666259.69 5260089.72, 666257.69 5260089.72, 666257.69 5260087.72, 666255.69 5260087.72, 666255.69 5260085.72, 666253.69 5260085.72, 666253.69 5260083.72, 666251.69 5260083.72, 666251.69 5260081.72, 666249.69 5260081.72, 666249.69 5260079.72, 666247.69 5260079.72, 666245.69 5260079.72, 666243.69 5260079.72, 666243.69 5260077.72, 666241.69 5260077.72, 666239.69 5260077.72, 666237.69 5260077.72, 666235.69 5260077.72, 666233.69 5260077.72, 666233.69 5260079.72, 666231.69 5260079.72, 666229.69 5260079.72, 666229.69 5260081.72, 666231.69 5260081.72, 666231.69 5260083.72, 666231.69 5260085.72, 666231.69 5260087.72, 666231.69 5260089.72, 666231.69 5260091.72, 666231.69 5260093.72, 666231.69 5260095.72, 666231.69 5260097.72, 666231.69 5260099.72, 666231.69 5260101.72, 666231.69 5260103.72, 666229.69 5260103.72, 666229.69 5260105.72, 666229.69 5260107.72, 666229.69 5260109.72, 666229.69 5260111.72, 666229.69 5260113.72, 666229.69 5260115.72, 666229.69 5260117.72, 666229.69 5260119.72, 666229.69 5260121.72, 666229.69 5260123.72, 666229.69 5260125.72, 666229.69 5260127.72, 666229.69 5260129.72, 666229.69 5260131.72, 666229.69 5260133.72, 666229.69 5260135.72, 666229.69 5260137.72, 666229.69 5260139.72, 666229.69 5260141.72, 666229.69 5260143.72, 666229.69 5260145.72, 666229.69 5260147.72, 666229.69 5260149.72, 666229.69 5260151.72, 666229.69 5260153.72, 666229.69 5260155.72, 666229.69 5260157.72, 666229.69 5260159.72, 666229.69 5260161.72, 666227.69 5260161.72, 666227.69 5260163.72, 666227.69 5260165.72, 666227.69 5260167.72, 666229.69 5260167.72, 666229.69 5260169.72, 666229.69 5260171.72, 666229.69 5260173.72, 666229.69 5260175.72, 666229.69 5260177.72, 666229.69 5260179.72, 666229.69 5260181.72, 666229.69 5260183.72, 666229.69 5260185.72, 666229.69 5260187.72, 666229.69 5260189.72, 666229.69 5260191.72, 666229.69 5260193.72, 666229.69 5260195.72, 666229.69 5260197.72, 666229.69 5260199.72, 666229.69 5260201.72, 666229.69 5260203.72, 666229.69 5260205.72, 666229.69 5260207.72, 666229.69 5260209.72, 666229.69 5260211.72, 666227.69 5260211.72, 666227.69 5260213.72, 666227.69 5260215.72, 666227.69 5260217.72, 666227.69 5260219.72, 666227.69 5260221.72, 666227.69 5260223.72, 666227.69 5260225.72, 666227.69 5260227.72, 666227.69 5260229.72, 666227.69 5260231.72, 666227.69 5260233.72, 666227.69 5260235.72, 666227.69 5260237.72, 666227.69 5260239.72, 666227.69 5260241.72, 666227.69 5260243.72, 666227.69 5260245.72, 666227.69 5260247.72, 666227.69 5260249.72, 666227.69 5260251.72, 666227.69 5260253.72, 666227.69 5260255.72, 666229.69 5260255.72, 666231.69 5260255.72, 666233.69 5260255.72, 666233.69 5260257.72, 666235.69 5260257.72, 666235.69 5260259.72, 666237.69 5260259.72, 666239.69 5260259.72, 666239.69 5260261.72, 666241.69 5260261.72, 666243.69 5260261.72, 666245.69 5260261.72, 666245.69 5260263.72, 666247.69 5260263.72, 666247.69 5260265.72, 666249.69 5260265.72))"

**Comment by airbreather** [comment]
@VarunGargCivilGeo The polygon from the original report is not valid, because it has a self-intersection at (X: -85.36413465083763, Y: 40.204683606255706).

@gktval your polygon also has a self-intersection at (X: 666259.69, Y:5260225.72).

I don't know exactly what change might have caused 1.15.x to deviate from 1.14.x, but to my knowledge, JTS does not guarantee consistent behavior across releases when dealing with invalid geometry, and so NTS follows suit.

Running those two in JTSTestBuilder from 1.15.1, I get the same results, so while I hesitate to go so far as to say "working as intended", there's not much more we can do other than report it upstream, where admittedly the most likely response would be "only use valid geometry".

That said, JTSTestBuilder from 1.16.1 seems to have no issues with these particular cases, so there's probably no need to go upstream, we just need to finally finish updating.

Some screenshots:

|JTSTestBuilder 1.15.1|JTSTestBuilder 1.16.1|
|-|-|
|![image](https://user-images.githubusercontent.com/3792815/53461148-a5abdb00-3a0d-11e9-98a0-2cea8fc1156e.png)|![image](https://user-images.githubusercontent.com/3792815/53461087-67aeb700-3a0d-11e9-9efd-9784dc1f2989.png)|
|![image](https://user-images.githubusercontent.com/3792815/53461185-b8beab00-3a0d-11e9-86a1-19d546f3976b.png)|![image](https://user-images.githubusercontent.com/3792815/53461103-77c69680-3a0d-11e9-959c-059036495b9b.png)|

**Comment by dr-jts** [comment]
Also note that a recent [enhancement](https://github.com/locationtech/jts/pull/369) in JTS should allow interiorPoint to work with many invalid polygons.  It's also much faster as described in my [blog post](http://lin-ear-th-inking.blogspot.com/2019/02/better-and-faster-interior-point-for.html).

**Comment by airbreather** [comment]
> 2. The center point in such cases appears to be incorrect.

@VarunGargCivilGeo can you please open a separate issue for this part, with details about what you see and what you expected to see?
