### ISSUE TITLE
[Discussion] vNext version number?

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#298]
See https://github.com/NetTopologySuite/NetTopologySuite/pull/290#issuecomment-469660837 and subsequent comment on that thread.

**Comment by airbreather** [comment]
> looks clearer to me in JTS/NTS world

For reference, here are some of our counterparts:
- [GEOS](https://trac.osgeo.org/geos/wiki) is on [3.7.1](https://trac.osgeo.org/geos/browser/git/NEWS?rev=3.7.1)
- [JSTS](https://github.com/bjornharrtell/jsts) is on [2.0.3](https://github.com/bjornharrtell/jsts/releases/tag/2.0.3)
- [Shapely](https://github.com/Toblerity/Shapely) is on [1.7a1](https://github.com/Toblerity/Shapely/releases/tag/1.7a1)

> my vote is to maintain **v1.16**

The problem I have with that is that it fails to communicate what our dependents should reasonably be able to expect when considering an upgrade.

I suspect that most package consumers on NuGet are used to SemVer semantics (in fact, NuGet itself strictly uses SemVer for some of its own functions, [sometimes to a fault](https://github.com/NuGet/Home/issues/6434#issuecomment-468421972)).  It seems totally reasonable to me for someone to rely on us incrementing the major version on a release with intentional breaking changes.

I agree that we should add the JTS compatibility level to the `AssemblyInformationalVersionAttribute` and/or `AssemblyFileVersionAttribute`  strings, and make it very prominent in the release documentation, but I strongly feel that the version numbers of NTS itself (especially NuGet package versions) should follow [SemVer 2.0.0](https://semver.org/spec/v2.0.0.html), especially package numbers.

**Comment by DGuidi** [comment]
I understand your arguments and I'm with you with nuget package versions and stuff: simply looks strange to me that a library that aims to be "as close as possible" to JTS, has a version number totally unrelated.
But ok, nothing that can't be solved using some attributes and a bunch of lines in a readme file.

**Comment by FObermaier** [comment]
From what I've learned about assembly versioning is that
`AssemblyFileVersion` should somehow relate to the `AssemblyVersion`.
IMHO `AssemblyInformatlVersion` is the place to place JTS conformance version information, together with a note in the nuget package description.

**Comment by airbreather** [comment]
Best-practices for versioning: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/versioning

I also think it should go in `AssemblyInformationalVersionAttribute`, despite the "AVOID" on that page I linked.  I'm throwing together a PR now that also includes elements of #244.
