### ISSUE TITLE
ShapefileDataReader - default character encoding

### ISSUE THREAD

**Issue by VictorTerraGIS** [NetTopologySuite/NetTopologySuite#30]
I personally found that not all shapes files are well organized from point of view of the character encoding. Are so much different types of shape created by different tools and from different environments. In cases which I investigated I found that if no information about encoding then usually this is relayed to the environment where was created.

Some my examples shows that shape (dbf) files was related to the current language locale. So to read this files I would like to specify the default encoding for that file.

First I tried to change myself the "shapeFileDataReader.DbaseHeader.Encoding" but looks that value was always overwritten. Then I start to analyze the library code and I found that always Encoding is overwritten.

I would to specify for each file which default encoding to use in case of no encoding data found into descriptions.

I tried to modify myself the code and to see how it will work. I did some changes and looks Ok for my cases. Please looks at these changes and decide to include or not on GitHub repository and NuGet gallery.

So, my changes are:
```
        /// <summary>
        /// Initializes a new instance of the ShapefileDataReader class.
        /// </summary>
        /// <param name="filename">The shapefile to read (minus the .shp extension)</param>
        ///<param name="geometryFactory">The GeometryFactory to use.</param>
        ///<param name="defaultEncoding">Use specified encoding in case that no encoding found into dbf header or not attached .cpg file.</param>
        public ShapefileDataReader(string filename, IGeometryFactory geometryFactory, Encoding defaultEncoding = null)
        {
            if (String.IsNullOrEmpty(filename))
                throw new ArgumentNullException("filename");
            if (geometryFactory == null)
                throw new ArgumentNullException("geometryFactory");
            _open = true;

            string dbfFile = Path.ChangeExtension(filename, "dbf");
            _dbfReader = new DbaseFileReader(dbfFile, defaultEncoding);
            string shpFile = Path.ChangeExtension(filename, "shp");
...
```
```    
    public partial class DbaseFileReader
    {
        private readonly Encoding _DEFAULT_ENCODING;
...
        public DbaseFileReader(string filename, Encoding defaultEncoding = null)
        {
            _DEFAULT_ENCODING = defaultEncoding;
...
        public DbaseFileHeader GetHeader()
        {
            if (_header == null)
            {
                FileStream stream = new FileStream(_filename, FileMode.Open, FileAccess.Read);
                BinaryReader dbfStream = new BinaryReader(stream);

                _header = (_DEFAULT_ENCODING != null) ? new DbaseFileHeader(_DEFAULT_ENCODING) : new DbaseFileHeader();
                // read the header
                _header.ReadHeader(dbfStream, _filename);

```
```
        private partial class DbaseFileEnumerator : IEnumerator, IDisposable
        {
...
            protected void ReadHeader()
            {
                _header = (_parent._DEFAULT_ENCODING != null) ? new DbaseFileHeader(_parent._DEFAULT_ENCODING) : null;
                // read the header
                _header.ReadHeader(_dbfStream, _parent._filename);
...
```
```
    public class DbaseFileHeader
    {
...
        private Encoding _encoding;
        private readonly Encoding _DEFAULT_ENCODING;
...
        public DbaseFileHeader(Encoding enc)
        {
            if (enc == null)
                throw new ArgumentNullException("enc");
            _encoding = enc;
            _DEFAULT_ENCODING = enc;
            _fieldDescriptions = new DbaseFieldDescriptor[0];
        }
...
        private Encoding DetectEncodingFromMark(byte lcid, string cpgFileName)
        {
            Encoding enc;
            if (lcid == 0 && _DEFAULT_ENCODING != null)
                return _DEFAULT_ENCODING;
...
```

I can pool these changes myself, but at this time I don't have any git client installed and because are relatively few changes I decide to describe the required changes here.

Regards,
Victor Scorpan.

**Comment by DGuidi** [comment]
Something that I don't like from actual NTS code is that encoding is a setter property, at least in some classes, but it's also inferred from header, so the specified encoding can be in some cases changed during execution.
It's something that I wanna fix.

**Comment by DGuidi** [comment]
opened a specified fork for this: https://github.com/DGuidi/NetTopologySuite

**Comment by FObermaier** [comment]
Does the Encoding refer to the data, or does it refer to the column names as well?
The answer to [Which character encoding is used by the DBF file in shapefiles?](http://gis.stackexchange.com/questions/3529/which-character-encoding-is-used-by-the-dbf-file-in-shapefiles) states that it only applies to the data. The column names have to be encoded in LATIN1 (ISO-8859-1).

If that is true, why don't we allow the `DbaseFileHeader` to be instantiated with a "null" encoding.
If I'm not mistaken, all we need to do then is to 
* ensure that an encoding has been set before we call `WriteHeader` or maybe `AddColumn`
* check if an Encoding has already been set in the `ReadHeader` function before we try to guess it from the cpg file or language driver id. If it has not been defined and there is no known language driver id and no cpg file, we can assign a default encoding.

What do you think?

**Comment by DGuidi** [comment]
>What do you think?

I think encoding is referred to data "only", so maybe your suggestion should work

**Comment by DGuidi** [comment]
thx felix
