### ISSUE TITLE
ESRI File Geodatabase GDB

### ISSUE THREAD

**Issue by sindizzy** [NetTopologySuite/NetTopologySuite#300]
OGR has a driver for reading ESRI file geodatabases. Is that something that could potentially make it to NTS?

**Comment by FObermaier** [comment]
If I'm not mistaken, OGR relies on some ESRI library to perform that.
You can have a .NET implementation for that by using / deriving from the [Esri.FileGdb](https://github.com/SharpMap/SharpMap/tree/Branches/1.0/SharpMap.Data.Providers.FileGdb) provider for SharpMap.

**Comment by sindizzy** [comment]
I think what I am asking is if this could be rolled into NTS so we could have one solution for feature classes in a GeoDB as well as a shapefile.

**Comment by airbreather** [comment]
I take it that there's no public spec for File GDB format, just FileGDB / OpenFileGDB binaries?

**Comment by FObermaier** [comment]
> I take it that there's no public spec for File GDB format, just FileGDB / OpenFileGDB binaries?

It is from ESRI.

**Comment by DGuidi** [comment]
Probably you just already know but there is anso a read-only driver that
doesn't depends on esri libs https://www.gdal.org/drv_openfilegdb.html

Il lun 11 mar 2019, 13:41 Felix Obermaier <notifications@github.com> ha
scritto:

**Comment by airbreather** [comment]
Looks like someone [reverse-engineered a spec](https://github.com/rouault/dump_gdbtable/wiki/FGDB-Spec) for it, in case we wanted something completely standalone.

**Comment by FObermaier** [comment]
This could be done in a sub-project, I'd say maintained by somebody else.
