### ISSUE TITLE
GeoAPI nuget package constraint is not valid development branch

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite#301]
The TeamCity build server fails to create nuget packages off of the current development branch due to the following issues:

- [x] GeoAPI prerelease package version is 2.0.0-nuget005 (instead of 2.0.0-pre005)
resolved on TeamCity
- [x] SharedAssemblyVersion.cs is no longer being created. 
resolved on TeamCity
- [x] The package constraint for GeoAPI is invalid `[2.0.0-nuget005,2.0.0-A)`

**Comment by airbreather** [comment]
Where's the TeamCity build server info so I can fix it?

Alternatively, I could just add the bits to `.travis.yml` to have it make the package and push to MyGet.

**Comment by FObermaier** [comment]
> Where's the TeamCity build server info so I can fix it?

It is @xivk 's, don't you have access to that?

**Comment by airbreather** [comment]
> > Where's the TeamCity build server info so I can fix it?
> 
> It is @xivk 's, don't you have access to that?

I don't remember ever seeing it.

**Comment by airbreather** [comment]
83f9d18 should take care of the `[2.0.0-nuget005,2.0.0-A)` issue.
