### ISSUE TITLE
Table-valued parameters

### ISSUE THREAD

**Issue by freworr** [NetTopologySuite/NetTopologySuite#302]
I have a .NET core 2.2 application with EF core and the NetTopologySuite extension. I need to execute a raw SQL command passing properties like ILinesString and IPoint via a table-valued parameter to a stored procedure. So I was wondering how I could set the correct type and value for the DataColumn in the DataTable passed in as a SqlParameter?  

Converting to DataTable
```csharp
public static DataTable ToDataTable<T>(this IEnumerable<T> self, string tableName, IList<string> exclude)
{
    var properties = typeof(T).GetProperties().Where(p => !exclude.Contains(p.Name)).ToList();

    var dataTable = new DataTable(tableName);
    foreach (var info in properties)
    {
        dataTable.Columns.Add(info.Name, Nullable.GetUnderlyingType(info.PropertyType) ?? info.PropertyType);
    }

    foreach (var entity in self)
    {
        dataTable.Rows.Add(properties.Select(p => p.GetValue(entity)).ToArray());
    }

    return dataTable;
}
```
Executing raw Sql command
```csharp
using (var data = remote.ToDataTable("dbo.Type", new List<string> {}))
{
    var parameter = new SqlParameter("@Type", data);
    parameter.TypeName = "dbo.Type";
    parameter.SqlDbType = SqlDbType.Structured;
    return await Context.Database.ExecuteSqlCommandAsync("exec dbo.StoredProcedure @Type", parameter);
}
```
The table-valued parameter that is defined with the datatype geography
```sql
CREATE TYPE [dbo].[Type] as TABLE (
    ...
    [Polyline] [geography] NULL,
    ...;
go
```

**Comment by bricelam** [comment]
You'll need to convert the IGeometry objects into SqlBytes first (using [NetTopologySuite.IO.SqlServerBytes](https://github.com/NetTopologySuite/NetTopologySuite.IO.SqlServerBytes)).

``` csharp
var geometryWriter = new SqlServerBytesWriter { IsGeography = true };
var rowValue = new SqlBytes(geometryWriter.Write(geometry))
```

But even after that, you may hit limitations (similar to https://github.com/dotnet/corefx/issues/35470) in SqlClient that prevent it from working.

Another alternative would be to try and get [NetTopologySuite.IO.SqlServer](https://github.com/NetTopologySuite/NetTopologySuite.IO.SqlServer2008) working on .NET Core via [dotMorten.Microsoft.SqlServer.Types](https://github.com/dotMorten/Microsoft.SqlServer.Types).

You're definitely in uncharted territory! Let us know what you find.

**Comment by freworr** [comment]
I did get it to work by setting the geometry column in the datable using the AsText() method, specifying only the name of the column as follows:
```csharp
public static DataTable ToDataTable<T>(this IEnumerable<T> self, string tableName, IList<string> exclude)
{
    var properties = typeof(T).GetProperties().Where(p => !exclude.Contains(p.Name)).ToList();
    var dataTable = new DataTable(tableName);
    
    foreach (var info in properties)
    {
        if (info.PropertyType == typeof(ILineString) || info.PropertyType == typeof(IPoint))
        {
            dataTable.Columns.Add(info.Name);
        }
        else
        {
            dataTable.Columns.Add(info.Name, Nullable.GetUnderlyingType(info.PropertyType) ?? info.PropertyType);
        }
    }

    foreach (var entity in self)
    {
        dataTable.Rows.Add(properties.Select(p =>
        {
            if (p.PropertyType == typeof(ILineString))
            {
                return ((ILineString) p.GetValue(entity))?.AsText();
            }

            if ( p.PropertyType == typeof(IPoint))
                return ((IPoint) p.GetValue(entity))?.AsText();

            return p.GetValue(entity);
        }).ToArray());
    }

    return dataTable;
}
```
The database was then able to translate the geometry string when passed in as a table-valued parameter. One should probably try to generalize this for IGeometry for further improvements. @bricelam I have not tried the alternatives you mentioned yet, but I would like to try them soon.

**Comment by bricelam** [comment]
Awesome. The solutions are essentially the same—yours uses WKT whole mine uses the MSSQL binary format.

**Comment by airbreather** [comment]
@freworr it looks like the approach that @bricelam suggested earlier (using `SqlServerBytesWriter`) should work now in .NET Core 3.0.

Either way, if this is working for you now, let me know and I'll close this.
