### ISSUE TITLE
Coordinates are flipped when using DBQuery

### ISSUE THREAD

**Issue by loth0** [NetTopologySuite/NetTopologySuite#304]
Found using:

- .NET Core 2.2
- Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 2.2.3
- Microsoft.AspNetCore.All 2.2.3

When using EF Core the coordinates are flipped when using DbQuery. Let's say I have this query:

`SELECT TOP 1 Geometri.AsTextZM()
    FROM VagGeometri
	ORDER BY VagGeometriId`

In SSMS this outputs the coordinates in the right order:

`LINESTRING (665560.493 6615244.716 22.009000000020023, 665567.246 6615221.815 22.889999999999418...`

If I add a GeometryPart class to my DbContext as a DbQuery:

Class:
`  public class GeometryPart
    {
        public ILineString Geometry { get; set; }
    }`

In DbContext:
`public virtual DbQuery<GeometryPart> GeometryPart { get; set; }`

And then use the same query with "FromSql":

            string sqlString = "SELECT TOP 1 Geometri as Geometry FROM VagGeometri ORDER BY VagGeometriId";

            var geom = _dbContext.GeometryPart.FromSql(sqlString).FirstOrDefault();

            Debug.WriteLine("geom: " + geom.Geometry.AsText());

This will output:

`geom: LINESTRING (6615244.716 665560.493 22.009000000020023, 6615221.815 665567.246 22.889999999999418...`

When added as a DbSet on the other hand:

In DbContext:
`        public virtual DbSet<VagGeometri> VagGeometri { get; set; }`

These two snippets:

        public void GeometryTest3()
        {
            string sqlString = @"SELECT TOP 1 *
                                    FROM VagGeometri
	                                ORDER BY VagGeometriId";

            var geom = _dbContext.VagGeometri.FromSql(sqlString).FirstOrDefault();

            Debug.WriteLine("geom: " + geom.Geometri.AsText());
        }

        public void GeometryTest4()
        {
            var geom = _dbContext.VagGeometri.OrderBy(vg => vg.VagGeometriId).FirstOrDefault();

            Debug.WriteLine("geom: " + geom.Geometri.AsText());
        }

Both outputs the coordinates in the right order:

`geom: LINESTRING (665560.493 6615244.716 22.009000000020023, 665567.246 6615221.815 22.889999999999418...`

**UPDATE:**

When removing HasColumnType("geometry") from the geometry column during model creating the same problem occurs for a DbSet. Is there a way to set column type for a DbQuery?

**UPDATE 2:**

Added this inside OnModelCteating in the DbContext:

        modelBuilder.Query<GeometryPart>(entity =>
            {
                entity.Property(e => e.Geometry)
                    .IsRequired()
                    .HasColumnType("geometry");
            });

Which solved the problem. Maybe this is intended behaviour? In that case you may close this issue.

**Comment by bricelam** [comment]
Intended behavior. Properties map to `geography` by default. You have to explicitly configure them as `geometry`.

**Comment by loth0** [comment]
Allright, thanks for info, closing this.
