### ISSUE TITLE
Export to GML supported?

### ISSUE THREAD

**Issue by sindizzy** [NetTopologySuite/NetTopologySuite#307]
So looking to output a feature to GML. In the source code [here ](https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/NetTopologySuite/Geometries/Geometry.cs) it says **"NO features or XLink are implemented here!"**. What exactly does that mean? Is that to say export to GML is not supported yet???

        /// <summary>
        /// Returns the feature representation as GML 2.1.1 XML document.
        /// This XML document is based on <c>Geometry.xsd</c> schema.
        /// **NO features or XLink are implemented here!**
        /// </summary>
        public XmlReader ToGMLFeature()
        {
            var writer = new GMLWriter();
            return writer.Write(this);
        }

**Comment by FObermaier** [comment]
Only the `Geometry` part is supported.
