### ISSUE TITLE
Remove IGeometry warts

### ISSUE THREAD

**Issue by bricelam** [NetTopologySuite/NetTopologySuite#308]
It seems like these properties are implementation detail and don't belong on the interface:

* BoundaryDimension
* EnvelopeInternal

**Comment by airbreather** [comment]
With these interfaces going away in v2.0 per NetTopologySuite/GeoAPI#70 / NetTopologySuite/GeoAPI#68, is there anything else to do about this one?

**Comment by bricelam** [comment]
Nope, I don't think this issue makes sense without separation between GeoAPI and NTS .
