### ISSUE TITLE
Make IsWithinDistance an extension method

### ISSUE THREAD

**Issue by bricelam** [NetTopologySuite/NetTopologySuite#309]
It feels like this method doesn't belong on the interface. It could easily be implemented as an extension method.

``` csharp
public static bool IsWithinDistance(this IGeometry thiz, IGeometry geom, double distance)
    => thiz.Distance(geom) <= distance;
```

**Comment by airbreather** [comment]
With `IGeometry` gone and `Geometry.IsWithinDistance` being there as `virtual`, 2.0 has this covered.
