### ISSUE TITLE
Missing NetopologySuite.Features namespace

### ISSUE THREAD

**Issue by futurify-ydang** [NetTopologySuite/NetTopologySuite#310]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
_(A description of the bug or feature)_

### Steps to Reproduce
_(List of steps, sample code, failing test or link to a project that reproduces the behavior)_

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 1.15.1
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on): Windows 10 pro x64
- .NET Framework version: NET Core 2.2
- Additional information: In 1.14.0 i can use **NetTopologySuite.Features.IFeature** and a lot of other classes. But i can not find them in version 1.15.1 
Please give me some instructions. Thanks!

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
It is in its own package:
`install-package NetTopologySuite.Features -version 1.15.1`

**Comment by airbreather** [comment]
Duplicate of #268

**Comment by futurify-ydang** [comment]
Thanks @FObermaier  and @airbreather

**Comment by futurify-ydang** [comment]
I have just faced another error when i tried to create shape file with **ShapefileDataWriter**
The error message is
`Reference to type 'IFeature' claims it is defined in 'NetTopologySuite', but it could not be found in ProjectName`

I installed NetTopologySuite.Features version 1.15.1 and NetTopologySuite.IO version 1.14.0.1

![image](https://user-images.githubusercontent.com/44663784/56020031-5527dd00-5d30-11e9-9bdf-64a1ef527167.png)

**Comment by airbreather** [comment]
> NetTopologySuite.IO version 1.14.0.1

Use the [`NetTopologySuite.IO.ShapeFile`](https://www.nuget.org/packages/NetTopologySuite.IO.ShapeFile/) package instead.

**Comment by futurify-ydang** [comment]
Thanks @airbreather. Can you give me a document about these changes of Nuget packages?

**Comment by airbreather** [comment]
> Can you give me a document about these changes of Nuget packages?

I can't, sorry, it sorta just happened as part of reorganizing the code to make #196 happen.  In general, all I/O formats we maintain outside of what used to be called the `NetTopologySuite` package now live in a separate NuGet package supporting **just** that I/O format.

My intent is to make sure future breaking changes like this are documented and come with a major version increment, with dependency version specs updated so that you can't accidentally mix pre- and post- versions without running into warnings.
