### ISSUE TITLE
GeoJSON Reader and Feature "id" attribute

### ISSUE THREAD

**Issue by Mangepange** [NetTopologySuite/NetTopologySuite#32]
I'm using GeoServer, and the Feature objects retrieved from it's WFS contains an id member. This cannot be deserialized using the GeoJsonSerializer since it throws an ArgumentException when a property name is not "bbox", "geometry" or "properties".

It's valid GeoJSON according to http://geojsonlint.com/ and when reading the specs, the "id" should be allowed: http://geojson.org/geojson-spec.html#feature-objects

Example (I've excluded geometry for readability...):

{"type":"FeatureCollection","totalFeatures":5,"features":[{"type":"Feature","id":"vfs_kommun.256","geometry":null,"properties":{"kommunnamn":"Karlskrona"}}],"crs":null}

**Comment by DGuidi** [comment]
Please be sure to test your json with source code, I'm sure to have fixed bug like this.
Anyway, I hope to check this issue soon.

**Comment by Mangepange** [comment]
I've built the latest source code, and FeatureConverter throws an ArgumentException. It looks like FeatureCollectionConverter was fixed to adress a similar issue, 186 (https://github.com/NetTopologySuite/NetTopologySuite/commit/b4fce08a3da85741b49e728eabadd9bfb01a4779)

**Comment by DGuidi** [comment]
ok thanks

**Comment by Mangepange** [comment]
Using my example GeoJSON above you will get another ArgumentException in ICRSObjectConverter. The ReadJson method can't handle a crs which is null. Maybe an if-statement should be added at the top of that method checking if the TokenType is null.

```c#
if (reader.TokenType == JsonToken.Null)
{
     reader.Read();
     return null;
}

**Comment by DGuidi** [comment]
@Mangepange can you take a look?

**Comment by Mangepange** [comment]
Maybe FeatureConverter should ignore all additional members just like FeatureCollectionConverter do? Geoserver adds a "geometry_name" property on its Features as well...
```
{"type":"FeatureCollection","totalFeatures":1,"features":[{"type":"Feature","id":"Road.1249","geometry":{"type":"MultiLineString","coordinates":[[[1610822.0864005657,7249990.524654245],[1610819.2585326964,7250021.630828278],[1611733.0938508697,7250797.447679726]]]},"geometry_name":"geom","properties":{"road_id":173922}}],"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::2400"}}}

**Comment by DGuidi** [comment]
@Mangepange from the [specs](http://geojson.org/geojson-spec.html#geojson-objects): "The GeoJSON object may have any number of members (name/value pairs)."

So I think you're right

**Comment by DGuidi** [comment]
tests are ok now

**Comment by Mangepange** [comment]
@DGuidi Yes, it seems to work now with my GeoServer as well! Thanks!

**Comment by DGuidi** [comment]
thanks to you for report and support
