### ISSUE TITLE
Support MSSQL-compatible WKT writing

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#324]
MSSQL doesn't actually support WKT as specified in OGC 06-103r4.

|OGC WKT|Apparent MSSQL Equivalent|
|-|-|
|`POINT (1 2)`|`POINT (1 2)`|
|`POINT Z (1 2 3)`|`POINT (1 2 3)`|
|`POINT ZM (1 2 3 4)`|`POINT (1 2 3 4)`|
|`POINT M (1 2 3)`|`POINT (1 2 NULL 3)`|

NTS 1.x happens to be more compatible for two reasons:
1. The JTS code that we ported it from **also** didn't support that exact version of the WKT spec
1. Neither JTS nor NTS supported M, so `POINT (1 2 3)` unambiguously meant Z = 3

**Comment by airbreather** [comment]
On the one hand, it's tempting to dismiss this outright by saying "MSSQL doesn't follow the spec, so it's up to either MSSQL or EF Core's MSSQL driver to deal with".

On the other hand, code to convert geometry to WKT is (unusually, especially for a text format) non-trivial, and MSSQL is historically a very big part of the ecosystems where C# / .NET often show up, so if anything might merit built-in support in NTS, this might be it.

**Comment by airbreather** [comment]
```sql
DECLARE @geomXY geometry = geometry::STGeomFromText('POINT (1 2)', 4326)
DECLARE @geomXYZ geometry = geometry::STGeomFromText('POINT (1 2 3)', 4326)
DECLARE @geomXYZM geometry = geometry::STGeomFromText('POINT (1 2 NULL 4)', 4326)

SELECT SRID=@geomXY.STSrid, X=@geomXY.STX, Y=@geomXY.STY, Z=@geomXY.Z, M=@geomXY.M
UNION ALL
SELECT @geomXYZ.STSrid, @geomXYZ.STX, @geomXYZ.STY, @geomXYZ.Z, @geomXYZ.M
UNION ALL
SELECT @geomXYZM.STSrid, @geomXYZM.STX, @geomXYZM.STY, @geomXYZM.Z, @geomXYZM.M
```

**Comment by airbreather** [comment]
I think we can solve this by allowing external code to inject code in a few specific spots.

First, it needs to be able to tell this filter to set the `Ordinates.Z` flag whenever the `Ordinates.M` flag is set:
https://github.com/NetTopologySuite/NetTopologySuite/blob/27b4c2bc8c87afc3d9f64f6b5cc487c99bf74a8b/NetTopologySuite/IO/WKTWriter.cs#L150-L154

Second, it needs to be able to tell this code not to run:
https://github.com/NetTopologySuite/NetTopologySuite/blob/27b4c2bc8c87afc3d9f64f6b5cc487c99bf74a8b/NetTopologySuite/IO/WKTWriter.cs#L721-L732

Third, it needs to be able to tell this code to write `" NULL"` instead of `" NaN"` if there's no Z:
https://github.com/NetTopologySuite/NetTopologySuite/blob/27b4c2bc8c87afc3d9f64f6b5cc487c99bf74a8b/NetTopologySuite/IO/WKTWriter.cs#L648-L666

**Comment by IanKemp** [comment]
> MSSQL doesn't actually support WKT as specified in OGC 06-103r4.

🤦‍♂

**Comment by bricelam** [comment]
@IanKemp Have you considered using PostgreSQL? I find it far more sane than any other RDBMS...
