### ISSUE TITLE
UnaryUnionOp Out of Sync with JTS Core

### ISSUE THREAD

**Issue by jhaverkost** [NetTopologySuite/NetTopologySuite#326]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of NetTopologySuite
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The overlay operation used in UnaryUnionOp is out of sync with the version in JTS Core. The JTS version uses SnapIfNeededOverlayOp while the NTS version only uses OverlayOp

NTS: [UnaryUnionOp](https://github.com/NetTopologySuite/NetTopologySuite/blob/540a32566f1e57a611e12b44d4162fdb1515aa04/NetTopologySuite/Operation/Union/UnaryUnionOp.cs#L253)

JTS: [UnaryUnionOp](https://github.com/locationtech/jts/blob/jts-1.15.1/modules/core/src/main/java/org/locationtech/jts/operation/union/UnaryUnionOp.java#L275)

### Steps to Reproduce
A UnaryUnionOp.Union operation on the example LineString below will fail using NTS due to non-noded intersections but will succeed when using JTS.

```
LINESTRING (-79.52286 8.89081, -79.57426 8.9547, -79.57421 8.95472, -79.57424 8.9547, -79.57429 8.9547, -79.57425 8.95469, -79.57429 8.95472, -79.57431 8.95472, -79.57424 8.95473, -79.57422 8.95478, -79.57424 8.95474, -79.57421 8.9547, -79.57426 8.95473, -79.57434 8.95472, -79.5742 8.95469, -79.57428 8.95474, -79.57433 8.95474, -79.57426 8.95471, -79.57419 8.95469, -79.57433 8.95479, -79.57426 8.95466, -79.57425 8.95476, -79.5743 8.95469, -79.57424 8.95469, -79.5742 8.95476, -79.57424 8.95465, -79.57423 8.95474, -79.57423 8.95471)
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 1.15.1 and 1.15.2
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on): Windows 10 Pro x64
- .NET Framework version: Mono 5.0.1 via Unity3D 2017.4.22f1 (.NET Framework 4.6 compatibility)

**Comment by airbreather** [comment]
Heh... ... ... it's possible that I should have investigated #325 a bit more before closing it outright.

Thanks for the detailed report.

**Comment by jhaverkost** [comment]
Thanks for addressing this. Appreciate the help.
