### ISSUE TITLE
Polygon across Dateline and Intersection

### ISSUE THREAD

**Issue by sindizzy** [NetTopologySuite/NetTopologySuite#330]
So I have an ellipse (a polygon geometry) that spans the Dateline. If I build the polygon with the coordinates as-is (namely the longitudes are in the range -180 to +180) it then results with the geometry being Invalid and thus when I intersect the polygon with the points I get the error:

`found non-noded intersection between LINESTRING(-155.32030939830221 83.16240616001781, -153.83095758124398 83.120852884772134) and LINESTRING(178.6792290990447 83.116588616289192, -179.84787091746912 83.158205372008268) [ (-155.06664425130143, 83.155328841178274, NaN, NaN) ]`

To alleviate this I take the polygon x values in the range -180 to +180 and shift them to the range 0 to 360. This gives me a valid geometry and the Intersection produces no exceptions. However the intersection only gives me points in the eastern hemisphere and the points in the western hemisphere are ignored.

Is this expected behavior? Is there anything I can do to process this data properly? Is the only solution to shift the points as well? I'm stumped as to how to proceed.

![image](https://user-images.githubusercontent.com/5298460/63289128-f9440680-c283-11e9-8c7c-2e92edbe379c.png)

**Comment by FObermaier** [comment]
You need to use a `MULTIPOLYGON` composed of parts on the eastern and parts of the western hemisphere. One way to achieve that is to 
1. Translate your polygons vertices +180°,
2. Build the `POLYGON`
3. Split your `POLYGON` using a `LINESTRING(180 100, 180 -100)` and build a `MULTIPOLYGON` of the parts ([see this](https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/test/NetTopologySuite.Samples.Console/Operation/Polygonize/SplitPolygonExample.cs)).
4. Translate the vertices of that `MULTIPOLYGON` -180° and use it for your intersection tests.
