### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by DGuidi** [NetTopologySuite/NetTopologySuite#337]
Compilations fail until I added this on csproj `<LangVersion>latest</LangVersion>` after `NoWarn` (inside tag `PropertyGroup`) - see [csproj](https://github.com/NetTopologySuite/NetTopologySuite/blob/5bdc85f9cc0fe1ae29e5bbe758cb333d095289eb/src/NetTopologySuite/NetTopologySuite.csproj#L7)

Not sure if it's related to the fact that I'm using VS2017 for this. I assume that in any case, adding this tag can't break anything.

**Comment by airbreather** [comment]
> Not sure if it's related to the fact that I'm using VS2017 for this.

Yes, that's the reason.  From https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version:
> The C# compilers that are part of the Visual Studio 2017 installation or earlier .NET Core SDK versions target C# 7.0 by default.
