### ISSUE TITLE
Finish GML3 writer support

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#341]
#334 got this started (thanks @m1dst), but there are some things I need to resolve before I'm comfortable releasing this support publicly:
1. `NetTopologySuite.IO.`**`GML2`**`.GMLWriter` probably isn't what people should have to use in order to write GML documents using GML **3.x** syntax.
1. It shouldn't use the deprecated `coordinates` tag (see also #331)
1. I need to read Annex I of OGC 07-036r1 again to verify that we've accounted for all the relevant differences.

So this issue is to track the progress of finishing up what #334 started.

**Comment by qcc-na** [comment]
What work remains for GML 3.x support?

**Comment by airbreather** [comment]
> What work remains for GML 3.x support?

It's just the things I listed in the description:

> 1. `NetTopologySuite.IO.`**`GML2`**`.GMLWriter` probably isn't what people should have to use in order to write GML documents using GML **3.x** syntax.
> 1. It shouldn't use the deprecated `coordinates` tag (see also #331)
> 1. I need to read Annex I of OGC 07-036r1 again to verify that we've accounted for all the relevant differences.

Maybe we can skip the last one (or someone else can do it), but we just had #472, so there may still be some gaps.
