### ISSUE TITLE
Reading/Writing to SQL Server

### ISSUE THREAD

**Issue by sindizzy** [NetTopologySuite/NetTopologySuite#344]
I am looking to read/write to MS SQL Server. Fields that are of type Geometry and Geography. Not sure I understand the difference between NetTopologySuite.IO.SqlServerBytes and NetTopologySuite.IO.SqlServer2008. Is the former just an updated version of the latter? And what about NetTopologySuite.IO.MsSqlSpatial?

**Comment by bricelam** [comment]
SqlServer2008 goes through Microsoft.SqlServer.Types which only* works on .NET Framework/Windows.

SqlServerBytes works without that assembly and therefore works on more frameworks/platforms.

\* There is an unofficial port of this assembly that works enough to enable SqlServer2008 on additional frameworks

**Comment by bricelam** [comment]
MsSqlSpatial pre-dates SQL Server’s geometry and geography types. This one definitely isn’t the library you’re looking for. 😉

**Comment by sindizzy** [comment]
Got it. Thanks for the info.
