### ISSUE TITLE
QuadEdge.oNext implementation missing

### ISSUE THREAD

**Issue by manaspatnaik** [NetTopologySuite/NetTopologySuite#345]
While exploring a stackoverflow solution https://stackoverflow.com/questions/13203080/example-of-how-to-interpolate-a-z-value-for-a-point-using-the-delaunay-triangula I found QuadEdge.oNext implementation is missing

can someone confirm it is so ?

**Comment by airbreather** [comment]
Hm, it's [there but `internal`](https://github.com/NetTopologySuite/NetTopologySuite/blob/01373b97c544056254b4240b007035bae0e05c16/src/NetTopologySuite/Triangulate/QuadEdge/QuadEdge.cs#L201-L205).  I wonder why

**Comment by manaspatnaik** [comment]
@airbreather  May be due to migration automation.
BTW , I just made those "Public" (locally) & it seems to be working fine .I am able traverse through the edges.
Will confirm once I test all round .

Thanks.
