### ISSUE TITLE
NetTopologySuite.CoordinateSystems.Transformations.GeometryTransform.TransformPolygon returns a GeoAPI polygon

### ISSUE THREAD

**Issue by donnyv** [NetTopologySuite/NetTopologySuite#346]
### Description
I've updated to v2.0.0 and during my code porting noticed that `NetTopologySuite.CoordinateSystems.Transformations.GeometryTransform.TransformPolygon` is still returning a GeoAPI.Geometries.IPolygon. Which breaks the code conversion over to `NetTopologySuite.Geometries.Polygon`.

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: v2.0.0
- Other NetTopologySuite packages and versions: GeoAPI.CoordinateSystems v1.7.5
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 4.7.2

**Comment by airbreather** [comment]
There is no `NetTopologySuite.CoordinateSystems` package for v2 at the moment, and `GeoAPI.*` packages are for NTS v1 not v2.

**Comment by donnyv** [comment]
I guess I'm stuck with NTS v1 for now if I need to do transforms?

**Comment by airbreather** [comment]
ProjNet 2.0.0 is out there, v2 just doesn't have an equivalent to that one package that bridged the two together.  I didn't jump on writing it immediately, because it didn't seem appropriate to continue publishing a whole package that implements what's essentially this:

```csharp
public static Geometry Transform(Geometry geom, MathTransform transform)
{
    geom = geom.Copy();
    geom.Apply(new MTF(transform));
    return geom;
}

sealed class MTF : ICoordinateSequenceFilter
{
    private readonly MathTransform _mathTransform;

    public MTF(MathTransform mathTransform) => _mathTransform = mathTransform;

    public bool Done => false;
    public bool GeometryChanged => true;
    public void Filter(CoordinateSequence seq, int i)
    {
        double x = seq.GetX(i);
        double y= seq.GetY(i);
        double z = seq.GetZ(i);
        _mathTransform.Transform(ref x, ref y, ref z);
        seq.SetX(i, x);
        seq.SetY(i, y);
        seq.SetZ(i, z);
    }
}
```

**Comment by donnyv** [comment]
Sorry I'm not that familiar with transforms and how to implement it.  Where is that "MathTransform" coming from?

**Comment by airbreather** [comment]
> Where is that "MathTransform" coming from?

It's in the [`ProjNet` package](https://www.nuget.org/packages/ProjNet) (which is what used to be the `ProjNet4GeoAPI` package).

**Comment by donnyv** [comment]
That did it! Thank you so much. Its funny because I had to update to v2 because I had found a bug with NetTopologySuite.IO.GeoJsonReader not liking properties set in a different order. V2 fixed it.
