### ISSUE TITLE
Polygon overlap return false while polygon equalExact

### ISSUE THREAD

**Issue by sendreams** [NetTopologySuite/NetTopologySuite#347]
### Prerequisites
use the latest 2.0.0 version

### Description
_(A description of the bug or feature)_

### Steps to Reproduce
POLYGON ((14444.89404440699 -13740.381743309472, 14450.29404440699 -13740.381743309472, 14450.29404440699 -13739.181743309471, 14444.89404440699 -13739.181743309471, 14444.89404440699 -13740.381743309472))
two polygon has the same points, then excute overlap function, i think it will be return true.
but the result is false.

### System Configuration

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
This is the expected result. According to the (DE9-IM)[https://en.wikipedia.org/wiki/DE-9IM] model, overlaps is not the same as equals:
> ... a overlaps b: they have __some but not all__ points in common, they have the same dimension, and the intersection of the interiors of the two geometries has the same dimension as the geometries themselves
