### ISSUE TITLE
Update NTS master to latest JTS trunk

### ISSUE THREAD

**Issue by DGuidi** [NetTopologySuite/NetTopologySuite#35]
To [r969](http://sourceforge.net/p/jts-topo-suite/code/969/) at time of this writings.

**Comment by DGuidi** [comment]
updated to jts r1040

**Comment by DGuidi** [comment]
JTS is now at [r1050](http://sourceforge.net/p/jts-topo-suite/code/commit_browser), with some interesting stuff like GeoJson Reader/Writer

**Comment by FObermaier** [comment]
NTS is at rev 1049. I left out GeoJSON reader writer since we have that already.
We can leave the issue open, though

**Comment by DGuidi** [comment]
+1

**Comment by DGuidi** [comment]
after a bit of investigation, NTS looks aligned with r1087 a7831571ca9afd340d0d05ada07f084ab9657ef9

**Comment by DGuidi** [comment]
added r1088 and r1099 with 92594fb977c69af36cd0b2310a174e615e50d38f

**Comment by DGuidi** [comment]
next todo is [r1100](https://sourceforge.net/p/jts-topo-suite/code/1100)
