### ISSUE TITLE
Migration from Dotnet 2.2.x to 3.0.0; Can no longer implicitly cast 'GeoAPI.Geometries.Coordinate' to 'NetTopologySuite.Geometries.Coordinate' 

### ISSUE THREAD

**Issue by trevelyanuk** [NetTopologySuite/NetTopologySuite#350]
(May be related to #332 )

I have a custom resolver - for Automapper - that maps two doubles to a point that can be stored in a Postgresql database.  

```
public class GeometryResolver : IMemberValueResolver<RecordModel, Record, double[], IGeometry>
    {
        public IGeometry Resolve(RecordModel, Record entity, double[] srcMember, IGeometry destMember, ResolutionContext context)
        {
            var geometryFactory = NtsGeometryServices.Instance.CreateGeometryFactory(srid: 4326);
            var coord = new GeoAPI.Geometries.Coordinate(srcMember[0], srcMember[1]);
            destMember = geometryFactory.CreatePoint(coord);
            return destMember;
        }
    }
```

Updating `Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite` to v3.0.0-preview9 and `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite` to version 3.0 had the effect of breaking the line of code below, giving me a message suggesting that it cannot convert from 'GeoAPI.Geometries.Coordinate' to 'NetTopologySuite.Geometries.Coordinate'

`destMember = geometryFactory.CreatePoint(coord);`

I removed the reference to GeoAPI.Geometries so that now I would be using `NetTopologySuite.Geometries.Coordinate` instead; however, this then breaks when I try to return 
`destmember`, saying that it cannot implicitly convert type 'NetTopologySuite.Geometries.Point' to 'GeoAPI.Geometries.IGeometry'.  

Simply changing the return type from `IGeometry` to `Geometry` seemed as though it was going to fix everything, since this removed the errors from my resolver. However, this then breaks Automapper, further on in my code, by suggesting that it; 
> "Cannot convert lambda expression to type 'string' because it is not a delegate type"

The code for where the error occurs is;
```
 cfg.CreateMap<RecordModel, Record>()
       .ForMember(dest => dest.Location, opts => opts.MapFrom<GeometryResolver, double[]>(src => (new double[] { src.devLon, src.devLat })))

```

I've reverted back to 2.2.x for now, but I'm a bit unsure as to what the cause exactly is; if we should be using Geometry, rather than IGeometry, then I've come to the conclusion that IGeometry must have been a delegate in a way that Geometry isn't, but I'm not sure where to look to confirm that (or what would need fixing).

**Comment by bricelam** [comment]
cc @roji

**Comment by roji** [comment]
EF Core 3.0.0 changes its dependency on NetTopologySuite to version 2.0.0, where the GeoAPI interfaces have been are no longer used - so you should definitely not be using IGeometry anymore. The concrete geometry classes such as Point, LineString simply inherit from Geometry, which is what should probably be returned in the code above.

However, I have no idea how AutoMapper operates or why it is being broken by this... You should probably ask for help with them...

**Comment by airbreather** [comment]
@trevelyanuk I'm unable to reproduce the issue with the information you've given me.  As @roji said above, the `IGeometry` interface is gone in 2.x, so if this code is compiling for you, then you are trying to mix 1.x versions of the NetTopologySuite library with 2.x versions (which will not work).

If you don't have any explicit references to earlier versions of the NetTopologySuite packages, then you may need to check for any transitive references among your dependencies.

Below is my attempt to reproduce the issue that you are seeing, which seems to work as intended:

# ConsoleApp0.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="9.0.0" />
    <PackageReference Include="NetTopologySuite" Version="2.0.0" />
  </ItemGroup>

</Project>
```

# Program.cs
```csharp
using System;

using AutoMapper;

using NetTopologySuite;
using NetTopologySuite.Geometries;

class RecordModel
{
    public double devLon { get; set; }

    public double devLat { get; set; }
}

class Record
{
    public Geometry Location { get; set; }
}

class GeometryResolver : IMemberValueResolver<RecordModel, Record, double[], Geometry>
{
    public Geometry Resolve(RecordModel source, Record destination, double[] sourceMember, Geometry destMember, ResolutionContext context)
    {
        var geometryFactory = NtsGeometryServices.Instance.CreateGeometryFactory(srid: 4326);
        var coord = new Coordinate(sourceMember[0], sourceMember[1]);
        destMember = geometryFactory.CreatePoint(coord);
        return destMember;
    }
}

class Program
{
    static void Main()
    {
        var config = new MapperConfiguration(Configure);
        var mapper = config.CreateMapper();
        var model = new RecordModel { devLat = 42.3293, devLon = -83.0398 };
        var record = mapper.Map<Record>(model);
        Console.WriteLine(record.Location); // writes POINT (-83.0398 42.3293)
    }

    static void Configure(IMapperConfigurationExpression cfg)
    {
        cfg.CreateMap<RecordModel, Record>()
           .ForMember(dest => dest.Location,
                      opts => opts.MapFrom<GeometryResolver, double[]>(src => (new double[] { src.devLon, src.devLat })));
    }
}
```

**Comment by trevelyanuk** [comment]
Curious, it all works fine now - although I noticed that . It could be that the version of Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite was the issue, since only v3.0.0-preview9 was available.. but I've updated this to 3.0.1 and it all looks fine now.

Sorry about that and thanks for checking!
