### ISSUE TITLE
Allow NtsGeometryServices to create subclasses of GeometryFactory

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#354]
In v2, we removed `IGeometryServices` in favor of `NtsGeometryServices`.

There is occasionally a need to use a subclass of `GeometryFactory`, but `NtsGeometryServices` does not have any methods that can be overridden.

Suggested fix is to unseal `NtsGeometryServices` and add a virtual method that we use [here](https://github.com/NetTopologySuite/NetTopologySuite/blob/741ce3675df99cd8a9bc68b27db732764f06cbea/src/NetTopologySuite/NtsGeometryServices.cs#L112) instead of always creating a new instance of the base class.

**Comment by SamuelEnglard** [comment]
Also, removing the forced change of Factory when setting SRID on a geometry would make this (personally) less of an issue.
