### ISSUE TITLE
Add elevation values to geometry - throws exception

### ISSUE THREAD

**Issue by HarelM** [NetTopologySuite/NetTopologySuite#356]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I would like to add elevation (z value) to a geometry but since I migrated to 2.0 I'm not sure how to accomplish this.

### Steps to Reproduce
the following code used to do the job before migrating to 2.0, but now it throws an exception:
```
foreach (var coordinate in featureCollection.SelectMany(f => f.Geometry.Coordinates))
{
    coordinate.Z = await _elevationDataStorage.GetElevation(coordinate);
}
```
I have read the wiki and understood the change, but I really don't know how to properly solve this without a lot of code to recreate the geometries.
Any idea would be good.
Note that the geometry is coming from an elasticsearch database - i.e. it is converted from JSON and some of the data just doesn't have elevation info...

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.0.0
- Other NetTopologySuite packages and versions: N/A
- Environment (Operating system, version and so on): Win 10.
- .NET Framework version: .Net core 3.0
- Additional information:

**Comment by HarelM** [comment]
I have changed the entire application to use `CoordinateZ` instead of `Coordinate` even when it is not needed in order not to get this exception. It's a hack, but it works...
Feel free to close this issue.
A conversion method of geometries from 2D to 3D would be ideal, IMO.

**Comment by airbreather** [comment]
Can you please share some more of the code that creates the geometries?  There may be an easier way to do it (if not, then we should probably consider options).

**Comment by HarelM** [comment]
Well, in theory, the point of abstraction is that I shouldn't care how the geometries are created.
What I mean to say is that in the context of the above code, I have no clue who created the geometries and if they are 2D or 3D.
The code that generates the geometries is far down the hierarchy. 
Nevertheless, to answer your question the geometry is either generated from the elasticsearch database here:
https://github.com/IsraelHikingMap/Site/blob/40a8001fd91f0e1ecbbdab93a8d89e0236b97ef2/IsraelHiking.DataAccess/ElasticSearchGateway.cs#L52L55
https://github.com/IsraelHikingMap/Site/blob/40a8001fd91f0e1ecbbdab93a8d89e0236b97ef2/IsraelHiking.DataAccess/ElasticSearchGateway.cs#L332
Or in a gateway, for example the following:
https://github.com/IsraelHikingMap/Site/blob/40a8001fd91f0e1ecbbdab93a8d89e0236b97ef2/IsraelHiking.DataAccess/INatureGateway.cs#L172L205
https://github.com/IsraelHikingMap/Site/blob/b464a3d227d8427eca88834a29a959831d4968f1/IsraelHiking.Common/CoordinateExtensions.cs#L14

**Comment by airbreather** [comment]
Yeah, I have a related comment in an upstream bug report: https://github.com/locationtech/jts/issues/434#issuecomment-525728437.  I agree that at the minimum, everything should be consistent (since there are multiple ways of doing this, only some of which throw for coordinates without Z).

One straightforward alternative to the block in the original code might be:
```csharp
foreach (var coordinate in featureCollection.SelectMany(f => f.Geometry.Coordinates))
{
    if (Coordinates.Dimension(coordinate) - Coordinates.Measures(coordinate) > 2)
    {
        coordinate.Z = await _elevationDataStorage.GetElevation(coordinate);
    }
}
```

However, `.Coordinates` is not guaranteed to give you the underlying instances (e.g., if you're using a different `CoordinateSequence` implementation), so it might make sense to use `ICoordinateSequenceFilter`... the `await` in there suggests a two-pass approach:

```csharp
var extractXYValuesFilter = new ExtractXYValuesFilter();
foreach (var feature in featureCollection)
{
    feature.Geometry.Apply(extractXYValuesFilter);
}

Coordinate c = new Coordinate();
foreach ((double x, double y) in extractXYValuesFilter.XYToElevation.Keys)
{
    c.X = x;
    c.Y = y;
    extractXYValuesFilter.XYToElevation[(x, y)] = await _elevationDataStorage.GetElevation(c);
}

var setElevationValuesFilter = new SetElevationValuesFilter(extractXYValuesFilter.XYToElevation);
foreach (var feature in featureCollection)
{
    feature.Geometry.Apply(setElevationValuesFilter);
}

/* ... */
private sealed class ExtractXYValuesFilter : ICoordinateSequenceFilter
{
    bool ICoordinateSequenceFilter.Done => false;
    bool ICoordinateSequenceFilter.GeometryChanged => false;

    public Dictionary<(double x, double y), double> XYToElevation { get; } = new Dictionary<(double x, double y), double>();

    public void Filter(CoordinateSequence seq, int i)
        => XYToElevation[(seq.GetX(i), seq.GetY(i))] = double.NaN;
}

private sealed class SetElevationValuesFilter : ICoordinateSequenceFilter
{
    private readonly Dictionary<(double x, double y), double> _XYToElevation;

    public SetElevationValuesFilter(Dictionary<(double x, double y), double> XYToElevation)
        => _XYToElevation = XYToElevation;

    bool ICoordinateSequenceFilter.Done => false;
    bool ICoordinateSequenceFilter.GeometryChanged => true;

    public void Filter(CoordinateSequence seq, int i)
    {
        // seq.HasZ check is optional, but probably faster
        if (seq.HasZ &&
            _XYToElevation.TryGetValue((seq.GetX(i), seq.GetY(i)), out double elevation))
        {
            seq.SetZ(i, elevation);
        }
    }
}
```

**Comment by HarelM** [comment]
WOW... Well... I don't expect anyone that doesn't have a deep knowledge of how this library works and how the implementation is to be able to write the above code...
I've been using this library for a few years now and I would get cold feet before adding this code to production.
In any case, I have changed all instanciation to use `CoordinateZ` which is a lot easier, I think...
The decision to separate the Coordinates implementation is cumbersome to me, while I understand the OOP behind this, I favor POCO style object that are easy to work with and just have missing values instead of immutable and restricted object that in theory should help make the code more robust but in practice makes you write a lot of code to work around the unproductive parts...

**Comment by FObermaier** [comment]
@hareim, 2 things you should be aware of:
* The coordinates of a geometry are not stored in an array of `Coordinate` items but in an `ICoordinateSequence` implementation. You were only getting away with your approach because the default `ICoordinateSequence` is `CoordinateArraySequence` which is backed by an array of `Coordinates`. 
* The `Geometry.Coordinates` and the single-item-geometry's `CoordinateSequence` property do not have a setter, which _indicates_ that created geometries are considered -more or less- *immutable*. So the clean approach would create and return new geometries when adding elevation data. When you do change items of a coordinate sequence (SetOrdinate(...)), you need to call `Geometry.GeometryChanged` in order to update things like `EnvelopeInternal`. 

@airbreather, doesn't `ICoordinateSequenceFilter` have a `Done` and `GeometryChanged` property?

**Comment by airbreather** [comment]
> I don't expect anyone that doesn't have a deep knowledge of how this library works and how the implementation is to be able to write the above code...
> I've been using this library for a few years now and I would get cold feet before adding this code to production.

This is a good point, it might make sense to put some common "recipes" like this into the wiki.

Personally I've written code like that a bunch of times (including 2 implementations similar to one of the ones I pasted above, which have been running in production for 5+ years), out of necessity, since the default `CoordinateArraySequence` has unacceptable performance for our use case at work.

> The decision to separate the Coordinates implementation is cumbersome to me, while I understand the OOP behind this, I favor POCO style object that are easy to work with and just have missing values instead of immutable and restricted object that in theory should help make the code more robust but in practice makes you write a lot of code to work around the unproductive parts...

It's a real challenge to strike an appropriate balance between performance, broad applicability, end-user developer productivity, and library developer productivity in a library like JTS/NTS.
- To maximize library developer productivity, we take code from JTS (with rare exceptions), even though the JTS code is aimed at Java end users with performance that's optimized for JVM implementations.
- To allow end users to efficiently store massive geometries without **too much** overhead, we allow them to supply their own `CoordinateSequence` implementation, but taking advantage of this can be unproductive for the end user (though the redesign in 2.x makes it a lot better), and many algorithms will actually perform worse* when doing so.
    - *because they use `Coordinate` instances under the covers anyway, which will have to be created for the optimized sequence.
    - It's more productive for the library developer to write the algorithms that way than to keep constantly working with "`CoordinateSequence`-and-index`, or to build an alternative to `List<Coordinate>` that dynamically resizes a sequence whose final size is unknown in advance.
- re: broad applicability, major parts of JTS/NTS assume that the geometries live in a Euclidean space, despite the fact that **highly** popular use cases use coordinates on the surface of a sphere / ellipsoid, which is non-Euclidean, because this is the most productive for the library developer.
    - at the expense of having problems that are **highly** unproductive for the user, manifesting in #233, #330, and I'm sure **many** others that I can't find right now in my search (perhaps because they're not getting reported)...
- and more...

I wish I could do more to make this library more intuitive, more IntelliSense-friendly, etc., but circumstances limit how far that can go.

**Comment by HarelM** [comment]
Thanks for you help once more.
I think this issue can be closed as I don't see anything that need to be done here besides maybe adding some information to the release notes/migration process between previous version and 2.0.
I have implemented a simple filter that does the entire job (instead of two filters), I hope my code is correct. It does work but so did the code before this one...
https://github.com/IsraelHikingMap/Site/commit/e8d5a62137fd66b19a552b801c009a7ef76de5ff
I assume it will fail for non `CoordinateZ` sequences, but so did the previous code...

**Comment by HarelM** [comment]
Is it possible that this doesn't work of STJ features?
I have the following code:
```cs
public static Geometry SetElevation(Geometry geometry, IElevationGateway elevationGateway)
        {
            var getCoordinatesFilter = new GetCoordinatesFilter();
            geometry.Apply(getCoordinatesFilter);
            var coordinates = getCoordinatesFilter.CoordinatesMap
                .OrderBy(k => k.Key)
                .ToArray();
            var elevationValues = elevationGateway.GetElevation(coordinates.Select(c => c.Value).ToArray()).Result;
            var elevationDictionary = new Dictionary<int, double>();
            for (var index = 0; index < coordinates.Length; index++)
            {
                var keyValuePair = coordinates[index];
                elevationDictionary[keyValuePair.Key] = elevationValues[index];
            }
            var setElevationValuesFilter = new SetElevationValuesFilter(elevationDictionary);
            geometry.Apply(setElevationValuesFilter);
            return geometry;
        }
```
Which should update the geometry elevation values, but it doesn't seem to change when used on STJ Features...
Am I missing anything?
Should I open a different issue?

**Comment by HarelM** [comment]
I guess it is related to the fact that STJ geojson creates a coordinate sequence that is 2D when reading a 2D geojson.
Is there a way to force the geojson factory to create 3D sequnece like in the past (`new GeoJsonConverter(factory, 3)`)?
I'm using the following code:
```cs
public static readonly GeoJsonConverterFactory GeoJsonWritableFactory = new (new GeometryFactory(), false, null, RingOrientationOption.EnforceRfc9746, true);
```

**Comment by HarelM** [comment]
I ended up writing the following code to add elevation to any geometry I get:
I'm not sure this is the right solution, it looks a bit clunky... 
```cs
    /// <summary>
    /// This helper helps setting the z value of coordinate sequence
    /// </summary>
    public static class ElevationSetterHelper
    {
        private static Coordinate[] CoordinatesTo3D(Coordinate[] coordinatesArray, IElevationGateway elevationGateway)
        {
            var zValues = elevationGateway.GetElevation(coordinatesArray).Result;
            return coordinatesArray.Select((c, i) => new CoordinateZ(c.X, c.Y, zValues[i]) as Coordinate)
                .ToArray();
        }

        private static Point PointTo3D(Point point, IElevationGateway elevationGateway)
        {
            var z = elevationGateway.GetElevation(point.Coordinate).Result;
            return new Point(point.Coordinate.X, point.Coordinate.Y, z);
        }
        
        private static LinearRing LinearRingTo3D(LinearRing linearRing, IElevationGateway elevationGateway)
        {
            return new LinearRing(CoordinatesTo3D(linearRing.Coordinates, elevationGateway));
        }

        private static Polygon PolygonTo3D(Polygon polygon, IElevationGateway elevationGateway)
        {
            return new Polygon(LinearRingTo3D(polygon.Shell, elevationGateway),
                polygon.Holes.Select(h => LinearRingTo3D(h, elevationGateway)).ToArray());
        }
        
        /// <summary>
        /// Main helper function to set the elevation for a geometry
        /// </summary>
        /// <param name="geometry">The geometry to update</param>
        /// <param name="elevationGateway">The elevation gateway</param>
        public static Geometry GeometryTo3D(Geometry geometry, IElevationGateway elevationGateway)
        {
            switch (geometry.OgcGeometryType)
            {
                case OgcGeometryType.Point:
                    return PointTo3D((Point)geometry, elevationGateway);
                case OgcGeometryType.LineString:
                    return new LineString(CoordinatesTo3D(geometry.Coordinates, elevationGateway));
                case OgcGeometryType.Polygon:
                    return PolygonTo3D((Polygon)geometry, elevationGateway);
                case OgcGeometryType.MultiPoint:
                    var multiPoint = (MultiPoint)geometry;
                    return new MultiPoint(multiPoint.Geometries.Cast<Point>().Select(p => PointTo3D(p, elevationGateway)).ToArray());
                case OgcGeometryType.MultiPolygon:
                    var multiPolygon = (MultiPoint)geometry;
                    return new MultiPolygon(multiPolygon.Geometries.Cast<Polygon>()
                        .Select(p => PolygonTo3D(p, elevationGateway)).ToArray());
                case OgcGeometryType.MultiLineString:
                    var multiLineString = (MultiPoint)geometry;
                    return new MultiLineString(multiLineString.Geometries.Cast<LineString>()
                        .Select(l => new LineString(CoordinatesTo3D(l.Coordinates, elevationGateway))).ToArray());
                case OgcGeometryType.GeometryCollection:
                    var geometryCollection = (GeometryCollection)geometry;
                    return new GeometryCollection(geometryCollection.Geometries
                        .Select(g => GeometryTo3D(g, elevationGateway)).ToArray());
                default:
                    throw new Exception("Invalid type: " + geometry.OgcGeometryType);
            }
        }

        /// <summary>
        /// Main helper function to set the elevation for a collection of features
        /// </summary>
        /// <param name="features">The features to update</param>
        /// <param name="elevationGateway">The elevation gateway</param>
        public static void GeometryTo3D(IEnumerable<IFeature> features, IElevationGateway elevationGateway)
        {
            foreach (var feature in features)
            {
                feature.Geometry = GeometryTo3D(feature.Geometry, elevationGateway);
            }
        }
    }
```
