### ISSUE TITLE
Non noded intersection on InteriorPoint with fixed precision model

### ISSUE THREAD

**Issue by Kortdag** [NetTopologySuite/NetTopologySuite#358]
The sample below demonstrates how to reproduce Non-Noded intersection when accessing interior point if useing a fixed precicion model. Floting model works as expected.

In both cases the geometries has IsValid=true.

var wkt = @"POLYGON ((481831.59 6200950.77, 481831.586 6200950.77, 481823.88 6200952.539, 481816.51 6200954.31, 481823.88 6200952.54, 481831.59 6200950.77))";
            var wktReader1 = new WKTReader(new NetTopologySuite.Geometries.GeometryFactory(new PrecisionModel(1000)));
            var wktReader2 = new WKTReader();

            var geo1 = wktReader1.Read(wkt);
            var geo2 = wktReader2.Read(wkt);

            var interiorPoint2 = geo2.InteriorPoint; // Non noded intersection
            var interiorPoint1 = geo1.InteriorPoint; // No problems

Tested in NTS 1.14.0 and NTS 1.15.3
Not very families with JTS Testbuilder but seems to be an issue in 1.14 there aswell, so it migth be an upstream issue..

**Comment by airbreather** [comment]
Confirmed in 1.15.3.

Fixed in 2.0.0.
