### ISSUE TITLE
Enhancement for GeometryFactory

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite#360]
NTS' (and JTS') `GeometryFactory` does not care about ring orientations for polygons. It doesn't even enforce that the orientation of the interior rings is opposite to that of the exterior ring.

When serializing these geometries with various providers it might lead to difficulties: 
#### Require left-hand-rule (CCW)
* OGC Simple Features Access - Common Architecture v1.2.1 (6.1.11.1)
* Oracle, 
* SqlServer Geography, 
* ... 

#### Require right-hand-rule (CW) for exterior shell
* GeoJSON,
* ...

#### Don't care
* PostGis
*

There is `OgcCompliantGeometryFactory` that enforces the left-hand-rule (CCW), so it works for the first list. I have issues with the name though, as it does not actually say what it does. Additionally there is currently no way to enforce the right-hand-rule (CW).

I propose we mark `OgcCompliantGeometryFactory` obsolete and either enhance the  default `GeometryFactory` to optionally enforce orientation rules on linear rings, or create derive another class that does so.

**Comment by airbreather** [comment]
> either enhance the default `GeometryFactory` to optionally enforce orientation rules on linear rings, or create derive another class that does so.

I think enhancing the default `GeometryFactory` is the way to go.
