### ISSUE TITLE
shell is empty but holes are not - Upgrading to NetTopologySuite 2.0

### ISSUE THREAD

**Issue by baartho** [NetTopologySuite/NetTopologySuite#365]
### Description
I'm getting "shell is empty but holes are not" for all shapes that were working fine on 1.13.2.0

I basically have the field below

`public Geometry Shape { get; set; }`

On 1.13.2.0 instead of using `Geometry` I was using `System.Data.Entity.Spatial.DbGeometry`

And this is the data stored on the DB.

`0x080C0000010406000000A027E9E999E24141206407895A02494180442221BAE7414140994C26B5034941E04BFB2263E6414120954A05B608494120168BB51BE5414180EA9FEABE0D4941200C069309E0414180929EB4740C4941A027E9E999E24141206407895A02494101000000020000000001000000FFFFFFFF0000000003`

I'm wondering if I have to transform the data somehow. Or what I'm doing wrong. 

Thank you!

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite 2.0.0:
- .NET Core 3.0

**Comment by baartho** [comment]
```
NetTopologySuite.Geometries.Coordinate[] coordinates = new[] {
                                    new NetTopologySuite.Geometries.Coordinate(2344243.8274278194, 3278005.0705380589 ),
                                    new NetTopologySuite.Geometries.Coordinate(2346868.2588582635, 3278698.2992126048),
                                    new NetTopologySuite.Geometries.Coordinate(2346182.2732939571, 3281260.0413385779),
                                    new NetTopologySuite.Geometries.Coordinate(2345527.4183070809, 3283837.8330052495),
                                    new NetTopologySuite.Geometries.Coordinate(2342931.1486220509, 3283177.4110892415),
                                    new NetTopologySuite.Geometries.Coordinate(2344243.8274278194, 3278005.0705380589) 
        };

GeometryFactory Factory = new GeometryFactory();

var linearRing = Factory.CreateLinearRing(coordinates);
var _polygon = Factory.CreatePolygon(linearRing);

var classInstance= new SomeClass();
classInstance.Shape = _polygon;

MyContext.SomeClass.Add(classInstance);
MyContext.SaveChanges();
```

On the DB I've a `Geometry` field. 

When I try to commit the shape above with `SaveChanges()` I get the following error: 

`SqlException: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 3 ("@p2"): The supplied value is not a valid instance of data type geography. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.`

**Comment by FObermaier** [comment]
EFCore maps spatial types to sql-server's `geograhy` type by default, so i see two possible reasons for your failure:
1. The coordinate values are not in the range of a SqlServer geography type:
  * Range longitude/x [-180, 180], 
  * Range latitude/y [-90,90]
2. The ring orientation might be wrong, it is supposed to be counter-clockwise for the exterior ring, clockwise for interior rings. Try to add:
```C#
// ...
var linearRing = Factory.CreateLinearRing(coordinates);
if (!linearRing.IsCCW) linearRing = (LinearRing)linearRing.Reverse();
var polygon = Factory.CreatePolygon(linearRing);
// ...
```

**Comment by baartho** [comment]
@FObermaier Thank you for taking the time! 

So I guess my issue is happening because values are not in range. 

One of the polygon coordinates is for instance:
`2344243.8274278194, 3278005.0705380589`

so I'll either have to transform this into a valid Latitude and Longitude, 

or do you know if I can somehow use a `geometry` type-field with those values in NetTopologySuite?

**Comment by FObermaier** [comment]
You can configure EFCore to use SQLServer `geometry` type to store spatial objects.
That should be explained in the EFCore documentation and is beyond the support for this project.

**Comment by baartho** [comment]
I know how to configure EFCore to use `geometry`. 

My question is: is there a way that NetTopologySuite can work with non-Latitude and Longitude values such as `2344243.8274278194, 3278005.0705380589`?

**Comment by FObermaier** [comment]
If you use SQLServer's `geometry` data type, you don't have the range constraint.

The exception message you posted states that your setup is configured to use SQLServer's `geography` type under the hood:
```
SqlException: The incoming tabular data stream (TDS) remote procedure call (RPC) 
protocol stream is incorrect. Parameter 3 ("@p2"): The supplied value is not a valid 
instance of data type __geography__. Check the source data for invalid values. An 
example of an invalid value is data of numeric type with scale greater than precision.
```

**Comment by baartho** [comment]
@FObermaier Thank you very much for all your input. You were extremely helpful. 

For all readers. If you run into `shell is empty but holes are not` and you are using `geometry` on your DB, you will simply have to set the column type on your Context `ModelBuilder`.

```
builder.Entity<SomeClass>()
                .Property(x => x.Shape).HasColumnType("geometry");
```
