### ISSUE TITLE
System.MissingMethodException when invoking any method on Geometry

### ISSUE THREAD

**Issue by YuriiNskyi** [NetTopologySuite/NetTopologySuite#367]
### Description
I'm reading some geometry data from PostGIS, and converts them to `Geometry` using `Dapper` and `Npgsql` with the help of this line of code: `NpgsqlConnection.GlobalTypeMapper.UseNetTopologySuite();`

Mapping is quite simple: Map(x => x.Way).ToColumn("way");

`Geometry` has successfully loaded and converted, except the fact, that invoking any method on this geometry throws 

> System.MissingMethodException: Method not found: 'Double NetTopologySuite.Geometries.Geometry.Distance(GeoAPI.Geometries.IGeometry)'

exception for example (of course, every time invoking method is not found, not the `Distance` method).

What's wrong with that and how can I fix that?

### Steps to Reproduce
_(List of steps, sample code, failing test or link to a project that reproduces the behavior)_

### System Configuration
I have tried to install ALL geo-libraries from NTS which I found:
- GeoAPI (1.7.5):
- NetTopologySuite.Core (1.15.3):
- NetTopologySuite.IO (1.14.0.1):
- NetTopologySuite.IO.GeoJSON (1.15.2):
- Dapper.FluentMap (1.8.0)
- Npgsql (4.1.2)

Environment:
- Windows 10:
- ASP NET Core 3:

**Comment by FObermaier** [comment]
You have version incompabilities:
* NetTopologySuite.IO v1.14.0.1 does not go with NetTopologySuite v1.15.*
If you need anything out of NetTopologySuite.IO v 1.14.0.1, you have to specifically pick the relevant IO packages with v.1.15.
* Npgsql v4.1.2 does not go with NetTopologySuite v1 at all, the latest you can use is Npgsql v4.0.10, or use NetTopologySuite v2

**Comment by YuriiNskyi** [comment]
Thank you, you are totally right.

This is working list of libraries:
- GeoAPI (1.7.5):
- NetTopologySuite.IO.GeoJSON (2.0.1):
- Dapper.FluentMap (1.8.0)
- Npgsql (4.1.2)

**Comment by FObermaier** [comment]
You need to remove GeoAPI, it has no function with NTS v2
