### ISSUE TITLE
Assembly Reference to GeoAPI in Visual Studio Code

### ISSUE THREAD

**Issue by hastebrot** [NetTopologySuite/NetTopologySuite#37]
Visual Studio Code [1] Version 0.1.0 seems unable to resolve references to the `GeoAPI` assembly.

Maybe there could be a `project.json` file with a DNX-project be provided as listed in [2].

[1] https://code.visualstudio.com/
[2] https://code.visualstudio.com/Docs/languages#_c35

**Comment by DGuidi** [comment]
thanks for reporting this, maybe I'll take a look when VSCode is released as stable version.
