### ISSUE TITLE
Reconsider updating Factory when setting SRID

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#371]
When we set `Geometry.SRID`, we also [adjust its `Factory`](https://github.com/NetTopologySuite/NetTopologySuite/blob/c822013e89d879e2a52bcd1d0d3e095274645131/src/NetTopologySuite/Geometries/Geometry.cs#L204-L214) to ensure that derived / related `Geometry` instances get the same `SRID`.

Per https://github.com/NetTopologySuite/NetTopologySuite/issues/354#issuecomment-551949147, this can be a bit of a burden in some cases.

Upstream doesn't do the same in [its equivalent block](https://github.com/locationtech/jts/blob/3fedb393ec02ccb58862c0caca65dfb544863445/modules/core/src/main/java/org/locationtech/jts/geom/Geometry.java#L265-L275); in fact, if I'm reading this right, it highlights that the stuff we pile on is something that its version **does not** do (though, this is probably because JTS doesn't have an equivalent to our `NtsGeometryServices`).

Does this still make sense?  If so, let's **at least** update [our copy of the JTS documentation](https://github.com/NetTopologySuite/NetTopologySuite/blob/c822013e89d879e2a52bcd1d0d3e095274645131/src/NetTopologySuite/Geometries/Geometry.cs#L180-L187) to reflect the actual behavior.  As-is, it's grossly misleading (unless I'm reading it incorrectly).

**Comment by FObermaier** [comment]
I'm in favor of changing the code documentation.

If you change a geometry's SRID value and dont change the underlying GeometryFactory, every geometry you create afterwards using its factory (e.g. Buffer, ConvexHull, ...), will have a SRID value differing from the original geometry which is not good.

**Comment by SamuelEnglard** [comment]
The reason setting `Geometry.SRID` was a problem for me was that [`Geometry.Copy()`](https://github.com/NetTopologySuite/NetTopologySuite/blob/c822013e89d879e2a52bcd1d0d3e095274645131/src/NetTopologySuite/Geometries/Geometry.cs#L1738) sets the SRID. This resulted in copied Geometries not having the same factory.

**Comment by FObermaier** [comment]
You can avoid that by creating the geometry factory by using `NtsGeometryServices.Instance.CreateGeometryFactory`.

We *must* disable copying SRID when calling `Geometry.Copy()`
