### ISSUE TITLE
Remove specific workarounds for Visual Studio 2017

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#378]
In #337, @DGuidi mentioned that he's using Visual Studio 2017, so there have been a few places here and there where I've gone out of my way to avoid knowingly breaking that.

At some point, though, it's going to be too much.  e.g., we need to pick one of the following:
- do #369
- keep VS2017 support
- add absolutely insane amounts of `#if` conditional compilation to get both of the above

So this issue has two purposes:
1. Document the things that we could do differently if we dropped VS2017 support
1. Track who still needs VS2017 support

**Comment by DGuidi** [comment]
+1 to support only VS2019

**Comment by airbreather** [comment]
> Document the things that we could do differently if we dropped VS2017 support

Tests run on .NET Core 2.2 ([a](https://github.com/NetTopologySuite/NetTopologySuite/blob/1dad496bf36f70ae4d41b499c71d5f6c90ece680/test/NetTopologySuite.Tests.NUnit/NetTopologySuite.Tests.NUnit.csproj#L5), [b](https://github.com/NetTopologySuite/NetTopologySuite/blob/1dad496bf36f70ae4d41b499c71d5f6c90ece680/test/NetTopologySuite.Samples.Console/NetTopologySuite.Samples.Console.csproj#L5), [c](https://github.com/NetTopologySuite/NetTopologySuite/blob/1dad496bf36f70ae4d41b499c71d5f6c90ece680/test/NetTopologySuite.Tests.Vivid.XUnit/NetTopologySuite.Tests.Vivid.XUnit.csproj#L5)), because VS2017 doesn't properly support 3.0+ of the .NET Core SDK.

Because of this, our [Travis-CI](https://github.com/NetTopologySuite/NetTopologySuite/blob/1dad496bf36f70ae4d41b499c71d5f6c90ece680/.travis.yml#L7-L10) config has to install the runtime separately (admittedly, I kinda think the built-in activities should let us give it arrays of SDK and runtime versions to install, but whatever).

We also can't directly do this in the GitHub Action for setting up .NET Core (actions/setup-dotnet#25).

**Comment by airbreather** [comment]
> Document the things that we could do differently if we dropped VS2017 support

VS2017 [limits](https://github.com/NetTopologySuite/NetTopologySuite/blob/1dad496bf36f70ae4d41b499c71d5f6c90ece680/Directory.Build.props#L6) the C# language version we can use: no higher than 7.3.

C# 8.0 is required for #369.

**Comment by airbreather** [comment]
> +1 to support only VS2019, please don't waste time just because it's (it was, actually) a problem for me to update to newer visual studio versions

Cool -- @FObermaier does VS2019 work for you?  If so, I can push some updates soon.
