### ISSUE TITLE
NTS vector tile IO

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/NetTopologySuite#379]
This is more of a general question/comment. We have built a small IO library on top of NTS to read/write vector tiles:

https://github.com/anyways-open/NetTopologySuite.IO.VectorTiles

It's not completely done/full featured just yet but it's getting there.

This is two-fold, just to let everyone here know this exists, and nobody start redoing this work for nothing and to discuss if a move to the NTS organization is desirable.

**Comment by FObermaier** [comment]
Ben, thanks for letting us know and your willingness to move `NetTopologySuite.IO.VectorTiles` to the NTS organization. I think that it is a truely valuable addition and I'd appreciate to have it within NTS.

**Comment by xivk** [comment]
Ok, thanks for the feedback, feel free to close this issue, I can get back to you here once the library is in a more final state.

All our services are also still on 1.15 of NTS so for now this library also has that same issue. I guess it's best we also upgrade to the latest NTS first.

**Comment by FObermaier** [comment]
> All our services are also still on 1.15 of NTS so for now this library also has that same issue. I guess it's best we also upgrade to the latest NTS first.

I'd appreciate if we provide the v1.15 package as well, as it seems to be close. We can update to v2 afterwards.

**Comment by FObermaier** [comment]
See [NetTopologySuite.IO.VectorTiles](https://github.com/NetTopologySuite/NetTopologySuite.IO.VectorTiles)
