### ISSUE TITLE
Use latest ProjNet4 version

### ISSUE THREAD

**Issue by sebasbaumh** [NetTopologySuite/NetTopologySuite#38]
I was trying to create a coordinate system from a WKT string like that (in Resources as `CS_4362_WGS84`):

```
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.01745329251994328,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
```

Using that code:
`ICoordinateSystem cs = new CoordinateSystemFactory().CreateFromWkt(Resources.CS_4362_WGS84);`

It fails with this error:

```
Error: 'G' is not recognized.
System.ArgumentException: 'G' is not recognized.
   bei ProjNet.Converters.WellKnownText.CoordinateSystemWktReader.Parse(String wkt)
   bei ProjNet.CoordinateSystems.CoordinateSystemFactory.CreateFromWkt(String WKT)
```

Then I used the latest version of ProjNet4GeoAPI @https://github.com/NetTopologySuite/ProjNet4GeoAPI and GeoAPI.
The result was no error - as expected.

So could you please use the latest ProjNet4 version in the main NetTopologySuite project?

**Comment by FObermaier** [comment]
We are preparing a new release ATM, so hold on for a couple of days. Thanks

**Comment by Depechie** [comment]
Current nuget version - still error "P is not recognized". Older version where we could add encoding to the Parse method works.
Any progress on this?

**Comment by DGuidi** [comment]
can we close this issue, right?

**Comment by Depechie** [comment]
If the beta nuget is released as stable :)

**Comment by airbreather** [comment]
Right now, the only NTS project that references `ProjNet4GeoAPI` is `NetTopologySuite.Samples.Console`.  I also don't see any of the other "stable" 1.14.x packages referencing it.  What was this issue referring to, exactly?

**Comment by sebasbaumh** [comment]
>What was this issue referring to, exactly?

I was using the integrated ProjNet4GeoAPI for projections as it is delivered together with NetTopologySuite.
So it should be safe to just not include it in our application when we use NetTopologySuite and use https://github.com/NetTopologySuite/ProjNet4GeoAPI separately.
