### ISSUE TITLE
Problem with selecting certain polygons, also Shells are empty but hulls are not?

### ISSUE THREAD

**Issue by juliusfriedman** [NetTopologySuite/NetTopologySuite#384]
### Prerequisites

Consider the following class:

```
[Table("Geofences")]
    public class Geofence
    {
        /// <summary>
        /// The primary key
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int GeofenceID { get; set; }

        /// <summary>
        /// The name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The description
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// The <see cref="Polygon"/> which represents the Geofence
        /// </summary>
        public Polygon Boundary { get; set; }

        /// <summary>
        /// The primary key in the <see cref="GeofenceType"/> table.
        /// </summary>
        public int GeofenceTypeID { get; set; }

        /// <summary>
        /// The <see cref="GeofenceType"/> identified by the <see cref="GeofenceTypeID"/>
        /// </summary>
        [ForeignKey(nameof(GeofenceTypeID))]
        public GeofenceType GeofenceType { get; set; }

        /// <summary>
        /// The primary key in the <see cref="Operator"/> table
        /// </summary>
        public int OperatorID { get; set; }

        /// <summary>
        /// The <see cref="Operator"/> identified by the <see cref="OperatorID"/>
        /// </summary>
        [ForeignKey(nameof(OperatorID))]
        public Operator Operator { get; set; }

        /// <summary>
        /// Indicates if this instance was created by a customer
        /// </summary>
        public bool IsCustomerGenerated { get; set; }
    }

public class AmsedDigitalDatabaseContext : DbContext
{
public DbSet<Geofence> Geofences { get; set; }
}

```

When I execute code such as:

`db.Geofences.Count()` I get a result say, 4867.

When I execute `db.Geofences.ToList()`

I get :
```'Unable to cast object of type 'NetTopologySuite.Geometries.Point' to type 'NetTopologySuite.Geometries.Polygon'.'```

If I change the type from `        public Polygon Boundary { get; set; } ` to `        public Geometry Boundary { get; set; } `

I get `Shells are empty but hulls are not?`

The underlying column types are Geography in the sql server.

### System Configuration
.Net Core 3.1
NetTopologySuite 2.0
Microsoft.EntityFrameworkCore.SqlServer.Net 3.1.2

{"Unable to cast object of type 'NetTopologySuite.Geometries.Point' to type 'NetTopologySuite.Geometries.Polygon'."}
"   at lambda_method(Closure , QueryContext , DbDataReader , ResultContext , Int32[] , ResultCoordinator )"

This occurs in QueryingEnumerable.cs and I have verified that all polygons stored in the Database are Polygons and they are valid.

**Comment by juliusfriedman** [comment]
Apparently some Points got inserted into the polygon table and I overlooked this before reporting. You can close this issue.

**Comment by juliusfriedman** [comment]
POLYGON ((-140.00296288337154 53.546136614707422, 162.36764026656385 52.595660082536916, 163.78696183659849 10.629692997566922, -170.44363787090384 12.008554372039274, -144.93790945340618 12.609642556124617, -140.00296288337154 53.546136614707422))

This polygon throws the `shell is empty but holes are not`

**Comment by airbreather** [comment]
> POLYGON ((-140.00296288337154 53.546136614707422, 162.36764026656385 52.595660082536916, 163.78696183659849 10.629692997566922, -170.44363787090384 12.008554372039274, -144.93790945340618 12.609642556124617, -140.00296288337154 53.546136614707422))

This crosses the antimeridian.  NTS's model doesn't completely support that.
