### ISSUE TITLE
Problem with LinearRing.IsCCW: true instead of false

### ISSUE THREAD

**Issue by charlenni** [NetTopologySuite/NetTopologySuite#386]
First of all: Thank you very much for your work o this project.

### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of NetTopologySuite
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have a LinearRing with the following coordinates:

    39.375  487
    40.75   486.25
    40.25   485.125
    41.5    486.125
    42.75   485.5
    43.5    486.25
    47.125  486
    47      484
    48.75   484.875
    48.75   486.25
    49.25   485.375
    50.75   486.125
    51.25   488.75
    53      489.625
    55.125  488.875
    55.375  490.125
    54.375  490.375
    54.875  491.5
    55.5    491.375
    55      491.875
    56.625  494.5
    55.75   501
    53.375  505.5
    54.625  506
    54.75   508.75
    54      508.25
    53      508.875
    54.25   510.375
    56.875  510.875
    55.75   511.75
    53.5    510.875
    53.25   510
    52.875  514
    50.875  515.875
    49.5    515.375
    51.625  519.375
    53.125  519.5
    53      520
    51.875  520
    51.375  519.5
    51.625  520
    -8      520
    -8      483.375
    1.5     479.25
    5.375   478.875
    7.5     477
    19      475.5
    21.125  474.375
    19.625  475.375
    25.25   475.75
    29.375  480.125
    30.125  479.5
    31      480
    29.625  480.5
    30.625  481.25
    31.625  480.75
    30.5    481.625
    31.25   484.5
    34.625  487.625
    35.625  486.75
    35.625  487.5
    37      487.375
    37.375  486.5
    37.75   487.25
    39      487.125
    38.625  485.5
    39.375  487

If I check LinearRing.IsCCW, than I get a true. But if I look on the coordinates, I would say, that this isn't correct. For me it is a clockwise oriented LinearRing. Could it be, that IsCCW is sometimes not correct? Is there a better function to check this? 

### Steps to Reproduce
_(List of steps, sample code, failing test or link to a project that reproduces the behavior)_

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 1.15.3
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on): Win 10 1909
- .NET Framework version:
- Additional information:

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by airbreather** [comment]
WKT formatted:
```
POLYGON ((39.375 487, 40.75 486.25, 40.25 485.125, 41.5 486.125, 42.75 485.5, 43.5 486.25, 47.125 486, 47 484, 48.75 484.875, 48.75 486.25, 49.25 485.375, 50.75 486.125, 51.25 488.75, 53 489.625, 55.125 488.875, 55.375 490.125, 54.375 490.375, 54.875 491.5, 55.5 491.375, 55 491.875, 56.625 494.5, 55.75 501, 53.375 505.5, 54.625 506, 54.75 508.75, 54 508.25, 53 508.875, 54.25 510.375, 56.875 510.875, 55.75 511.75, 53.5 510.875, 53.25 510, 52.875 514, 50.875 515.875, 49.5 515.375, 51.625 519.375, 53.125 519.5, 53 520, 51.875 520, 51.375 519.5, 51.625 520, -8 520, -8 483.375, 1.5 479.25, 5.375 478.875, 7.5 477, 19 475.5, 21.125 474.375, 19.625 475.375, 25.25 475.75, 29.375 480.125, 30.125 479.5, 31 480, 29.625 480.5, 30.625 481.25, 31.625 480.75, 30.5 481.625, 31.25 484.5, 34.625 487.625, 35.625 486.75, 35.625 487.5, 37 487.375, 37.375 486.5, 37.75 487.25, 39 487.125, 38.625 485.5, 39.375 487))
```

This looks counter-clockwise to me.

To be a little more precise, treating the coordinates as vertices of a polygon (as in the WKT above), the interior of the polygon is always on the left when traversing the given coordinates in their given order.

**Comment by charlenni** [comment]
Thank you for your attention.

Ah, now I see it with your eyes. When using a coordinate system with top left as zero and going down and right, than the coordinates are CCW. If looking at them with a coordinate system with lower left as zero and going right and up, than the coordinates are CW. So perhaps I should use the oposit of IsCCW as result. Is this correct?
