### ISSUE TITLE
Need to update Portable Class Profile?

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite#39]
Currently the GeoAPI/NTS/ProjNet stacks PCL projects are 
* compiled with __.NETPortable,version=v4.0,profile=Profile147__
* packaged with __portable-net403+sl5+netcore45+wp8+MonoAndroid1+MonoTouch1__

Is this setting ok, or do we need to change that. Here is a list of what is currently possible:
http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY

**Comment by pauldendulk** [comment]
BruTile uses Profile336 which includes Windows Phone 8.1. 

Is it also an option to jump forward to a profile that includes .NET 4.5 and drop Silverlight and Windows Phone Silverlight. This add a lot of modern functionality. For NTS this may be to early.

**Comment by cedricseah** [comment]
I would like to give a vote to using at least Profile328.
Reasons 
1) This seems like the minimum target that users of Visual Studio 2013 can use, possibly solving mine and jcdekoning's issue. 
I'm not sure what the minimum target will be for Visual Studio 2015 which is coming out in July. I'm installing 2015 RC now to check
2) I would like to be able to use GeoAPI, NTS, Proj.Net in a Universal Windows App :)

**Comment by FObermaier** [comment]
We'll be releasing a new version of GeoAPI/NTS with PCL assemblies targeting Profile 328.

**Comment by DGuidi** [comment]
@FObermaier thanks felix, hope to be more helpful in next months

**Comment by FObermaier** [comment]
We'll be releasing a new version of GeoAPI/NTS with PCL assemblies targeting Profile 336 in the next week.
For 328 we'd have to change some code that depended on portable-net403

**Comment by FObermaier** [comment]
@cedricseah,  @jcdekoning:
Could you please test GeoAPI.1.7.4-pre2 and NetTopologySuite.1.13.4-pre3 packages
The PCL TargetProfile is set to 336.

**Comment by cedricseah** [comment]
I am able to install GeoAPI 1.7.4-pre2 in a PCL project (targetting 336) using Nuget.
When I try to install NTS -Topology Suite 1.13.4-pre3, I get the following error message even though GeoAPI 1.7.4-pre2 is installed

Attempting to resolve dependency 'GeoAPI (≥ 1.7.4 && < 1.8)'.
Unable to resolve dependency 'GeoAPI (≥ 1.7.4 && < 1.8)'.

**Comment by FObermaier** [comment]
> I am able to install GeoAPI 1.7.4-pre2 in a PCL project (targetting 336) using Nuget.
> When I try to install NTS -Topology Suite 1.13.4-pre3, I get the following error message even though > GeoAPI 1.7.4-pre2 is installed
> 
> Attempting to resolve dependency 'GeoAPI (≥ 1.7.4 && < 1.8)'.
> Unable to resolve dependency 'GeoAPI (≥ 1.7.4 && < 1.8)'.

I know that, I just don't know how to deal with prerelease packages in the nuspec version constraints. You can install it anyhow by adding the `-ignoredependency` flag.
