### ISSUE TITLE
Triangulation for concave polygons

### ISSUE THREAD

**Issue by WENTBY** [NetTopologySuite/NetTopologySuite#396]
### Description
Hi
Is the DelaunayTriangulationBuilder suitable for triangulation for concave polygons. I did some tests and the results showed that some triangles were biased.

### System Configuration
- NetTopologySuite version: 1.14.0.0
- .NET Framework version: 4.5

**Comment by FObermaier** [comment]
Yes it is. NTS v1.14.0.0 is fairly old. The the most recent version 
* with GeoAPI dependency is at v1.15.3, 
* without GeoAPI dependency is v2.0 (current).

Could you provide a unit test?

**Comment by WENTBY** [comment]
Yes, I did a text with the&nbsp;POLYGON ((3400 -800, 1700 -800, 1700 1000, 1000 1000, 1000 800, 1600 800, 1600 -1000, 3400 -1000, 3400 -800)), but the triangulation results I got are like this:


POLYGON ((1000 1000, 1000 800, 1600 800, 1000 1000))
POLYGON ((1000 1000, 1600 800, 1700 1000, 1000 1000))
POLYGON ((1700 1000, 1600 800, 3400 -800, 1700 1000))
POLYGON ((3400 -800, 1600 800, 1700 -800, 3400 -800))
POLYGON ((3400 -800, 1700 -800, 3400 -1000, 3400 -800))
POLYGON ((1600 -1000, 3400 -1000, 1700 -800, 1600 -1000))
POLYGON ((1600 -1000, 1700 -800, 1000 800, 1600 -1000))
POLYGON ((1000 800, 1700 -800, 1600 800, 1000 800))






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Felix Obermaier"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 晚上7:26
收件人:&nbsp;"NetTopologySuite/NetTopologySuite"<NetTopologySuite@noreply.github.com&gt;;
抄送:&nbsp;"王鹏翔"<372450257@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [NetTopologySuite/NetTopologySuite] Triangulation for concave polygons (#396)





 
Yes it is. NTS v1.14.0.0 is fairly old. The the most recent version
  
with GeoAPI dependency is at v1.15.3,
 
without GeoAPI dependency is v2.0 (current).
  
Could you provide a unit test?

**Comment by FObermaier** [comment]
I must modify my previous answer. When a polygon is passed to `[Conforming]DelaunayTriangulationBuilder` it's exterior is not respected as off-limits. To achive that,
you have to use `ConformingDelaunayTriangulationBuilder` set the constraints to the input polygon and finally remove those triangles that are not contained by the polygon:
```C#
public void TestConcavePolygon()
{
    const string SitesWKT = @"POLYGON ((3400 -800, 1700 -800, 1700 1000, 
1000 1000, 1000 800, 1600 800, 
1600 -1000, 3400 -1000, 3400 -800))";
    const string ConstraintsWKT = SitesWKT;

    var reader = new WKTReader();
    var builder = new ConformingDelaunayTriangulationBuilder();
    var prep = PreparedGeometryFactory.Prepare(reader.Read(ConstraintsWKT));

    builder.SetSites(reader.Read(SitesWKT));
    builder.Constraints = prep.Geometry;
    Geometry result = builder.GetTriangles(reader.Factory);
    var geoms = new List<Geometry>(result.NumGeometries);
    for (int i = 0; i < result.NumGeometries; i++)
    {
        var atomic = result.GetGeometryN(i);
        if (prep.Contains(atomic))
            geoms.Add(atomic);
    }

    result = reader.Factory.BuildGeometry(geoms);
    Console.WriteLine(result.AsText());
}
```

**Comment by WENTBY** [comment]
Thanks you very much, it works and this can do me a great favor! And I also want to known is there any solution without new point generated?

**Comment by FObermaier** [comment]
> I also want to known is there any solution without new point generated?

Not with JTS/NTS.

**Comment by WENTBY** [comment]
OK,  Thanks again for your solution, It is enough for me.
