### ISSUE TITLE
Question: Lines to valid Polygons?

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#399]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I would like to find out if I can use NetTopologySuite for creating polygons from lines.Here is my example with lines and I would like to receive 9 polygons.  is there any example available to help me get familiar with NetTopologySuite
![image](https://user-images.githubusercontent.com/26113670/79556304-cc592500-8098-11ea-8d20-27a2cedab30d.png)

**Comment by FObermaier** [comment]
Yes, you can, somewhere along these lines
```C#
// Get your lines from somewhere, here we read them from WKT
var rdr = new WKTReader(new GeometryFactory(new PrecisionModel(1e8)));
var lines = new Geometry[]
{
    rdr.Read("LINESTRING(-11 17, 9.41 11.39, 29 6)"),
    rdr.Read("LINESTRING(-10.12 2.53, 29 2.11)"),
    rdr.Read("LINESTRING(-9 -16, 3.6 -16.5, 16 -17)"),
    rdr.Read("LINESTRING(-11 17, -10.12 2.53, -9 -16)"),
    rdr.Read("LINESTRING(9.41 11.39, 3.6 -16.5)"),
    rdr.Read("LINESTRING(16 -17, 15 -5, 29 -6, 29 2.11, 29 6)"),
    rdr.Read("LINESTRING(1 3, 13 4, 15 -5, 3 -6, 1 3)"),
};

// Create a polygonizer
var pgz = new Polygonizer(false);

// Be sure to node your linework before you add it to the polygonizer
var gn = new GeometryNoder(rdr.Factory.PrecisionModel);
pgz.Add(gn.Node(lines).ToArray());

// Do sth with polygons
foreach (var geometry in pgz.GetPolygons())
    Console.WriteLine(geometry);

```

**Comment by michaldengusiak** [comment]
@FObermaier this is absolutely amazing, thanks a lot. It works perfectly. 
Is it an OpenSource project that can be referenced in another opensource project?

**Comment by FObermaier** [comment]
NTS' license is BSD3, that is about as open-source as it can get.
