### ISSUE TITLE
Running into exception trying to load Oracle Spatial Object

### ISSUE THREAD

**Issue by aarongundel** [NetTopologySuite/NetTopologySuite#40]
Right now I'm not sure what the root cause of this exception is; all I know is that I'm running into an exception when I attempt to access an Oracle Spatial Object.  I'm using devart's dotConnect as my EntityFramework connector.  If you have any ideas what might cause this exception to occur so I can address the right people, that would be awesome.  Note that I'm using NetTopologySuite 1.13.  I'm also using Postgis in this project, so I have a reference to NetTopologySuite.IO.PostGis

"ExceptionMessage": "premature end of enumerator",
 "ExceptionType": "System.InvalidOperationException",
 "StackTrace": "   at NetTopologySuite.IO.WKTReader.GetNextWord(IEnumerator`1 tokens)\\\r\\\n   at NetTopologySuite.IO.WKTReader.ReadGeometryTaggedText(IEnumerator`1 tokens)\\\r\\\n   at NetTopologySuite.IO.WKTReader.Read(TextReader reader)\\\r\\\n   at NetTopologySuite.IO.WKTReader.Read(String wellKnownText)\\\r\\\n   at Devart.Common.Entity.bi.a(Int32 A_0, Boolean A_1)\\\r\\\n   at Devart.Common.Entity.bi.b(Int32 A_0)\\\r\\\n   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.<GetSpatialPropertyValueWithErrorHandling>b__1c[TProperty](DbDataReader reader, Int32 column)\\\r\\\n   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.ErrorHandlingValueReader`1.GetValue(DbDataReader reader, Int32 ordinal)\\\r\\\n   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.GetSpatialPropertyValueWithErrorHandling[TProperty](Int32 ordinal, String propertyName, String typeName, PrimitiveTypeKind spatialTypeKind)\\\r\\\n   at lambda_method(Closure , Shaper )\\\r\\\n   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)\\\r\\\n   at lambda_method(Closure , Shaper )\\\r\\\n   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)\\\r\\\n   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()\\\r\\\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\\\r\\\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)\\\r\\\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)\\\r\\\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)\\\r\\\n   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)\\\r\\\n   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)\\\r\\\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\\\r\\\n   at System.Net.Http.Formatting.JsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, Encoding effectiveEncoding)\\\r\\\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content)\\\r\\\n   at System.Net.Http.Formatting.BaseJsonMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken)\\\r\\\n--- End of stack trace from previous location where exception was thrown ---\\\r\\\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\\\r\\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\\r\\\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\\\r\\\n   at System.Web.Http.WebHost.HttpControllerHandler.<WriteBufferedResponseContentAsync>d__1b.MoveNext()"

**Comment by DGuidi** [comment]
hard to say where's the problem.
try to make a simpler test calling NTS WKTReader.Read with oracle geometries (converted to wkt via SDO_UTIL package)
