### ISSUE TITLE
Question: Offset on Polygons and Multi-lines?

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#401]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I love this tool! :heart:  :boom:  :heart_eyes: 
Do you have method to offset geometry by distance? like that:

![image](https://user-images.githubusercontent.com/26113670/79861623-95eb1500-83cc-11ea-832a-3a8f02683495.png)

I found a [function](http://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Operation.Buffer.OffsetCurveSetBuilder.html?q=offset) but am not quite sure how to use it ...and what is `OffsetCurveBuilder` is for I would appreciate an example again...

**Comment by FObermaier** [comment]
```C#
var rdr = new WKTReader();
var geom = (LineString)rdr.Read("LINESTRING Z(0 -10 0, 0 -20 0, 6 -18 0, 14 -20 0, 12 -10 0, 5 -14 0, 0 -10 0)");
var ocb = new OffsetCurveBuilder(rdr.Factory.PrecisionModel,
    new BufferParameters
    {
        EndCapStyle = EndCapStyle.Flat,
        JoinStyle = JoinStyle.Round,
        QuadrantSegments = 12,
        IsSingleSided = true
    });

var off = rdr.Factory.CreateLineString(ocb.GetRingCurve(geom.Coordinates, Positions.Left, 0.6));
Console.WriteLine(off);
```
![grafik](https://user-images.githubusercontent.com/2065346/79868875-de143280-83e0-11ea-849d-380797ed5ba0.png)

Please note that for obstuse angles circle-like-fillets are being added. If the offset distance is too big, you might get a self-intersecting ring or other artefacts. This is no skeleton algorithm.

**Comment by michaldengusiak** [comment]
ok, this is perfect! thanks a lot
