### ISSUE TITLE
Question: How to find a point inside LinearRing?

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#402]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We would like to check if a point is inside your LinearRing.
Unfortunately it did not work for me,
What should we use?
We tried :

`public bool Within(Geometry g);`
http://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.Geometry.html#NetTopologySuite_Geometries_Geometry_Within_NetTopologySuite_Geometries_Geometry_
`public virtual bool Contains(Geometry g);`
http://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.Geometry.html#NetTopologySuite_Geometries_Geometry_Contains_NetTopologySuite_Geometries_Geometry_

but unfortunatly I did not work, 
![image](https://user-images.githubusercontent.com/26113670/79879568-c6d84380-83e6-11ea-99d7-a6a7bb3e2c65.png)

**Comment by FObermaier** [comment]
A `LinearRing` is a lineal `Geomery`. For `Contains` predicate you need to build a `Polygon` first.

**Comment by michaldengusiak** [comment]
perfect will try this

**Comment by michaldengusiak** [comment]
ok is working perfectly THANKS A LOT :blush:
