### ISSUE TITLE
Question: How to find the same shapes, perfect overlap to filter out geometry?

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#403]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
_(A description of the bug or feature)_
If I have two same overlapping Polygons or  LinearRings do you have any method so I can find and "merge " or filter out one as I results I need one set of valid geometry?
![image](https://user-images.githubusercontent.com/26113670/79888314-546e6000-83f4-11ea-8a8e-4711670ae1d1.png)

**Comment by FObermaier** [comment]
To compare 2 geometry instances you should use `Geometry.EqualsTopologically(Geometry)` as shown in the following example:
```C#
public void TestTopo()
{
    var rdr = new WKTReader();
    var ring1 = rdr.Read("LINESTRING (0 0, 5 0, 10 0)");
    var ring2 = rdr.Read("LINESTRING (0 0, 10 0)");

    Assert.That(ring1.EqualsTopologically(ring2));

    var poly1 = rdr.Read("POLYGON((0 0,      10 0,       10 10,       0 10, 0 0))");
    var poly2 = rdr.Read("POLYGON((0 0, 5 0, 10 0, 10 3, 10 10, 7 10, 0 10, 0 0))");

    Assert.That(poly1.EqualsTopologically(poly2));
}

```

**Comment by michaldengusiak** [comment]
It works perfectly, I run lots of tests and all Passed! even with opposite order, duplicate points, and point wining tolerance :) AMAZING and thanks a lot @FObermaier 

```csharp

            var rdr = new WKTReader(new GeometryFactory(new PrecisionModel(1000)));

            var ring1 = rdr.Read("LINESTRING (0 0, 5 0.0001, 10 0)");
            var ring2 = rdr.Read("LINESTRING (0 0, 10 0)");

            bool Test_1 = ring1.EqualsTopologically(ring2);
```
