### ISSUE TITLE
`GeometryFactoryEx.CreatePolygon` Crashes when `shell` is `null`

### ISSUE THREAD

**Issue by SamuelEnglard** [NetTopologySuite/NetTopologySuite#405]
`NetTopologySuite.IO.Handlers.PolygonHandler` calls `CreatePolygon(shell, holes)` with both parameters as `null` if The shape type is `NullShape`. This crashes `GeometryFactoryEx` since it doesn't check if `shell` is `null` before checking the direction of the shell.

**Comment by SamuelEnglard** [comment]
@FObermaier This will solve empty geometries but not null, no?

**Comment by FObermaier** [comment]
Ooops, yes.
