### ISSUE TITLE
Question: How to snap Polygons to form close shape?

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#406]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
_(A description of the bug or feature)_
How to merge two polygons so that after transformation they form one closed shape which is made from two mofified polygons.  

![image](https://user-images.githubusercontent.com/26113670/81086240-2149c780-8ef0-11ea-806e-5b9d745a8530.png)

**Comment by FObermaier** [comment]
You can use the `GeometrySnapper`:
```C#
const string wkt1 = "POLYGON ((0 0, 0 10, 9.999999 0, 0 0))";
const string wkt2 = "POLYGON ((10 0.000001, 10 10, 0 10, 5 5.000002, 10 0.000001))";
var rdr = new NetTopologySuite.IO.WKTReader();
var p1 = rdr.Read(wkt1);
var p2 = rdr.Read(wkt2);

var ps = NetTopologySuite.Operation.Overlay.Snap.GeometrySnapper.Snap(p1, p2, 1e-4);
System.Console.WriteLine(p1);
System.Console.WriteLine(p2);
foreach (var geometry in ps)
    System.Console.WriteLine(geometry);
```
It does not do exactly what you want, but it is as cloes as you can get using this library.

**Comment by michaldengusiak** [comment]
@FObermaier , thanks a lot for your reply. 
I tried this solution and generated two polygons from your example and run it via

`            NetTopologySuite.Geometries.Geometry[] geometries = GeometrySnapper.Snap(polygon_1, polygon_2, snapDistance);`

however, from two triangles, I have two overlapping polygons in the same location.
Is this how this function works? I just want to make sure I did not miss anything 
![image](https://user-images.githubusercontent.com/26113670/81582953-9281f280-93a8-11ea-8092-507a0c5512a1.png)

**Comment by michaldengusiak** [comment]
OK I found an issue in my code now works better, I can see order makes difference

![image](https://user-images.githubusercontent.com/26113670/81585539-36b96880-93ac-11ea-819f-868c8477129f.png)
and original example
![image](https://user-images.githubusercontent.com/26113670/81585870-a2033a80-93ac-11ea-976e-a66fcb9b1323.png)
