### ISSUE TITLE
Question how to clean Polygon from internal lines?

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#408]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am trying to find method to clean polygon and return valid polygon without these two internal lines,

We tried
`DouglasPeuckerSimplifier`
`TopologyPreservingSimplifier` but it did not work. Did not clean this shape.  
Any suggestions?

![image](https://user-images.githubusercontent.com/26113670/81419543-53ecfd80-9146-11ea-8fa5-4e633b5e5f9a.png)

**Comment by FObermaier** [comment]
You can use `GeometrySnapper`:
```C#
const string wkt = "POLYGON ((0 0, 0 10, 10 10, 10 20, 50 20, 50 5, 40 5, 50 5, 50 0, 15 0, 15 15, 15 0, 0 0))";
var rdr = new NetTopologySuite.IO.WKTReader();
var p1 = rdr.Read(wkt);
var p2 = NetTopologySuite.Operation.Overlay.Snap.GeometrySnapper.SnapToSelf(p1, 1e-6, true);
System.Console.WriteLine(p1);
System.Console.WriteLine(p2);
```

**Comment by michaldengusiak** [comment]
Absolutely amazing! works perfectly
![image](https://user-images.githubusercontent.com/26113670/81536542-a820f900-9363-11ea-9c78-fc2a3bb8e4bb.png)
