### ISSUE TITLE
(Question) Polygon and LineString symmetry / similarity / chirality

### ISSUE THREAD

**Issue by juliusfriedman** [NetTopologySuite/NetTopologySuite#409]
Is there an easy way to determine how similar one `Geometry` is to another? (In percentage or 0->1 value)

e.g. Given LineString and LineString I want to know if they are within a certain similarity of each other or [achiral](https://en.wikipedia.org/wiki/Chirality#Geometry)

Is there any easy Algorithm or known calculation which is provided or in Labs which can be used for such?

Currently I am performing what is like an `Area` based calculation based on Difference of `Area` and another `Area` and I was thinking we should actually be using `SymetricalDifference(other).Area` but before I started changing that I wanted to see if there was anything already in the library which would help me..

Thank you again for your repeated assistance.

**Comment by FObermaier** [comment]
Have a look at the `NetTopologySuite.Algorithm.Match` namespace.

**Comment by juliusfriedman** [comment]
Will do, any specific places?

**Comment by juliusfriedman** [comment]
Looks like I should have what I need for now, will definitely let you know if anything else comes up.

Thank you again for your help!
