### ISSUE TITLE
KdTree Matching Bug

### ISSUE THREAD

**Issue by jasonpepper** [NetTopologySuite/NetTopologySuite#41]
The kd-tree does not correctly find existing nodes. It ignores branches that may contain matches within the tree’s threshold.

To demonstrate this, create a kd-tree with a threshold of 1.0. Then add the following points (0.0, 0.0), (0.1, 1.0), and (-0.1, 1.0). The third point should be matched to the second point. However, the code ignores the right child of the root node and does not find the match.

I also posted this to the JTS mailing list.

**Comment by DGuidi** [comment]
jts fixed this after your segnalation with [r990](http://sourceforge.net/p/jts-topo-suite/code/990) and [r991](http://sourceforge.net/p/jts-topo-suite/code/991)
hope to integrate soon newer code (see #35)

**Comment by FObermaier** [comment]
Here you go: b16134d08a5373a531276bce00df20de788e6a3f
