### ISSUE TITLE
Question: How to clean Polygon from tine tolerance stripes?

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#411]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified that the problem exists in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure that it has not already been reported

### Description
@FObermaier 

There is a polygon with a very thin piece 0.000001.
We got it after the PolygonBoolean operation.
Our goal is to keep it as a simple traingle without this long piece.
Any suggestions what method to use would be appreciated!

Here are points
```
0{-4.763585 4.325001}
1{9.999999 4.325}
2{9.999999 5.270959}
3{11.706555 4.324999}
4{9.999999 2.060323}
5{9.999999 4.324999}
6{-4.763586 4.325}
7{-4.763585 4.325001}
```

as NTS
```
LINESTRING (-4.763584569 4.325001, 9.999999431 4.325)
LINESTRING (9.999999431 4.325, 9.999999431 5.270959)
LINESTRING (9.999999431 5.270959, 11.706555431 4.324999)
LINESTRING (11.706555431 4.324999, 9.999999431 2.060323)
LINESTRING (9.999999431 2.060323, 9.999999431 4.324999)
LINESTRING (9.999999431 4.324999, -4.763585569 4.325)
LINESTRING (-4.763585569 4.325, -4.763584569 4.325001)
```

I would prefer points from `1,2,3,4,5` or even better` 2,3,4`

![image](https://user-images.githubusercontent.com/26113670/82576869-21012b80-9b82-11ea-862f-8f636fd6a39c.png)

**Comment by FObermaier** [comment]
These _sliver_ polygons are hard to identify automatically so there is no automatic removal. A good criteria to identify them seems to be the __[thinness-ratio](https://tereshenkov.wordpress.com/2014/04/08/fighting-sliver-polygons-in-arcgis-thinness-ratio/)__:
```
var tr = 4d * System.Math.Pi * polygon.Area / (polygon.Length * polygon.Length)
```
> Most sliver polygons would have the ratio really close to 0, but from what I’ve seen whatever that is lower than 0.3 might be a good candidate, too. However, consider the features areas first before running into any hasty conclusions. Large and/or multipart features with irregular shape might have a really low thinness ratio yet they are not even close to be sliver polygons. You would probably want to set a definition query on your feature class excluding most of the polygons with large area.

**Comment by FObermaier** [comment]
You can try a
[SpikeRemover](https://github.com/NetTopologySuite/NetTopologySuite/files/4667039/SpikeRemover.zip) utility that I came up with. On the geometry at hand, you have to apply it twice to get the geometry cleaned.

**Comment by FObermaier** [comment]
Reducing the geometry's precision and call ` NetTopologySuite.Operation.Overlay.Snap.GeometrySnapper.SnapToSelf` also helps with this.

**Comment by michaldengusiak** [comment]
thanks a lot for your suggestions, this method for identifying problematic Polygons works great, 

I found a second example
![image](https://user-images.githubusercontent.com/26113670/82689462-68ef8380-9c52-11ea-964f-4dfe61a9ad0b.png)
 
here as NTS

```c#
LINESTRING (-1.280821569 0.000169, 8.447178431 0.000169)
LINESTRING (8.447178431 0.000169, 8.447051431 0.000001)
LINESTRING (8.447051431 0.000001, 9.999998431 0.000001)
LINESTRING (9.999998431 0.000001, 9.999998431 4.324998)
LINESTRING (9.999998431 4.324998, 9.999895431 4.324998)
LINESTRING (9.999895431 4.324998, 9.999895431 2.060316)
LINESTRING (9.999895431 2.060316, 8.447895431 0.000315)
LINESTRING (8.447895431 0.000315, -1.280104569 0.000315)
LINESTRING (-1.280104569 0.000315, -6.300104569 2.557314)
LINESTRING (-6.300104569 2.557314, -4.763378569 4.325)
LINESTRING (-4.763378569 4.325, -6.742031569 4.325)
LINESTRING (-6.742031569 4.325, -6.742031569 0.000001)
LINESTRING (-6.742031569 0.000001, -1.280491569 0.000001)
LINESTRING (-1.280491569 0.000001, -1.280821569 0.000169)
```

I used your method and run it twice
```c#
NetTopologySuite.Clean.SpikeRemover sr = new NetTopologySuite.Clean.SpikeRemover();
Geometry geometry = sr.Clean(linearRing_1);
geometry = sr.Clean(geometry);
```

but still, have the same issue. I wish to get two polygons.... will explore more... or I missing some setting

**Comment by FObermaier** [comment]
Using _SpikeRemover_ you will only get rid of the spike on the right.
You should _really_ consider using a less precise precision model. Given that your coordinates are in meters you are working with an accuracy of microns. For architectural purposes that seems like overkill to me (I studied civil engineering once upon a time....).

**Comment by michaldengusiak** [comment]
@FObermaier yes this is the issue...
when I change to 0.001 I do not have any more this issue, however,
I have polygons that when removing overlap, not all are removed and therefore not all polygons are created... need to explore more... I will close this and will come back with more detail question here in case I need additional help
