### ISSUE TITLE
Redirect the old API documentation site to the new DocFX-based site

### ISSUE THREAD

**Issue by roji** [NetTopologySuite/NetTopologySuite#413]
[The API documentation](http://nettopologysuite.github.io/html/index.html) appears to be quite out of date, specifying version 1.13.3 (generated in 2014?), it's probably a good idea to regenerate it.

You could also consider moving to docfx, which has become the standard for API and conceptual documentation for .NET.

**Comment by FObermaier** [comment]
Have a look at [this](http://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.html).
But you are right, of course!

**Comment by roji** [comment]
Looking great @FObermaier! I can see these newer docs are linked to from the github page, I reached the old doxygen ones from Google - maybe it's worth putting a redirect?

**Comment by FObermaier** [comment]
Fixed with https://github.com/NetTopologySuite/NetTopologySuite.github.io/commit/07facb582ea3fa7d7b77fbdced451379a2118bec
