### ISSUE TITLE
Question: Polygon from Linestring

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#414]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
@FObermaier 

We have three shapes that we try to to GetPolygons and expect to have 3 but only got 2,
Our recession is : tolerance = 1E-05
![image](https://user-images.githubusercontent.com/26113670/83267988-e2d8bd00-a1bc-11ea-9e81-93708821edba.png)

![image](https://user-images.githubusercontent.com/26113670/83268135-187da600-a1bd-11ea-98a0-fe289908f686.png)

here is out input...

```
LINESTRING (23.59653 5.4132, 16.80852 5.81681)
LINESTRING (16.80852 5.81681, 16.78478 5.41752)
LINESTRING (16.78478 5.41752, 16.59484 2.22316)
LINESTRING (16.59484 2.22316, 16.42865 -0.5719)
LINESTRING (16.42865 -0.5719, 16.32181 -2.36873)
LINESTRING (16.32181 -2.36873, 6.73873 -1.79892)
LINESTRING (6.73873 -1.79892, 3.94367 -1.63272)
LINESTRING (3.94367 -1.63272, -0.24892 -1.38343)
LINESTRING (-0.24892 -1.38343, -1.8461 -1.28846)
LINESTRING (-1.8461 -1.28846, -4.64117 -1.12227)
LINESTRING (-4.64117 -1.12227, -9.23306 -0.84923)
LINESTRING (-9.23306 -0.84923, -9.20932 -0.44994)
LINESTRING (-9.20932 -0.44994, -9.12622 0.94759)
LINESTRING (-9.12622 0.94759, -9.03125 2.54477)
LINESTRING (-9.03125 2.54477, -8.98376 3.34336)
LINESTRING (-8.98376 3.34336, -8.87692 5.14019)
LINESTRING (-8.87692 5.14019, -8.77009 6.93701)
LINESTRING (-8.77009 6.93701, -8.74634 7.33631)
LINESTRING (-8.74634 7.33631, -12.93894 7.5856)
LINESTRING (-12.93894 7.5856, -13.01016 6.38771)
LINESTRING (-13.01016 6.38771, -20.99606 6.86256)
LINESTRING (-20.99606 6.86256, -22.17757 -13.00812)
LINESTRING (-22.17757 -13.00812, 8.60068 -20.34213)
LINESTRING (8.60068 -20.34213, 22.01768 -21.1399)
LINESTRING (22.01768 -21.1399, 23.59653 5.4132)
LINESTRING (-2.93715 0.57959, -2.58102 6.56901)
LINESTRING (-2.58102 6.56901, -2.55728 6.9683)
LINESTRING (-2.55728 6.9683, -4.15445 7.06327)
LINESTRING (-4.15445 7.06327, -4.1544500000000006 7.063270000000001)
LINESTRING (-4.15446 7.06327, -4.1782 6.66398)
LINESTRING (-4.1782 6.66398, -4.28504 4.86715)
LINESTRING (-4.28504 4.86715, -4.36813 3.46962)
LINESTRING (-4.36813 3.46962, -4.43936 2.27174)
LINESTRING (-4.43936 2.27174, -4.53433 0.67456)
LINESTRING (-4.53433 0.67456, -2.93715 0.57959)
LINESTRING (-6.97326 6.83017, -7.0801 5.03335)
LINESTRING (-7.0801 5.03335, -6.6808 5.0096)
LINESTRING (-6.6808 5.0096, -6.57396 6.80643)
LINESTRING (-6.57396 6.80643, -4.1782 6.66398)
LINESTRING (-4.15446 7.06327, -8.74634 7.33631)
LINESTRING (-8.77009 6.93701, -6.97326 6.83017)
```
I belive this is line 28
`LINESTRING (-4.15445 7.06327, -4.1544500000000006 7.063270000000001)`

Any idea how to could get 3 polygons?
I tried to remove item 28 but It did not solve my problem...
maybe there is some function I should run before creating Polygon?

**Comment by FObermaier** [comment]
You are only getting 2 polygons because the ring of the 3rd polygon is not closed.
You identified the LINESTRING that is wrong correctly, but removing that item is not correct, you need to close the ring.
```
LINESTRING (-4.15445 7.06327, -4.1544500000000006 7.063270000000001)
```
should be
```
LINESTRING (-4.15445 7.06327, -4.15446 7.06327)
```
The error must be in your input.

**Comment by michaldengusiak** [comment]
ok we implemented tolerance and it works fine now thanks
