### ISSUE TITLE
Warning: Package 'NetTopologySuite.IO 1.14.0.1'

### ISSUE THREAD

**Issue by robertovaldesperez** [NetTopologySuite/NetTopologySuite#415]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Warning: Package 'NetTopologySuite.IO 1.14.0.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

### Steps to Reproduce
_(List of steps, sample code, failing test or link to a project that reproduces the behavior)_

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version:
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by airbreather** [comment]
There is no equivalent to the NetTopologySuite.IO package for NetTopologySuite 1.15.x, and none of the 1.14.x packages actually supported anything other than the classic .NET Framework.

Please upgrade your packages to newer versions, and remove any explicit references to the NetTopologySuite.IO package.
