### ISSUE TITLE
Question:  How to split 'O' shape Polygons 

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#416]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
_(A description of the bug or feature)_
Is there some method to recognize and split Polygons `O shape` into two `C shapes` ?
![image](https://user-images.githubusercontent.com/26113670/84797870-3424e100-aff2-11ea-92e3-fb24f70bbe4d.png)

**Comment by FObermaier** [comment]
You might identify an O-shaped polygon by testing the following:
* does it have  **1 hole**,
* is the thinness ratio for shell and hole ring in a reasonable range. *I must admit that I have no idea what that range would be*.

Splitting a polygon with a line is *currently* not that simple, you can try 
https://github.com/NetTopologySuite/NetTopologySuite/blob/1c463b032c116904bf76e1e07aa9017933e0d6bf/test/NetTopologySuite.Samples.Console/Operation/Polygonize/SplitPolygonExample.cs#L26-L59

**Comment by michaldengusiak** [comment]
thanks a lot, it seems that issue will be to find nice ...cutting line hmm
