### ISSUE TITLE
Question exception Difference method?

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#417]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Hi we come across this exception... when applying Difference method on Geometry (Polygon).
Do you have any idea what could solve this issue or do you need exact geometry sample for tests?

__(A description of the bug or feature)_
An exception of type 'NetTopologySuite.Geometries.TopologyException' occurred in mscorlib.dll but was not handled in user code
Additional information: found non-noded intersection between LINESTRING ( 60.176000000000002 -17.672999999999998, 60.176000000000002 -19.944428571428574 ) and LINESTRING ( 60.176000000000002 -17.672999999999998, 60.176000000000002 -20.748000000000001 ) [ (60.176, -17.673) ]_

**Comment by FObermaier** [comment]
This usually is a robustness issue. Reducing the precision usually helps.
For further investigation we need to see the geometries.

**Comment by juliusfriedman** [comment]
I also experienced this exception recently which crashes my app..
> Unhandled exception. NetTopologySuite.Geometries.TopologyException: found non-noded intersection between LINESTRING ( -88.2227096557                                                         62003 40.157470703125, -88.764466760520676 39.921520845835978 ) and LINESTRING ( -88.222946166992003 40.157775878906001, -88.2307815                                                         55175994 40.143199920653998 ) [ (-88.22323266221385, 40.157242919683696) ]

Anyway to work around this?

**Comment by juliusfriedman** [comment]
@FObermaier 

How can one have a non noded LineString? Are not the nodes the start and the end points at least?

Additionally calling `ReducePrecision` usually just results in an exception, how would one reduce the precision of a LineString, remove points? Which ones and why?

What is the maximum precision of a LineString and how is this known in advance?

Finally where is the `MakeValid` support for SqlServer or just in general around invalid Geography?

**Comment by FObermaier** [comment]
When I advise to reduce the precision, I refer to the number of decimal places your coordinates have, not necessarily the number of coordinates that make up a geometry. Having many decimal places on coordinates can lead to accuracy problems when computing the intersections of almost parallel line segments (see https://github.com/locationtech/jts/issues/464). For overlay operations (like Difference) this is crucial.

The number of decimal places / the precision you need to use depend on your requirements:
![#WhereIsWaldo](https://user-images.githubusercontent.com/2065346/88173180-714c4680-cc22-11ea-857e-3f4bb8644a39.png)

There is no __MakeValid__ function in NTS (and JTS).

**Comment by juliusfriedman** [comment]
The precision we use at the db level is capped at (16,12) which provides adequate resolution and should be acceptable for the application no?

I am not sure I follow your statement, most of these exceptions come from the ReducePrecision method themselves...

**Comment by FObermaier** [comment]
> The precision we use at the db level is capped at (16,12) which provides adequate resolution and should be acceptable for the application no?

The coordinate storage precision for `geometry` or `geography` on SQLSever is double. The exception you posted has coordinates with 15 decimal places which is overkill when working with spatial data.

Could you share the WKT for the geometries involved with this or a similar exception?

**Comment by juliusfriedman** [comment]
> > The precision we use at the db level is capped at (16,12) which provides adequate resolution and should be acceptable for the application no?
> 
> The coordinate storage precision for `geometry` or `geography` on SQLSever is double. The exception you posted has coordinates with 15 decimal places which is overkill when working with geography coordinates.
> 
> Could you share the WKT for the geometries involved with this or a similar exception?

I would think your `BufferOp` is likely adding that precision as again I have stated in our db the value is Decimal(16,12) which we then use to create the position..

For this exception the WKT was a LineString I will provide an example of the LineString asap.

**Comment by juliusfriedman** [comment]
Here are some more exceptions from a very large run:

```
 ---> (Inner Exception #3) NetTopologySuite.Geometries.TopologyException: found non-noded intersection between LINESTRING ( 17.562557379421069 48.39622433978893, 17.562556160840636 48.396225399424083 ) and LINESTRING ( 17.562557379421445 48.396224339788596, 17.562556160841094 48.396225399423685 ) [ (17.562556266804204, 48.396225307281846) ]
   at NetTopologySuite.Noding.FastNodingValidator.CheckValid()
   at NetTopologySuite.Operation.Overlay.OverlayOp.ComputeOverlay(SpatialFunction opCode)
   at NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.GetResultGeometry(SpatialFunction opCode)
--- End of stack trace from previous location where exception was thrown ---
   at NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.GetResultGeometry(SpatialFunction opCode)
   at TripPlanner.Program.ProgramState.<>c__DisplayClass34_1.<CreateOccupationTripsAndRoutes>b__6(Trip trip)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

 ---> (Inner Exception #4) NetTopologySuite.Geometries.TopologyException: found non-noded intersection between LINESTRING ( 16.628885557383622 48.317284817165195, 16.628886272093247 48.317284991484627 ) and LINESTRING ( 16.628886272093258 48.317284991484627, 16.628867678536206 48.317280868393084 ) [ (16.62888627209314, 48.3172849914846) ]
   at NetTopologySuite.Noding.FastNodingValidator.CheckValid()
   at NetTopologySuite.Operation.Overlay.OverlayOp.ComputeOverlay(SpatialFunction opCode)
   at NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.GetResultGeometry(SpatialFunction opCode)
--- End of stack trace from previous location where exception was thrown ---
   at NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.GetResultGeometry(SpatialFunction opCode)
   at TripPlanner.Program.ProgramState.<>c__DisplayClass34_1.<CreateOccupationTripsAndRoutes>b__6(Trip trip)
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)<---

 ---> (Inner Exception #5) NetTopologySuite.Geometries.TopologyException: found non-noded intersection between LINESTRING ( 18.928127176621366 46.185662662281196, 18.9281170585041 46.185633572693966 ) and LINESTRING ( 18.928124091991304 46.18565427752435, 18.92812538147 46.185657501221002 ) [ (18.928125381469997, 46.185657501220994) ]
   at NetTopologySuite.Noding.FastNodingValidator.CheckValid()
   at NetTopologySuite.Operation.Overlay.OverlayOp.ComputeOverlay(SpatialFunction opCode)
   at NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.GetResultGeometry(SpatialFunction opCode)
--- End of stack trace from previous location where exception was thrown ---
   at NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp.GetResultGeometry(SpatialFunction opCode)
```

**Comment by FObermaier** [comment]
@juliusfriedman these exceptions are useless for investigating the problem. The WKT provided in these messages is just the portion of the geometries where noding failed. To actually help, we need to see the input geometries of the overlay operation that threw the exception.

**Comment by juliusfriedman** [comment]
I apologize,  They are LineStrings, I will attempt to provide you the WKT from them, when this exception happens what is the most straightforward way to determine what the WKT of the offending Geometry is?

Sorry and thank you for your time!

**Comment by FObermaier** [comment]
I converted this to a [unit test](https://gist.github.com/FObermaier/f28a6e054cf56d8ce6e44de74494ea8a) and _unfortunately_ it does not show any issues. Either the issue is in fractions not representable in the WKT or these are not the geometries in question.

To eliminate the first possibility could you pass the representation as WKB hex-string (`WKBWriter.ToHex(geom.AsBinary())`?

**Comment by juliusfriedman** [comment]
> I converted this to a [unit test](https://gist.github.com/FObermaier/f28a6e054cf56d8ce6e44de74494ea8a) and _unfortunately_ it does not show any issues. Either the issue is in fractions not representable in the WKT or these are not the geometries in question.
> 
> To eliminate the first possibility could you pass the representation as WKB hex-string (`WKBWriter.ToHex(geom.AsBinary())`?

Yes, gimme a few minutes

**Comment by FObermaier** [comment]
`geom0` and `geom1` are directly from the database or are they a result of an NTS operation?
If they are directly from the database, is there a way that you can provide the original data?

**Comment by juliusfriedman** [comment]
I have geography in the db (NONE ARE INVALID)... I am not sure if this is from a bufferop or not because of the stack.

How can I articulate that to you or provide you with more information?

**Comment by FObermaier** [comment]
This is strange, of course WKBWriter can handle geometries of type `Polygon`:
https://github.com/NetTopologySuite/NetTopologySuite/blob/108f8400f12b8c2df63fe098d3c0b7d69ef3db0c/src/NetTopologySuite/IO/WKBWriter.cs#L47-L81
The error does not make sense.

Could it be that some other portion of your application is modifying the geometry while they are being accessed in the spatial overlay operation? Some shared/global variable?

**Comment by juliusfriedman** [comment]
No... not in this case. I have ensured that any modification are double locked, once around the object which contains the Geography and then locking on the Geogrpahy as well.

**Comment by airbreather** [comment]
> No... not in this case. I have ensured that any modification are double locked, once around the object which contains the Geography and then locking on the Geogrpahy as well.

`Geometry` instances are intended to be treated as immutable after you start using them.  It's fine to modify them in-place for the purposes of creating them initially, but otherwise, you should be creating copies if you want to represent "**this** `Geometry`, but with **that** transformation".

If you **must** modify `Geometry` instances after you have started using them (not recommended), then **at the minimum**, make sure to call [`GeometryChanged`](https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Geometries.Geometry.html#NetTopologySuite_Geometries_Geometry_GeometryChanged) on the instances that you have modified after you are finished modifying them.  Depending on what you have already done with the modified instances, there may be other state that you need to invalidate as well.

**Comment by juliusfriedman** [comment]
Thank you but I am not transforming this or that, and before I perform any operation I lock the class which owns the geometry, then lock the geometry itself, I make my union or otherwise and then assign back to the geometry from the result and subsequently to the class which holds the geometry.

Can't see how I am doing anything which would require raising that event...

Furthermore it seems that method is not thread safe but I don't wanna get into that since I know I am locking in this case.

Thank you for the advice none the less....

If there any other information you can provide?

**Comment by FObermaier** [comment]
Could you pass `geom.Copy()` to the overlay operation to make sure everything is ok?

**Comment by juliusfriedman** [comment]
I get WKB the first time I am at this break point after my latest run:
[geom0.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/5044154/geom0.txt)
[geom1.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/5044155/geom1.txt)


I will see if I can replicate the issue again where I can get the error, but as I had stated in a previous thread I think it comes down to how you build the geometry each time....

I will let you know asap if I can find the example which causes the error I posted above shortly and what happens when the OverlayOp is used on the geometry which crashed the WKB Writer.

In either case the above 2 polygons result in the Non noded line exception. (for me)

**Comment by FObermaier** [comment]
Using NTS v2.0, the provided geometry files (text, qoutes and line breaks removed) don't show any issues:
```C#
[TestCase(@"d:\obe\Downloads\geom0.txt", @"d:\obe\Downloads\geom1.txt")]
public void TestDifferenceWkb(string filePath0, string filePath1)
{
    var wrt = new WKTWriter();
    wrt.Formatted = true;
    wrt.MaxCoordinatesPerLine = 3;
    wrt.OutputOrdinates = Ordinates.XY;

    var rdr = new WKBReader();
    var g1 =  rdr.Read(WKBReader.HexToBytes(File.ReadAllText(filePath0, Encoding.UTF8)));
    TestContext.WriteLine(wrt.WriteFormatted(g1));
    var g2 = rdr.Read(WKBReader.HexToBytes(File.ReadAllText(filePath1, Encoding.UTF8)));
    TestContext.WriteLine("\n");
    TestContext.WriteLine(wrt.WriteFormatted(g1));

    Assert.That(g1.IsValid, "g1.IsValid");
    Assert.That(g2.IsValid, "g2.IsValid");

    Geometry gd = null;
    Assert.That(() => gd = g1.Difference(g2), Throws.Nothing);

    TestContext.WriteLine("\n");
    TestContext.WriteLine(wrt.WriteFormatted(gd));
}

```

**Comment by juliusfriedman** [comment]
I apologize for wasting your time, those are the values I am getting when the exception occurred...

I just updated to 2.1.0 last night, I am consistently hitting an error which crashed my program from `LengthIndexedLine.ExtractLine`, I am trying to get more information but the data set is large so I have opted to just try catch around it and use `LINESTRING EMPTY` to mark where this happens such that I can go back more easily and attempt to replicate this without having to regenerate the entire set of data.

There are also seemingly a lot more `Depth mismatch exceptions occurring`, is the process for diagnosing these the same as was for the others? e.g. just provide the WKB in question of the `Geometry` in question?

Here is a LineString and  a Polygon which are also throwing the exception during a Union or Difference Operation:

[lineStringWKB.zip](https://github.com/NetTopologySuite/NetTopologySuite/files/5050557/lineStringWKB.zip) (Both files are obtained from `System.IO.File.WriteAllBytes(@"path", new NetTopologySuite.IO.WKBWriter().Write(geom)`

I attempted to get the WKT of the SnapIfNeededOverlyOp using the same code but it appears to have halted my application...
(I tried while caught in an exception on line 78 `result = SnapOverlayOp.Overlay(_geom[0], _geom[1], opCode);`)

From `WKBWriter.GetBytes`:

`if (geometry is Polygon)
                return new byte[SetByteStream(geometry as Polygon)];`

But I was able to get the WKT from one of them:

[Failing.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/5050577/Failing.txt)

Let me know what you find and sorry if this yeilds nothing

**Comment by FObermaier** [comment]
@juliusfriedman, I strongly feel that your issues are related to a concurrency problem.

Plainly using the provided files and perform what I grasp that you do is working without issues:
```C#
public void TestDifference(string wkbFileA, string wkbFileB)
{
    if (!File.Exists(wkbFileA) || !File.Exists(wkbFileB))
        Assert.Ignore("At least one of the files is not present!");

    // NOTE: this is not necessary, it works without this, too.
    NtsGeometryServices.Instance = new NtsGeometryServicesEx();

    var wkbReader = new WKBReader();
    var geomA = ReadPolygon(wkbReader, wkbFileA);
    var geomB = ReadPolygon(wkbReader, wkbFileB);

    Geometry res = null;
    Assert.DoesNotThrow(() => res = geomA.Difference(geomB));
    Assert.That(res, Is.Not.Null);

    Assert.DoesNotThrow(() => res = geomA.Union(geomB));
    Assert.That(res, Is.Not.Null);

}

private static Geometry ReadPolygon(WKBReader wkbReader, string wkbFile)
{
    var res = wkbReader.Read(File.ReadAllBytes(wkbFile));
    if (!(res is IPolygonal))
        res = res.Buffer(0.001d);
    return res;
}

private class NtsGeometryServicesEx : NtsGeometryServices
{
    protected override GeometryFactory CreateGeometryFactoryCore(PrecisionModel precisionModel, int srid,
        CoordinateSequenceFactory coordinateSequenceFactory)
    {
        return new GeometryFactoryEx(precisionModel, srid, coordinateSequenceFactory);
    }
}
```

**Comment by juliusfriedman** [comment]
Thank you for your help! I will adjust as soon as possible and report back.

**Comment by FObermaier** [comment]
Floating.Songle is sufficient if you jave less than 7 significant digits.
