### ISSUE TITLE
OverlayNG port

### ISSUE THREAD

**Issue by KarolKolenda** [NetTopologySuite/NetTopologySuite#418]
Hi
Do you have any plans (timescale) for porting new overlay algorithms (Next Generation) as indicated in [http://lin-ear-th-inking.blogspot.com/2020/05/jts-overlay-next-generation.html](http://lin-ear-th-inking.blogspot.com/2020/05/jts-overlay-next-generation.html)

Thanks.

BTW: Big thank you for all your work on NTS – managed .Net port does work brilliantly!

**Comment by FObermaier** [comment]
see https://github.com/NetTopologySuite/NetTopologySuite/tree/enhancement/overlay-sr

**Comment by KarolKolenda** [comment]
Thank you Felix, that was quick!
