### ISSUE TITLE
Help! Convert Geometry To Geography 

### ISSUE THREAD

**Issue by juliusfriedman** [NetTopologySuite/NetTopologySuite#421]
In one DataContext I have a column with a Geometry type, I can query from this model by specifying `Column(TypeName='geometry')`

In another DataContext I have a column with a Geography type.

This code seems to be working

```c#
Geography geography = someobject.Geography; //Geometry Polygon
Geography geometry = otherObject.Geometry; //Geography Polygon
var newBoundary = (NetTopologySuite.Geometries.Polygon)geography.Boundary.Difference(geometry.Geography).Union(geography.Boundary);
//Not working here?
//GeometryHelper.CombinePolygons(geography.Boundary, (NetTopologySuite.Geometries.Polygon)geometry.Geography);

                                newBoundary.Normalize();

                                newBoundary.SRID = GeometryHelper.SpatialReferenceId;

                                if (false == newBoundary.Shell.IsCCW)
                                {
                                    newBoundary = (NetTopologySuite.Geometries.Polygon)newBoundary.Reverse();
                                }
```

I have a function I typically use for this:

```c#
// <summary>
		/// Combines polygons
		/// </summary>
		/// <param name="polygons"></param>
		/// <returns></returns>
		public static Polygon CombinePolygons(params Polygon[] polygons)
		{
			return CombinePolygons((System.Collections.Generic.IEnumerable<Polygon>)polygons);
		}

		/// <summary>
		/// Combines polygons
		/// </summary>
		/// <param name="polygons"></param>
		/// <returns></returns>
		public static Polygon CombinePolygons(System.Collections.Generic.IEnumerable<Polygon> polygons)
		{
			//There was an existing polygon combine it with the new one
			NetTopologySuite.Geometries.Utilities.GeometryCombiner combiner = new NetTopologySuite.Geometries.Utilities.GeometryCombiner(polygons);

			//Set the polygon and the Boundary (Removing Union) here helps
			Polygon result = combiner.Combine().ConvexHull() as Polygon;

//Without this I get unusual results
			result.Normalize();

			result.SRID = GeometryHelper.SpatialReferenceId;

			if (false == result.Shell.IsCCW)
			{
				result = result.Reverse() as Polygon;
			}

			return result;
		}
```

However when I run this function to combine them I get Polygon with the appropriate SRID but when I attempt to insert it into the Geography column I get an error that the type is not a valid Geometry? The `IsValid` is true, I don't know where to look to see if the type is Geography or Geometry but I would assume that it would depend on the context, and in this case I have set the SRID so it should be Geography yet it says explicitly that it's not valid Geometry?

What am I doing wrong?

Furthermore...

Consider this function:
```c#
public static Polygon CreatePolygon(Coordinate[] coordinates)
        {
			var polygon = GeometryFactory.CreatePolygon(coordinates);
			polygon.SRID = SpatialReferenceId;
			polygon.Normalize();
			if(false == polygon.Shell.IsCCW)
            {
				polygon = (Polygon)polygon.Reverse();
            }
			return polygon;
        }
```

If I pass it the `Geography.Coordinates` (which is a Geometry in the db), I would expect I would get a valid `Geography` back but instead I get the error:

> The supplied value is not a valid instance of data type geography. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision.

The factory is defined as follows:

```c#
/// <summary>
		/// GeometryHelper.SpatialReferenceId refers to WGS 84, a standard used in GPS and other geographic systems.
		/// </summary>
		public const int SpatialReferenceId = 4326;

		/// <summary>
		/// Used to easily create points or polygons with the correct <see cref="SpatialReferenceId"/>
		/// </summary>
		public static readonly GeometryFactory GeometryFactory = NtsGeometryServices.Instance.CreateGeometryFactory(SpatialReferenceId);
```

If any examples of the `Geometry` and `Geography` I am combining I will provide some, just let me know.

Example of the binary which is type 'geography' which is failing:

`E6-10-00-00-01-04-0F-00-00-00-AA-C6-8D-D5-30-B9-57-C0-6D-90-F6-2C-B6-AE-3D-40-63-5F-13-A1-02-BA-57-C0-F1-91-97-51-94-AF-3D-40-D6-90-1E-B6-1A-BA-57-C0-FF-1F-B2-B5-1D-BC-3D-40-BA-F3-34-BC-14-BA-57-C0-82-FD-E3-D1-46-BD-3D-40-CA-2A-B6-85-C4-B9-57-C0-43-2C-92-85-CC-BD-3D-40-DA-61-37-89-85-B9-57-C0-C3-FC-8D-DC-6B-BE-3D-40-EA-98-B8-B3-4C-B9-57-C0-A6-B7-75-04-18-BF-3D-40-73-34-F9-60-18-B9-57-C0-94-E0-1A-CD-DC-BE-3D-40-37-82-99-01-07-B9-57-C0-1A-50-DF-81-D1-BE-3D-40-19-A9-E9-13-00-B9-57-C0-FD-B7-9D-D5-78-BE-3D-40-FA-CF-39-CC-CB-B8-57-C0-D1-34-B2-4D-6E-BE-3D-40-FA-CF-39-0C-7D-B8-57-C0-E5-A7-FB-FF-50-BE-3D-40-C2-95-66-C2-8A-B8-57-C0-FA-DA-B6-06-76-BB-3D-40-F1-2D-08-2A-7B-B8-57-C0-E1-AC-B4-CE-E7-AF-3D-40-AA-C6-8D-D5-30-B9-57-C0-6D-90-F6-2C-B6-AE-3D-40-01-00-00-00-02-00-00-00-00-01-00-00-00-FF-FF-FF-FF-00-00-00-00-03`

Is there anyway to use the `MakeValid` on the server automatically avoid this issue? (maybe opt in only)

```DECLARE @g geometry; 
SET @g = geometry::STGeomFromWKB(0xE610000001040F000000AAC68DD530B957C06D90F62CB6AE3D40635F13A102BA57C0F191975194AF3D40D6901EB61ABA57C0FF1FB2B51DBC3D40BAF334BC14BA57C082FDE3D146BD3D40CA2AB685C4B957C0432C9285CCBD3D40DA61378985B957C0C3FC8DDC6BBE3D40EA98B8B34CB957C0A6B7750418BF3D407334F96018B957C094E01ACDDCBE3D403782990107B957C01A50DF81D1BE3D4019A9E91300B957C0FDB79DD578BE3D40FACF39CCCBB857C0D134B24D6EBE3D40FACF390C7DB857C0E5A7FBFF50BE3D40C29566C28AB857C0FADAB60676BB3D40F12D082A7BB857C0E1ACB4CEE7AF3D40AAC68DD530B957C06D90F62CB6AE3D4001000000020000000001000000FFFFFFFF0000000003, 0)
SELECT @g;

DECLARE @z geography; 
SET @z = geography::STGeomFromWKB(0xE610000001040F000000AAC68DD530B957C06D90F62CB6AE3D40635F13A102BA57C0F191975194AF3D40D6901EB61ABA57C0FF1FB2B51DBC3D40BAF334BC14BA57C082FDE3D146BD3D40CA2AB685C4B957C0432C9285CCBD3D40DA61378985B957C0C3FC8DDC6BBE3D40EA98B8B34CB957C0A6B7750418BF3D407334F96018B957C094E01ACDDCBE3D403782990107B957C01A50DF81D1BE3D4019A9E91300B957C0FDB79DD578BE3D40FACF39CCCBB857C0D134B24D6EBE3D40FACF390C7DB857C0E5A7FBFF50BE3D40C29566C28AB857C0FADAB60676BB3D40F12D082A7BB857C0E1ACB4CEE7AF3D40AAC68DD530B957C06D90F62CB6AE3D4001000000020000000001000000FFFFFFFF0000000003, 4326)
SELECT @z;
```

both produce the same results:

> Msg 6522, Level 16, State 1, Line 11
A .NET Framework error occurred during execution of user-defined routine or aggregate "geometry": 
System.FormatException: 24115: The well-known binary (WKB) input is not valid.
System.FormatException: 
   at Microsoft.SqlServer.Types.WellKnownBinaryReader.Read(OpenGisType type, Int32 srid)
   at Microsoft.SqlServer.Types.SqlGeometry.GeometryFromBinary(OpenGisType type, SqlBytes binary, Int32 srid)
.

> (1 row affected)
> Msg 6522, Level 16, State 1, Line 15
> A .NET Framework error occurred during execution of user-defined routine or aggregate "geography": 
> System.FormatException: 24201: Latitude values must be between -90 and 90 degrees.
> System.FormatException: 
>    at Microsoft.SqlServer.Types.GeographyValidator.ValidatePoint(Double x, Double y, Nullable`1 z, Nullable`1 m)
>    at Microsoft.SqlServer.Types.Validator.BeginFigure(Double x, Double y, Nullable`1 z, Nullable`1 m)
>    at Microsoft.SqlServer.Types.ForwardingGeoDataSink.BeginFigure(Double x, Double y, Nullable`1 z, Nullable`1 m)
>    at Microsoft.SqlServer.Types.CoordinateReversingGeoDataSink.BeginFigure(Double x, Double y, Nullable`1 z, Nullable`1 m)
>    at Microsoft.SqlServer.Types.WellKnownBinaryReader.ReadFirstPoint(ByteOrder byteOrder, Boolean readZ, Boolean readM)
>    at Microsoft.SqlServer.Types.WellKnownBinaryReader.ParseWkbPointWithoutHeader(ByteOrder byteOrder, Boolean readZ, Boolean readM)
>    at Microsoft.SqlServer.Types.WellKnownBinaryReader.ParseWkb(OpenGisType type)
>    at Microsoft.SqlServer.Types.WellKnownBinaryReader.Read(OpenGisType type, Int32 srid)
>    at Microsoft.SqlServer.Types.SqlGeography.GeographyFromBinary(OpenGisType type, SqlBytes wkbGeography, Int32 srid)
> .
> 

Even going this route yields no different results..

```c#
  List<NetTopologySuite.Geometries.Coordinate> goodCoords = new List<NetTopologySuite.Geometries.Coordinate>();

                                foreach(var c in geometry.Coordinates)
                                {
                                    var point = GeometryHelper.CreatePoint(c);
                                    if (!point.IsValid)
                                    {
//Never hit?
                                        continue;
                                    }
                                    goodCoords.Add(c);
                                }
```

The `IsValid` appears to be true as well...

**Comment by airbreather** [comment]
I'm not entirely sure what you're trying to accomplish with all this `.Boundary` stuff.  The boundary of a `geometry` polygon is a set of lines that make up its shell and holes (not a polygon), and `STBoundary` doesn't exist on a `geography`...

> when I attempt to insert it into the Geography column I get an error that the type is not a valid Geometry? The `IsValid` is true, I don't know where to look to see if the type is Geography or Geometry but I would assume that it would depend on the context, and in this case I have set the SRID so it should be Geography yet it says explicitly that it's not valid Geometry?

This may be another case where something like NetTopologySuite/NetTopologySuite.IO.SqlServerBytes#9 could help.

> Example of the binary which is type 'geography' which is failing:

The first byte of a valid WKB sequence is always `00` or `01`.  `E6` looks like the first byte of a geography in SQL Server's internal representation, so `STGeomFromWKB` won't do it for you.  To convert the internal representation to `geography`, it's just:
```sql
SELECT CAST(0xE6100000010C0000000000000040000000000000F03F AS geography)
```

**Comment by juliusfriedman** [comment]
I tried both with and without the Boundary because I was not sure although I later read and changed it to just use the `Geometry` whatever it maybe.

I just updated the function above to coincide so you understand what I mean.

In short can you provide a straight forward way of taking an existing `Geography` and combining it with a `Geometry`?

**Comment by juliusfriedman** [comment]
@airbreather an example of the query which fails insertion:

```sql
Microsoft.EntityFrameworkCore.Database.Command: Information: Executed DbCommand (260ms) [Parameters=[@p11='4633', @p0='0xE61000000104090000007AC2C8F02B0F4440CF399126291356C07E8E4799430F...' (Nullable = false) (Size = 176) (DbType = Object), @p1='2020-06-19T11:02:37', @p2='NA' (Size = 4000), @p3='4', @p4='True', @p5='True', @p6='True', @p7='2020-07-07T14:22:04', @p8='Plastipak' (Nullable = false) (Size = 4000), @p9='334', @p10='8533' (Nullable = true), @p23='4634', @p12='0xE610000001040D000000ADEFBC5570BD3D40FACF39BC44B957C0E4E09720C4BD...' (Nullable = false) (Size = 240) (DbType = Object), @p13='2020-06-19T11:02:37', @p14='NA' (Size = 4000), @p15='14', @p16='True', @p17='True', @p18='True', @p19='2020-07-07T14:22:04', @p20='Ravago Baytown ' (Nullable = false) (Size = 4000), @p21='334', @p22='8534' (Nullable = true), @p35='4635', @p24='0xE610000001040C0000002E386A1EF4BC3D405157DEEE1BB957C02E0A7B73D8BD...' (Nullable = false) (Size = 224) (DbType = Object), @p25='2020-06-19T11:02:37', @p26='NA' (Size = 4000), @p27='19', @p28='True', @p29='True', @p30='True', @p31='2020-07-07T14:22:04', @p32='TGS' (Nullable = false) (Size = 4000), @p33='334', @p34='8535' (Nullable = true), @p47='4676', @p36='0xE61000000104080000000D9EF0708BB541402015F412725F58C01374254A88B5...' (Nullable = false) (Size = 160) (DbType = Object), @p37='2020-06-19T11:02:37', @p38='NA' (Size = 4000), @p39='4', @p40='True', @p41='True', @p42='True', @p43='2020-07-07T14:22:04', @p44='API ENTERPRISES ' (Nullable = false) (Size = 4000), @p45='334', @p46='8576' (Nullable = true), @p59='4701', @p48='0xE610000001040B0000001022CEF643B94440B2A83F90327354C09C7054911CB9...' (Nullable = false) (Size = 208) (DbType = Object), @p49='2020-06-19T11:02:37', @p50='NA' (Size = 4000), @p51='4', @p52='True', @p53='True', @p54='True', @p55='2020-07-07T14:22:04', @p56='ALPHA PACKAGING HOLDINGS INC - Cleveland, OH' (Nullable = false) (Size = 4000), @p57='334', @p58='8603' (Nullable = true), @p71='4702', @p60='0xE6100000010408000000F1F9B4181E20424017F3C0D5F5D357C0F1F9B4181E20...' (Nullable = false) (Size = 160) (DbType = Object), @p61='2020-06-19T11:02:37', @p62='NA' (Size = 4000), @p63='4', @p64='True', @p65='True', @p66='True', @p67='2020-07-07T14:22:04', @p68='Berry Global Inc - Pryor, OK' (Nullable = false) (Size = 4000), @p69='334', @p70='8604' (Nullable = true), @p83='4764', @p72='0xE610000001040900000084A90EF6A51F4240B199DAEE7AD557C007EAF6C6BD1F...' (Nullable = false) (Size = 176) (DbType = Object), @p73='2020-06-19T11:02:37', @p74='NA' (Size = 4000), @p75='4', @p76='True', @p77='True', @p78='True', @p79='2020-07-07T14:22:04', @p80='Berry Global Yard ' (Nullable = false) (Size = 4000), @p81='334', @p82='8667' (Nullable = true), @p95='4765', @p84='0xE610000001040B000000D00AF2583D124440D92370F9930E56C0D9EAAD415215...' (Nullable = false) (Size = 208) (DbType = Object), @p85='2020-06-19T11:02:37', @p86='NA' (Size = 4000), @p87='4', @p88='True', @p89='True', @p90='True', @p91='2020-07-07T14:22:04', @p92='Plastipak Yard' (Nullable = false) (Size = 4000), @p93='334', @p94='8668' (Nullable = true)], CommandType='Text', CommandTimeout='300']
SET NOCOUNT ON;
UPDATE [GeographyTable] SET [GeographyColumn] = @p0, [CreatedDate] = @p1, [Description] = @p2, [Column1] = @p3, [Column2] = @p4, [IsDeleted] = @p5, [IsValid] = @p6, [ModifiedDate] = @p7, [Name] = @p8, [Column3] = @p9, [RecordID] = @p10
WHERE [PrimaryKey] = @p11;
SELECT @@ROWCOUNT;

UPDATE [GeographyTable] SET [GeographyColumn] = @p12, [CreatedDate] = @p13, [Description] = @p14, [Column1] = @p15, [Column2] = @p16, [IsDeleted] = @p17, [IsValid] = @p18, [ModifiedDate] = @p19, [Name] = @p20, [Column3] = @p21, [RecordID] = @p22
WHERE [PrimaryKey] = @p23;
SELECT @@ROWCOUNT;

UPDATE [GeographyTable] SET [GeographyColumn] = @p24, [CreatedDate] = @p25, [Description] = @p26, [Column1] = @p27, [Column2] = @p28, [IsDeleted] = @p29, [IsValid] = @p30, [ModifiedDate] = @p31, [Name] = @p32, [Column3] = @p33, [RecordID] = @p34
WHERE [PrimaryKey] = @p35;
SELECT @@ROWCOUNT;

UPDATE [GeographyTable] SET [GeographyColumn] = @p36, [CreatedDate] = @p37, [Description] = @p38, [Column1] = @p39, [Column2] = @p40, [IsDeleted] = @p41, [IsValid] = @p42, [ModifiedDate] = @p43, [Name] = @p44, [Column3] = @p45, [RecordID] = @p46
WHERE [PrimaryKey] = @p47;
SELECT @@ROWCOUNT;

UPDATE [GeographyTable] SET [GeographyColumn] = @p48, [CreatedDate] = @p49, [Description] = @p50, [Column1] = @p51, [Column2] = @p52, [IsDeleted] = @p53, [IsValid] = @p54, [ModifiedDate] = @p55, [Name] = @p56, [Column3] = @p57, [RecordID] = @p58
WHERE [PrimaryKey] = @p59;
SELECT @@ROWCOUNT;

UPDATE [GeographyTable] SET [GeographyColumn] = @p60, [CreatedDate] = @p61, [Description] = @p62, [Column1] = @p63, [Column2] = @p64, [IsDeleted] = @p65, [IsValid] = @p66, [ModifiedDate] = @p67, [Name] = @p68, [Column3] = @p69, [RecordID] = @p70
WHERE [PrimaryKey] = @p71;
SELECT @@ROWCOUNT;

UPDATE [GeographyTable] SET [GeographyColumn] = @p72, [CreatedDate] = @p73, [Description] = @p74, [Column1] = @p75, [Column2] = @p76, [IsDeleted] = @p77, [IsValid] = @p78, [ModifiedDate] = @p79, [Name] = @p80, [Column3] = @p81, [RecordID] = @p82
WHERE [PrimaryKey] = @p83;
SELECT @@ROWCOUNT;

UPDATE [GeographyTable] SET [GeographyColumn] = @p84, [CreatedDate] = @p85, [Description] = @p86, [Column1] = @p87, [Column2] = @p88, [IsDeleted] = @p89, [IsValid] = @p90, [ModifiedDate] = @p91, [Name] = @p92, [Column3] = @p93, [RecordID] = @p94
WHERE [PrimaryKey] = @p95;
SELECT @@ROWCOUNT;
```

**Comment by juliusfriedman** [comment]
I have checked and rechecked again...

I am not sure there are any `Geometry` Columns in our DB, we have everything in `Geography` I have no idea where this value is formed given I only have `Geography` Columns and can find no invalid `Geography` in my database.

https://github.com/NetTopologySuite/NetTopologySuite/issues/427

My question issue here is 2:

1) Where does the Geometry come from given I only have Geography?
2) How does one convert this invalid Geometry to Geography (lack of MakeValid method or use in SQL)?

**Comment by juliusfriedman** [comment]
When the ColumnType is specified as geometry the Coordinates are reversed by NTS where as this is not done for geography, it appears this is handled correctly IF you:

1. Specify the ColumnType 
2. Create a Geometry instance using Coordinates
3. Assign that Geometry to a Instance with a ColumnType desired

If you arbitrarily assign a Geometry instance to a property with a ColumnType then NTS will write the Coordinates as specified by the ColumnType on that property.

`Let a = Point(1,0)`
`class MyTypeGeography{ Geometry Boundary {get;set;} //A=1,0` 
`class MyTypeGeometry{[ColumnType("geometry")]Geometry Boundary {get;set;} //A=0,1`

This indicates to convert from Geography to Geometry you don't have to reverse the Coordinates as it's done for you.

I believe this issue can be closed, if you need more information let me know!
