### ISSUE TITLE
Invalid Scale (Greater than Precision)

### ISSUE THREAD

**Issue by juliusfriedman** [NetTopologySuite/NetTopologySuite#427]
WKB = `0xE6100000010C8AC33EA65AFF58C06ECF3D35A89B3940`

I think this is a point, not sure whats up with it yet, I can't seem to locate it in my DB yet it appears in the query formed by EF / NTS.... Further more a SELECT from the table where the SpatialColumn.STIsValid() = 0 yields no results...

The type of the spatial column is Geography

**Comment by FObermaier** [comment]
> I think this is a point, ...

It is `SRID=4326;POINT (25.6080354 -99.9899078)`

The binary string you posted as WKB is actually the SqlServer's internal blob of that point.
I don't see what else we can do to help you here.

**Comment by juliusfriedman** [comment]
I have no idea why it's invalid, there are no invalid geography instances in my database...

The other odd thing is the query which is formed looks for the GeographyColumn = `0xE6100000010C8AC33EA65AFF58C06ECF3D35A89B3940` but I can't find that WKB in my database.

**Comment by FObermaier** [comment]
The blobs beginning with `0xE6` are geometries/geograhphies stored in SqlSever's notation, that is not WKB.
It is probably being created using `[NetTopologySuite.IO.SqlServerBytes](https://github.com/NetTopologySuite/NetTopologySuite.IO.SqlServerBytes)`

**Comment by juliusfriedman** [comment]
I apologize for any inconvenience can you transfer this issue there, I think @airbreather  said previously in the `Help Convert Geometry to Geography` thread that what you are saying may be the case.

Should I open the issue there or can you transfer it please?

**Comment by juliusfriedman** [comment]
This was due to `geometry` as the ColumnType, sorry for any waste of time!
