### ISSUE TITLE
NTS.IO.GeoJSON.nuspec limits Newtonsoft.Json to the major release number of latest release

### ISSUE THREAD

**Issue by jnicho02** [NetTopologySuite/NetTopologySuite#43]
https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NTS.IO.GeoJSON.nuspec includes the line &lt;dependency id="Newtonsoft.Json" version="[6.0,7.0)" /&gt; ...which itself has a type on the array.

The latest version of Newtonsoft.Json is 7.0.1 so this package won't work with it. I assume that the author didn't intend to limit the upper version, could it be changed to &lt;dependency id="Newtonsoft.Json" version="6.0" /&gt; i.e. greater than or equal to 6.0, please ?

**Comment by DGuidi** [comment]
can be useful something like assembly redirect, in app.config?

```
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="GeoAPI" publicKeyToken="a1a0da7def465678" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.7.4.0" newVersion="1.7.4.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by FObermaier** [comment]
@DGuidi, @jnicho02:
In the process of preparing 1.13.4 release I have removed the upper version constraint.
May not be yet synced.

**Comment by DGuidi** [comment]
@FObermaier ok well done.
BTW I've some troubles bullding PCS.Tests assembly in a clean PC (Win10 + VS2015 installation).
I'm investingating...

**Comment by FObermaier** [comment]
@DGuidi qoute:"this is the new stuff, ..."

**Comment by jnicho02** [comment]
That's great, thank you. I'm impressed with your turnaround speed.
