### ISSUE TITLE
Redundant points in Geometry.ConvexHull()

### ISSUE THREAD

**Issue by gchling** [NetTopologySuite/NetTopologySuite#434]
[s22a.zip](https://github.com/NetTopologySuite/NetTopologySuite/files/5230084/s22a.zip)

I found that function ConvexHull() sometimes gets wrong results. The order of the boundary points is not right. Need to remove redundancy. But no function to remove redundancy was found.

**Comment by FObermaier** [comment]
To change the order of the geometry points call `geometry.Reverse()` or use `GeometryFactoryEx` configured to use a specific ring orientation.
The _redundant_ points in the ring are the result of precision issues. To remove these call `NetTopologySuite.Simplify.TopologyPreservingSimplifier.Simplify(geometry, tolerance)`.
A `tolerance` value of 1E-6 yields 
```POLYGON Z((27622.2754596 46891.8215107 -1183.6875, 
28993.5712944 51674.098451 -1118.0369873, 
10849.7567723 56876.7535028 -1080.3553467, 
9478.4609375 52094.4765625 -1226.4155273, 
27622.2754596 46891.8215107 -1183.6875))
```
for the provided data set.

**Comment by gchling** [comment]
Thank you!
After the Simplify I got the correct rusult。
I do it l as the following：

PrecisionModel precisionModel = new PrecisionModel(PrecisionModel.MaximumPreciseValue);
GeometryFactory factory = new GeometryFactory(precisionModel, 0);
var ch = new ConvexHull(coordinates, factory);
Geometry actual = ch.GetConvexHull();

Trace.WriteLine("Before Simplify:");
foreach(Coordinate coor in actual.Coordinates)
{
Trace.WriteLine($"{coor.X},{coor.Y}");
}

double dTolerance = 1E-6;
Geometry geoSimplify = NetTopologySuite.Simplify.TopologyPreservingSimplifier.Simplify(actual, dTolerance);
Trace.WriteLine("After Simplify:");
foreach (Coordinate coor in geoSimplify.Coordinates)
{
Trace.WriteLine($"{coor.X},{coor.Y}");
}

**Before _Simplify_ the result coordinates is no in the line order(not just reverse), I tested _geometry.Reverse()_ cannot got right result.
I'll test more data using combination of _ConvexHull_ and _Simplify_。**

**Comment by FObermaier** [comment]
> Before Simplify the result coordinates is no in the linear order(not just reverse), I tested geometry.Reverse() cannot got correct result.

What do you mean by _in no linear order_? The result of `geometry.ConvexHull()` is a `POLYGON` with an exterior ring made up of consecutive points. The points in this ring are oriented __counter-clockwise__. Calling `geometry.Reverse()` will re-orient the ring so the points are oriented __clockwise__. This applies if you use the default `GeometryFactory`.

**Comment by gchling** [comment]
The order of result coordinates is  neither clockwise nor counter-clockwise.
Now I upload the picture of coordinates with order(Just the bottom border, the left border and the top border is correct, but the bottom border and the right border is not correct).
![border](https://user-images.githubusercontent.com/42533057/93851867-7fcae300-fce3-11ea-98b7-591b87fede19.png)

[border.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/5259562/border.txt)

**Comment by FObermaier** [comment]
This image does not prove anything. For the sake of simplicity, don't provide individual coordinates but the result of `Geometry.AsText()`.

Try changing your code to this:
```C#
var precisionModel = new PrecisionModel(PrecisionModel.MaximumPreciseValue);
var factory = new GeometryFactory(precisionModel, 0);
var ch = new ConvexHull(coordinates, factory);
var actual = ch.GetConvexHull();

Trace.WriteLine("Before Simplify:");
Trace.WriteLine(string.Format("Geometry type: {0}", actual.GeometryType));
if (actual is Polygon p)
{
    var ring = (LinearRing)p.ExteriorRing;
    Trace.WriteLine(string.Format("Exterior ring orientation: {0}", ring.IsCCW ? "counter-clockwise" : "clockwise"));
    p.Reverse();
    ring = (LinearRing)p.ExteriorRing;
    Trace.WriteLine(string.Format("Exterior ring orientation: {0}", ring.IsCCW ? "counter-clockwise" : "clockwise"));
}
Trace.WriteLine(actual.AsText());

double dTolerance = 1E-6;
Geometry geoSimplify = NetTopologySuite.Simplify.TopologyPreservingSimplifier.Simplify(actual, dTolerance);
Trace.WriteLine("\nAfter Simplify:");
Trace.WriteLine(geoSimplify.AsText());
```

**Comment by gchling** [comment]
I want to use this picture to illustrate that the result coordinates is neither clockwise nor counter-clockwise。If coordinates order is counter-clockwise, the right point of point index 99 should be 100;if it is clockwise, the right point index of point index 99 should be 98，but the result is 105。I think the points should order like 98,99,100,101，but just not.
I changed my code as your said, the polygon is same as before.
Thanks for your help.

**Comment by FObermaier** [comment]
I'm afraid to say that you must be mixing things up. None of the convex hulls created from your sample input has 100 points.

The following code 

```C#
[TestCase(@"D:\obe\Downloads\border.txt")]
[TestCase(@"D:\obe\Downloads\s22a.xyz")]
public void TestFiles(string filePath)
{
    var pts = ReadFile(filePath);
    var convexHullOp = new ConvexHull(pts, GeometryFactory.Default);
    var ch = convexHullOp.GetConvexHull();

    Assert.That(ch, Is.Not.Null);
    TestContext.WriteLine("ConvexHull:");
    TestContext.WriteLine("Geometry type: {0}", ch.GeometryType);
    TestContext.WriteLine("Number of points: {0}", ch.NumPoints);
    if (ch is Polygon p)
    {
        var ring = (LinearRing) p.ExteriorRing;
        TestContext.WriteLine("Exterior ring orientation: {0}", ring.IsCCW ? "counter-clockwise" : "clockwise");
    }
    var wktWriter = new WKTWriter {Formatted = true, MaxCoordinatesPerLine = 3, OutputOrdinates = Ordinates.XY};
    TestContext.WriteLine("WKT:\n{0}", wktWriter.WriteFormatted(ch));

    var simplifyOp = new TopologyPreservingSimplifier(ch) { DistanceTolerance = 1E-6 };
    var ch1 = simplifyOp.GetResultGeometry();
    TestContext.WriteLine("\nSimplified ConvexHull:");
    TestContext.WriteLine("Geometry type: {0}", ch1.GeometryType);
    TestContext.WriteLine("Number of points: {0}", ch1.NumPoints);
    if (ch1 is Polygon p1)
    {
        var ring = (LinearRing)p1.ExteriorRing;
        TestContext.WriteLine("Exterior ring orientation: {0}", ring.IsCCW ? "counter-clockwise" : "clockwise");
    }

    TestContext.WriteLine("WKT:\n{0}", wktWriter.WriteFormatted(ch1));

}

private IReadOnlyList<Coordinate> ReadFile(string filePath)
{
    if (!System.IO.File.Exists(filePath))
        throw new InconclusiveException($"File not present: '{filePath}'");

    using var sr = new StreamReader(File.OpenRead(filePath));
    var res = new List<Coordinate>();
    while (!sr.EndOfStream)
    {
        string line = sr.ReadLine();
        if (string.IsNullOrWhiteSpace(line))
            continue;

        string[] parts = line.Split(",");
        if (parts.Length < 2)
            throw new InvalidDataException();
        res.Add(new Coordinate(double.Parse(parts[0], NumberFormatInfo.InvariantInfo),
            double.Parse(parts[1], NumberFormatInfo.InvariantInfo)));
    }

    return res;
}
```

yields the following result:
```
ConvexHull (border.txt):
Geometry type: Polygon
Number of points: 20
Exterior ring orientation: counter-clockwise
WKT:
POLYGON ((27622.27546 46891.82151, 27636.05733 46939.8846, 27794.54881 47492.61007, 
  28690.37021 50616.71058, 28959.11663 51553.94074, 28979.78943 51626.03537, 
  28993.57129 51674.09845, 27767.96263 52025.53608, 25340.77685 52721.5204, 
  15271.56058 55608.82168, 12892.43788 56291.02413, 11450.54533 56704.48016, 
  10849.75677 56876.7535, 9547.370276 52334.79199, 9478.460938 52094.47656, 
  9526.524022 52080.69469, 10343.59646 51846.40294, 24281.89106 47849.66131, 
  27598.24392 46898.71244, 27622.27546 46891.82151))

Simplified ConvexHull:
Geometry type: Polygon
Number of points: 18
Exterior ring orientation: counter-clockwise
WKT:
POLYGON ((27622.27546 46891.82151, 27794.54881 47492.61007, 28690.37021 50616.71058, 
  28959.11663 51553.94074, 28979.78943 51626.03537, 28993.57129 51674.09845, 
  27767.96263 52025.53608, 25340.77685 52721.5204, 15271.56058 55608.82168, 
  11450.54533 56704.48016, 10849.75677 56876.7535, 9547.370276 52334.79199, 
  9478.460938 52094.47656, 9526.524022 52080.69469, 10343.59646 51846.40294, 
  24281.89106 47849.66131, 27598.24392 46898.71244, 27622.27546 46891.82151))
```
and
```
ConvexHull (s22a.xyz):
Geometry type: Polygon
Number of points: 32
Exterior ring orientation: counter-clockwise
WKT:
POLYGON ((27622.2754596 46891.8215107, 27636.0573273 46939.8845955, 27663.6210627 47036.0107652, 
  27698.0757319 47156.1684772, 28504.3149916 49967.8589396, 28869.5344853 51241.5306875, 
  28966.0075591 51577.9722813, 28986.6803606 51650.0669085, 28993.5712944 51674.098451, 
  28777.2874127 51736.1168556, 27671.8364617 52053.0998124, 27119.1109862 52211.5912908, 
  24187.2628118 53052.2852197, 13565.3210651 56098.0779785, 12123.4285203 56511.5340091, 
  11402.4822479 56718.2620244, 11234.261451 56766.4985613, 10897.8198572 56862.9716351, 
  10849.7567723 56876.7535028, 10691.2652939 56324.0280273, 9533.5884082 52286.7289018, 
  9485.3518713 52118.5081049, 9478.4609375 52094.4765625, 9526.5240223 52080.6946948, 
  9622.650192 52053.1309594, 9838.9340737 51991.1125548, 10391.6595492 51832.6210764, 
  13323.5077236 50991.9271475, 23945.4494703 47946.1343887, 26829.2345599 47119.2223275, 
  27598.2439172 46898.7124445, 27622.2754596 46891.8215107))

Simplified ConvexHull:
Geometry type: Polygon
Number of points: 5
Exterior ring orientation: counter-clockwise
WKT:
POLYGON ((27622.2754596 46891.8215107, 28993.5712944 51674.098451, 10849.7567723 56876.7535028, 
  9478.4609375 52094.4765625, 27622.2754596 46891.8215107))
```

**Comment by gchling** [comment]
Maybe my version has been modified, but I can't remember where it was modified. After fully synchronizing the code, it is found that the calculation result is correct.
Thank you very much!

**Comment by gchling** [comment]
I found the cause of the problem. It is caused by modifying the default precision in a function.
         // origion code
        private static int Signum(double x)
        {
            if (x > 0) return 1;
            if (x < 0) return -1;
            return 0;
        }
      // after edit
        private static int Signum(double x)
        {
            if (x > Zero) return 1;
            if (x < -Zero) return -1;
            return 0;
        }

**Comment by FObermaier** [comment]
> I think if change all double variables to decimal can solve the problem.

NTS internally works with double precision. Using decimal to parse the coordinates won't help

> Or can use PrecisionModel to control the Precision in this function?

Yes, that is what they are for. With ConvexHull you have to apply it to the input coordinates, though.

**Comment by gchling** [comment]
**There is a difference between "decimal" and "double" in judging whether they are equal, as in the following example, I don't know if there is any benefit.**
            double a = 0.3 - 0.2;
            double b = 0.2 - 0.1;
            Console.WriteLine(a == b);    // False
            Console.WriteLine(a == 0.1);  // False
            Console.WriteLine(b == 0.1);  // True
 
            decimal x = 0.3m - 0.2m;
            decimal y = 0.2m - 0.1m;
            Console.WriteLine(x == y);    // True
            Console.WriteLine(x == 0.1m); // True
            Console.WriteLine(y == 0.1m); // True

**Comment by FObermaier** [comment]
__But NTS does not work with decimals__
