### ISSUE TITLE
MySQL needs support to swap X/Y coordinates in `WKTWriter`

### ISSUE THREAD

**Issue by lauxjpn** [NetTopologySuite/NetTopologySuite#436]
We recently added NTS support to [Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql).

As it turns out, MySQL assumes that the first coordinate is latitude and the second coordinate is longitude, if an SRID of 4326 is used when calling functions like `ST_GeomFromWKB()` and `ST_GeomFromText()`.

To support this without parsing and changing the generated text from `Geometry.ToText()` or without reimplementing the whole `WKTWriter` class, we propose to add a method like `ForMicrosoftSqlServer()` for MySQL or just to change the `AppendCoordinate()` method signature to `protected virtual`, so we can easily override it in a derived class. Of course some option on `WKTWriter` would work as well.

**Comment by airbreather** [comment]
You mentioned `ST_GeomFromWKB()`, would this be needed for `WKBWriter` too?

**Comment by lauxjpn** [comment]
Technically yes, though we currently call only `ST_GeomFromText()` in our translation of literal values to SQL, to keep the generated SQL more readable.

So while we currently only need the textural representation, for completeness, the same mechanism should be made available for `WKBWriter` as well.

**Comment by FObermaier** [comment]
As PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1163 is closed, do you still need this feature, @lauxjpn?

**Comment by lauxjpn** [comment]
@FObermaier Thanks for following up on this one, I seem to have forgotten that this is still open here.

> do you still need this feature

No, we use a different way to accomplish the same behavior now, so we don't need this feature anymore!
