### ISSUE TITLE
GmlReader creates a GeometryFactory even when initialized with a GeometryFactoryEx

### ISSUE THREAD

**Issue by initram** [NetTopologySuite/NetTopologySuite#437]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using GmlReader to read a geometry and the geometry has an srsName set, it tries to create a GeometryFactory with the correct srid, which is fine. But when I have constructed it with a GeometryFactoryEx with `OrientationOfExteriorRing = LinearRingOrientation.CounterClockwise` then I expect the polygon to be created with a counter clockwise exterior ring, but it is not.

### Steps to Reproduce
```var factory = new GeometryFactoryEx() { OrientationOfExteriorRing = LinearRingOrientation.CounterClockwise };
var reader = new GmlReader(factory);
var geom = (Polygon)reader.Read(_xmlReader);
```

my gml looks like this:
`<gml:Polygon srsName="urn:ogc:def:crs:EPSG::25832"><gml:exterior><gml:LinearRing><gml:posList>723814.5274999999 6174591.989800001 [...]`

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.1.0
- Other NetTopologySuite packages and versions: NetTopologySuite.IO.SqlServerBytes 2.0.0
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: dotnet core 3.1
- Additional information:

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
Does the `factory` passed to the `GmlReader` constructor have SRID 25832 assigned?

**Comment by initram** [comment]
It does not have the correct srid, so it is fine that it creates a new factory. It should just create a factory of the correct kind with the correct properties set on it. But it will never create a GeometryFactoryEx even if you pass it one in the constructor.

Another example would be that you have created a custom factory class that you would like the reader to use. That is not possible either.

I think that a solution could be to have a "clone with new srid" function on the factory class. Then it could always create a new one of the correct type.

**Comment by FObermaier** [comment]
You need to create your own [NtsGeometryServices](https://www.github.com/NetTopologySuite/NetTopologySuite/tree/develop/src%2FNetTopologySuite%2FNtsGeometryServices.cs) class and you are all set.

**Comment by initram** [comment]
Yes, I could do that. But that is not really nice to do, and also I am not provided the GeometryFactory I want to clone, so I would have to set a global variable to a custom version of NtsGeometryServices that forces counter clockwise exterior rings for all factories created by this service.

Why is it that I have to create my own implementation of a central service like that to use GeometryFactoryEx (which comes with NTS) and GmlReader (which also comes with NTS) togeather? It seems like I am given pieces that do not fit nicely together.

I already have a workaround, by creating a sub-class of GmlReader that then creates the right factory. It is just not intuitive that I have to do these things when I provide a factory (of a specific type, with specific settings) to the constructor and it is not used. I had to look into the code on github to fix my issue, after spending more than an hour debugging my code.
