### ISSUE TITLE
Replacing obsolete DoubleDouble functions by operators

### ISSUE THREAD

**Issue by jany-tenaj** [NetTopologySuite/NetTopologySuite#44]
I replaced the obsolete DoubleDouble functions by operators. As I have no idea how to upload the changes I'll leave them here for someone to integrate.

**NetTopologySuite\Algorithm\CGAlgorithmsDD.cs**
 In **line 58** (inside public static int SignOfDet2x2(DoubleDouble x1, DoubleDouble y1, DoubleDouble x2, DoubleDouble y2))
replace
``` DoubleDouble det = x1.Multiply(y2).Subtract(y1.Multiply(x2)); ```
by
```DoubleDouble det = x1 * y2 - y1 * x2; ```

**NetTopologySuite\Mathematics\DD.cs**
In **line 1174** (inside public static DoubleDouble Parse(String str)) 
replace 
```   val2 = val.Multiply(scale); ```
by 
```  val2 = val*scale;```

**NetTopologySuite\Triangulate\QuadEdge\TrianglePredicate.cs**
In **line 142 - 147** (inside public static bool IsInCircleDDSlow(Coordinate a, Coordinate b, Coordinate c, Coordinate p))
replace 
```
 DoubleDouble aTerm = (ax.Multiply(ax).Add(ay.Multiply(ay))).Multiply(TriAreaDDSlow(bx, by, cx, cy, px, py));
 DoubleDouble bTerm = (bx.Multiply(bx).Add(by.Multiply(by))).Multiply(TriAreaDDSlow(ax, ay, cx, cy, px, py));
 DoubleDouble cTerm = (cx.Multiply(cx).Add(cy.Multiply(cy))).Multiply(TriAreaDDSlow(ax, ay, bx, by, px, py));
 DoubleDouble pTerm = (px.Multiply(px).Add(py.Multiply(py))).Multiply(TriAreaDDSlow(ax, ay, bx, by, cx, cy));

 DoubleDouble sum = aTerm.Subtract(bTerm).Add(cTerm).Subtract(pTerm);
```
by
```
 DoubleDouble aTerm = (ax * ax + ay * ay) * TriAreaDDSlow(bx, by, cx, cy, px, py);
 DoubleDouble bTerm = (bx * bx + by * by) * TriAreaDDSlow(ax, ay, cx, cy, px, py);
 DoubleDouble cTerm = (cx * cx + cy * cy) * TriAreaDDSlow(ax, ay, bx, by, px, py);
 DoubleDouble pTerm = (px * px + py * py) * TriAreaDDSlow(ax, ay, bx, by, cx, cy);

 DoubleDouble sum = aTerm - bTerm + cTerm - pTerm;
```

In **line 170** inside (private static DoubleDouble TriAreaDDSlow(DoubleDouble ax, DoubleDouble ay, DoubleDouble bx, DoubleDouble by, DoubleDouble cx, DoubleDouble cy))
replace
 ``` return (bx.Subtract(ax).Multiply(cy.Subtract(ay)).Subtract(by.Subtract(ay).Multiply(cx.Subtract(ax))));```
        by
``` return (bx - ax) * (cy - ay) - (by - ay) * (cx - ax);```

**Comment by DGuidi** [comment]
Why you marked old code as "obsolete"? I haven't checked all code you posted, but forst methods look the same as in [jts trunk](http://goo.gl/o6w34O).
BTW you can use [Pull Requests](https://help.github.com/articles/using-pull-requests/) to make changes to repository.

**Comment by FObermaier** [comment]
@DGuidi 
I have added operators on DoubleDouble (+, -, *, /) that are not in JTS. I don't know if there are operators in Java at all. When I did this, I marked the `Add`, `Subtract`, `Multiply` and `Divide` functions as `Obsolete`.

**Comment by DGuidi** [comment]
Ok now it's clear.
Anyway, I'd love to have a Close match betwee  jts and nts code 

----- Messaggio originale -----
Da: "Felix Obermaier" <notifications@github.com>
Inviato: ‎11/‎08/‎2015 15:13
A: "NetTopologySuite/NetTopologySuite" <NetTopologySuite@noreply.github.com>
Cc: "Diego Guidi" <diegoguidi@gmail.com>
Oggetto: Re: [NetTopologySuite] Replacing obsolete DoubleDouble functions byoperators (#44)

@DGuidi 
I have added operators on DoubleDouble (+, -, *, /) that are not in JTS. I don't know if there are operators in Java at all. When I did this, I marked the Add, Subtract, Multiply and Divide functions as Obsolete.

**Comment by FObermaier** [comment]
@DGuidi: It improves the readability a lot :)

**Comment by DGuidi** [comment]
Actually, most of my nightmares with NTS debugging are related to operator overloads (==  != actually) 😃 

----- Messaggio originale -----
Da: "Felix Obermaier" <notifications@github.com>
Inviato: ‎12/‎08/‎2015 08:41
A: "NetTopologySuite/NetTopologySuite" <NetTopologySuite@noreply.github.com>
Cc: "Diego Guidi" <diegoguidi@gmail.com>
Oggetto: Re: [NetTopologySuite] Replacing obsolete DoubleDouble functions byoperators (#44)

@DGuidi: It improves the readability a lot :)
