### ISSUE TITLE
How to determine that a polygon is closed

### ISSUE THREAD

**Issue by mammadkoma** [NetTopologySuite/NetTopologySuite#442]
Hi
I create a Polygon by CreatePolygon() method of GeometryFactory Class.
How can we determine if Coordinates numbers for X and Y are correct and that Polygon is a **closed** Polygon for return a good error to end user?

**Comment by FObermaier** [comment]
When you create a polygon using `GeometryFactory` the minimal requirement -that all rings are closed- is tested automatically. To see that it is valid call `Geometry.IsValid`, or use `NetTopologySuite.Operation.Valid.IsValidOp` class.

**Comment by mammadkoma** [comment]
Thank you
I used this code : 
                var fact = NtsGeometryServices.Instance.CreateGeometryFactory(srid: 4326);
                Polygon polygon;
                try
                {
                    polygon = fact.CreatePolygon(coordinates.ToArray());
                }
                catch (Exception)
                {
                    throw new CustomException(nameof(deliveryZone.Name), StoreConstants.PolyonNotValid);
                }
