### ISSUE TITLE
Create a circle area

### ISSUE THREAD

**Issue by mammadkoma** [NetTopologySuite/NetTopologySuite#443]
Hi
How we can create a **circle** area for save in a **geography** field in sql server?

**Comment by FObermaier** [comment]
For a puntal geometry an approximation is `Geometry.Buffer(distance in unit of coordinates)`.

**Comment by mammadkoma** [comment]
I can create a polygon border by this code line : 

                polygon = fact.CreatePolygon(coordinates.ToArray());

But we  don't know which code line we can create a circle border.
I think I need three number for lat and long of center and a number for radius.

**Comment by DGuidi** [comment]
You can create a point with x and y coordinate using
GeometryFactory.Default.CreatePoint and then call the Buffer method on the
returned geometry

>

**Comment by mammadkoma** [comment]
Thank you
There is an error : 
![image](https://user-images.githubusercontent.com/17564001/97103900-c76ad300-16c4-11eb-8f20-d2eb5bcea1bc.png)

**Comment by DGuidi** [comment]
Remove .Default because you are using an instance and not the static
property, but the result should be the same.

>

**Comment by mammadkoma** [comment]
Thank you

I used this code : 

var coordinate = new Coordinate((double)deliveryZone.CenterLongtitude, (double)deliveryZone.CenterLatitude);
var circle = geometryFactory.CreatePoint(coordinate).Buffer((double)deliveryZone.Radius);
deliveryZone.Border = circle;

But I get error on SaveChanges() : **When writing a SQL Server geography value, the shell of a polygon must be oriented counter-clockwise.**

var circle fills : {POLYGON ((2035.7451028 51.3659442, 1997.3156636064609 -338.81469983225651, 1883.5041678225734 -714.00092053017966, 1698.6843274050905 -1059.7745218392042, 1449.9586651730951 -1362.847618173095, 1146.8855688392046 -1611.5732804050904, 801.11196753017975 -1796.3931208225733, 425.92574683225666 -1910.2046166064608, 35.745102800000119 -1948.6340558, -354.43554123225641 -1910.2046166064608, -729.62176193017945 -1796.3931208225733, -1075.3953632392038 -1611.5732804050906, -1378.4684595730948 -1362.847618173095, -1627.1941218050906 -1059.7745218392042, -1812.0139622225736 -714.000920530179, -1925.8254580064611 -338.81469983225543, -1964.2548972 51.365944200001536, -1925.8254580064604 441.54658823225844, -1812.0139622225724 816.73280893018182, -1627.1941218050888 1162.5064102392068, -1378.4684595730926 1465.5795065730974, -1075.3953632392015 1714.3051688050925, -729.62176193017569 1899.125009222575, -354.43554123225215 2012.9365050064619, 35.745102800004958 2051.3659442, 425.92574683226184 2012.9365050064598, 801.111967530185 1899.1250092225714, 1146.8855688392098 1714.3051688050871, 1449.9586651731 1465.5795065730904, 1698.6843274050946 1162.5064102391987, 1883.5041678225764 816.7328089301725, 1997.3156636064625 441.54658823224872, 2035.7451028 51.3659442))}

"radius": 2000,
"centerLatitude": 35.7451028,
"centerLongtitude": 51.3659442,

**Comment by FObermaier** [comment]
No, the problem is that your radius is not in the unit of the coordinates, they appear to be lat/lon in degrees and your radius probably meter. That does not match.

For conversion see [Aviation Formulary V1.46](http://edwilliams.org/avform.htm)

**Comment by mammadkoma** [comment]
When I set radius between 1 and 50 it worked.
How we can set radius in kilometers?

**Comment by FObermaier** [comment]
You need to convert your kilometer value into degree, there is no other way.

**Comment by mammadkoma** [comment]
Thank you but how to convert?
Must we use **RadiusDegree*100** formula?

**Comment by FObermaier** [comment]
> For conversion see [Aviation Formulary V1.46](http://edwilliams.org/avform.htm)

**Comment by mammadkoma** [comment]
We can't find the meter formula in "Aviation Formulary V1.46" link.
Could you give us a C# method for convert from meter to degree?

**Comment by mammadkoma** [comment]
`public double MeterToDegree(double meters, double latitude)
{
    return meters / (111.32 * 1000 * Math.Cos(latitude * (Math.PI / 180)));
}`

**Comment by DGuidi** [comment]
maybe this can help? https://stackoverflow.com/a/40471701
