### ISSUE TITLE
Sample For ASP Core - taxi/truck dispatch

### ISSUE THREAD

**Issue by papyr** [NetTopologySuite/NetTopologySuite#445]
Hello I am trying to experiment with this in an ASP core situation for an Uber taxi dispatch like situation, do you have a sample on how to draw this in an ASP view

**Comment by DGuidi** [comment]
NTS does not offer drawing API so probably you shoud check libraries like https://github.com/SharpMap/SharpMap or client libraries like https://leafletjs.com/
