### ISSUE TITLE
non-noded line intersection on polygon after upgrading from NTS 2.0.0 to 2.1.0

### ISSUE THREAD

**Issue by freakmoder** [NetTopologySuite/NetTopologySuite#448]
Hi,

We upgraded our project to NTS 2.1 and with the upgrade some unit tests started to fail. After some investigation it turned out that a non-noded line intersection on some polygons are thrown. Here is one Example:

`POLYGON ((142.66136360168457 -10.993280410766602, 142.6657428741455 -10.966495513916016, 142.59590339660645 -10.872663497924805, 142.5610523223877 -10.875774383544922, 142.51317024230957 -10.947561264038086, 142.5190601348877 -10.898311614990234, 142.60376167297363 -10.756645202636719, 142.5304126739502 -10.697803497314453, 142.44224739074707 -10.713384628295898, 142.35716438293457 -10.88302993774414, 142.28868293762207 -10.921380996704102, 142.16691780090332 -10.932344436645508, 142.128511428833 -10.983280181884766, 142.15887641906738 -11.15578842163086, 142.15144538879395 -11.131696701049805, 142.116792678833 -11.377456665039062, 142.0283908843994 -11.659732818603516, 142.0661334991455 -11.603767395019531, 142.02714729309082 -11.663700103759766, 142.0283908843994 -11.659732818603516, 142.01837348937988 -11.674585342407227, 142.00432014465332 -11.752458572387695, 142.09683418273926 -11.740201950073242, 141.9779224395752 -11.777053833007812, 141.9400806427002 -11.973823547363281, 142.0039234161377 -12.015653610229492, 142.05035591125488 -11.98192024230957, 142.09749031066895 -11.979232788085938, 142.1499195098877 -12.019742965698242, 142.10478401184082 -11.986074447631836, 142.0634479522705 -11.985034942626953, 142.02054023742676 -12.07464599609375, 141.95768928527832 -12.044544219970703, 141.90391731262207 -12.180862426757812, 141.92463874816895 -12.117269515991211, 141.91771125793457 -12.038642883300781, 141.90657234191895 -11.95889663696289, 141.88226509094238 -11.956319808959961, 141.81085395812988 -12.048810958862305, 141.73405647277832 -12.220352172851562, 141.77916145324707 -12.220952987670898, 141.76838874816895 -12.241588592529297, 141.71824836730957 -12.232194900512695, 141.7050952911377 -12.2559814453125, 141.59260749816895 -12.556943893432617, 141.6262378692627 -12.582029342651367, 141.69136238098145 -12.559276580810547, 141.66026496887207 -12.527973175048828, 141.65928840637207 -12.455286026000977, 141.72285652160645 -12.385147094726562, 141.66775703430176 -12.462591171264648, 141.69432258605957 -12.514860153198242, 141.75908088684082 -12.53994369506836, 141.81872749328613 -12.599784851074219, 142.04158210754395 -12.551605224609375, 141.80691719055176 -12.677164077758789, 141.7424030303955 -12.851753234863281, 141.62906074523926 -12.924980163574219, 141.5859546661377 -12.99449348449707, 141.63492012023926 -13.160924911499023, 141.69680976867676 -13.256412506103516, 141.6618824005127 -13.34228515625, 141.7304859161377 -13.370710372924805, 141.72697639465332 -13.405460357666016, 141.69192695617676 -13.457027435302734, 141.69116401672363 -13.385467529296875, 141.63214302062988 -13.369537353515625, 141.57676887512207 -13.47797966003418, 141.57388496398926 -13.571128845214844, 141.53775215148926 -13.577106475830078, 141.54997444152832 -13.501398086547852, 141.50714302062988 -13.639608383178711, 141.46829414367676 -13.923561096191406, 141.57122993469238 -14.051200866699219, 141.60161018371582 -14.124334335327148, 141.59622383117676 -14.266647338867188, 141.52629280090332 -14.484729766845703, 141.58935737609863 -14.850801467895508, 141.66874885559082 -15.031288146972656, 141.61853218078613 -15.21466064453125, 141.4811725616455 -15.498619079589844, 141.4367389678955 -15.655891418457031, 141.3958911895752 -15.904661178588867, 141.43286323547363 -16.06666374206543, 141.30061531066895 -16.39362335205078, 141.26695442199707 -16.563396453857422, 141.20733833312988 -16.68914222717285, 141.0944538116455 -16.80809211730957, 140.99005317687988 -16.979839324951172, 140.975923538208 -16.972637176513672, 140.95804023742676 -17.000303268432617, 140.94725227355957 -17.14891242980957, 140.83040046691895 -17.464258193969727, 140.73637580871582 -17.516502380371094, 140.71394538879395 -17.5093994140625, 140.53045845031738 -17.631288528442383, 140.3952808380127 -17.677204132080078, 140.11596870422363 -17.724695205688477, 140.00248908996582 -17.71539878845215, 139.9314136505127 -17.62706184387207, 139.64468574523926 -17.539186477661133, 139.4679126739502 -17.394058227539062, 139.308687210083 -17.363550186157227, 139.23938179016113 -17.32324981689453, 139.16484260559082 -17.196853637695312, 139.14082527160645 -17.02507972717285, 139.04826545715332 -16.950687408447266, 139.0444507598877 -16.91213035583496, 138.75799751281738 -16.836606979370117, 138.6355152130127 -16.771074295043945, 138.53672981262207 -16.78618049621582, 138.33081245422363 -16.755847930908203, 138.17741584777832 -16.689016342163086, 137.99603462219238 -16.544639587402344, 137.99890327453613 -26.002355575561523, 141.00096321105957 -26.005739212036133, 140.99971199035645 -29.00675392150879, 148.96704292297363 -29.002714157104492, 149.03213691711426 -28.962600708007812, 149.09440803527832 -28.840932846069336, 149.26133918762207 -28.741111755371094, 149.39273262023926 -28.69658660888672, 149.4562702178955 -28.59548568725586, 149.5088062286377 -28.577022552490234, 149.59086799621582 -28.577308654785156, 149.66925239562988 -28.622264862060547, 149.97996711730957 -28.61240577697754, 150.00000190734863 -28.592187881469727, 150.22517585754395 -28.569965362548828, 150.44769477844238 -28.66815948486328, 150.76538276672363 -28.640830993652344, 151.00642585754395 -28.743303298950195, 151.09004402160645 -28.840837478637695, 151.273042678833 -28.94294548034668, 151.28009223937988 -29.107378005981445, 151.31413459777832 -29.170124053955078, 151.39378547668457 -29.181011199951172, 151.50340461730957 -29.075820922851562, 151.49475288391113 -29.034801483154297, 151.54609870910645 -28.958349227905273, 151.59509468078613 -28.930747985839844, 151.72447395324707 -28.875198364257812, 151.74273872375488 -28.925485610961914, 151.82538032531738 -28.974021911621094, 152.00445747375488 -28.915128707885742, 152.03909492492676 -28.867401123046875, 152.04016304016113 -28.75537109375, 151.9514331817627 -28.559165954589844, 151.95865058898926 -28.5142765045166, 152.20573616027832 -28.43621826171875, 152.35415840148926 -28.36402130126953, 152.46893501281738 -28.264156341552734, 152.50950813293457 -28.255277633666992, 152.59558296203613 -28.324298858642578, 152.74727058410645 -28.362632751464844, 152.93101692199707 -28.337860107421875, 153.10772895812988 -28.357786178588867, 153.19270515441895 -28.253158569335938, 153.2826099395752 -28.233367919921875, 153.37185859680176 -28.247953414916992, 153.48298835754395 -28.160099029541016, 153.5168628692627 -28.164453506469727, 153.45320320129395 -28.087562561035156, 153.419038772583 -28.003215789794922, 153.35623359680176 -27.71547508239746, 153.299165725708 -27.568105697631836, 153.14935493469238 -27.4071044921875, 153.15735054016113 -27.372745513916016, 153.06073188781738 -27.265356063842773, 153.0705738067627 -27.248844146728516, 153.07873725891113 -27.266794204711914, 153.110933303833 -27.255863189697266, 153.11474800109863 -27.197511672973633, 153.07458686828613 -27.207956314086914, 153.03201484680176 -27.18460464477539, 153.02862739562988 -27.133811950683594, 153.09582710266113 -27.100486755371094, 153.09659004211426 -27.032936096191406, 153.0509204864502 -26.94887351989746, 153.1184253692627 -26.883190155029297, 153.14109992980957 -26.693008422851562, 153.097261428833 -26.65753936767578, 153.11674690246582 -26.40894317626953, 153.05891609191895 -26.447612762451172, 153.03875923156738 -26.370935440063477, 153.17883491516113 -25.95099639892578, 153.11564826965332 -25.929542541503906, 153.07061958312988 -25.813796997070312, 152.97342109680176 -25.816204071044922, 152.9875202178955 -25.774065017700195, 152.925142288208 -25.717077255249023, 152.87649726867676 -25.616262435913086, 152.899995803833 -25.489835739135742, 152.95671272277832 -25.4374942779541, 152.93445014953613 -25.43487548828125, 152.84424018859863 -25.50418472290039, 152.83108711242676 -25.489843368530273, 152.87742805480957 -25.44278907775879, 152.86670112609863 -25.41497230529785, 152.91690254211426 -25.42318344116211, 152.90690803527832 -25.286418914794922, 152.73016548156738 -25.268280029296875, 152.66311836242676 -25.24720573425293, 152.61664009094238 -25.184450149536133, 152.5719165802002 -25.18659019470215, 152.57083320617676 -25.168752670288086, 152.61949348449707 -25.17528533935547, 152.6322956085205 -25.15218162536621, 152.5590534210205 -25.099334716796875, 152.48906135559082 -24.976242065429688, 152.4708423614502 -24.819759368896484, 152.41705513000488 -24.761486053466797, 152.37889289855957 -24.77491569519043, 152.37883186340332 -24.749080657958984, 152.30696296691895 -24.73184585571289, 152.02879524230957 -24.536712646484375, 152.0384693145752 -24.499183654785156, 151.95561408996582 -24.285991668701172, 151.77791023254395 -24.092992782592773, 151.70518684387207 -24.06122589111328, 151.73034858703613 -24.025074005126953, 151.61096382141113 -23.98310089111328, 151.60794258117676 -24.009380340576172, 151.63817024230957 -24.00935173034668, 151.657075881958 -24.08967399597168, 151.402193069458 -24, 151.43390083312988 -24.001998901367188, 151.32449531555176 -23.884729385375977, 151.29791450500488 -23.891372680664062, 151.27081489562988 -23.840898513793945, 151.17814826965332 -23.85654640197754, 151.11761665344238 -23.671300888061523, 151.00291633605957 -23.599594116210938, 151.00627326965332 -23.571205139160156, 150.97639656066895 -23.56098747253418, 150.85840034484863 -23.626802444458008, 150.8158130645752 -23.616762161254883, 150.85667610168457 -23.61529541015625, 150.86323738098145 -23.578941345214844, 150.82747077941895 -23.56513786315918, 150.80121040344238 -23.57033920288086, 150.78306770324707 -23.62228775024414, 150.71495246887207 -23.607337951660156, 150.68257331848145 -23.57728385925293, 150.7131519317627 -23.543373107910156, 150.7000904083252 -23.51201820373535, 150.63041877746582 -23.49172019958496, 150.44583320617676 -23.347429275512695, 150.4233112335205 -23.257848739624023, 150.49270820617676 -23.361330032348633, 150.65495491027832 -23.488779067993164, 150.68646430969238 -23.458253860473633, 150.70103645324707 -23.483348846435547, 150.7666187286377 -23.507665634155273, 150.84861946105957 -23.512094497680664, 150.87083625793457 -23.48706817626953, 150.808198928833 -23.41097640991211, 150.7656421661377 -23.308414459228516, 150.79059028625488 -23.314437866210938, 150.82930183410645 -23.263580322265625, 150.74865913391113 -23.134960174560547, 150.77063179016113 -23.019893646240234, 150.72618293762207 -22.913129806518555, 150.78624153137207 -22.93668556213379, 150.81115913391113 -22.680850982666016, 150.78154182434082 -22.53046226501465, 150.75395393371582 -22.526212692260742, 150.7234058380127 -22.633697509765625, 150.7147388458252 -22.636150360107422, 150.70988655090332 -22.631881713867188, 150.7234058380127 -22.633697509765625, 150.72137641906738 -22.52145767211914, 150.6440601348877 -22.349496841430664, 150.56399726867676 -22.321792602539062, 150.53946113586426 -22.355030059814453, 150.53082466125488 -22.45318031311035, 150.5915699005127 -22.584779739379883, 150.44645881652832 -22.524356842041016, 150.17662239074707 -22.365720748901367, 150.18498420715332 -22.324966430664062, 150.03778266906738 -22.13089370727539, 149.953462600708 -22.19036865234375, 149.91034126281738 -22.349912643432617, 150.03064155578613 -22.636486053466797, 150.0584888458252 -22.6580810546875, 150.03572273254395 -22.658206939697266, 149.9599323272705 -22.54051399230957, 149.88560676574707 -22.494733810424805, 149.8072681427002 -22.385852813720703, 149.78470039367676 -22.430299758911133, 149.67442512512207 -22.488723754882812, 149.70024299621582 -22.45431137084961, 149.659273147583 -22.37042999267578, 149.57995796203613 -22.4089412689209, 149.5824909210205 -22.36903190612793, 149.65625190734863 -22.35610008239746, 149.56048774719238 -22.305950164794922, 149.59829902648926 -22.26581382751465, 149.48210334777832 -21.992053985595703, 149.43101692199707 -21.802326202392578, 149.43681526184082 -21.64406967163086, 149.48399543762207 -21.575498580932617, 149.48156929016113 -21.535419464111328, 149.38150215148926 -21.522228240966797, 149.3335132598877 -21.479450225830078, 149.28694343566895 -21.479280471801758, 149.31158638000488 -21.361526489257812, 149.285249710083 -21.28141212463379, 149.2519702911377 -21.249155044555664, 149.23335456848145 -21.26044273376465, 149.18969917297363 -21.19536590576172, 149.20414924621582 -21.079832077026367, 149.1473560333252 -21.005903244018555, 149.0549030303955 -20.988142013549805, 149.01281929016113 -21.001340866088867, 149.00906562805176 -20.940034866333008, 149.03247261047363 -20.929288864135742, 148.83882331848145 -20.873958587646484, 148.7980670928955 -20.81652069091797, 148.83215522766113 -20.78924560546875, 148.70842170715332 -20.678796768188477, 148.65655708312988 -20.586673736572266, 148.70575141906738 -20.483245849609375, 148.6947956085205 -20.449411392211914, 148.77989387512207 -20.44436264038086, 148.85252571105957 -20.515949249267578, 148.92703437805176 -20.535564422607422, 148.747407913208 -20.2624568939209, 148.67373847961426 -20.277301788330078, 148.57812690734863 -20.19980239868164, 148.55284309387207 -20.119565963745117, 148.46483039855957 -20.067432403564453, 148.4404468536377 -20.071334838867188, 148.43962287902832 -20.106054306030273, 148.474702835083 -20.126203536987305, 148.43345832824707 -20.165903091430664, 148.33793830871582 -20.15362548828125, 148.2271900177002 -20.051925659179688, 148.25613594055176 -19.984140396118164, 148.18329048156738 -19.949331283569336, 148.11088752746582 -19.946725845336914, 148.07481575012207 -19.887880325317383, 147.99136543273926 -19.926652908325195, 147.92149543762207 -19.910688400268555, 147.86340522766113 -19.855661392211914, 147.8488483428955 -19.738500595092773, 147.821382522583 -19.70989418029785, 147.7511157989502 -19.70699691772461, 147.7441120147705 -19.764522552490234, 147.78994941711426 -19.839757919311523, 147.6564655303955 -19.823110580444336, 147.465913772583 -19.642318725585938, 147.5855884552002 -19.63603973388672, 147.55865669250488 -19.60420799255371, 147.5544147491455 -19.587993621826172, 147.57286262512207 -19.596139907836914, 147.55308723449707 -19.541257858276367, 147.45396614074707 -19.393871307373047, 147.41958808898926 -19.425016403198242, 147.24547004699707 -19.429027557373047, 147.14007759094238 -19.40592384338379, 147.05613899230957 -19.3057804107666, 147.05854988098145 -19.272808074951172, 147.00616645812988 -19.245206832885742, 146.95640754699707 -19.298297882080078, 146.88958930969238 -19.307170867919922, 146.71829414367676 -19.19024085998535, 146.63000679016113 -19.17377471923828, 146.4526081085205 -19.07860565185547, 146.28978157043457 -18.90056610107422, 146.28344917297363 -18.76493263244629, 146.33296394348145 -18.639822006225586, 146.33410835266113 -18.533506393432617, 146.21782112121582 -18.488264083862305, 146.0168170928955 -18.245532989501953, 146.0074634552002 -18.132326126098633, 146.0937213897705 -17.969255447387695, 146.10566902160645 -17.718564987182617, 146.14639472961426 -17.65280532836914, 146.06120491027832 -17.512042999267578, 146.079439163208 -17.495817184448242, 146.07397651672363 -17.395912170410156, 146.01225471496582 -17.333538055419922, 145.95036506652832 -17.135513305664062, 145.890474319458 -17.063648223876953, 145.90381050109863 -16.976720809936523, 145.95947456359863 -16.895814895629883, 145.9194049835205 -16.863779067993164, 145.88957405090332 -16.905073165893555, 145.78050422668457 -16.937103271484375, 145.7705249786377 -16.881494522094727, 145.7201862335205 -16.802045822143555, 145.4113483428955 -16.458541870117188, 145.41862678527832 -16.343324661254883, 145.45359992980957 -16.27872657775879, 145.4799518585205 -16.270788192749023, 145.47618293762207 -16.078857421875, 145.43058967590332 -15.97425651550293, 145.35978889465332 -15.921266555786133, 145.360689163208 -15.715827941894531, 145.26355171203613 -15.460588455200195, 145.31761360168457 -15.261585235595703, 145.264497756958 -15.254119873046875, 145.2380542755127 -15.17424201965332, 145.24046516418457 -15.13055419921875, 145.35196113586426 -14.982511520385742, 145.35209846496582 -14.954710006713867, 145.27649116516113 -14.941024780273438, 145.18359565734863 -14.842182159423828, 145.02824592590332 -14.7952880859375, 144.90349006652832 -14.610294342041016, 144.83426094055176 -14.611061096191406, 144.68284797668457 -14.551202774047852, 144.61841011047363 -14.4691162109375, 144.59605598449707 -14.262569427490234, 144.53100776672363 -14.184724807739258, 144.4913501739502 -14.18117904663086, 144.4494342803955 -14.249032974243164, 144.34131050109863 -14.307323455810547, 144.28331184387207 -14.303886413574219, 144.25020027160645 -14.267864227294922, 144.19830513000488 -14.262247085571289, 144.20233345031738 -14.321256637573242, 144.1681842803955 -14.379022598266602, 144.08711433410645 -14.450141906738281, 143.96919441223145 -14.484729766845703, 143.94981575012207 -14.517242431640625, 143.78450202941895 -14.401275634765625, 143.72065925598145 -14.240779876708984, 143.67703437805176 -14.009490966796875, 143.63354682922363 -13.98133659362793, 143.5324420928955 -13.749792098999023, 143.6004810333252 -13.427850723266602, 143.52041816711426 -13.258735656738281, 143.50871467590332 -13.142280578613281, 143.513521194458 -12.964641571044922, 143.54605293273926 -12.84459114074707, 143.45147895812988 -12.84860610961914, 143.35338020324707 -12.888519287109375, 143.3671588897705 -12.78022575378418, 143.42859077453613 -12.611959457397461, 143.30867195129395 -12.551843643188477, 143.27653694152832 -12.5103759765625, 143.26870918273926 -12.393604278564453, 143.08000373840332 -12.337688446044922, 143.09253120422363 -12.15900993347168, 143.192476272583 -11.987096786499023, 143.1015796661377 -11.895198822021484, 142.96267890930176 -11.925849914550781, 142.85722541809082 -11.849958419799805, 142.85928535461426 -11.641721725463867, 142.82676887512207 -11.467226028442383, 142.86845588684082 -11.38371467590332, 142.81802558898926 -11.29155158996582, 142.7877368927002 -11.080459594726562, 142.71878242492676 -10.966400146484375, 142.66136360168457 -10.993280410766602, 142.65371894836426 -11.04000473022461, 142.65997505187988 -10.99393081665039, 142.66136360168457 -10.993280410766602))`

The Exception is thrown for Point `POINT (142.66136360168457 -10.993280410766602)` which is exactly the start and end point of the polygon. Both points have exactly the same location and this is why I don't really know why this should be a non-noded line intersection now. 

The code that throws the exception is here: 
`private Geometry NodeLines(Geometry lines)
            {
                Geometry point = GetPointAtIndex(lines, 0);
                if (point is null)
                {
                    return null;
                }
                return lines.Union(point);
            }`

Exception is thrown in the Union call. 

The Geometry looks like this in this area: 
![image](https://user-images.githubusercontent.com/19290858/98934704-cdddb500-24e2-11eb-9838-1bdd6b6e0414.png)

Has anyone an idea what the problem could be?

Frank

**Comment by FObermaier** [comment]
The given polygon is not valid. Using `NetTopologySuite.Operation.Valid.IsValidOp` reveals
```
Ring Self-intersection at or near point (142.028, -11.66, NaN)
```
You can fix that by using the _Buffer0_-Trick:
```C#
polygon = polygon.Buffer(0);
```
