### ISSUE TITLE
ound non-noded intersection between 

### ISSUE THREAD

**Issue by bouyeijiang** [NetTopologySuite/NetTopologySuite#454]
wkt sample:
POLYGON ((35464934.126 2898634.6712,35464934.126 2898624.6712,35464929.126 2898624.6712,35464929.126 2898619.6712,35464924.126 2898619.6712,35464924.126 2898614.6712,35464914.126 2898614.6712,35464914.126 2898609.6712,35464919.126 2898609.6712,35464919.126 2898604.6712,35464934.126 2898604.6712,35464934.126 2898594.6712,35464934.126 2898590.7363,35464933.9041 2898589.6712,35464929.126 2898589.6712,35464929.126 2898584.6712,35464924.126 2898584.6712,35464924.126 2898579.6712,35464919.126 2898579.6712,35464919.126 2898574.6712,35464914.126 2898574.6712,35464914.126 2898569.6712,35464909.126 2898569.6712,35464909.126 2898564.6712,35464904.126 2898564.6712,35464904.126 2898554.6712,35464924.126 2898554.6712,35464924.126 2898545.0065,35464923.8999 2898544.8256,35464923.8178 2898544.6712,35464919.126 2898544.6712,35464919.126 2898535.8507,35464915.839 2898529.6712,35464914.126 2898529.6712,35464914.126 2898526.4507,35464913.978 2898526.1725,35464913.2724 2898524.6712,35464909.126 2898524.6712,35464909.126 2898519.6712,35464904.126 2898519.6712,35464904.126 2898514.6712,35464904.126 2898509.6712,35464899.126 2898509.6712,35464899.126 2898504.6712,35464894.126 2898504.6712,35464894.126 2898499.6712,35464889.126 2898499.6712,35464889.126 2898503.7631,35464892.1711 2898505.8259,35464895.5577 2898516.8327,35464902.3312 2898515.5626,35464906.3527 2898525.7227,35464900.1259 2898530.1367,35464901.9824 2898533.177,35464893.8279 2898538.0283,35464895.9446 2898544.1138,35464888.2717 2898564.7513,35464878.4821 2898572.9534,35464876.9311 2898571.6544,35464871.2159 2898564.6695,35464868.0411 2898554.2977,35464870.5809 2898542.8677,35464865.7128 2898536.3061,35464858.0927 2898539.6927,35464855.9399 2898541.149,35464852.9766 2898542.0804,35464848.6699 2898542.8384,35464847.4309 2898542.9235,35464839.6839 2898544.3205,35464834.126 2898545.5451,35464834.126 2898549.6712,35464827.845 2898549.6712,35464824.1898 2898555.4965,35464820.7608 2898562.8626,35464817.7128 2898571.2446,35464816.0618 2898576.7056,35464814.3262 2898587.1408,35464814.5802 2898591.3318,35464814.6846 2898594.6712,35464819.126 2898594.6712,35464819.126 2898599.6712,35464829.126 2898599.6712,35464829.126 2898594.6712,35464839.126 2898594.6712,35464839.126 2898589.6712,35464849.126 2898589.6712,35464849.126 2898619.6712,35464844.126 2898619.6712,35464844.126 2898634.6712,35464834.126 2898634.6712,35464834.126 2898629.6712,35464829.126 2898629.6712,35464829.126 2898624.6712,35464824.126 2898624.6712,35464824.126 2898619.6712,35464814.126 2898619.6712,35464814.126 2898624.6712,35464809.3598 2898624.6712,35464806.8331 2898627.7809,35464803.0231 2898632.4799,35464798.3241 2898637.8139,35464789.8525 2898645.4545,35464785.5211 2898649.1002,35464770.2895 2898653.0072,35464764.1935 2898654.7852,35464754.2875 2898656.0552,35464749.5885 2898656.4362,35464745.2705 2898655.9282,35464742.7305 2898653.0072,35464742.0955 2898648.0542,35464744.8895 2898641.3231,35464749.126 2898636.6521,35464749.126 2898634.6712,35464739.126 2898634.6712,35464739.126 2898639.6712,35464714.126 2898639.6712,35464714.126 2898619.6712,35464709.126 2898619.6712,35464709.126 2898614.6712,35464699.126 2898614.6712,35464699.126 2898619.6712,35464674.126 2898619.6712,35464674.126 2898624.6712,35464644.126 2898624.6712,35464644.126 2898614.6712,35464649.126 2898614.6712,35464649.126 2898604.6712,35464654.126 2898604.6712,35464654.126 2898599.6712,35464669.126 2898599.6712,35464669.126 2898594.6712,35464679.126 2898594.6712,35464679.126 2898599.6712,35464704.126 2898599.6712,35464704.126 2898604.6712,35464744.126 2898604.6712,35464744.126 2898609.6712,35464769.126 2898609.6712,35464769.126 2898614.6712,35464779.3633 2898614.6712,35464781.5925 2898610.7161,35464783.1165 2898604.2391,35464784.6793 2898599.6712,35464734.126 2898599.6712,35464734.126 2898594.6712,35464724.126 2898594.6712,35464724.126 2898589.6712,35464674.126 2898589.6712,35464674.126 2898584.6712,35464669.126 2898584.6712,35464669.126 2898579.6712,35464664.126 2898579.6712,35464664.126 2898559.6712,35464669.126 2898559.6712,35464669.126 2898554.6712,35464674.126 2898554.6712,35464674.126 2898549.6712,35464679.126 2898549.6712,35464679.126 2898544.6712,35464674.126 2898544.6712,35464674.126 2898534.6712,35464669.126 2898534.6712,35464669.126 2898529.6712,35464664.126 2898529.6712,35464664.126 2898534.6712,35464654.126 2898534.6712,35464654.126 2898539.6712,35464644.126 2898539.6712,35464644.126 2898534.6712,35464624.126 2898534.6712,35464624.126 2898529.6712,35464629.126 2898529.6712,35464629.126 2898509.6712,35464634.126 2898509.6712,35464634.126 2898459.6712,35464639.126 2898459.6712,35464639.126 2898454.6712,35464644.126 2898454.6712,35464644.126 2898449.6712,35464639.126 2898449.6712,35464639.126 2898429.6712,35464644.126 2898429.6712,35464644.126 2898424.6712,35464649.126 2898424.6712,35464649.126 2898414.6712,35464654.126 2898414.6712,35464654.126 2898409.6712,35464659.126 2898409.6712,35464659.126 2898404.6712,35464664.126 2898404.6712,35464664.126 2898399.6712,35464689.126 2898399.6712,35464689.126 2898394.6712,35464709.126 2898394.6712,35464709.126 2898389.6712,35464717.5416 2898389.6712,35464719.126 2898387.9107,35464719.126 2898384.6712,35464722.0414 2898384.6712,35464723.0585 2898383.541,35464724.126 2898381.3577,35464724.126 2898369.2994,35464721.4106 2898369.1213,35464718.5663 2898370.4443,35464715.9203 2898372.6933,35464713.4729 2898376.1329,35464710.4303 2898379.2417,35464706.4339 2898380.9891,35464697.3058 2898383.1057,35464683.1506 2898384.9579,35464669.5245 2898386.6775,35464659.0735 2898388.2651,35464654.7077 2898389.8525,35464651.1359 2898393.1599,35464644.2568 2898401.6265,35464632.8797 2898415.2527,35464625.339 2898424.1161,35464618.3463 2898434.6712,35464619.126 2898434.6712,35464619.126 2898444.6712,35464613.8478 2898444.6712,35464611.4483 2898451.765,35464610.3901 2898461.8193,35464609.8609 2898473.4611,35464609.3317 2898481.7955,35464608.4057 2898487.0871,35464607.2149 2898490.3944,35464602.5847 2898493.5695,35464592.5306 2898497.4059,35464585.6515 2898499.5225,35464579.0505 2898503.1883,35464569.126 2898510.7258,35464569.126 2898519.6712,35464564.126 2898519.6712,35464564.126 2898524.6712,35464559.126 2898524.6712,35464559.126 2898529.6712,35464550.4508 2898529.6712,35464547.3005 2898532.8215,35464542.9349 2898536.5256,35464537.511 2898538.3779,35464533.9391 2898538.3779,35464530.3672 2898536.9225,35464529.5063 2898534.6712,35464529.126 2898534.6712,35464529.126 2898539.6712,35464519.126 2898539.6712,35464519.126 2898544.6712,35464504.126 2898544.6712,35464504.126 2898549.6712,35464509.126 2898549.6712,35464509.126 2898554.6712,35464514.126 2898554.6712,35464514.126 2898559.6712,35464519.126 2898559.6712,35464519.126 2898574.6712,35464514.126 2898574.6712,35464514.126 2898604.6712,35464519.126 2898604.6712,35464519.126 2898609.6712,35464514.126 2898609.6712,35464514.126 2898624.6712,35464505.1206 2898624.6712,35464504.5281 2898632.4913,35464491.8282 2898631.8563,35464491.8282 2898639.9525,35464484.126 2898639.7405,35464484.126 2898649.6712,35464489.126 2898649.6712,35464489.126 2898654.6712,35464454.126 2898654.6712,35464454.126 2898659.6712,35464449.126 2898659.6712,35464449.126 2898684.6712,35464439.126 2898684.6712,35464439.126 2898679.6712,35464419.126 2898679.6712,35464419.126 2898644.6712,35464414.126 2898644.6712,35464414.126 2898634.6712,35464419.126 2898634.6712,35464419.126 2898624.6712,35464434.126 2898624.6712,35464434.126 2898614.6712,35464424.126 2898614.6712,35464424.126 2898611.3431,35464409.9266 2898609.9577,35464409.3672 2898609.6712,35464397.7031 2898609.6712,35464396.0899 2898613.8821,35464393.9732 2898620.2321,35464393.9732 2898626.5821,35464394.8198 2898632.0854,35464398.6299 2898640.9755,35464403.0749 2898651.9821,35464405.8647 2898661.0929,35464406.4999 2898671.0411,35464403.5365 2898686.7045,35464403.2653 2898689.6712,35464404.126 2898689.6712,35464404.126 2898711.6262,35464404.3872 2898712.8576,35464404.9553 2898714.6712,35464409.126 2898714.6712,35464409.126 2898727.0559,35464410.1534 2898729.6712,35464414.126 2898729.6712,35464414.126 2898735.9663,35464414.5969 2898736.6716,35464416.7919 2898740.1401,35464419.5701 2898743.6293,35464422.6698 2898747.0987,35464432.3818 2898756.5488,35464433.9147 2898757.9259,35464434.126 2898758.0803,35464434.126 2898754.6712,35464439.126 2898754.6712,35464439.126 2898749.6712,35464444.126 2898749.6712,35464444.126 2898744.6712,35464484.126 2898744.6712,35464484.126 2898739.6712,35464489.126 2898739.6712,35464489.126 2898734.6712,35464494.126 2898734.6712,35464494.126 2898729.6712,35464514.126 2898729.6712,35464514.126 2898734.6712,35464529.126 2898734.6712,35464529.126 2898729.6712,35464534.126 2898729.6712,35464534.126 2898724.6712,35464539.126 2898724.6712,35464539.126 2898709.6712,35464554.126 2898709.6712,35464554.126 2898684.6712,35464559.126 2898684.6712,35464559.126 2898679.6712,35464564.126 2898679.6712,35464564.126 2898674.6712,35464569.126 2898674.6712,35464569.126 2898679.6712,35464574.126 2898679.6712,35464574.126 2898674.6712,35464579.126 2898674.6712,35464579.126 2898679.6712,35464584.126 2898679.6712,35464584.126 2898704.6712,35464579.126 2898704.6712,35464579.126 2898714.6712,35464584.126 2898714.6712,35464584.126 2898719.6712,35464594.126 2898719.6712,35464594.126 2898724.6712,35464599.126 2898724.6712,35464599.126 2898729.6712,35464609.126 2898729.6712,35464609.126 2898724.6712,35464614.126 2898724.6712,35464614.126 2898719.6712,35464619.126 2898719.6712,35464619.126 2898714.6712,35464624.126 2898714.6712,35464624.126 2898719.6712,35464629.126 2898719.6712,35464629.126 2898724.6712,35464634.126 2898724.6712,35464634.126 2898734.6712,35464639.126 2898734.6712,35464639.126 2898739.6712,35464644.126 2898739.6712,35464644.126 2898729.6712,35464654.126 2898729.6712,35464654.126 2898734.6712,35464659.126 2898734.6712,35464659.126 2898739.6712,35464664.126 2898739.6712,35464664.126 2898744.6712,35464669.126 2898744.6712,35464669.126 2898749.6712,35464674.126 2898749.6712,35464674.126 2898754.6712,35464679.126 2898754.6712,35464689.126 2898754.6712,35464689.126 2898759.6712,35464694.126 2898759.6712,35464699.126 2898759.6712,35464699.126 2898764.6712,35464704.126 2898764.6712,35464714.126 2898764.6712,35464714.126 2898769.6712,35464724.126 2898769.6712,35464724.126 2898774.6712,35464744.126 2898774.6712,35464744.126 2898769.6712,35464749.126 2898769.6712,35464749.126 2898739.6712,35464744.126 2898739.6712,35464744.126 2898734.6712,35464759.126 2898734.6712,35464759.126 2898739.6712,35464769.126 2898739.6712,35464769.126 2898744.6712,35464779.126 2898744.6712,35464779.126 2898749.6712,35464784.126 2898749.6712,35464784.126 2898744.6712,35464794.126 2898744.6712,35464794.126 2898739.6712,35464804.126 2898739.6712,35464804.126 2898734.6712,35464809.126 2898734.6712,35464809.126 2898729.6712,35464834.126 2898729.6712,35464834.126 2898739.6712,35464839.126 2898739.6712,35464839.126 2898734.6712,35464854.126 2898734.6712,35464854.126 2898704.6712,35464859.126 2898704.6712,35464859.126 2898699.6712,35464864.126 2898699.6712,35464864.126 2898694.6712,35464879.126 2898694.6712,35464879.126 2898699.6712,35464884.126 2898699.6712,35464884.126 2898719.6712,35464889.126 2898719.6712,35464889.126 2898734.6712,35464884.126 2898734.6712,35464884.126 2898744.6712,35464879.126 2898744.6712,35464879.126 2898749.6712,35464874.126 2898749.6712,35464874.126 2898754.6712,35464869.126 2898754.6712,35464869.126 2898759.6712,35464864.126 2898759.6712,35464864.126 2898764.6712,35464859.126 2898764.6712,35464859.126 2898769.6712,35464854.126 2898769.6712,35464854.126 2898774.6712,35464849.126 2898774.6712,35464849.126 2898779.6712,35464839.126 2898779.6712,35464839.126 2898784.6712,35464834.126 2898784.6712,35464834.126 2898789.6712,35464829.126 2898789.6712,35464829.126 2898799.6712,35464824.126 2898799.6712,35464824.126 2898804.6712,35464819.126 2898804.6712,35464819.126 2898814.6712,35464824.126 2898814.6712,35464824.126 2898826.7002,35464827.9844 2898827.0736,35464830.1912 2898827.7652,35464832.706 2898828.7671,35464839.5154 2898831.4245,35464847.7175 2898838.3037,35464853.2737 2898850.7391,35464859.2902 2898868.6055,35464859.7202 2898869.6712,35464864.126 2898869.6712,35464864.126 2898873.0146,35464872.9355 2898874.2402,35464874.126 2898874.5755,35464874.126 2898849.6712,35464914.126 2898849.6712,35464914.126 2898849.9808,35464917.303 2898849.6631,35464923.9742 2898850.3654,35464929.126 2898852.1857,35464929.126 2898849.6712,35464924.126 2898849.6712,35464924.126 2898844.6712,35464919.126 2898844.6712,35464919.126 2898839.6712,35464914.126 2898839.6712,35464914.126 2898829.6712,35464919.126 2898829.6712,35464919.126 2898824.6712,35464924.126 2898824.6712,35464924.126 2898819.6712,35464929.126 2898819.6712,35464929.126 2898824.6712,35464944.126 2898824.6712,35464944.126 2898857.792,35464952.7485 2898861.3048,35464962.5381 2898864.4798,35464974.4443 2898870.5653,35464983.4402 2898875.5923,35464988.2027 2898879.0319,35464994.2881 2898880.0903,35464997.4631 2898878.2382,35465000.3736 2898872.9465,35465000.8254 2898869.6712,35464999.126 2898869.6712,35464999.126 2898864.6712,35464994.126 2898864.6712,35464994.126 2898834.6712,35464989.126 2898834.6712,35464989.126 2898819.6712,35464969.126 2898819.6712,35464969.126 2898824.6712,35464964.126 2898824.6712,35464964.126 2898819.6712,35464959.126 2898819.6712,35464959.126 2898804.6712,35464984.126 2898804.6712,35464984.126 2898794.6712,35464989.126 2898794.6712,35464989.126 2898777.0881,35464985.7788 2898769.6712,35464984.126 2898769.6712,35464984.126 2898764.5729,35464981.4788 2898756.0699,35464981.0995 2898754.6712,35464979.126 2898754.6712,35464979.126 2898747.3928,35464978.4634 2898744.9492,35464978.4409 2898744.6712,35464974.126 2898744.6712,35464974.126 2898739.6712,35464969.126 2898739.6712,35464969.126 2898734.6712,35464959.126 2898734.6712,35464959.126 2898739.6712,35464949.126 2898739.6712,35464949.126 2898744.6712,35464939.126 2898744.6712,35464939.126 2898719.6712,35464944.126 2898719.6712,35464944.126 2898699.6712,35464949.126 2898699.6712,35464949.126 2898694.6712,35464954.126 2898694.6712,35464954.126 2898684.6712,35464949.126 2898684.6712,35464949.126 2898679.6712,35464944.126 2898679.6712,35464944.126 2898669.6712,35464939.126 2898669.6712,35464939.126 2898659.6712,35464949.126 2898659.6712,35464949.126 2898656.9392,35464948.0676 2898654.6712,35464944.126 2898654.6712,35464944.126 2898646.2247,35464942.5531 2898642.8541,35464942.9775 2898639.6712,35464939.126 2898639.6712,35464939.126 2898634.6712,35464934.126 2898634.6712,35464934.126 2898639.6712,35464919.126 2898639.6712,35464919.126 2898644.6712,35464909.126 2898644.6712,35464909.126 2898649.6712,35464904.126 2898649.6712,35464904.126 2898654.6712,35464899.126 2898654.6712,35464899.126 2898644.6712,35464894.126 2898644.6712,35464894.126 2898624.6712,35464904.126 2898624.6712,35464904.126 2898619.6712,35464909.126 2898619.6712,35464909.126 2898624.6712,35464924.126 2898624.6712,35464924.126 2898629.6712,35464929.126 2898629.6712,35464929.126 2898634.6712,35464934.126 2898634.6712),(35464629.126 2898434.6712,35464629.126 2898444.6712,35464624.126 2898444.6712,35464624.126 2898434.6712,35464629.126 2898434.6712),(35464607.9553 2898546.3749,35464594.5633 2898534.78,35464610.0982 2898515.3167,35464611.1728 2898514.2886,35464615.1888 2898510.4466,35464624.8461 2898517.5903,35464620.7519 2898522.1524,35464613.2705 2898530.4888,35464615.7619 2898534.7528,35464616.7101 2898536.3758,35464613.4814 2898540.4924,35464608.9287 2898546.297,35464607.9553 2898546.3749),(35464528.3116 2898592.5651,35464560.9084 2898555.9467,35464571.2801 2898565.0485,35464560.9084 2898576.0551,35464566.4117 2898580.9235,35464561.5433 2898587.6969,35464554.5583 2898582.1935,35464537.6249 2898601.2435,35464528.3116 2898592.5651),(35464652.7015 2898664.6712,35464653.7622 2898665.9018,35464652.4141 2898667.917,35464647.8235 2898672.1657,35464636.8697 2898680.4207,35464631.4721 2898674.7057,35464630.6111 2898660.0016,35464635.7585 2898655.338,35464642.3841 2898658.7736,35464644.126 2898658.0187,35464644.126 2898634.6712,35464659.126 2898634.6712,35464659.126 2898639.6712,35464664.126 2898639.6712,35464664.126 2898644.6712,35464674.126 2898644.6712,35464674.126 2898654.6712,35464679.126 2898654.6712,35464679.126 2898674.6712,35464684.126 2898674.6712,35464684.126 2898684.6712,35464679.126 2898684.6712,35464679.126 2898679.6712,35464654.126 2898679.6712,35464654.126 2898664.6712,35464652.7015 2898664.6712),(35464518.8421 2898651.0915,35464528.976 2898655.3715,35464527.8319 2898657.8946,35464520.9587 2898673.0519,35464511.1692 2898667.7603,35464518.8421 2898651.0915),(35464551.4389 2898661.8999,35464557.9477 2898660.6299,35464566.3614 2898666.6623,35464561.2814 2898674.9173,35464556.2013 2898672.0599,35464549.2164 2898682.5372,35464540.6437 2898676.3461,35464548.1051 2898663.4873,35464551.4389 2898661.8999),(35464824.126 2898714.6712,35464814.126 2898714.6712,35464814.126 2898709.6712,35464809.126 2898709.6712,35464809.126 2898704.6712,35464804.126 2898704.6712,35464804.126 2898689.6712,35464814.126 2898689.6712,35464814.126 2898684.6712,35464829.126 2898684.6712,35464829.126 2898694.6712,35464834.126 2898694.6712,35464834.126 2898704.6712,35464829.126 2898704.6712,35464829.126 2898709.6712,35464824.126 2898709.6712,35464824.126 2898714.6712),(35464889.126 2898764.6712,35464884.126 2898764.6712,35464884.126 2898759.6712,35464889.126 2898759.6712,35464889.126 2898764.6712),(35464894.126 2898769.6712,35464889.126 2898769.6712,35464889.126 2898764.6712,35464894.126 2898764.6712,35464894.126 2898769.6712),(35464894.126 2898769.6712,35464904.126 2898769.6712,35464904.126 2898779.6712,35464899.126 2898779.6712,35464899.126 2898774.6712,35464894.126 2898774.6712,35464894.126 2898769.6712),(35464939.126 2898794.6712,35464944.126 2898794.6712,35464944.126 2898804.6712,35464939.126 2898804.6712,35464939.126 2898799.6712,35464934.126 2898799.6712,35464934.126 2898794.6712,35464929.126 2898794.6712,35464929.126 2898784.6712,35464934.126 2898784.6712,35464934.126 2898774.6712,35464939.126 2898774.6712,35464939.126 2898794.6712),(35464914.126 2898784.6712,35464909.126 2898784.6712,35464909.126 2898779.6712,35464914.126 2898779.6712,35464914.126 2898784.6712),(35464914.126 2898784.6712,35464919.126 2898784.6712,35464919.126 2898789.6712,35464914.126 2898789.6712,35464914.126 2898784.6712),(35464919.126 2898789.6712,35464924.126 2898789.6712,35464924.126 2898794.6712,35464919.126 2898794.6712,35464919.126 2898789.6712))

 
NetTopologySuite.Geometries.TopologyException

found non-noded intersection between LINESTRING (35464934.126 2898634.6712, 35464934.126 2898624.6712) 
and LINESTRING (35464939.126 2898634.6712, 35464934.126 2898634.6712) [ (35464934.126, 2898634.6712, NaN) ]

how can i to do?

**Comment by FObermaier** [comment]
Is the polygon valid?
What did you do with it to get the `TopologyException`?

**Comment by FObermaier** [comment]
The polygon is not valid: `Ring Self-intersection at or near point (35464934.126, 2898634.671, NaN)`
Fix your polygon by doing the Buffer0-Trick:
```C#
polygon = polygon.Buffer(0);
```

**Comment by bouyeijiang** [comment]
i used repair geometry tools to repair it,but it not effect.I'll try your method first.
