### ISSUE TITLE
Possible "bug" in the GettingStarted wiki doc?

### ISSUE THREAD

**Issue by PureKrome** [NetTopologySuite/NetTopologySuite#464]
👋🏻 G'Day!

Just trying to use NTS in a new/different application and I jumped back to your Getting Started wiki.

Very first part about setting up the instance doesn't seem to work?

WIKI says this:

```
NetTopologySuite.NtsGeometryServices.Instance = new NetTopologySuite.NtsGeometryServices(
    NetTopologySuite.Geometries.Implementation.CoordinateArraySequenceFactory.Instance,
    new NetTopologySuite.Geometries.PrecisionModel(1000d),
    4326,
    NetTopologySuite.Geometries.GeometryOverlay.NG);
```

but the latest ctor doesn't accept a `GeometryOverlay` ?

![image](https://user-images.githubusercontent.com/899878/103537229-2aa88b00-4ee8-11eb-87b9-be82a75d07cc.png)

Here's what VS looks like with the compile time error:

![image](https://user-images.githubusercontent.com/899878/103537335-57f53900-4ee8-11eb-8f08-52655d2dbdb4.png)

Nuget Version: 2.1.0 (from 2020-08-20)

**Comment by FObermaier** [comment]
You are right, `NetTopologySuite.Geometries.GeometryOverlay.NG` is for upcoming 2.2 package
