### ISSUE TITLE
Question: how to know what metric is used when doing a Buffer?

### ISSUE THREAD

**Issue by PureKrome** [NetTopologySuite/NetTopologySuite#465]
Hello NTS,

I'm trying to create a bounding box around a specific POINT. To do this, I'll basically do a `Buffer(x).Envelope`.

I'm not sure sure what the _unit of measure_ `x` should be. So for example, If i want to make a 10km buffer, then I would assume i need to do a 5km `Buffer`.  Reading the info, it looks like the value is directly related to the `PrecisionModel` of the factory?

Given the 'Getting Started' docs...

```
NetTopologySuite.NtsGeometryServices.Instance = new NetTopologySuite.NtsGeometryServices(
    NetTopologySuite.Geometries.Implementation.CoordinateArraySequenceFactory.Instance,
    new NetTopologySuite.Geometries.PrecisionModel(1000d),
    4326,
    NetTopologySuite.Geometries.GeometryOverlay.NG);
```

the `PrecisionModel` is `1000` <something> for the SRID 4326 (GPS, etc)

Is this 1000 meters (1 km) so if I start doing `Buffer(5)` that will now be 5km?

**Comment by FObermaier** [comment]
Same as coordinates, in case of SRID=4326 degrees, unfortunately.
In NTS all is planar.

**Comment by PureKrome** [comment]
So is there an _easy_ way to say `Buffer(5km)` then?

**Comment by DGuidi** [comment]
as felix explained, the unit of measure depends of the SRID you set; so if you se as example an UTM SRID like [32632](https://epsg.io/32632) you are working with *metres*, so of you want a buffer of 5 km around a point you can use `Buffer(5000)`.  
The key part to understand is that the units in NTS are **just numbers**:  if you use a *global* srid like [4326](https://epsg.io/4326) you are working with **degrees**; NTS doesn't account for the earth curvature or other kinds of corrections, and you can not expect to use `Buffer(5000)` to have a buffer of 5 km around your point.

**Comment by PureKrome** [comment]
Cheers - that helps .. and makes me cry 😢 

Also, I was just assuming that the `operations on the `Geometry` class actually took the curvature of the earth into account. Sure, i'm dealing with military grade calculations and precision but I just assumed that this was the default. urgh.

It hurts so much how this is all so complicated.

So -> if I wish to do a 5km circle around a lat/long, i'm now going to have to do something like this?

- create a point with WSG84 `4326`
- convert this point to URM 32632
- `Buffer(5000)`
- convert back to WSG84 ?

I've got some older code (before I was looking at using NTS) which was ripping some code from somewhere which is the Haversine Formula .. which sorta looks ok ... but of course, was just seeing if there was a built in way with NTS.

**Comment by airbreather** [comment]
See also #233

> So -> if I wish to do a 5km circle around a lat/long, i'm now going to have to do something like this?
> * create a point with WSG84 `4326`
> * convert this point to URM 32632
> * `Buffer(5000)`
> * convert back to WSG84 ?

Pretty much, yeah, though the exact ideal projection to use depends on your data.

You also ought to consider stupid cases like antimeridian crossings and projection bounds, unless you can hand-wave the issues away by restricting the inputs.  I rant a little bit about this kind of thing in https://github.com/NetTopologySuite/NetTopologySuite/issues/233#issuecomment-455780259, and that's not even the end of it: if your buffer happens to cover either the North or South Pole, then most algorithms in NTS will probably break down.

**Comment by PureKrome** [comment]
Oh wow - love that rant! Personally, I don't see it as a rant because I'm feeling lots of what you said. Sure, I don't deal with polys that cross the antimeridian and even between hemisphere's (hi sql server 2008 "denali" when geography first came out) ... but I do deal with (what I would have thought was) simple, common spatial operations:

- lat/longs
- buffers (in meters or kms)
- point in poly (intersect)
- bounding box (envelope) 
- distance between two points
- centre point of a poly (which is so much visual fun, when the poly is a weird shape ... and even more fun when the centre point lies outside of the weird ass shape!)

I also hated the fact that with SqlServer they have 2 types of types: `Geom` and `Geog` ... like .. they feel like the same thing most of the time .. until you want to do an operation that is either 3D (world sphere) or 2D. ... so I just ignorantly thought that the NTS `Geometry` was a standard way and when you wanted to do some operations against a world sphere, you could just set a param so the underlying magic might just 'know'.

I'm not a map person at all. Totally newbie. But i just would have thought that if _anyone_ was going to do _anything_ with a Lat/Long .. that basically says they are doing something with the Earth. So therefore, any WSG84 4326 operations would take into consideration the curvature of the Earth. So my lack of education here (and gross assumption) probably insults very cartographer out there <blush> .

But back to the topic -> I guess i can experiment with the above idea of projecting back and forth.

And again, i thought this would be like .. _really common stuff_ for people ... that this could (should?) be documented somewhere, without getting into a deep dive about projections and stuff?
