### ISSUE TITLE
Question: Method to create straight skeleton

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#466]
@FObermaier 
### Description

We are trying to find a way to get topological skeleton from NTS polygon. Do you have any method that we could use to do that?

 straight skeleton
https://en.wikipedia.org/wiki/Straight_skeleton

**Comment by FObermaier** [comment]
There is no straight skeleton algorithm in NTS, sorry.

**Comment by michaldengusiak** [comment]
ok thanks for a quick reply
