### ISSUE TITLE
GMLWriter output not valid??

### ISSUE THREAD

**Issue by RobertSmart** [NetTopologySuite/NetTopologySuite#47]
Hi, I'm trying to create a really simple GML file using NTS and it is failing to open in QGIS.

I'm using this code:

            var gmlOut = new NetTopologySuite.IO.GML2.GMLWriter();        
            var stream = new FileStream(@"D:\temp\test.gml", FileMode.CreateNew);
            var geom = new NetTopologySuite.Geometries.Point(52, -0.9);
            gmlOut.Write(geom, stream);

and I get this output:

<gml:GML xmlns:gml="http://www.opengis.net/gml"><gml:Point><gml:coord><gml:X>52</gml:X><gml:Y>-0.9</gml:Y></gml:coord></gml:Point></gml:GML>

Looks simple enough, but its not opening in QGIS, and if I try the OGC validator I get this message.

cvc-elt.1: Cannot find the declaration of element 'gml:GML'.

do I need to create a schema or something to go with the file? How do I do that?

Thanks

**Comment by DGuidi** [comment]
GMLWriter writes a GML "representation" of a Geometry: a GML fragment and not a complete GML document.

**Comment by RobertSmart** [comment]
Hi, thanks for the feedback. I managed to use sharpkml to get a quick usable output, but it would be good to see an export to gml file option.

**Comment by FObermaier** [comment]
If I got it right, the problem is the wrapping `<gml:GML></gml:GML>` tag that is created using the writer. At least JTS does not write that in its xml.

**Comment by DGuidi** [comment]
Have you tried to read JTS GML output with QGIS?
I suspect you can obtain another error, jost becaus the GML fragment isn't a GML/XML valid document.
Anyway, remove gml namespace can be a valid strategy, at least to maintain JTS behavior.

**Comment by FObermaier** [comment]
Having said that, I think the API should change and the `GMLWriter.Write` functions should take an XmlWriter as argument, thus knowing which namespaces have already been defined to not pollute the file with namespace declarations.

**Comment by FObermaier** [comment]
As a comparison:
JTS:
```
<gml:Point>
  <gml:coordinates>
    52,-0.9 
  </gml:coordinates>
</gml:Point>`
```

NTS:
```
<gml:GML xmlns:gml="http://www.opengis.net/gml">
  <gml:Point>
    <gml:coord>
      <gml:X>52</gml:X>
      <gml:Y>-0.9</gml:Y>
    </gml:coord>
 </gml:Point>
</gml:GML>
```

**Comment by DGuidi** [comment]
I'm working on a pull request.
Actually, I don't remember the meaning of gml:GML tag, I remember that code was modified for MSSQLSpatial purposes...

**Comment by DGuidi** [comment]
+1 for change the API

**Comment by DGuidi** [comment]
@FObermaier @RobertSmart please check. Hope this fix the problem.

**Comment by DGuidi** [comment]
can I close this issue now?

**Comment by RobertSmart** [comment]
I haven't had time to check, but if matches the JTS implementation, then it should be fine to close now.

Thanks, Rob
