### ISSUE TITLE
TopologyException when performing OverlayOp.Intersection on polygons with fixed PrecisionModel

### ISSUE THREAD

**Issue by martijnkoopman** [NetTopologySuite/NetTopologySuite#474]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of NetTopologySuite
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A TopologyException is thrown when Intersection is performed on two valid polygons. The polygons have fixed precision and are almost identical. The coordinate differences between the polygons are within the specified precision.

```
NetTopologySuite.Geometries.TopologyException
  HResult=0x80131600
  Message=found non-noded intersection between LINESTRING (181879.611 434884.599, 180975.23 435703.384) and LINESTRING (181879.61 434884.6, 180975.23 435703.38) [ (181858.70565763491, 434903.52573635161) ]
  Source=NetTopologySuite
  StackTrace:
   at NetTopologySuite.Noding.FastNodingValidator.CheckValid()
   at NetTopologySuite.Operation.Overlay.OverlayOp.ComputeOverlay(SpatialFunction opCode)
   at NetTopologySuite.Operation.Overlay.OverlayOp.GetResultGeometry(SpatialFunction overlayOpCode)
...
```

### Steps to Reproduce
```cs
string wkt1 = "POLYGON ((180468.153 436502.89, 181385.164 436064.011, 181864.723 435504.13, 183905.374 434543.219, 183947.748 433885.974, 181879.615 434884.596, 180975.23 435703.384, 179967.81 436141.722, 180468.153 436502.89))";
string wkt2 = "POLYGON ((180468.15 436502.89, 181385.16 436064.01, 181864.72 435504.13, 183905.37 434543.22, 183947.75 433885.97, 181879.61 434884.6, 180975.23 435703.38, 179967.81 436141.72, 180468.15 436502.89))";

// Geometry from WKT
var geometryFactory = new NetTopologySuite.Geometries.GeometryFactory(new NetTopologySuite.Geometries.PrecisionModel(1000), 28992);
var reader = new NetTopologySuite.IO.WKTReader(geometryFactory);
var geom1 = reader.Read(wkt1);
var geom2 = reader.Read(wkt2);

// Validate geometry
Assert.IsTrue(geom1.IsValid);
Assert.IsTrue(geom2.IsValid);

var overlayOp = new NetTopologySuite.Operation.Overlay.OverlayOp(geom1, geom2);

try {
    var intersection = overlayOp.GetResultGeometry(NetTopologySuite.Operation.Overlay.SpatialFunction.Intersection);
} catch (Exception e) {
    // Exception thrown
}
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.1.0
- Other NetTopologySuite packages and versions: -
- Environment (Operating system, version and so on): Windows Server 2019
- .NET Framework version: 4.8
- Additional information: -

### Work Around
Disable validation in `OverlayOp`.
```cs
NetTopologySuite.Operation.Overlay.OverlayOp.NodingValidatorDisabled = true;
```
The resulting geometry is a GEOMETRYCOLLECTION instead of a single POLYGON.
```
GEOMETRYCOLLECTION (
LINESTRING (181879.611 434884.599, 180975.23 435703.384, 179967.812 436141.721), 
POLYGON ((183934.746 434087.639, 183947.748 433885.974, 182589.449 434541.845, 181879.611 434884.599, 181879.61 434884.6, 180975.23 435703.38, 179967.81 436141.72, 179967.812 436141.721, 180208.039 436315.129, 180468.152 436502.889, 181385.16 436064.01, 181864.72 435504.13, 183905.37 434543.22, 183934.746 434087.639))
)
```

Alternatively, remove the `PrecisionModel` or increase the precision. For example: 10000.

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
Why do you explicitly use `NetTopologySuite.Operation.Overlay.OverlayOp`?
Simply calling
```C#
var intersection = geom1.Intersection(geom2);
```
succeeds.   
This is because `Geometry.Intersection` internally uses `NetTopologySuite.Operation.Overlay.Snap.SnapIfNeededOverlayOp`.
