### ISSUE TITLE
Question Gaps between polygons

### ISSUE THREAD

**Issue by cosmintaran** [NetTopologySuite/NetTopologySuite#476]
Hello.
Sorry for posting this question here, but I ran out of sources. 
I'm trying  to detect gaps and slivers between polygons, but I cannot do it right.
I have tried to:
- get all intersecting polygons
-  cascadeunion with them
-  get all polygons from a multipolygon  
- check for holes.
I get a lot of false positive for this case.

Another aproach was to union intersecting polygons in pairs (only two).
The result was a little bit better, but still I get many false positive.

Can anyone please give me a hint on how to do it properly.  

Thank you and sorry for my pour English.

**Comment by airbreather** [comment]
@cosmintaran Can you please post this as a [discussion](https://github.com/NetTopologySuite/NetTopologySuite/discussions) in the "Q&A" category?

Sorry for the bother -- we're supposed to be able to convert issues like this to discussions on our own, but that functionality has been [disabled](https://github.com/github/feedback/discussions/2924?sort=top#discussioncomment-254592) for now.
