### ISSUE TITLE
RawCoordinateSequence ArgumentOutOfRangeException on paired XY

### ISSUE THREAD

**Issue by bjornharrtell** [NetTopologySuite/NetTopologySuite#499]
At:

https://github.com/NetTopologySuite/NetTopologySuite/blob/8d62d620ba9f762b8d81f0ee8afb6e6492e64dcb/src/NetTopologySuite/Geometries/Implementation/RawCoordinateSequence.cs#L208

When used fx. like this:
```C#
var factory = new RawCoordinateSequenceFactory(new Ordinates[] { Ordinates.XY });
var cs = factory.Create(new Coordinate[] { new Coordinate(0, 10) });
var a = cs.ToCoordinateArray();
```

**Comment by bjornharrtell** [comment]
NOTE: This is for the new experimental RawCoordinateSequence by @airbreather at https://github.com/NetTopologySuite/NetTopologySuite/tree/gh-482.

**Comment by airbreather** [comment]
Pushed a fix to that branch.  Please verify.

**Comment by bjornharrtell** [comment]
Verified working.
