### ISSUE TITLE
ShapefileDataReader creating PolygonZ instead of Polygon for XY Wkt

### ISSUE THREAD

**Issue by billpratt** [NetTopologySuite/NetTopologySuite#51]
We are using WktReader to create geometries from Wkt that are XY coordinates and using ShapefileDataWriter to create a shapefile with these geometries. When reading the shapefile in something like QGIS v2.10.1, the polygons are read as PolygonZ with a 'nan' Z coordinate. What we want is just a XY Polygon. 

Here are the steps I used for debugging this

1) Convert Wkt to Geometry
```
// Wkt in 4326 SRID (WGS84)
var wkt = "POLYGON ((-86.7605020509258 41.5101338613656, -86.7604972038273 41.5100611525915, -86.7604971708084 41.5100606308085, -86.7604611720717 41.5094596307695, -86.7604611426546 41.5094591103497, -86.7604291439208 41.5088571103154, -86.760429130715 41.508856853856, -86.7603991319814 41.5082548538241, -86.7603991259966 41.5082547317887, -86.7603701303631 41.5076537960468, -86.7603401446338 41.5070530565908, -86.7603071566895 41.5064532528163, -86.7603071500912 41.506453131098, -86.7602814240795 41.5059715533315, -86.7605549835241 41.5059607024218, -86.7605808466407 41.5064448078787, -86.760613844555 41.5070447469854, -86.7606138651484 41.5070451395365, -86.7606438664126 41.5076461395046, -86.7606438727239 41.5076462680791, -86.7606728710439 41.5082472070294, -86.7607028628788 41.5088490177453, -86.7607348434949 41.5094506292495, -86.7607708135428 41.5100511081057, -86.760776407335 41.5101350123382, -86.7605020509258 41.5101338613656))";

var geomFactory = new GeometryFactory(new PrecisionModel(), 4326);
var wktReader = new WKTReader(geomFactory);

Debug.WriteLine($"Geometry Type: {geometry.GeometryType}");
Debug.WriteLine($"Shapefile Type: {Shapefile.GetShapeType(geometry)}");
```

Output: 
Geometry Type: Polygon
Shapefile Type: PolygonZM

2) Cast geometry to IPolygon to get the CoordindateSequence Ordinates
```
IPolygon geomPolygon = geometry as IPolygon;
Debug.WriteLine($"IPolygon Geometry Type: {geomPolygon.GeometryType}");
Debug.WriteLine($"IPolygon Shell CoordindateSequence Ordinates: {geomPolygon.Shell.CoordinateSequence.Ordinates}");
```

Output:
IPolygon Geometry Type: Polygon
IPolygon Shell CoordindateSequence Ordinates: XYZ

What I need is for the Ordindates to be XY. Not sure if this is as intended or we are not using the corect GeometryFactory settings or a bug. We have a temp fix in by creating our own instance of ICoordinateSequenceFactory and passing an instance into GeometryFactory.

Here's a gist of the full sample to recreate: https://gist.github.com/billpratt/6bf4ab8e4435dc39db92

**Comment by billpratt** [comment]
Heres a screenshot of opening the shapefile in QGIS v2.10.1 and using the extension "getWkt" to view the WKT

![screen shot 2015-09-15 at 4 21 18 pm](https://cloud.githubusercontent.com/assets/2847527/9888949/e9656a2a-5bc5-11e5-9e8b-b853cca3561a.png)

**Comment by Gonkers** [comment]
Basically it appears the issue we are having is when reading the WKT. The `public ICoordinateSequence Create(Coordinate[] coordinates)` in the default `CoordinateArraySequenceFactory` is statically set to create CoordinateSequences with 3 dimensions. In the mean time we have come up with a workaround to create our own ICoordinateSequenceFactory. I'm not sure this is the ideal solution and I was hoping we could get a more elegant/proper solution.

```
    public sealed class FlatCoordinateArraySequenceFactory : ICoordinateSequenceFactory
    {
        private FlatCoordinateArraySequenceFactory() { }

        /// <summary>
        /// Returns the singleton instance of CoordinateArraySequenceFactory.
        /// </summary>
        public static FlatCoordinateArraySequenceFactory Instance { get; } = new FlatCoordinateArraySequenceFactory();

        /// <summary>
        ///  Returns a CoordinateArraySequence based on the given array (the array is not copied).
        /// </summary>
        /// <param name="coordinates">the coordinates, which may not be null nor contain null elements.</param>
        /// <returns></returns>
        public ICoordinateSequence Create(Coordinate[] coordinates)
        {
            //return GeometryFactory.Default.CoordinateSequenceFactory.Create(coordinates);
            return new CoordinateArraySequence(coordinates, OrdinatesUtility.OrdinatesToDimension(Ordinates));
        }

        public ICoordinateSequence Create(ICoordinateSequence coordSeq)
        {
            return GeometryFactory.Default.CoordinateSequenceFactory.Create(coordSeq);
        }

        public ICoordinateSequence Create(int size, int dimension)
        {
            return GeometryFactory.Default.CoordinateSequenceFactory.Create(size, dimension);
        }

        public ICoordinateSequence Create(int size, Ordinates ordinates)
        {
            return GeometryFactory.Default.CoordinateSequenceFactory.Create(size, ordinates);
        }

        public Ordinates Ordinates => Ordinates.XY;
    }
```

**Comment by FObermaier** [comment]
Could you please verify that 3c9f90b solves you issue and does not have any other drawbacks?

**Comment by billpratt** [comment]
I tested and it is working as expected. Thanks! :+1:

**Comment by billpratt** [comment]
Do you have a timeframe when this will be released to nuget?

**Comment by DGuidi** [comment]
can I close this issue now?

**Comment by billpratt** [comment]
Yes. Thank you
