### ISSUE TITLE
Performance: Optimize CoordinateSequences.Copy for known types?

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#516]
I haven't fully investigated this yet, but some code that we have in our application currently special-cases for certain `CoordinateSequence` types rather than call this: https://github.com/NetTopologySuite/NetTopologySuite/blob/c838c5061aa0f13d1fa65f828a868d790302ec06/src/NetTopologySuite/Geometries/CoordinateSequences.cs#L55-L59

For example, when both sequences have equal `Dimension` and `Measures` values and both are instances of exactly `PackedDoubleCoordinateSequence`, it should be considerably faster to perform the copy using `.GetRawCoordinates()`, as the general-purpose version is quite fat.

Also note that I think that `CopyCoord` is incorrect: if you're copying a section of an `XYZ` sequence to a section of an `XYM` sequence, then you'll be overwriting M values with Z values, which seems inappropriate.  That's for another GitHub issue, though...

**Comment by airbreather** [comment]
To investigate: benchmark the cost of copying a large sequence using this general-purpose method, compared to what we stand to gain from the proposed optimization.

**Comment by FObermaier** [comment]
Closed with https://github.com/NetTopologySuite/NetTopologySuite/commit/5d460aba729fac353f33aee2df90514483a5b82a
