### ISSUE TITLE
Why does a rectangle not overlap another rectangle inside it?

### ISSUE THREAD

**Issue by urbanhop** [NetTopologySuite/NetTopologySuite#52]
The JTS docs say this about the Overlaps predicate:

"Overlaps: The Geometries share some but not all points in common, and the intersection has the same dimension as the Geometries themselves"

The 2 rectangles below share some points, the intersection is the smaller rectangle, so why on earth does JTS (and NTS) say that these 2 rectangles do NOT overlap?

NTS behaves like JTS.

![overlaps](https://cloud.githubusercontent.com/assets/9371283/9937300/6eaa3e9a-5d60-11e5-855c-a89b2550a787.jpg)

**Comment by DGuidi** [comment]
http://docs.geotools.org/stable/userguide/library/jts/relate.html#overlaps
_The geometries have some points in common; but not all points in common (so if one geometry is inside the other overlaps would be false)._

**Comment by DGuidi** [comment]
please use [google group](https://groups.google.com/forum/#!forum/nettopologysuite) for questions like this one.

**Comment by urbanhop** [comment]
"but not all", oh yesm thank you so much, very helpful.
