### ISSUE TITLE
NetTopologySuite with DynamoDb and entityFrameworkCore

### ISSUE THREAD

**Issue by cissemy** [NetTopologySuite/NetTopologySuite#522]
Hi
How can I use NetTopologySuite with Dynamodb and entityFrameworkCore ?
Thanks

**Comment by bricelam** [comment]
Currently, EF Core with NTS is only [available on](https://docs.microsoft.com/ef/core/modeling/spatial#installing)...

* Microsoft SQL Server
* PostgreSQL (with PostGIS)
* SQLite (with SpatiaLite)
* MySQL
* Teradata
