### ISSUE TITLE
GeometryFactory.CreateGeometry does not process coordinates

### ISSUE THREAD

**Issue by urbanhop** [NetTopologySuite/NetTopologySuite#53]
GeometryFactory.CreateGeometry(IGeometry g) doc says:
"This is a convenient way to **change the CoordinateSequence** used to represent a geometry, or to change the factory used for a geometry."

I tried this code:

var g = // some sample polygon
var gf = new GeometryFactory(new PrecisionModel(1000));
var gscaled = gf.CreateGeometry(g); // issue: does not process coordinates

gscaled has the PrecisionModel attached but its coordinates are not changed. Debugging showed that PrecisionModel.MakePrecise() is never called.

**Comment by FObermaier** [comment]
From the code documentation:
`Note that the factory constructor methods do <b>not</b> change the input coordinates in any way.
In particular, they are not rounded to the supplied <c>PrecisionModel</c>.
It is assumed that input Coordinates meet the given precision.`
