### ISSUE TITLE
question EqualsTopologically

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#533]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
_(A description of the bug or feature)_
ver 2.2.0
We have two polygons

```
POLYGON ((-1.426955 -1.9145, -1.426954 -1.9145, -3.65313 -1.9145, -3.65313 1.9145, -1.426954 1.9145, -1.426955 1.9145, -1.426955 -1.9145))

POLYGON ((-1.426955 1.9145, -1.426954 1.9145, -1.426955 1.9145, -3.65313 1.9145, -3.65313 -1.9145, -1.426954 -1.9145, -1.426955 -1.9145, -1.426955 -1.9145, -1.426955 1.9145))

```
and we try to check if they are topologically the same... we using EqualsTopologically however it returns error.
How can/should we run it to get correct results - which means for our example - True or False
(for us within tolerance 1e-6 and does not need the same nr of points)
![image](https://user-images.githubusercontent.com/26113670/124892672-f7979f00-dfd1-11eb-9843-4552dfc65fdb.png)

### Steps to Reproduce
_(List of steps, sample code, failing test or link to a project that reproduces the behavior)_
run steps above
### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version:
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
`polygon_1` is not valid, it has a self-intersection at or near `POINT(-1.426955 -1.9145)`. `polygon_2` might have issues, too, I have not checked that.

I don't know where the polygon comes from, but if it is computed through means of NTS you could use an `NtsGeometryServices` instance with `GeometryOverlay.NG` and a `PrecisionModel(1000000)`. It should solve this issue.
See: https://github.com/NetTopologySuite/NetTopologySuite/wiki/GettingStarted#setting-up-the-environment

**Comment by michaldengusiak** [comment]
thanks a lot
