### ISSUE TITLE
NetTopologySuite.IO.GeoTools version

### ISSUE THREAD

**Issue by bendetat** [NetTopologySuite/NetTopologySuite#54]
Hi, I may be missing something but it looks like the current version of `NetTopologySuite.IO.GeoTools` on NuGet (<https://www.nuget.org/packages/NetTopologySuite.IO.GeoTools/>) - 1.13.2.0 - doesn't match the current version of the other packages - `NetTopologySuite` for instance is 1.13.3.2.

This means that an application that uses `NetTopologySuite.IO.GeoTools` can't be upgraded to the current version of NTS and GeoAPI.

**Comment by DGuidi** [comment]
As far as I know, as I see buinding nuget packages with msbuild with command ```msbuild /t:nugetpack TeamCity.targets```, there isn't a GeoTools nuget package anymore.

**Comment by bendetat** [comment]
What's the upgrade path for a project that currently uses the `NetTopologySuite.IO.GeoTools` package?

**Comment by DGuidi** [comment]
[here](https://www.nuget.org/profiles/nettopologysuite%20-%20team) you can see NTS.IO plus specific libraries for different providers.
