### ISSUE TITLE
Breaking change in EF Core 6 RC1 causes NTS error

### ISSUE THREAD

**Issue by JonSchwartzDev** [NetTopologySuite/NetTopologySuite#550]
### Prerequisites

- [ x ] I have written a descriptive issue title
- [ x ] I have verified that I am running the latest version of NetTopologySuite
- [ n/a ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ x ] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Breaking change in EF Core 6 RC1 causes error:

Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite, Version=5.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

### Steps to Reproduce
Configure the use of NTS in an AspNetCore 6 MVC app:

builder.Services.AddDbContext<ApplicationDbContext>(options => 
        options.UseSqlServer(connectionString, sqlOptions => 
        sqlOptions.UseNetTopologySuite()));
        
Prepare and attempt to add a migration for a new entity type:

PM> Add-Migration EntityType

Generation of the new migration will fail with the error:

Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite, Version=5.0.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.

The breaking change was reported in EF Core 6 and closed as "closed-by-design":

https://github.com/dotnet/efcore/issues/26022 

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 5.0.10
- Other NetTopologySuite packages and versions: n/a
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: 
Microsoft.NETCore.App 6.0.0-rc.1.21451.13
Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15
Microsoft.EntityFrameworkCore 6.0.0-rc.1.21452.10
Microsoft.EntityFrameworkCore.SqlServer 6.0.0-rc.1.21452.10

- Additional information:
As described in the efcore issue linked above, GetServiceProviderHashCode has a new return type of int rather than long.

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by airbreather** [comment]
> NetTopologySuite version: 5.0.10

We have not released a version of the `NetTopologySuite` package with that version number.  Can you please double-check?

**Comment by airbreather** [comment]
Ahh -- if you're referring to `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite`, then perhaps you need to update your package reference for that one to version `6.0.0-rc.1.21452.10`?

**Comment by JonSchwartzDev** [comment]
That did it, thanks. NuGet doesn't offer that version, and I didn't know there was a matching one. Knowing it did, I dug for it, installed it, and confirmed the problem doesn't happen with that latest.
