### ISSUE TITLE
GML3Writer results in wrong namespace

### ISSUE THREAD

**Issue by bjornharrtell** [NetTopologySuite/NetTopologySuite#554]
The GML3Writer will output geometry element fx. like this:

```xml
<gml:Point xmlns:gml="http://www.opengis.net/gml">
  <gml:pos>0 0</gml:pos>
</gml:Point>
```

`http://www.opengis.net/gml` is wrong (because it represents GML 2), it should be `http://www.opengis.net/gml/3.2`.

**Comment by FObermaier** [comment]
Closed with https://github.com/NetTopologySuite/NetTopologySuite/commit/83f3f44c89eeca82e4c0a03e645f257010d8cc44

**Comment by m1dst** [comment]
This broke our ability to write geometry to our GeoServer.  Not sure why yet but the exception thrown on the GeoServer is...

Error performing insert: java.lang.String cannot be cast to org.locationtech.jts.geom.Geometry

with a geometry of...

<gml:Polygon xmlns:gml="http://www.opengis.net/gml/3.2" srsName="EPSG:4326">
                    <gml:exterior>
                        <gml:LinearRing>
                            <gml:posList>12.825712 50.817932 12.825712 50.818461 12.827278 50.818461 12.827278 50.817932 12.825712 50.817932</gml:posList>
                        </gml:LinearRing>
                    </gml:exterior>
                </gml:Polygon>

Remove the /3.2 and it works fine.
