### ISSUE TITLE
Could not load file or assembly 'NetTopologySuite'

### ISSUE THREAD

**Issue by asouth** [NetTopologySuite/NetTopologySuite#569]
Hi,

Ive installed NetTopologySuite  and NetTopologySuite.IO using Nuget and setup a simple console application to try and load a SHP file, but i receive the exception below. Is there any advice on how to resolve this?

![image](https://user-images.githubusercontent.com/10164856/140617842-b0a4a8ec-e41f-4a86-88d2-d579c03268f8.png)

```
using NetTopologySuite.IO.ShapeFile.Extended;


namespace MY_INTERFACE
{
    class Program
    {       
        static void Main(string[] args)
        {
	    bool success = false;
            string shfileName = @"c:\temp\LINKS.shp";
     
            using (ShapeDataReader reader = new ShapeDataReader(shfileName))
            {
                success = true;
			}
		}
	}
}
```

At runtime i receive this error,

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'NetTopologySuite, Version=1.15.3.0, Culture=neutral, PublicKeyToken=f580a05016ebada1' or one of its dependencies. The system cannot find the file specified.
  Source=NetTopologySuite.IO.ShapeFile.Extended
  StackTrace:
   at NetTopologySuite.IO.ShapeFile.Extended.ShapeDataReader..ctor(String shapeFilePath)
   at EXCEL_INTERFACE.Program.Main(String[] args) in Program.cs:line 215

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'NetTopologySuite, Version=1.14.0.0, Culture=neutral, PublicKeyToken=f580a05016ebada1' or one of its dependencies. The system cannot find the file specified.

**Comment by DGuidi** [comment]
you're using an old "nettopologysuite.io" package. be sure to reference a 2.x version

**Comment by DGuidi** [comment]
I will close this issue, feel free to reopen it in case my suggestion did not solved the issue
