### ISSUE TITLE
Evaluating of geometry members fails with ThreadAbortException when debugging code that is running in a separate thread

### ISSUE THREAD

**Issue by SAASTN** [NetTopologySuite/NetTopologySuite#573]
### Prerequisites

- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [ ] ~~I have verified if the problem exist in both `DEBUG` and `RELEASE` mode~~ It's a debugging problem
- [x] I have written a descriptive issue title

### Description
I recently have moved part of my code to async methods. Ever since I'm having trouble debugging NTS related parts. All members are working fine when I use them from code. But when I place a break point and try to evaluate them with a watch or in the Quick Watch window, it says 
> '_the expression_' threw an exception of type 'System.TypeInitializationException'	string {System.TypeInitializationException}

For example, evaluating a polygon's `AsText()` throws the followings:
> The type initializer for 'NetTopologySuite.Geometries.Geometry' threw an exception.
> The type initializer for 'NetTopologySuite.Geometries.GeometryFactory' threw an exception.
> Thread was being aborted.

### Steps to Reproduce
I was able to reproduce the error with the following example:
```
private static void Run()
{
    Console.WriteLine("run started");
    Polygon polygon = new NetTopologySuite.Utilities.GeometricShapeFactory()
    {
        Width = 10,
        Height = 10,
        NumPoints = 5
    }.CreateRectangle();
    Console.WriteLine(polygon.AsText());
    Console.WriteLine("run ended");
}

static void Main(string[] args)
{
    Thread thread = new Thread(Run);
    thread.Start();
    while (thread.IsAlive)
    {
        Thread.Sleep(100);
    }
    Console.WriteLine("done");
    Console.ReadLine();
}
```
1. Place a break point on the _"run ended"_ line
2. Run the program in Debug mode
3. When execution breaks the previous line (`Console.WriteLine(polygon.AsText());`) has produced the expected output
4. Now try to evaluates the same expression, `polygon.AsText()`, in the quick watch window

Here I get the mentioned exception instead of the evaluation result. So am I doing something terribly wrong?

### System Configuration
- NetTopologySuite version: 2.4
- Other NetTopologySuite packages and versions: none
- Environment: 
    - win10 v2004 build 19041.264
    - VS 2019 version 16.11.05
    - VMware Workstation Pro version 15.5.2 build-15785246
- .NET Framework version: 4.8

**Comment by FObermaier** [comment]
I'm sorry, I can't reproduce your issue, so I'm guessing:
* Instantiate `NtsGeometryServices.Instance` at the very beginning of your application.
  see: [Getting Started](https://github.com/NetTopologySuite/NetTopologySuite/wiki/GettingStarted)

**Comment by SAASTN** [comment]
Thanks Felix. I tried instantiating `NtsGeometryServices`, but no success. The fact that you said you do not see the error, persuaded me to run the program in VS 2017 as well. Surprisingly, all the members get evaluated there without any problems. So definitely something's wrong with 2019.
I searched but could not find anything about that. Do you have any idea how I can further investigate the issue?

**Comment by jnyrup** [comment]
Disabling "Just My Code" gives some extra hints.
![image](https://user-images.githubusercontent.com/919634/144408096-fc6d5d28-4c3f-40b7-953d-d4a19b634390.png)

The exception happens when calling `Lazy<T>.Value` in the initialization one the static fields of `GeometryFactory`.

.net 4.8 [`Lazy<T>.Value`](https://referencesource.microsoft.com/#mscorlib/system/Lazy.cs,606a17645b0dc0ff)
calls `Debugger.NotifyOfCrossThreadDependency()`.

.net 6 [`Lazy<T>.Value`](https://source.dot.net/#System.Private.CoreLib/Lazy.cs,606a17645b0dc0ff)
does not call `Debugger.NotifyOfCrossThreadDependency()`.

**Comment by grizoood** [comment]
I have the exact same problem, works fine in Release but in Debug I have an exception: TypeInitializationException

**Comment by FObermaier** [comment]
Thanks @jnyrup  for the useful information around Lazy and NotifyOfCrossThreadDependency.

@SAASTN and @grizoood, objects that have some Lazy instantiation are:
* `NetTopologySuite.Geometries.PrecisionModel.Floating`
  (This one is used by default for a new `NetTopologySuite.NtsGeometryServices` instance)
* `NetTopologySuite.Geometries.PrecisionModel.FloatingSingle`
* `NetTopologySuite.Geometries.PrecisionModel.Fixed`
For these it might help to call `NetTopologySuite.Geometries.PrecisionModel.Floating[|Single|Fixed]MakePrecise(0d)` prior to starting your debug session.

The only other spot:
* `NetTopologySuite.Geometries.GeometryFactoryEx._polygonShellRingOrientation`
If this one is the cause, you probably need to create a `Polygon` with that factory first, so that the value is instantiated.

**Comment by grizoood** [comment]
@FObermaier I tried, it doesn't change anything.  When I instantiate NtsGeometryServices I always get the same error... I don't know what to do to debug.

**Comment by DGuidi** [comment]
I was able to reproduce the error

**Comment by DGuidi** [comment]
here's the smallest possible program that reproduces the error
```
using NetTopologySuite;
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("run started");
            var factory = NtsGeometryServices.Instance.CreateGeometryFactory();
            //var factory = GeometryFactory.Default; // Works on my machine
            var geom = factory.CreatePolygon();
            Console.WriteLine(geom.AsText());
            Console.WriteLine("run ended"); // put geom.SRID/geom.IsValid/geom.AsText() in the immediate window
            Console.WriteLine("done");
            Console.ReadLine();
        }
    }
}
```

**Comment by FObermaier** [comment]
@DGuidi found the solution:
```C#
var some_factory_that_I_may_or_may_not_use = 
    NetTopologySuite.Geometries.GeometryFactory.[Default|Floating|FloatingSingle|Fixed];
```
Assign any of the predefined factories right at startup to a factory that you may or may not use in the course of your application.

**Comment by DGuidi** [comment]
I can confirmed that the workaround works

**Comment by rcollette** [comment]
That closes the issue? This is relying on a secondary effect for initialization and there are no documentation updates.

**Comment by DGuidi** [comment]
> That closes the issue?

Yep, at least for me. The problem seems related to some interaction with the visual studio debugger with framework 4.8, so for me no need to go deeper. you can do something like this
```
#if DEBUG
var forgetAboutIt = GeometryFactory.Default;
#endif
```

**Comment by SAASTN** [comment]
> @DGuidi found the solution:
> 
> ```cs
> var some_factory_that_I_may_or_may_not_use = 
>     NetTopologySuite.Geometries.GeometryFactory.[Default|Floating|FloatingSingle|Fixed];
> ```
> 
> Assign any of the predefined factories right at startup to a factory that you may or may not use in the course of your application.

Thanks @FObermaier. I can also confirm that the workaround resolves the problem. Back here, all used NTS methods are wrapped in a static class. I added the following to the very first line of the wrapper class and done:
```
#if DEBUG
        /// <summary>
        /// The following assignment is only a workaround to solve the problem of debugging geometries in VS2019 when running async codes.
        /// Read <see href="https://github.com/NetTopologySuite/NetTopologySuite/issues/573">this thread</see> for more information.
        /// </summary>
        private static GeometryFactory theDefaultFactory = GeometryFactory.Default;
#endif
```

**Comment by DGuidi** [comment]
you shoud just add this code in the very first method that is called in your revit addin (like some `Initialize`, `Setup` ot similar methods)
```
#if DEBUG
        private static GeometryFactory theDefaultFactory = GeometryFactory.Default;
#endif
```
you just need to check revit addin documentation to find this method.

An easier thing that should work can be to add the same code to the static constructor
```
internal class NTS
{
static NTS()
{
#if DEBUG
        private static GeometryFactory theDefaultFactory = GeometryFactory.Default;
#endif
}
... // use exactly the same code are you using
}
```

**Comment by DGuidi** [comment]
an updated version of your code
```
internal class NTS
{
       #region Constants

       private const double _eps = 1e-9; //1.e-9 Revit

       #endregion

       #region Fields

       private static GeometryFactory _geometryFactory;

       #endregion

       #region Properties

       internal static int NtsSRID => 4326;

       internal static double Eps => _eps;

       static NTS()
       {
       #if DEBUG
              private static GeometryFactory theDefaultFactory = GeometryFactory.Default;
       #endif

       var precisionModel = new PrecisionModel(1 / _eps);
       precisionModel.MakePrecise(0d);
       NtsGeometryServices.Instance = new NtsGeometryServices(
              CoordinateArraySequenceFactory.Instance,
              precisionModel,
              NtsSRID,
              GeometryOverlay.NG,
              new CoordinateEqualityComparer());
}

       internal static NtsGeometryServices GetNtsGeometryServices
       {
              get
              {
                     return NtsGeometryServices.Instance;
              }
       }

       internal static GeometryFactory GetGeometryFactory
       {
              get
              {
                     if (_geometryFactory != null)
                           return _geometryFactory;
                    _geometryFactory = GetNtsGeometryServices.CreateGeometryFactory(NtsSRID);
                     return _geometryFactory;
              }
       }
}
```

**Comment by grizoood** [comment]
Nickel, I didn't use the static property:

```cs
NtsGeometryServices.Instance
```

because between 2 addins, this one can be modified, I created my own NtsGeometryServices instance.

```csharp
var precisionModel = new PrecisionModel(1 / _eps);
precisionModel.MakePrecise(0d);
_ntsGeometryServices = new NtsGeometryServices(
       CoordinateArraySequenceFactory.Instance,
       precisionModel,
       NtsSRID,
       GeometryOverlay.NG,
       new CoordinateEqualityComparer());
```

Here is my final class: 

```csharp
internal class NTS
{
    #region Constants

    private const double _eps = 1e-9; //1.e-9 Revit

    #endregion

    #region Fields

    private static NtsGeometryServices _ntsGeometryServices;


    private static GeometryFactory _geometryFactory;

    #endregion

    #region Properties

    internal static double Eps => _eps;

    internal static int NtsSRID => 43267;

    internal static NtsGeometryServices GetNtsGeometryServices => _ntsGeometryServices;

    internal static GeometryFactory GetGeometryFactory
    {
        get
        {
            if (_geometryFactory != null)
                return _geometryFactory;
            _geometryFactory = GetNtsGeometryServices.CreateGeometryFactory(NtsSRID);
            return _geometryFactory;
        }
    }

    #endregion

    #region Constructors

    static NTS()
    {
DEBUG
        // Assign GeometryFactory.Default to make sure lazy properties are 
        // properly instantiated and debugging works without exceptions 
        // https://github.com/NetTopologySuite/NetTopologySuite/issues/573
        var theDefaultFactory = GeometryFactory.Default;
if

        var precisionModel = new PrecisionModel(1 / _eps);
        precisionModel.MakePrecise(0d);
        _ntsGeometryServices = new NtsGeometryServices(
               CoordinateArraySequenceFactory.Instance,
               precisionModel,
               NtsSRID,
               GeometryOverlay.NG,
               new CoordinateEqualityComparer());
    }

    #endregion
}
```

 thank you (@DGuidi  @FObermaier) 👍 👍 👍
