### ISSUE TITLE
WKTReader.Read() method returning MissingMethodException

### ISSUE THREAD

**Issue by Markemp** [NetTopologySuite/NetTopologySuite#576]
### Prerequisites

- [✔] I have written a descriptive issue title
- [✔] I have verified that I am running the latest version of NetTopologySuite
- [✔] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [✔] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When attempting to convert a WKT to a Geometry object, the code is throwing a MissingMethodException.  The project is a kafka consumer that is reading a topic that contains a (valid) WKT.  When trying to convert it to an IGeometry object, it fails with the exception.  There is another project in this Solution that is also using the NetTopologySuite libraries as well, but it is working properly (although not using the `.Read()` method).

### Steps to Reproduce
Just run the project.  As it gets the WKT string and attempts to convert it, the exception is thrown. 

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: v2.4.0
- Other NetTopologySuite packages and versions:
  - NetTopologySuite.Core version v.1.15.3
- Environment (Operating system, version and so on): Windows 10 running through Visual Studio
- .NET Framework version:  .Net 6
- Additional information:  
I've tried various combinations of NetTopologySuite and GeoAPI (including the .Core packages) and nothing seems to make a difference.  I have another .Net 6 Solution where the same code is working, but this Solution has the NetTopologySuite packages assigned to a couple of projects.  It has no problem compiling the code, but when it gets to the part where it has to convert the WKT to an IGeometry object, it throws the exception.

![image](https://user-images.githubusercontent.com/12057128/146029461-6ef94bf8-8266-4034-8dfe-2e23aca36e9e.png)

**Comment by airbreather** [comment]
> - Other NetTopologySuite packages and versions:
>    - NetTopologySuite.Core version v.1.15.3

Please remove NetTopologySuite.Core references when working with NetTopologySuite 2.0+

**Comment by Markemp** [comment]
Our models are expecting a `GeoAPI.Geometries.IGeometry` type.  There doesn't seem to be a way to cast the NetTopologySuite `Geometry` output, and it's not inheriting from the `IGeometry` interface either.  Is there another way to get around this?

With the other solution that is doing this, we are using `NetTopologySuite.Core` and `GeoApi.Core` to convert the WKT to an IGeometry object, but this solution is throwing the error whenever it tries the conversion.

**Comment by airbreather** [comment]
NetTopologySuite 2.x types are incompatible with NetTopologySuite / NetTopologySuite.Core / GeoAPI.Core 1.x packages.  You will need to choose one or the other within a given solution.  You can, of course, create WKT using NTS 1.x and parse it using NTS 2.x.

In NetTopologySuite 2.x, there is no `GeoAPI.Geometries.IGeometry`.  There's just `NetTopologySuite.Geometries.Geometry`.

See https://github.com/NetTopologySuite/NetTopologySuite/wiki/Upgrading-to-2.0-from-1.x for documentation on this and other breaking changes.

**Comment by Markemp** [comment]
Ah, thanks for that link!  Looks like I'll have to do some refactoring so that everything this up to the 2.x standard now.  I appreciate the rapid response!
