### ISSUE TITLE
GeoJsonSerializer cannot serialize properties that are objects

### ISSUE THREAD

**Issue by jnicho02** [NetTopologySuite/NetTopologySuite#58]
given a geojson property that is an object then the serializer attempts to add the 'properties' attribute more than once.

I have a very quick fix and will submit a pull request with some accompanying tests

the following won't work....

```C#
const string geojsonString = @"
{
  ""type"": ""FeatureCollection"",
  ""features"": [
    {
      ""type"": ""Feature"",
      ""geometry"": {
        ""type"": ""Point"",
        ""coordinates"": [
          1.0,
          2.0
        ]
      },
      ""properties"": {
        ""foo"": {
          ""bar"": ""xyz""
        }
      }
    }
  ]
}
";
var reader = new GeoJsonReader();
var resultCollection = reader.Read<FeatureCollection>(geojsonString);
var gjs = new GeoJsonWriter();
gjs.Write(resultCollection);
```

**Comment by DGuidi** [comment]
@jnicho02 which NTS version do you use? can you check using latest version from source code?

**Comment by jnicho02** [comment]
I'm using the current live major Nuget package 1.13.3.2

If I do a fork/pull request which branch should I base it on? master?

This is a fairly simple change, but i'd like to be able to contribute in the future

**Comment by DGuidi** [comment]
Pleasw fork current master, check if bug persist and then fix+pull request

----- Messaggio originale -----
Da: "Jez Nicholson" <notifications@github.com>
Inviato: ‎07/‎10/‎2015 12:30
A: "NetTopologySuite/NetTopologySuite" <NetTopologySuite@noreply.github.com>
Cc: "Diego Guidi" <diegoguidi@gmail.com>
Oggetto: Re: [NetTopologySuite] GeoJsonSerializer cannot serialize propertiesthat are objects (#58)

I'm using the current live major Nuget package 1.13.3.2
If I do a fork/pull request which branch should I base it on? master?
This is a fairly simple change, but i'd like to be able to contribute in the future

**Comment by DGuidi** [comment]
@jnicho02 I'm checking and problem persists also in master.

**Comment by DGuidi** [comment]
@jnicho02 can you please check?

**Comment by jnicho02** [comment]
it looks good to me. Thank you.

I've got another one....about reading array properties. Will raise an issue.
