### ISSUE TITLE
CLA issue

### ISSUE THREAD

**Issue by sindizzy** [NetTopologySuite/NetTopologySuite#581]
I've added a pull request here https://github.com/NetTopologySuite/NetTopologySuite/pull/580 and I followed the link to sign the CLA. However, I still get this message "Perez seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.".

I am signed in with GitHub and only have one email address. So not sure why it's not going through.

**Comment by airbreather** [comment]
> I am signed in with GitHub and only have one email address. So not sure why it's not going through.

The e-mail address that needs to be added to your GitHub account is the one that was used for creating the commits, which is `<digits>@corpaa.aa.com`, where "`<digits>`" is a sequence of digits that I will not repeat on this comment.

I can neither confirm nor deny that this e-mail is present on your GitHub account.

**Comment by sindizzy** [comment]
Oooooo that's my work account. I created this commit with GitHub Desktop and am signed in to my personal account. Let me scope that out.

**Comment by sindizzy** [comment]
I don't get it. On GitHub Desktop I am signed in to my personal account. In the browser I'm also signed in to the same account. When I look at my settings it only has one email, my personal email.

![image](https://user-images.githubusercontent.com/5298460/148618481-d3bc1b62-caca-48a5-a31a-d08d4743182a.png)

**Comment by sindizzy** [comment]
Further if I go to my PR list I see the dateline PR I added

![image](https://user-images.githubusercontent.com/5298460/148619315-5b41ec46-1693-406f-80ee-02f3ee5dc7c0.png)

**Comment by airbreather** [comment]
> On GitHub Desktop I am signed in to my personal account.

Perhaps you're using a different Git client to create the commits, and all that GitHub Desktop is doing is merely pushing them up?  There's nothing about Git that would fundamentally stop you from creating a commit that **appears** to be made by someone else, and then using your GitHub account to push it to a GitHub repository that your GitHub account controls.
- As an aside. some people have taken this fact and had a bit of lighthearted fun with it.  e.g., Amog-OS/AmogOS@4f503a0b491434eba5e038e341c75e8e3122dc71 **looks** like an uncharacteristically unprofessional commit made by a well-known public figure who almost certainly had nothing to do with that actual commit.

Just a hunch: is there anything in either the `.git/config` folder at the root of your local clone of this repository, and/or (if you're on Windows) your `%USERPROFILE%\.gitconfig` file that looks like it might be the cause of this?

**Comment by sindizzy** [comment]
Nope I only use Desktop. Let me check one other thing.

**Comment by sindizzy** [comment]
Ok what it appears is that the commits were done when I was VPN'ed into my work network. When I am connected to the network my full user profile is <digits>@corpaa.aa.com. It's not an email as I never use that address for emails. But I am puzzled as to why the commits were made under that email when I was logged in to my personal account in GitHub Desktop and website. I **was** signed in to my work email in the browser at the time so maybe that sign-in was propagated to GitHub ???

**Comment by sindizzy** [comment]
I also checked .git/config folder and %USERPROFILE%\.gitconfig and dont see any user related info in there.

**Comment by sindizzy** [comment]
OK I installed Git and set up the global gitconfig to my user email. I then do a small commit and it seems that now it is working. Question: how would I change the user in the other commits?

![image](https://user-images.githubusercontent.com/5298460/148658056-5cc538c1-dab9-4ef3-ad1b-d9a104516c85.png)

**Comment by sindizzy** [comment]
This link seems to show me how to change published commit author. I can try this as I have already backed up my code on my laptop. The only thing don't understand is when it says "identify the last 'good' commit". In my case https://github.com/NetTopologySuite/NetTopologySuite/pull/580/commits would that be 2c7852a?
