### ISSUE TITLE
Polyline offset with variable width ("buffer")?

### ISSUE THREAD

**Issue by WindingWinter** [NetTopologySuite/NetTopologySuite#582]
I find it interesting that unlike many libraries out there, NetTopologySuite contains a [VariableBuffer](https://nettopologysuite.github.io/NetTopologySuite/api/NetTopologySuite.Operation.Buffer.VariableBuffer.html#NetTopologySuite_Operation_Buffer_VariableBuffer__ctor_NetTopologySuite_Geometries_Geometry_System_Double___) class that allows one to specify _variable_ buffer at each vertex. This is useful as it's not always that we have uniform buffer throughout.

But my use case is a bit different; I'm not really doing polygon offset-- in which you have to "blow up" a polyline into a close form polygon. I need to do _polyline_ offset with variable width or buffer, something like [Cavalier Contours](https://github.com/jbuckmccready/CavalierContours) is doing for uniform offset.

![Polyline offset](https://raw.githubusercontent.com/jbuckmccready/CavalierContoursDoc/master/images/pretty_examples/example1.png)

Is there any chance that NetTopologySuite can handle polyline offset ( which I think uses a different algorithm that polygon offset)?

**Comment by FObermaier** [comment]
I'm afraid there is no such functionality within `NetTopologySuite`.
