### ISSUE TITLE
Adding some properties to GeometryOverlay and CoordinateEqualityComparer

### ISSUE THREAD

**Issue by edihasaj** [NetTopologySuite/NetTopologySuite#584]
I've been having some issues with GraphQL library from Hotchocolate. You can follow this link to check the status of the issue there and in dotnet/efcore library as well. #https://github.com/ChilliCream/hotchocolate/issues/4579

After debugging the error, I've seen that some changes made in your library has affeced the standard that GraphQL uses based on the specification [GraphQL specs](https://spec.graphql.org/June2018/#sec-Input-Objects)

Now having this information I've seen that you have made some changes to CoordinateEqualityComparer making the class methods obsolete like i.e. 'Equals' method in class Geometry, replacing with Equals method in CoordinateEqualityComparer (but that the latter has no properties defined), or creating an instance of GeometryOverlay (has no properties defined) from Factory class. 

Having no properties and being used in other Geometry types like Point, Polygon, MultiPolygon, etc., causes some problems in our use case. Is it allowed to add two random properties (one for each) in those two classes (I make a PR here), or you have a better proposal?

Any help would be much appreciated. Thanks

**Comment by FObermaier** [comment]
You can implement you own `CoordinateEqualityComparer` class with the semantics you want and then set up your `NtsGeometryServices.Instance` using just that. You should be all set.

see: https://github.com/NetTopologySuite/NetTopologySuite/wiki/GettingStarted

**Comment by edihasaj** [comment]
Ok, technically this seems to be good with that. Thank you for your support 👊
