### ISSUE TITLE
How to get the same rounding with WKTWriter and WKTReader?

### ISSUE THREAD

**Issue by grizoood** [NetTopologySuite/NetTopologySuite#587]
### Prerequisites

- [ X] I have written a descriptive issue title
- [ X ] I have verified that I am running the latest version of NetTopologySuite
- [ X ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [  X] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I don't get the same result when reading with the WKTReader function.

### Steps to Reproduce
```csharp
var precisionModel = new PrecisionModel(1 / 1e-9);
precisionModel.MakePrecise(0d);
var ntsGeometryServices = new NtsGeometryServices(
         CoordinateArraySequenceFactory.Instance,
         precisionModel,
         4236,
         GeometryOverlay.NG,
         new CoordinateEqualityComparer());

var geofactory = ntsGeometryServices.CreateGeometryFactory(4236);

var point1 = geofactory.CreatePoint(new Coordinate(10.39452545417d, 0));
var reader = new WKTReader(ntsGeometryServices);
var point2 = reader.Read(point1.ToString());
```

point1 => `{POINT (10.3945254542 0)}`
point2 =>` {POINT (10.394525454 0)}`

point1 to one decimal place more (2).

### System Configuration
- NetTopologySuite version: 2.4.0
- .NET Framework version: 4.8

**Comment by FObermaier** [comment]
The GeometryFactory methods do not use the PrecisionModel internally when creating a Geometry. That is for performance reasons. You need to use the PrecisionModel before you use the GeometryFactory.

**Comment by grizoood** [comment]
Could you provide me an example based on my code.  thank you

**Comment by FObermaier** [comment]
```C#
// Create Coordinate
var coord1 = geoFactory.PrecisionModel.MakePrecise(new Coordinate(10.39452545417d, 0));
var point1 = geofactory.CreatePoint(coord1);
```

**Comment by grizoood** [comment]
For information the MakePrecise method returns void.

```csharp
// Create coordinate
var coordinate1 = new Coordinate(10.39452545417d, 0);
// Set coordinate precision
geoFactory.PrecisionModel.MakePrecise(coordinate1);
// Create point
var point1 = geofactory.CreatePoint(coord1);
```

**Comment by FObermaier** [comment]
> For information the MakePrecise method returns void.

Good catch 🥇
