### ISSUE TITLE
KMLReader stuck infinite loop on <Polygon>

### ISSUE THREAD

**Issue by CMihalcik** [NetTopologySuite/NetTopologySuite#594]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
KMLReader gets stuck in an infinite loop when reading a polygon with optional KML elements that are not passed to the KMLReader constructor.

### Steps to Reproduce
The following code will not terminate:
```
string kml = @"<Polygon>
      <extrude>1</extrude>
      <altitudeMode>relativeToGround</altitudeMode>
      <outerBoundaryIs>
        <LinearRing>
          <coordinates>-122.366278,37.818844,30 -122.365248,37.819267,30 -122.365640,37.819861,30 -122.366669,37.819429,30 -122.366278,37.818844,30</coordinates>
        </LinearRing>
      </outerBoundaryIs>
    </Polygon>";
KMLReader kmlReader = new KMLReader();
kmlReader.Read(kml);
```

However, passing the names of the optional elements to the constructor leads to a successful read.

```new KMLReader("extrude", "altitudeMode", "tessellate")```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.4.9
- Other NetTopologySuite packages and versions: n/a
- Environment (Operating system, version and so on): macOS 10.15
- .NET Framework version: 6.0.100
- Additional information:

**Comment by mathias13** [comment]
Hello 
I created this issue https://github.com/NetTopologySuite/GeoAPI/issues/72
I'm a little further behind on versions because i use Dotspatial but i see that theese issues may be related.
Maybe i should move my issue to [NetTopologySuite](https://github.com/NetTopologySuite/NetTopologySuite) instead cause the Coordinate.cs is here in the current version and would produce the same problem.
