### ISSUE TITLE
Link to JTS Topology Suite licenses is broken

### ISSUE THREAD

**Issue by UniQP** [NetTopologySuite/NetTopologySuite#596]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce
- Open https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/License.md
- Search for https://github.com/locationtech/jts/LICENSES.md
- Click on the link

### Actual behavior
- Not Found (link is broken)

### Expected behavior
- Link points to https://github.com/locationtech/jts/blob/master/LICENSES.md

**Comment by FObermaier** [comment]
Thanks for pointing that out.
