### ISSUE TITLE
CoordinateArraySequence and Ordinate.M

### ISSUE THREAD

**Issue by GHoven** [NetTopologySuite/NetTopologySuite#60]
If CoordinateArraySequenceFactory.Create(int size, int dimension) (which is the Default factory) is used with dimension = 4, the returning CoordinateArray will claim it has Ordinates XY.

Reason is this peace of Code in NetTopologySuite.Geometries.Implementation.CoordinateArray.cs
```c#
public Ordinates Ordinates
        {
            get
            {
                return _dimension == 3 
                    ? Ordinates.XYZ 
                    : Ordinates.XY;
            }
        }
```
I had this Problem, because customers data contains XYZM geometries with was read with GaiaGeoReader and he only received XY geometries. This was a problem, because he was especially interested in Z values.

My suggestion is to change the statement from 
```c#
return _dimension == 3 
```
to
```c#
return _dimension >= 3 
```
Even if a CoordinateArray can not hold M values, it should not throw away Z values, e.g. when geometries are read with GaiaGeoReader.

As you can see, I'm new to github. Is this a major change, which needs an extensive discussion or did I just find a bug?

Please, any of you github NetTopologySuite pros, can you leave any comment in this?

**Comment by FObermaier** [comment]
CoordinateArraySequence cannot store Ordinate.M values.
You will have to use a different `ICoordinateSequence` implementation.

You can either create your own or use either
- `PackedCoordinateArraySequence`
- `DotSpatialAffineCoordinateSequence`

If I'm not mistaken, there is also the choice of `ExtendedCoordinateArraySequence` somewhere in the samples projects.

To use these, you have to set `GeometryFactory.DefaultCoordinateSequenceFactory` to the appropriate factory.

**Comment by GHoven** [comment]
I know that there are more ICoordinateSequence in NTS. My suggestion aimed to add better functionality with CoordinateArray when used unaware with ZM values: Keep Z data in these cases.
