### ISSUE TITLE
Line Segment GetHashCode is prone to hash collision

### ISSUE THREAD

**Issue by Skibisky** [NetTopologySuite/NetTopologySuite#607]
### Description
[LineSegment.GetHashCode()](https://github.com/NetTopologySuite/NetTopologySuite/blob/cdaed3e9a8c7167f2d0fa6d0fca65e64748ddbfe/src/NetTopologySuite/Geometries/LineSegment.cs#L701) is very prone to collisions.
Hash collisions result in calling .Equals() when used in some standard data structures.
This causes massive performance degradation.

### Steps to Reproduce
Use LineSegment as a key in a dictionary.

### Tests
__Current GetHashCode implementation:__
Creating grid of 500
\# squares: 500000
Finished in 102283 ms

__[Community Acceptable](https://stackoverflow.com/questions/263400/what-is-the-best-algorithm-for-overriding-gethashcode) implementation__
Creating grid of 500
\# squares: 500000
Finished in 190 ms

**Comment by dr-jts** [comment]
I implemented the proposed `LineSegment.hashCode` algorithm and the performance test, and it is indeed MUCH faster.  I'll be making a PR soon.  I'd say you can go ahead and make this change in NTS as well.
