### ISSUE TITLE
Determining reason for WKT reader returning 'invalid' geoemetry 

### ISSUE THREAD

**Issue by hf-farmqa** [NetTopologySuite/NetTopologySuite#613]
### Description
This is perhaps more of a question than an issue so I apologize if you interpret this as spam however I ran across an issue with the WKTReader when parsing a specific WKT geometry found within the attached file: [ProblemWKT.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/8871527/ProblemWKT.txt).

The core of my question is that I don't know 'why' this WKT is being treated as invalid and the resultant Geometry object does not contain any detail as to the reasons. 

### Steps to Reproduce
-- C# --
```
Geometry geometry = new NetTopologySuite.IO.WKTReader().Read(<Value>);
Console.WriteLine(geometry.IsValid); // False
```

It came across as odd to me because I'm able to validate the validity of the shape using some other other tools 

-- SQL --
```
DECLARE @g geography;  
SET @g = geography::STGeomFromText(<Value>, 4326);  
SELECT @g.ToString(), @g.STIsValid() // True
```

-- QGIS --
Converted WKT to [ProblemGeoJson.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/8871650/ProblemGeoJson.txt) and imported as a new layer
Vector -> Geometry Tools -> Check Validity -> True (or rather no issues reported)

I will certainly grant that different tools work on different rulesets so I'm mostly trying to figure out what is tripping up NetTopology here so that I can understand how to react to failures and/or put restrictions on the inputs to avoid the problems in the first place.

As a workaround I did find that the GeoemetryFixer spits out a valid shape that appears to be a decent enough approximation of the original inputs. I'd like to avoid that as we still want to reject truly invalid inputs and so don't want to accidentally patch up and accept real garbage or grossly oversimplify a shape just to make it work.
```
Geometry fixedGeo = NetTopologySuite.Geometries.Utilities.GeometryFixer.Fix(geometry);
Console.WriteLine(fixedGeo.IsValid); // True
```

Thanks for any insight you can provide

### System Configuration
- NetTopologySuite version: 2.4.0
- .NET Framework version: 472

**Comment by FObermaier** [comment]
I cannot reproduce your issue. With the current codebase the geometry is read alright and it is valid, too.
If you need more information on the cause of a geometry's invalidity, you have to use `NetTopologySuite.Operation.Valid.IsValidOp`:

```C#
var op = new NetTopologySuite.Operation.Valid.IsValidOp(geom);
if (!op.IsValid)
{
    var ve = op.ValidationError;
    // handle ve
}
```

**Comment by hf-farmqa** [comment]
Thanks for quick response and the pointer to 'IsValidOp'.

I monkeyed around with things further and dug into the NetTopologySuite codebase a bit more since I was still failing and found out that out that we were setting the NtsGeometryServices.Instance up with FloatingSingle as the defaulting PrecisionModel.

To no one's surprise this causes significantly ~~delicate~~ complex shapes to fail as a result of mi-nute clipping and shifting.
So... EBKAC

Sorry to have caused an unnecessary investigation and thanks again for taking a look.
