### ISSUE TITLE
Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite not working with .NET6.0 application

### ISSUE THREAD

**Issue by jessecallahan** [NetTopologySuite/NetTopologySuite#619]
## Trying to update application .NET 6.0 while class library targets  .NETstandard 2.0.

We are trying to update our application to .NET6.0.

We have a class library that is a dependency and it targets .NETstandard 2.0.

According to NuGet.org, Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite v.3.1.8 should support .NET6.0 (it's listed as additional computed target framework) 

However at runtime we are getting the error:
```
System.TypeLoadException: 'Method 'GetServiceProviderHashCode' in type 'ExtensionInfo' from assembly 'Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'
```

Class Library:
EF Core version: 3.1.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite
Target framework:  .NETstandard 2.0

Application: 
EF Core version: 6.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework:  .NET6

Operating system: Windows 11 Pro
IDE: Visual Studio 2022 17.2

**Comment by FObermaier** [comment]
`Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite v.3.1.8` is not our library. This is the wrong place to ask this question.

**Comment by airbreather** [comment]
You need to upgrade all your `Microsoft.EntityFrameworkCore` packages together.

Latest `Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite` is 6.0.6.
