### ISSUE TITLE
Sqlite migrations: table rebuild with spatial column errors out

### ISSUE THREAD

**Issue by d79ima** [NetTopologySuite/NetTopologySuite#622]
### Description
I am using EF Core 5.013 targeting SQLite.
I have a simple table with a few columns, including a GEOMETRY column for which i am using NetTopologySuite 5.013 to match EF Core version.
If i create a migration where i drop one of the regular (non-Geometry) columns, and try to create a database, will get an error with the following message: 
Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'table ef_temp_MyTableName has no column named MyGeometryColumnName'.

If i perform the same drop column migration on a table that has no Geometry columns, then it has no problems.

### System Configuration
- NetTopologySuite version: 5.013
- Environment: Windows 10x64
- .NET Framework version: core 3.1

**Comment by DGuidi** [comment]
Looks not related at all with NTS to me. I suggest to verify if the behaviour happens also with non-spatial tables, and then ask in some ef.core projects

**Comment by DGuidi** [comment]
As you write, geometry columns are handled by EF and they do not have nothing to do with the NTS library itself. So I suggest to post the same issue in the EF GitHub page

**Comment by d79ima** [comment]
But aren't geometry columns only enabled with NetTopologySuite? If i dont pull in NetTopologySuite and call UseNetTopologySuite() in DbContext.OnConfiguring, EF Core has no idea what a Geometry type even is. On my model the Geometry type comes from NetTopologySuite.Geometries namespace. So i don't see how this is not a NetTopologySuite-related issue. If i post this on the EF Core GitHub page they will refer me to this GitHub page.

**Comment by d79ima** [comment]
i raised same issue with attached sample on EF Core github site just in case: https://github.com/dotnet/efcore/issues/28384
