### ISSUE TITLE
Unable to install prerelease packages in .NET 4.5 project

### ISSUE THREAD

**Issue by xivk** [NetTopologySuite/NetTopologySuite#63]
Steps to reproduce:

- Create a new Console project targeting .NET 4.5.
- Try to add NetTopologySuite using the prerelease options.

GeoAPI 1.7.4 cannot be found, there does exist a package for GeoAPI also a prelease packages but that doesn't seem to be sufficient. I think the requirments 'GeoAPI (≥ 1.7.4 && < 1.8)' are too strict. 1.7.4-pre3 < 1.7.4.

Maybe the prerelease packages should not have embedded strict dependencies listed and we should leave it to the user to install the dependencies properly.

**Comment by xivk** [comment]
I need to update to the latest version beause there are several issues with writing shapefiles in the current release.

**Comment by FObermaier** [comment]
You can update the packages anyhow by using flag `-ignoredependencies`
But you are right, we need to correct the version constraints.

**Comment by xivk** [comment]
I'm prepared to submit a pull-request but how do you guys prefer to fix this? I'm not sure how to properly do this because the same nuspec files are used for release/prerelease.

**Comment by FObermaier** [comment]
I have no preference. Do you think nuspec files for prerelease versions/nightly builds are a good idea?

**Comment by FObermaier** [comment]
@xivk: Is this still an issue?

**Comment by xivk** [comment]
No not anymore sorry... closing... As long as this doesn't happen in the actual release packages then there's no real problem.
