### ISSUE TITLE
geojson deserialization insists on decimal places in coordinates

### ISSUE THREAD

**Issue by jnicho02** [NetTopologySuite/NetTopologySuite#64]
If points are specified without a decimal place then deserialization throws a

System.InvalidCastException: Specified cast is not valid.
Result StackTrace:	
at NetTopologySuite.IO.Converters.GeometryConverter.PointCoords(List`1 list)
at NetTopologySuite.IO.Converters.GeometryConverter.ParseGeometry(JsonReader reader)

to test:

const string geojsonString = @"
{
  ""type"":""FeatureCollection"",
  ""features"": [
    {
      ""type"":""Feature"",
      ""geometry"": {
        ""type"": ""Point"",
        ""coordinates"": [
          1,
          2
        ]
      }
    }
  ]
}
";
var reader = new GeoJsonReader();
var resultCollection = reader.Read<FeatureCollection>(geojsonString);

**Comment by jnicho02** [comment]
if you are using WGS84 then it is pretty likely that you will have decimal places, but if you are using something like GB National Grid then a location will frequently have no decimal places e.g. "530507, 180542" http://gridreferencefinder.com/?gr=TQ3050780542%7CPoint_s_A%7C0&t=Point%2520A&v=r

**Comment by FObermaier** [comment]
To me it is currently not clear why GeometryConverter has its own parsing of coordinates and does not rely on CoordinatesConverter class

**Comment by DGuidi** [comment]
maybe code should  be refactored to use coordinates converter
Il 20/ott/2015 02:34 PM, "Felix Obermaier" <notifications@github.com> ha
scritto:

**Comment by FObermaier** [comment]
It used to do that up to 36fafff8

**Comment by DGuidi** [comment]
a merge for #6, am I right?

**Comment by FObermaier** [comment]
Yes. I checked that in.

**Comment by DGuidi** [comment]
@FObermaier no bad feelings.
I can check this issue, I hope soon.
Now we have more tests in GeoJSON stuff, so I hope to made a solution that fix this issue and doesn't broke standard behavior.

**Comment by jnicho02** [comment]
I'm working on a microservices platform at the moment. So there is a lot of
serialisation/deserialisation as the outputs of one service are consumed as
the input to another. If you want some more basic unit tests for the
geojson then I could probably provide some.

**Comment by FObermaier** [comment]
> I'm working on a microservices platform at the moment.

So you are using the PCL version of GeoJSON? A unit test using the "normal" GeoJson project reveals no problems.

>If you want some more basic unit tests for the geojson then I could probably provide some

That would be great

**Comment by FObermaier** [comment]
The current code does not lead to a failure.
Could it be that a679d009b847340c01104b996332be8d58f4f234 fixed your problem?

**Comment by DGuidi** [comment]
@jnicho02 any news about this? do you provide some failure tests?

**Comment by jnicho02** [comment]
Hello. I'll schedule in some time to do some tomorrow.

**Comment by jnicho02** [comment]
That test mentioned by @FObermaier does prove that this is now fixed.

I am adding some geojson read-write and write-read tests anyway
