### ISSUE TITLE
ShapeFileDataReader fields indexing does not match value indexing

### ISSUE THREAD

**Issue by bojake** [NetTopologySuite/NetTopologySuite#647]
NetTopologySuite version=2.0.0 and ShapeFile version 2.1.0 for Net472.

ShapefileDataReader.GetValue(x) does not match with DbaseFileHeader.Fields[x]. This means the field name returned in Fields[x] does not correspond to the value returned from GetValue(x). In fact, to match them you must GetValue(x+1) to properly get the Fields[x] value that you expect.

I don't see this nuance documented anywhere. The list of data fields returned in the header should return the first field as the geometry data, which is an accurate description of what comes from GetValue(0).

**Comment by bojake** [comment]
This should have been posted to repo NetTopologySuite/NetTopologySuite.IO.ShapeFile, apologies.

**Comment by KubaSzostak** [comment]
Closed as posted in incorrect repository.
