### ISSUE TITLE
Geometry.Difference throws Exception "found non-noded intersection' where there is not non-noded intersection

### ISSUE THREAD

**Issue by UliEgger** [NetTopologySuite/NetTopologySuite#664]
### Description

The method Geometry.Difference uses OverlayOp.ComputeOverlay
In that method, there is a check 

                var nv = new EdgeNodingValidator(_edgeList.Edges);
                nv.CheckValid();

If one of the polygons has an exterior ring that uses one point twice as in the example of wkt1 Point (4, 2)

            string wkt1 = "POLYGON ((0 0, 0 4, 4 4, 4 2, 3 3, 3 1, 4 2, 4 0, 0 0),(1 1, 1 3, 3 2, 2 1, 1 1))";
            string wkt2 = "POLYGON ((-1 -1, -1 5, 1.5 5, 1.5 -1, -1 -1))";

The Difference method does not work. Polygon from wkt1 is also not classified as valid.
The Geometry.IsValid property returns false. I do not know why.

### Steps to Reproduce

Run the following code as tested in this Unit Test 

        [Test]
        public void TestNetTopologySuiteDifference()
        {
            string wkt1 = "POLYGON ((0 0, 0 4, 4 4, 4 2, 3 3, 3 1, 4 2, 4 0, 0 0),(1 1, 1 3, 3 2, 2 1, 1 1))";
            string wkt2 = "POLYGON ((-1 -1, -1 5, 1.5 5, 1.5 -1, -1 -1))";

            Polygon polygon1 = GetPolygonFromWkt(wkt1);
            Polygon polygon2 = GetPolygonFromWkt(wkt2);

            var difference = polygon1.Difference(polygon2);
        }

        private Polygon GetPolygonFromWkt(string wkt)
        {
            var reader = new WKTReader();
            var polygon = (Polygon)reader.Read(wkt);
            return polygon;
        }

This results in an exception with the message

found non-noded intersection between LINESTRING (4 4, 4 2) and LINESTRING (4 2, 4 0) [ (4, 2, NaN) ]

But the two LINESTRINGs have a common node 4 2 at their intersection.

**Comment by UliEgger** [comment]
I know I could switch the validation off by

OverlayOp.NodingValidatorDisabled = false;

But I am afraid I will not be informed in case a real problem exists.

**Comment by FObermaier** [comment]
The overlay code has been reworked. You can enable the new code by calling the following initialization code:
```C#
NtsGeometryServices.Instace = new NtsGeometryServices(GeometryOverlay.NG);
```
