### ISSUE TITLE
Using GeometryOverlay.NG results in incompatible geometries in case the default contructors are used.

### ISSUE THREAD

**Issue by UliEgger** [NetTopologySuite/NetTopologySuite#665]
### Description

I want to use GeometryOverlay.NG

So at the very beginning of the code (in the main method) I make a call
NtsGeometryServices.Instance = new NtsGeometryServices(GeometryOverlay.NG);

But this has no effect on GeometryFactory.Default, since this is a static member variable initialized only once.
So after the call above if I create any geometry in the usual way without an alternative GeometryFactory as second argument,
I get an incompatible geometry for all geometry operations such as e.g. Geometry.Difference

### Steps to Reproduce

        [Test]
        public void TestNetTopologySuiteGeometryOverlay()
        {
            NtsGeometryServices.Instance = new NtsGeometryServices(GeometryOverlay.NG);
            var linearRing = new LinearRing(new Coordinate[] { });

            Assert.AreEqual("NG", linearRing.Factory.GeometryServices.GeometryOverlay.ToString()); //error

        }

        [Test]
        public void TestNetTopologySuiteGeometryOverlay2()
        {
            NtsGeometryServices.Instance = new NtsGeometryServices(GeometryOverlay.NG);

            var factory = new GeometryFactory();

            var sequence = factory.CoordinateSequenceFactory.Create(new Coordinate[] { });

            var linearRing = new LinearRing(sequence, factory);

            Assert.AreEqual("NG", linearRing.Factory.GeometryServices.GeometryOverlay.ToString()); //works fine but more difficult to create the LinearRing

        }

**Comment by FObermaier** [comment]
Don't use `GeometryFactory.Default`, use `NtsGeometryServices.Instance.Create(...)`;

**Comment by UliEgger** [comment]
OK, but as you see from my first unit test, I don't use GeometryFactory.Default explicitly

It is the Code e.g. inside the constructor of LinearRing, that uses it

        public LinearRing(Coordinate[] points) :
            this(DefaultFactory.CoordinateSequenceFactory.Create(points), DefaultFactory) { }

public static readonly GeometryFactory DefaultFactory = GeometryFactory.Default;



Do you mean 

var factory = NtsGeometryServices.Instance.CreateGeometryFactory();

and then create the geometries as I did in the second example ?

**Comment by UliEgger** [comment]
Now I think I understood. You mean 

        [Test]
        public void TestNetTopologySuiteGeometryOverlay()
        {
            NtsGeometryServices.Instance = new NtsGeometryServices(GeometryOverlay.NG);

            var factory = NtsGeometryServices.Instance.CreateGeometryFactory();

            var linearRing = factory.CreateLinearRing(new Coordinate[] { });

            Assert.AreEqual("NG", linearRing.Factory.GeometryServices.GeometryOverlay.ToString()); //error

        }

**Comment by UliEgger** [comment]
.... but this would require many changes in our code !

**Comment by FObermaier** [comment]
I'm sorry, but using the geometry constructors directly has been discouraged ever since I've got in contact with NTS, in fact GeometryFactory has been present in the inital commit (b6f273231aa4931af92ac12cec7232b6d8f42cfe).

**Comment by DGuidi** [comment]
>  has been discouraged ever since I've got in contact with NTS

yep, JTS doesn't even provide costructors, that were added later the first release in NTS to support monoGIS (good old times)
maybe it's time to add the `[Obsolete]` attribute

**Comment by UliEgger** [comment]
Thank you very much! I am closing this issue.
