### ISSUE TITLE
NetTopologySuite (1.14) installed with NuGet installs assemblies with a missing reference.

### ISSUE THREAD

**Issue by sweco-sedahd** [NetTopologySuite/NetTopologySuite#67]
Tested with a new console app (.NET 4.5) and added NetTopologySuite and NetTopologySuite.IO
The and this test code to Main:
var factory = new GeometryFactory();
var shpReader = new ShapefileDataReader(@"testfile.shp", factory);
var shpType = shpReader.ShapeHeader.ShapeType;

Compiling the project gives the following error:
Error	1	The type 'NetTopologySuite.IO.Streams.IStreamProviderRegistry' is defined in an assembly that is not referenced. You must add a reference to assembly 'NetTopologySuite.IO, Version=1.14.0.0, Culture=neutral, PublicKeyToken=f580a05016ebada1'.	C:\Projects\TestNetTopologySuite\TestNetTopologySuite\Program.cs	16	4	TestNetTopologySuite

But there is no such assembly file to add.
With .NET Reflector I can see that it is these files that is referencing the missing file.
NetTopologySuite.IO.ShapeFile.Extended.dll and NetTopologySuite.IO.GeoTools.dll

**Comment by VictorVelarde** [comment]
Same issue for me... Any workaround?

**Comment by sweco-sedahd** [comment]
I rebuilt all from GitHub source and use those binaries for now.
Because then I could add the missing DLL (NetTopologySuite.IO.dll).

**Comment by VictorVelarde** [comment]
I'm trying right now to get it from "master", but I cannot compile it, due to several reference-problems in the solution. Any chance to get those binaries?

**Comment by VictorVelarde** [comment]
Hi @FObermaier 
Any plan to deploy the updated nuspec file' soon?

I'm in a hurry with a project and I would like to see my options. I need the v1.14 cause it solves some problems I've had with .geojson files (coming from qgis).

And thanks for your work in the library!. It is a must for our projects

**Comment by sweco-sedahd** [comment]
To build it you also need to get PowerCollections and then I had to unload several projects that do not build, like all test proj and anything related to PCL. That’s I all I did to be able to build from source.

**Comment by FObermaier** [comment]
I just pushed NetTopologySuite.IO.1.14.0.1 package.
Could you please see if that works?

**Comment by sweco-sedahd** [comment]
Yes, it seems to work, I don't have time for a full test but my simple testprojekt now compiles and runs with your latest package version (1.14.0.1).
Thanks.

**Comment by VictorVelarde** [comment]
*Great!* No compilation problems with the new package. Thank you Felix.
