### ISSUE TITLE
Polygon.Buffer returns a polygon with an unexpected protrusion

### ISSUE THREAD

**Issue by AgnetaRung** [NetTopologySuite/NetTopologySuite#678]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am making a buffer on a Polygon. The resulting polygon gets an unexpected protrusion.

![BufferedPolygon](https://user-images.githubusercontent.com/128351344/226286824-a6709dd9-beed-4011-8f16-c42d580e6748.png)

### Steps to Reproduce
```C#
var bufferParameters = new BufferParameters(
    quadrantSegments: 1,
    endCapStyle: EndCapStyle.Square,
    joinStyle: JoinStyle.Mitre,
    mitreLimit: 5) {
        SimplifyFactor = 5,
    };

const string polygonStr = "POLYGON ((527725.120643654 6424983.5058084615, 527719.20937271812 6424991.3875030428, 527715.17711302673 6424996.4278276572, 527712.0533893354 6425001.6340338094, 527710.97531942907 6425007.024383341, 527712.05648117629 6425011.3490303308, 527714.17814558465 6425015.592359147, 527716.58578643762 6425018, 527722.27698396472 6425018, 527727.66860104725 6425014.7650297508, 527731.87344107509 6425009.5089797154, 527733.94747254136 6425004.32390105, 527736 6424997.1400549449, 527736 6424970.7639320223, 527732.97418816574 6424964.7123083537, 527731.99388373469 6424955.8895684741, 527731.8834522086 6424954.89568474, 527729.89568473923 6424955.1165477913, 527731.02581183426 6424965.2876916463, 527734 6424971.2360679777, 527734 6424996.8599450551, 527732.05252745864 6425003.67609895, 527730.12655892491 6425008.4910202846, 527726.33139895275 6425013.2349702492, 527721.85754471528 6425015.9192827921, 527715.75935393129 6425014.1769425683, 527713.03656792559 6425006.9161798861, 527713.9466106646 6425002.3659661906, 527716.82288697327 6424997.5721723428, 527720.79062728188 6424992.6124969572, 527726.879356346 6424984.4941915385, 527730.9284766909 6424974.3713906761, 527731.29986736726 6424973.4429139849, 527729.44291398546 6424972.7001326326, 527725.120643654 6424983.5058084615))";

var polygon = new WKTReader().Read(polygonStr);

var bufferedPolygon = polygon.Buffer(50, bufferParameters);
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5.0
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: .Net 6
- Additional information:

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
The value for `SimplifyFactor` is out of the suggested range `]0, 0.1]`
