### ISSUE TITLE
Handle srsDimension attribute in GMLReader smarter

### ISSUE THREAD

**Issue by jstorteboom** [NetTopologySuite/NetTopologySuite#685]
Hi,

NTS only deals with srsDimension when the attribute is on the posList inside a polygon. The use case I have is that the srsDimension attribute is on the Polygon (parent node) next to the srsName.

It would be nice if either way would work, but to make that happen I think the GeometryFactory should be extended. This way, when the Polygon gets parsed, it will set the Dimension on that factory, and next when any inner objects are being parsed, those factories will inherit from the Polygon factory and thus default to have that dimension set to whatever that parent node had in its srsDimension.

Quite doalble I'd say, but touching the GeometryFactory potentionally is also quite impactfull. It could be extending (non-breaking) the codebase, but still.

Is it worth doing this, or is this never going to make it into an accepted Pull Request in the first place?

Here is some sample code (notice how srsDimension is on the Polygon, this fails, but when on the posList this runs fine):
```C#
    [Fact]
    public void ParseSrsTest()
    {
        // Parse GML data
        string gmlData = "<gml:Polygon xmlns:gml=\"http://www.opengis.net/gml\" srsDimension=\"3\" srsName=\"http://www.opengis.net/gml/srs/epsg.xml#4326\" >" +
                 "<gml:exterior><gml:LinearRing><gml:posList>244420.388 488213.902 0.0 244407.058 488204.758 0.0 244413.487 488195.387 0.0 244418.813 488199.041 0.0 244415.419 488203.989 0.0 244423.422 488209.478 0.0 244420.388 488213.902 0.0</gml:posList></gml:LinearRing></gml:exterior>" +
                 "</gml:Polygon>";
        var reader = new GMLReader();
        var geom = reader.Read(gmlData);

        // Get the coordinates of the polygon
        var coords = ((Polygon)geom).ExteriorRing.Coordinates;

        // Print the coordinates
        foreach (var coord in coords)
        {
            Console.WriteLine(coord);
        }
    }
```

### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ ] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
_(A description of the bug or feature)_

### Steps to Reproduce
_(List of steps, sample code, failing test or link to a project that reproduces the behavior)_

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version:
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
I don't see that you have to change the `GeometryFactory` in any way. The class responsible for the coordinate dimension is the `CoordinateSequenceFactory` attached to the `GeometryFactory`. All implementations of this abstract class can produce 3d coordinate sequences so you should be all set.
All you have to do is take care that you pass arrays of `CoordinateZ` instances to the `GeometryFactory`'s `CreateLinearRing` method if you find any ``srsDimension="3"` attribute and use those rings to create the polygon.

**Comment by jstorteboom** [comment]
Thanks for the reply. So, I don't control the ```CreateLinearRing``` call. That is in ```GMLReader``` line 292. That one passes in the result of ```ReadLineString``` (line 229). There, on line 269/270, is a hardcode value of 2 that is used when the node we are parsing (in this case the ```posList```-node) does not contain a ```srsDimension```-attribute. Now instead of using this default value, I'd like to use the value that was on a parent-nodes srsDimension attribute. So, the polygon (is parent node) has srsDimension (value 3, also srsName is on the polygon), but that should affect how the inner nodes parsing should behave, hence use the value 3 when parsing the PosList coordinates (line 272).

I could solve this by remembering the srsDimension in a class-scoped variable, but that seems ugly since we already create ```GeometryFactory``` instances per xml-node/geometry-object that we parse. So it seems cleaner to extend that pattern (but also more impact) then doing the class-variable solution. At the other hand, To have less of a impactful change, if the change is only in the ```GMLReader``` class, it would be no big deal and easier to have a PR approved. Because, if changing it the nicer way, we should consider way more scenario's (like what to do with that dimension if we use the factory to write out a format). 

Again, thanks of taking the time

**Comment by FObermaier** [comment]
Could you review https://github.com/NetTopologySuite/NetTopologySuite/pull/686/commits/afcde00a5000c2c15c8be63e8a96d827129fecd3

**Comment by jstorteboom** [comment]
Awesome, you rock, works like a charm. Thanks heaps. I pulled that branch, ran my test, also ran my bigger process (parsing 46 of those), and seems just fine. I didn't work with anything other then the Polygon yet, but from what I see you do in code, it makes a lot of sense so I'm quite confident.

Thanks for this ;)

How do you go about releasing these kind of changes? I see the last official release (2.5) was July last year. Is there like a beta-version you build more often?

Again, thanks heaps.

**Comment by FObermaier** [comment]
You can get a pre-release version from [myget](https://github.com/NetTopologySuite/NetTopologySuite#pre-release--).
