### ISSUE TITLE
How to get the irregular triangle inside the concave hull built by the ConcaveHull class？

### ISSUE THREAD

**Issue by pucx** [NetTopologySuite/NetTopologySuite#687]
By use ConcaveHull class:
https://github.com/NetTopologySuite/NetTopologySuite/blob/develop/src/NetTopologySuite/Algorithm/Hull/ConcaveHull.cs
How to get the irregular triangle inside the concave hull built by the ConcaveHull class？

**Comment by FObermaier** [comment]
Can you elaborate a bit more what you try to achieve. Maybe some sample data/image to illustrate?

**Comment by pucx** [comment]
For discrete point data, first establish the concave hull of the discrete points, and then generate contour lines based on the irregular triangle mesh inside the concave hull. So I want to get the irregular triangles inside the concave hull ,thanks.
