### ISSUE TITLE
missing Triangles issue

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#689]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
_(A description of the bug or feature)_

We have an issue with triangulation dues to missing  triangles as per image below:
![image](https://github.com/NetTopologySuite/NetTopologySuite/assets/26113670/b66c090b-1d88-476b-bdb6-2986d523645e)

so 
this is our input

`POLYGON ((0 0, -78.777779 0, -78.777779 -3, 0 -3, 0 0), (-46.489959 -2.2, -47.398933 -2.2, -47.398933 -0.2, -46.489959 -0.2, -46.489959 -2.2))`

we use

```csharp
        private static List<Polygon> Triangulate(this Polygon polygon, double tolerance = Core.Tolerance.MicroDistance)
        {
            if(polygon == null)
            {
                return null;
            }

            DelaunayTriangulationBuilder delaunayTriangulationBuilder = new DelaunayTriangulationBuilder();
            delaunayTriangulationBuilder.SetSites(polygon);

            GeometryFactory geometryFactory = new GeometryFactory(new PrecisionModel(1 / tolerance));

            GeometryCollection geometryCollection = delaunayTriangulationBuilder.GetTriangles(geometryFactory);
            if (geometryCollection == null)
            {
                return null;
            }

            List<Polygon> polygons = new List<Polygon>();
            foreach (NetTopologySuite.Geometries.Geometry geometry in geometryCollection.Geometries)
            {
                Polygon polygon_Temp = geometry as Polygon;
                if (polygon == null)
                {
                    continue;
                }

                polygons.Add(polygon_Temp);
            }

            List<Polygon> result = new List<Polygon>();
            foreach (Polygon polygon_Temp in polygons)
            {
                NetTopologySuite.Geometries.Geometry geometry = polygon.Intersection(polygon_Temp);

                List<Polygon> polygons_Intersection = new List<Polygon>();
                if(geometry is Polygon)
                {
                    polygons_Intersection.Add((Polygon)geometry);
                }
                else if(geometry is GeometryCollection)
                {
                    foreach(NetTopologySuite.Geometries.Geometry geometry_Temp in (GeometryCollection)geometry)
                    {
                        if(geometry_Temp is Polygon)
                        {
                            polygons_Intersection.Add((Polygon)geometry_Temp);
                        }
                    }
                }

                foreach(Polygon polygon_Intersection in polygons_Intersection)
                {

                    if (Core.Query.AlmostEqual(polygon_Temp.Area, polygon_Intersection.Area, tolerance))
                    {
                        result.Add(polygon_Intersection);
                        continue;
                    }

                    List<Polygon> polygons_Temp_Temp = Triangulate(polygon_Intersection, tolerance);
                    if (polygons_Temp_Temp == null || polygons_Temp_Temp.Count == 0)
                    {
                        continue;
                    }

                    result.AddRange(polygons_Temp_Temp);
                }



            }

            return result;
        }
```

### Steps to Reproduce
_(List of steps, sample code, failing test or link to a project that reproduces the behavior)_
run code above with attached example

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5.0
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version: 4.7.2
- Additional information:

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
The _simple_ `DelauneyTriangulationBuilder` just takes the plain vertices of the geometries you feed it and builds a triangulation for those vertices. You get the same result if you put in 
* `MULTIPOINT ((0 0), (-78.777779 0), (-78.777779 -3), (0 -3), (-46.489959 -2.2), (-47.398933 -2.2), (-47.398933 -0.2), (-46.489959 -0.2))` or 
* `GEOMETRYCOLLECTION(MULTIPOINT ((0 0), (-78.777779 0), (-78.777779 -3), (0 -3)), LINESTRING(-46.489959 -2.2, -47.398933 -2.2, -47.398933 -0.2, -46.489959 -0.2))`

For your use case you need to use the `ConformingDelaunayTriangulationBuilder` class.

**Comment by michaldengusiak** [comment]
@FObermaier  I appreciate your swift response to my previous queries. I have another question related to the triangulation of my geometry. My primary objective is to triangulate a given area in a manner that no triangles are formed inside the internalEdges2D polygon.

Below is a visual representation of the issue:

![image](https://github.com/NetTopologySuite/NetTopologySuite/assets/26113670/c136e7df-3358-4f4a-8cb3-d68082d770b7)


Here are my specific questions:

1. I understand that I can input Points, LineString, or Polygon to the [setSites](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/triangulate/ConformingDelaunayTriangulationBuilder.html#setSites-org.locationtech.jts.geom.Geometry-) method of [Geometry](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html). This part is clear to me.

2. Do I need to utilize the [setConstraints](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/triangulate/ConformingDelaunayTriangulationBuilder.html#setConstraints-org.locationtech.jts.geom.Geometry-) method? If yes, could you please suggest the ideal inputs that would yield the best results?

3. Is there a specific way to provide inputs to ensure that no triangles are formed inside the internalEdges2D polygon, as per the image above?

I look forward to your guidance on this matter.

Thanks in advance for your support.

**Comment by FObermaier** [comment]
You need to set the `Constraints` property if you want to be able to exclude the areas bounded by `internalEdges2d` from the results. In order to be sure to get all triangles you have to build a geometry that is slightly larger than the original.   
This works for me:
```C#
const string wkt = "POLYGON((0 0, 100 0, 100 10, 0 10, 0 0), " +
                            "(35 1, 40 1, 40 8, 35 8, 35 1), " +
                            "(42 2, 46 2, 46 9, 42 9, 42 2), " +
                            "(87 1, 92 1, 92 9, 87 9, 87 1))";

var inputGeom = new WKTReader().Read(wkt);
var workGeom = GetWorkGeometry(inputGeom);

var cdtb = new ConformingDelaunayTriangulationBuilder();
cdtb.SetSites(workGeom);
cdtb.Constraints = workGeom;

var res = FilterRelevant(cdtb.GetTriangles(inputGeom.Factory));

Geometry GetWorkGeometry(Geometry geom)
{
    var boundEnv = geom.Boundary.EnvelopeInternal;
    boundEnv = new NetTopologySuite.Geometries.Envelope(boundEnv.MinX - 1, boundEnv.MaxX + 1, boundEnv.MinY - 1, boundEnv.MaxY + 1);
    var bounds = geom.Factory.ToGeometry(boundEnv);

    return geom.Factory.CreateGeometryCollection(new[] { geom, bounds });
}

Geometry FilterRelevant(IEnumerable<Geometry> geoms)
{
    var rel = new List<Geometry>();
    var p = NetTopologySuite.Geometries.Prepared.PreparedGeometryFactory.Prepare(inputGeom);
    foreach(var geom in geoms)
        if (p.Contains(geom)) rel.Add(geom);

    return inputGeom.Factory.BuildGeometry(rel);
}

```

**Comment by michaldengusiak** [comment]
@FObermaier, thank you very much. Your assistance is greatly appreciated.

We now have all the triangles and our geometry is correctly represented without any missing elements.

![image](https://github.com/NetTopologySuite/NetTopologySuite/assets/26113670/5b99ed2f-125f-4bb2-80dc-87f6e60a5b37)

**Comment by FObermaier** [comment]
Great @michaldengusiak. I want to mention that I overhauled the `GetWorkGeometry` function, it might yield better results (fewer triangles) that way.

**Comment by michaldengusiak** [comment]
I updated image to include this
