### ISSUE TITLE
Pointer is referencing coordinates to previous geometry after Union

### ISSUE THREAD

**Issue by gktval** [NetTopologySuite/NetTopologySuite#690]
### Description
I am running a union with several geometries. After running the union, the coordinates are changed when doing some reprojections. This work great with the resulting union geometry, but a pointer for the coordinates are still referencing the coordinates to the geometries that were input into the union operation. As a result, the input geometries are corrupt and no longer valid. 

### Steps to Reproduce
This code is a bit pseudo. If you need a full repository example, please let me know.
Polygon geom1 = ... Load polygon geometry
Polygon geom2 = ... Load another polygon geometry

Geometry[] geomToUnion = new Geometry[] { geom1, geom2};
UnaryUnionOp unionOp = new NetTopologySuite.Operation.Union.UnaryUnionOp(geomToUnion);
Geom resultGeom = unionOp.Union();

// Do some type of action to change the coordinates
for (int i = 0; i<resultGeom.Coordinates.Length; i++)
{
      resultGeom.Coordinates[i].X += 7.236;
      resultGeom.Coordinates[i].Y += 4.5678;
}
resultGeom.GeometryChanged();

//This will now fail
System.Diagnostics.Debug.Assert(geom1.IsValid);

The easy workaround is to clone every geometry before passing it into the Union. 

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5.0
- Environment (Operating system, version and so on): Windows 11
- .NET Framework version: 4.7

**Comment by FObermaier** [comment]
# DON'T CHANGE VALUES IN THE `COORDINATES` ARRAY DIRECTLY, YOU ARE BOUND TO FAIL

NTS' geometries are considered immutable, even though they are technically not. The `Coordinates` property is a created off the values in the internally used `CoordinateSequence`s. That is why you are getting unexpected results.

If you want to translate the geometry you need to create a class implementing `IEntireCoordinateSequenceFilter` interface and apply that to your geometries:
```C#
class Translate : IEntireCoordinateSequenceFactory 
{
    private readonly double _tx, _ty;

    Translate(double tx, double ty) {
        _tx = tx;
        _ty = ty;
    }

    public void Filter(CoordinateSequence seq)
    {
        for (int i = 0; i < seq,Count; i++)
        {
            seq.SetX(i, seq.GetX(i) + _tx);
            seq.SetY(i, seq.GetY(i) + _ty);
        }
    }

    public bool Done => false;

    public bool GeometryChanged => true;
}

// Usage
var translate = new Translate(1.234, 5.678);
geom.Apply(translate);
```
Note: This has not seen a compiler, but you should get the idea
