### ISSUE TITLE
Should GeometryCollection implement IReadOnlyList<Geometry>?

### ISSUE THREAD

**Issue by roji** [NetTopologySuite/NetTopologySuite#702]
GeometryCollection currently implements `IEnumerable<Geometry>`, but not `IList<Geometry>`. However, it exposes a very IList-like interface (GetGeometryN accepting an array index, Geometries returning the internal array). So it could easily implement `IReadOnlyList<Geometry>`, which basically exposes Count and an indexer, making it easier to use GeometryCollection in some standard .NET contexts.

For example, some LINQ operators have special behavior when a type implement IList/IReadOnlyList (in EF we have some special behavior too). This would simply kick in if GeometryCollection implemented that.

/cc @ajcvickers

**Comment by FObermaier** [comment]
I have no objections, do you @airbreather?

**Comment by airbreather** [comment]
`IReadOnlyList<Geometry>`: great, easy enough, no issues.  In fact, I haven't tested this, but I think it would be as simple as just changing `IEnumerable<Geometry>` to `IReadOnlyList<Geometry>`.

`IList<Geometry>` was mentioned too.  That one's more annoying (to implement **and** to use correctly), so let's not do that one unless someone really needs it.
