### ISSUE TITLE
LengthIndexedLine.ExtractLine() generates line with duplicate start coordinate

### ISSUE THREAD

**Issue by hallsbyra** [NetTopologySuite/NetTopologySuite#704]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The start coordinate is repeated, so the resulting LineString starts with an empty line segment.

### Steps to Reproduce
```cs
    [Fact]
    public void LengthIndexedLine_ExtractLine_generates_line_with_duplicate_start_coordinate()
    {
        var ls = new WKTReader().Read("LINESTRING (8202.42284720634 635.20622151789166, 8206.4228262417164 635.19327097526127, 8207.0623893572938 635.08860147546511)");
        var lil = new LengthIndexedLine(ls);
        var result = lil.ExtractLine(4, lil.EndIndex);
        //  result =  LINESTRING (8206.4228262417164 635.19327097526127, 8206.4228262417164 635.19327097526127, 8207.0623893572938 635.08860147546511)
        //                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        //                        duplicate start coordinate              duplicate start coordinate
        //
        // The following assertion with expected output fails.
        Assert.Equal("LINESTRING (8206.4228262417164 635.19327097526127, 8207.0623893572938 635.08860147546511)", result.ToText());
    }
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5.0
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on): Win11
- .NET Framework version: 4.8
- Additional information:

**Comment by FObermaier** [comment]
This is a precision issue, JTS produces the same result.
