### ISSUE TITLE
There is a bug in the project method of the LineSegment class

### ISSUE THREAD

**Issue by wenshinlee** [NetTopologySuite/NetTopologySuite#707]
LineSegment line1 = new(new Coordinate(0, 0), new Coordinate(0, double.MaxValue)); ;
 Coordinate coordinate1 = new Coordinate(20, 10);
Coordinate coord = line1.Project(coordinate1);

coord is （NAN， NAN）

**Comment by wenshinlee** [comment]
In fact, the coordinates of coord should be (0,10).

**Comment by FObermaier** [comment]
NTS fails to compute a projection factor when the squared length of a line segment is greater than `double.MaxValue`.
This is an edge case, do you really need `double.MaxValue` as ordinate or is that just _convenient_?
