### ISSUE TITLE
multiPolygon.Union() error

### ISSUE THREAD

**Issue by michaldengusiak** [NetTopologySuite/NetTopologySuite#708]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I have geometry:

`MULTIPOLYGON (((0.2 0.51707, 3.920456 5.54167, 3.920456 8.776188, 0.2 8.776188, 0.2 0.51707)), ((4.170456 6.023975, 6.54158 10.598393, 5.564706 13.489555, 6.173258 11.688481, 4.170456 17.615983, 4.170456 17.615982, 4.170456 6.023975)), ((3.920456 8.796188, 3.920456 17.615983, 1.101741 17.615983, 0.2 8.796188, 3.920456 8.796188)))`

and we try to multiPolygon.Union()
however it return error

__NetTopologySuite.Geometries.TopologyException
  HResult=0x80131600
  Message=side location conflict: arg 0 [ (6.1284514955120368, 11.821090536522037) ]
  Source=NetTopologySuite
  StackTrace:
   at NetTopologySuite.Operation.OverlayNG.OverlayLabeller.PropagateAreaLocations(OverlayEdge nodeEdge, Int32 geomIndex)
   at NetTopologySuite.Operation.OverlayNG.OverlayLabeller.LabelAreaNodeEdges(IEnumerable`1 nodes)
   at NetTopologySuite.Operation.OverlayNG.OverlayLabeller.ComputeLabelling()
   at NetTopologySuite.Operation.OverlayNG.OverlayNG.LabelGraph(OverlayGraph graph)
   at NetTopologySuite.Operation.OverlayNG.OverlayNG.ComputeEdgeOverlay()
   at NetTopologySuite.Operation.OverlayNG.OverlayNG.GetResult()
   at NetTopologySuite.Operation.OverlayNG.OverlayNGRobust.Overlay(Geometry geom0, Geometry geom1, SpatialFunction opCode)
   at NetTopologySuite.Operation.Union.CascadedPolygonUnion.<>c.<.cctor>b__21_0(Geometry g0, Geometry g1)
   at NetTopologySuite.Operation.Union.CascadedPolygonUnion.UnionSafe(Geometry g0, Geometry g1)
   at NetTopologySuite.Operation.Union.CascadedPolygonUnion.BinaryUnion(IList`1 geoms, Int32 start, Int32 end)
   at NetTopologySuite.Operation.Union.CascadedPolygonUnion.Union()
   at NetTopologySuite.Operation.Union.UnaryUnionOp.Union()
   at NetTopologySuite.Geometries.GeometryOverlay.OverlayV1.Union(Geometry a)_
   

### Steps to Reproduce
_(List of steps, sample code, failing test or link to a project that reproduces the behavior)_
Run union on given geometry

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5.0
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on): Windows
- .NET Framework version: 4.7.2
- Additional information:

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by michaldengusiak** [comment]
we tested an alternative route and this works now.
However, can you advise if there is a better way to check it and run it?
we would like to avoid` try/catch` so any idea will be appreciated and avoid if possible `SimplifyByTopologyPreservingSimplifier`
on every single polygon. Try/catch is not needed in 99% of cases

```
            NetTopologySuite.Geometries.Geometry geometry = null;
            try
            {
                geometry = multiPolygon.Union();
            }
            catch
            {
                double tolerance = Tolerance.Distance;

                Polygon[] polygons_Temp = new Polygon[polygons.Count()];
                for(int i =0; i < polygons_Temp.Length; i++)
                {
                    polygons_Temp[i] = SimplifyByTopologyPreservingSimplifier(polygons.ElementAt(i), tolerance);
                }

                multiPolygon = new MultiPolygon(polygons_Temp, new GeometryFactory(new PrecisionModel(1 / tolerance)));
                geometry = multiPolygon.Union();
            }
```

here is code to method `SimplifyByTopologyPreservingSimplifier`

```
        public static Polygon SimplifyByTopologyPreservingSimplifier(this Polygon polygon, double tolerance = Tolerance.Distance)
        {
            if (polygon == null)
                return null;

            Polygon result = TopologyPreservingSimplifier.Simplify(polygon, tolerance) as Polygon;
            if (result == null || result.Area <= tolerance)
                return polygon;

            return result;
        }
```

**Comment by FObermaier** [comment]
The input geometry is not valid (self-intersection). You need to use `GeometryFixer.Fix(Geometry)` function prior to calling `Geometry.Union()` and you are all set.

**Comment by michaldengusiak** [comment]
thanks a lot, this is now implemented...

is `GeometryFixer.Fix(Geometry)` a heavy method or not really and we should add this always before we run any operations?

**Comment by FObermaier** [comment]
The `IsValidOp` has been improved performance wise, so I'd advise to only call `GeometryFixer.Fix(Geometry)` if `Geometry.IsValid` is not true.
