### ISSUE TITLE
Why holes do not applies to shells in Polygonizer?

### ISSUE THREAD

**Issue by mKliver** [NetTopologySuite/NetTopologySuite#721]
### Prerequisites

- [v] I have written a descriptive issue title
- [v] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [v] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm trying to create MultiPolygon with Polygonizer. In general case it has a Holes and Islands like on picture:
![image](https://github.com/NetTopologySuite/NetTopologySuite/assets/3050125/3f352ef8-7ec9-49d0-9513-1726b55942be)

But Polygonizer returns not what i exepected to see:
```
GEOMETRYCOLLECTION (POLYGON ((0 0, 0 100, 100 100, 100 0, 0 0), (25 25, 75 25, 75 75, 25 75, 25 25)), POLYGON ((25 25, 25 75, 75 75, 75 25, 25 25), (40 40, 60 40, 60 60, 40 60, 40 40)), POLYGON ((40 40, 40 60, 60 60, 60 40, 40 40)), POLYGON ((125 0, 125 100, 225 100, 225 0, 125 0)))
```
And if you look at shells and holes list they are the same:
![image](https://github.com/NetTopologySuite/NetTopologySuite/assets/3050125/645d2b3c-5b82-4b05-843a-ebbe3873655d)

Mayby i just lost in translation and use Polygonizer on wrong way?

### Steps to Reproduce
```
//geometry
var g1 = "POLYGON((0 0, 100 0, 100 100, 0 100, 0 0))".ToGeometry();
var g2 = "POLYGON((25 25, 75 25, 75 75, 25 75, 25 25))".ToGeometry();
var g3 = "POLYGON((40 40, 60 40, 60 60, 40 60, 40 40))".ToGeometry();
var g4 = "POLYGON((125 0, 225 0, 225 100, 125 100, 125 0))".ToGeometry();

//check orientation
var o1 = Orientation.IsCCW(g1.Coordinates);
var o2 = Orientation.IsCCW(g2.Coordinates);
var o3 = Orientation.IsCCW(g3.Coordinates);
var o4 = Orientation.IsCCW(g4.Coordinates);

//reverse orientation for shells
g1 = (Polygon)g1.Reverse();
g4 = (Polygon)g4.Reverse();

//check again
var o1_1 = Orientation.IsCCW(g1.Coordinates);
var o2_1 = Orientation.IsCCW(g2.Coordinates);
var o3_1 = Orientation.IsCCW(g3.Coordinates);
var o4_1 = Orientation.IsCCW(g4.Coordinates);

var polygonizer = new Polygonizer(false);
polygonizer.Add(LineStringExtracter.GetLines(g1.Boundary));
polygonizer.Add(LineStringExtracter.GetLines(g2.Boundary));
polygonizer.Add(LineStringExtracter.GetLines(g3.Boundary));
polygonizer.Add(LineStringExtracter.GetLines(g4.Boundary));

var geom = polygonizer.GetGeometry();
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: .NET 6.0
- Additional information:

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
Please note: 
**NTS does not care about ring orientations during computation**

With the current codebase `Polygonizer` class returns 4 individual geometries:

```
POLYGON ((0 0, 0 100, 100 100, 100 0, 0 0), (25 25, 75 25, 75 75, 25 75, 25 25))
POLYGON ((25 25, 25 75, 75 75, 75 25, 25 25), (40 40, 60 40, 60 60, 40 60, 40 40))
POLYGON ((40 40, 40 60, 60 60, 60 40, 40 40))
POLYGON ((125 0, 125 100, 225 100, 225 0, 125 0))
```
![image](https://github.com/user-attachments/assets/63d3cfa6-fa04-427a-bf66-7289cc4288fc)

When they are unioned, the first 3 polygons are turned into one, which makes perfect sense.

If you want a different result, you will have to combine the geometries yourself.
