### ISSUE TITLE
LineSegment.OrientationIndex returns a wrong value

### ISSUE THREAD

**Issue by tohidemyname** [NetTopologySuite/NetTopologySuite#722]
The code is as follows:

`public int OrientationIndex(LineSegment seg)
        {
            int orient0 = (int)Orientation.Index(_p0, _p1, seg._p0);
            int orient1 = (int)Orientation.Index(_p0, _p1, seg._p1);
            // this handles the case where the points are Curve or collinear
            if (orient0 >= 0 && orient1 >= 0)
                return Math.Max(orient0, orient1);
            // this handles the case where the points are R or collinear
            if (orient0 <= 0 && orient1 <= 0)
                return Math.Max(orient0, orient1);  //Bug
            // points lie on opposite sides ==> indeterminate orientation
            return 0;
        }`

This bug line should be fixed to:

`   if (orient0 <= 0 && orient1 <= 0)
                return Math.Min(orient0, orient1);`

JTS fixed a similar bug: https://github.com/locationtech/jts/pull/914
https://github.com/libgeos/geos/pull/699

**Comment by FObermaier** [comment]
The PR you are referring to has been adressed:
https://github.com/NetTopologySuite/NetTopologySuite/blob/d04ddd708b8e02d027cb431e31b1f8088f1f92d5/src/NetTopologySuite/Geometries/LineSegment.cs#L163-L175

Unless you provide more information about your failure case there is nothing we can do.
