### ISSUE TITLE
DistanceOp.ComputeMinDistancePoints should be fixed for empty points.

### ISSUE THREAD

**Issue by tohidemyname** [NetTopologySuite/NetTopologySuite#723]
This method does not handle the cases when pt0 and pt1 are empty.  JTS has fixed a related problem:

https://github.com/locationtech/jts/pull/1010

**Comment by FObermaier** [comment]
Go ahead.

**Comment by FObermaier** [comment]
fixed with 7f7de43caece0ee543fda0d3c05936479743ad41
