### ISSUE TITLE
TriangleEdgesListVisitor.Visit can fail with FetchTriangleToVisit.

### ISSUE THREAD

**Issue by tohidemyname** [NetTopologySuite/NetTopologySuite#724]
The JTS bug report is as follows:
https://github.com/locationtech/jts/pull/945

It mentions a failure when calling with FetchTriangleToVisit. 
The current NTS implementation is identical to the buggy method.

**Comment by FObermaier** [comment]
The PR you are referring to has been adressed: https://github.com/NetTopologySuite/NetTopologySuite/blob/d04ddd708b8e02d027cb431e31b1f8088f1f92d5/src/NetTopologySuite/Triangulate/QuadEdge/QuadEdgeSubdivision.cs#L742-L745

Unless you provide more detail about your failure case there is nothing we can do.

**Comment by tohidemyname** [comment]
My code base is obsolete. I will update my code. Thanks a lot.
