### ISSUE TITLE
[WKBReader]Geometry type not recognized. GeometryCode: 16

### ISSUE THREAD

**Issue by CRC32EX** [NetTopologySuite/NetTopologySuite#731]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I want use NetTopologySuite with MySQL.
I have to convert WKB.
I can't use `UseNetTopologySuite` because I'm using [MySqlConnector](https://github.com/mysql-net/MySqlConnector) and [Dapper](https://github.com/DapperLib/Dapper).

### Steps to Reproduce
1. Generate binary using MySQL
```sql
# Statue of Liberty (40.6892 -74.0445)
select ST_GeomFromText('POINT(40.6892 -74.0445)', 4326)

# Output:
# 0xe610000001010000009c33a2b437584440022b8716d98252c0
```
2. Write C# code
```cs
var bytes = new byte[]
{
  0xE6, 0x10, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x9C, 0x33, 0xA2,
  0xB4, 0x37, 0x58, 0x44, 0x40, 0x02, 0x2B, 0x87, 0x16, 0xD9, 0x82, 0x52, 0xC0
};

var geoFactory = NetTopologySuite.NtsGeometryServices.Instance.CreateGeometryFactory(4326);
var wkbReader = new NetTopologySuite.IO.WKBReader(geoFactory.GeometryServices)
{
  HandleOrdinates = NetTopologySuite.Geometries.Ordinates.XY,
  HandleSRID = true
};

var geometry = wkbReader.Read(bytes);
Console.WriteLine($"Longitude: {geometry.Coordinate.X}");
Console.WriteLine($"Latitude: {geometry.Coordinate.Y}");
```

3. Error
```
Unhandled exception. NetTopologySuite.IO.ParseException: System.ArgumentException:
  Geometry type not recognized. GeometryCode: 16
   at NetTopologySuite.IO.WKBReader.Read(BinaryReader reader)
 ---> System.ArgumentException: Geometry type not recognized. GeometryCode: 16
   at NetTopologySuite.IO.WKBReader.Read(BinaryReader reader)
   --- End of inner exception stack trace ---
   at NetTopologySuite.IO.WKBReader.Read(BinaryReader reader)
   at NetTopologySuite.IO.WKBReader.Read(Stream stream)
   at NetTopologySuite.IO.WKBReader.Read(Byte[] data)
   at Program.<Main>$(String[] args) in C:\Programs\TestConsoleApp\Program.cs:line 14
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5.0
- Other NetTopologySuite packages and versions: Nothing
- Environment (Operating system, version and so on): Windows 11 21H2
- .NET Framework version: .NET 8.0
- Additional information: 
I have to use  `4326`.
Because calculation result is difference.

```sql
# Statue of Liberty (40.6892 -74.0445)
# White house (38.897957 -77.036560)

SELECT ST_Distance(  
  ST_GeomFromText('POINT(40.6892 -74.0445)'),
  ST_GeomFromText('POINT(38.897957 -77.036560)')
) as result1;

SELECT ST_Distance(  
  ST_GeomFromText('POINT(40.6892 -74.0445)', 4326),
  ST_GeomFromText('POINT(38.897957 -77.036560)', 4326)
) as result2;

# Output
# result1: 3.4872588846612715
# result2: 324356.3100902279
```

**Comment by FObermaier** [comment]
You need to use `NetTopologySuite.IO.SqlServerBytes`(https://www.nuget.org/packages/NetTopologySuite.IO.SqlServerBytes) to read your geometry instead of WKBReader/-Writer.
