### ISSUE TITLE
GeometryFactory.CreateEmpty throws exception when passed Dimension.Dontcare

### ISSUE THREAD

**Issue by LiteracyFanatic** [NetTopologySuite/NetTopologySuite#737]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The documentation claims that passing `Dimension.Dontcare` to `GeometryFactory.CreateEmpty` will produce an empty geometry collection. In reality, it throws an exception.

### Steps to Reproduce
Call `geometryFactory.CreateEmpty(Dimension.Dontcare)`

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5.0
- Environment (Operating system, version and so on): Arch Linux
- .NET Framework version: net8.0

**Comment by FObermaier** [comment]
Good catch, can you provide a PR to fix this?
