### ISSUE TITLE
Can you request a nuget package prefix for NetTopologySuite 

### ISSUE THREAD

**Issue by SimonCropp** [NetTopologySuite/NetTopologySuite#742]
https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation#id-prefix-reservation-application-process

this will make it easier for people who are protecting against nuget name hijacking via  https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping since they can wildcard `NetTopologySuite*`

**Comment by airbreather** [comment]
Good call. I was about to send the e-mail, but looking at the NuGet organization, I think they'll probably want this person to do it:
![image](https://github.com/NetTopologySuite/NetTopologySuite/assets/3792815/b7bc69f2-29ff-43aa-b790-78f69a558c91)

**Comment by SimonCropp** [comment]
thanks peeps

**Comment by FObermaier** [comment]
![image](https://github.com/NetTopologySuite/NetTopologySuite/assets/2065346/20f892cb-8722-4abe-b7ea-e57a4014e362)
It worked.

**Comment by SimonCropp** [comment]
awesome
