### ISSUE TITLE
An error create instance of STRtree class

### ISSUE THREAD

**Issue by DMuzer** [NetTopologySuite/NetTopologySuite#744]
Hi I create script using IronPython and NTS lib. I want to use STRtree and get an error No callable method. What's problem?
>>> nts.Index.Strtree.STRtree()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: No callable method.

**Comment by FObermaier** [comment]
`NetTopologySuite.Index.Strtree.STRtree<TItem>` is a generic class. I'm not sure, but you may have to include that in your declaration.
