### ISSUE TITLE
Add additional TFM to enable a 0 dependency scenario

### ISSUE THREAD

**Issue by thompson-tomo** [NetTopologySuite/NetTopologySuite#749]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Memory as it can be provided by adding an additional framework. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by airbreather** [comment]
Is this different from #745?
