### ISSUE TITLE
Invalid Z coordinate is added to geometry point with X and Z coordinates

### ISSUE THREAD

**Issue by RoHa1000** [NetTopologySuite/NetTopologySuite#754]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Invalid Z coordinate is added to geometry point with X and Y coordinates, see reproduce instruction

### Steps to Reproduce
A database table has a geometry column. This might contain a point with X and Z coordinates, like:
0xBE0B0000010Cyyyyyyyyyyyyyyyyxxxxxxxxxxxxxxxx (where x and y are the valid hex values for the coordinates)
Table rows are fetched, using Entity Framework.
An entry is modified (no changes are made to the Geometry instance)
Changes are saved (Entity Framework)
In the database the geometry value has now changed to:
0xBE0B0000010Fyyyyyyyyyyyyyyyyxxxxxxxxxxxxxxxx000000000000F8FF000000000000F8FF
That looks like a point with valid X and Y but a Z value = NaN has been added

Possibly related to https://github.com/NetTopologySuite/NetTopologySuite/issues/567 ?

### System Configuration
.Net 8.0
NuGet Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 8.0.4 => NetTopologySuite 2.5.0
SqlServer 2019

**Comment by FObermaier** [comment]
Could you please set up a small sample project to showcase your issue? Thanks

**Comment by FObermaier** [comment]
> Could you please set up a small sample project to showcase your issue? Thanks

This would really be helpful.

**Comment by cameronwellerIDWR** [comment]
Here you are. I have never made a sample project so let me know if you need anything else from me.
[SampleProject.zip](https://github.com/user-attachments/files/15564135/SampleProject.zip)

**Comment by FObermaier** [comment]
@cameronwellerIDWR , I tried your sample project. To make it run, I
1. created `SampleEntities` database on `(localdb)\MSSQLLocalDB (SQL Server 15.0.4153)`
2. replaced connection string (`Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=SampleEntities;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False`)
3. ran project and got `DbUpdateException` (Invalid object name 'dbo.ThingThatHasShapes')
4. created "ThingThatHasShape" table with "Id" int PrimaryKey and "Shape" geometry columns.
5. ran project and got `DbUpdateExceotion` (geometry != geography)
6. added [Column(TypeName="geometry")] to Shape property of `ThingThatHasShape`
7. ran project successfully. The thing that has a shape was inserted like this;
![image](https://github.com/NetTopologySuite/NetTopologySuite/assets/2065346/ef3388bd-28f6-40bf-b998-30b68ff99001)

**Comment by cameronwellerIDWR** [comment]
> 6. added [Column(TypeName="geometry")] to Shape property of `ThingThatHasShape`

This fixed my issue. Adding [Column(TypeName="geometry")] to decorate the Shape field of my entities has fixed the issue. Thanks!
