### ISSUE TITLE
Buffer produces empty polygon

### ISSUE THREAD

**Issue by hallsbyra** [NetTopologySuite/NetTopologySuite#760]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of NetTopologySuite
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/NetTopologySuite/NetTopologySuite/issues) and [closed](https://github.com/NetTopologySuite/NetTopologySuite/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Inwards buffer on a pretty simple polygon results in an EMPTY result.

### Steps to Reproduce
```cs
        [Fact]
        public void Buffer_on_polygon_results_in_empty_polygon()
        {
            var geom = new WKTReader().Read("POLYGON ((2886.0994 -471.6888, 2886.0994 -470.0302, 2736.0445 -322.4259, 2734.3578 -322.4259, 2734.3578 -471.6888, 2736.0445 -471.6888, 2886.0994 -471.6888))");
            var buffer = geom.Buffer(-2);
            buffer.IsEmpty.Should().BeFalse();
        }
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5.0
- Other NetTopologySuite packages and versions: -
- Environment (Operating system, version and so on): Windows
- .NET Framework version: 4.8
- Additional information: -

_Thanks for reporting the issue to NetTopologySuite!_

**Comment by FObermaier** [comment]
This does not apply to the current codebase.
