### ISSUE TITLE
Geometry.Intersection() results changes for polygons between version 2.1 and 2.2 (and later), and might be incorrect

### ISSUE THREAD

**Issue by southernsun** [NetTopologySuite/NetTopologySuite#764]
### Description
Geometry.Intersection(geometry) for polygons changed behavior between multiple version of NTS, where the latest version is returning a result that to my best knowledge is incorrect. Z-values are being calculated for certain points, which wasn't happening in older versions (tested from 1.15.1 till v2.1)

### Steps to Reproduce
I attached a Visual Studio sample solution that contains two test projects:
- NTS.IntersectionTestNew
- NTS.IntersectionTestOld

"New" is using NTS v2.5.0 and "Old" is using v1.15.3

From version 1.15 (didn't test lower versions) till version 2.1 NTS would return a polygon where several points of the resulting polygon would have no Z-value or have it set to NaN, which is in my opinion the correct result. Version 2.2.0 and higher return Z-values for all the points of the Intersection() while some of these points don't have an intersection with the input geometries.

Visual Studio example project: [Intersection.zip](https://github.com/user-attachments/files/16688616/Intersection.zip)

![image](https://github.com/user-attachments/assets/351e6f1e-64d2-48a0-b22b-b2075152a52b)

In the image above, red is the "elemtriangle" geometry, yellow is the "shape" geometry and purple is the resulting intersection geometry since version 2.2 and higher. The right side of the resulting polygon is correct, but the left side has Z coordinates for its coordinates that I can't explain. Previously NTS would just produce NaN or no values for these particular coordinates.

So, for IntersectionRoutine() test in the GeomFactoryNewTest project, i would expect a result similar to resultWkt2 or resultWkt3, but it is returning resultWkt1.

Is there a way to make sure the Intersection() method will behave similar to v2.1 or lower? Another option would be to check each coordinate and see whether it intersects/is within with the yellow shape, and if not, set the Z-value to NaN, but this would be an computational extensive extra check. Any other suggestions?

### System Configuration
- NetTopologySuite version: different behavior since v2.2 till v2.5. v2.0 and v2.1 would report NaN for the Z-value for these particular points. v1.15.1 till v15.3 would just not report a Z-value for these particular points.
- Windows 11, Visual Studio, AnyCpu, Debug and Release. NET FW 4.8.1
- Additional information: not applicable.

**Comment by FObermaier** [comment]
The preservation/computation of z-ordinate values has been added with v2.2. If needed these values are interpolated from the `LineSegment`s producing the intersection.

This is the relevant [commit].(https://github.com/NetTopologySuite/NetTopologySuite/commit/efbc5dc421b6abaaa72bb1f4aa48e4a34e4a30f3)

There is no way to turn that off other than 
* to make sure the input is only 2D or
* remove the 3rd dimension after intersection computation, e.g. by deriving your own `GeometryTransformer`

**Comment by FObermaier** [comment]
1. Intersection point calculation
    * The x- and y- ordinates of an intersection point are computed as if no z-ordinate was involved.   
    * For the two `LineSegment`s causing the intersection point in 2D, the slope of each is computed and used to compute the z-ordinate value on the `LineSegment` at the intersection point. The mean of these values is then used as z-ordinate. _Is that clear, don't make me draw a sketch of that_
    
3. GeometryTransformer
```C#
internal class TwoDTransformer : GeometryTransformer
{
    protected override CoordinateSequence Copy(CoordinateSequence seq)
    {
        var res = Factory.CoordinateSequenceFactory.Create(seq.Count, 2, 0);
        CoordinateSequences.Copy(seq, 0, res, 0, seq.Count);
        return res;
    }
}

var to2D = new TwoDTransformer();
var twoDGeom = to2d.Transform(<geom from somewhere>);
```

**Comment by southernsun** [comment]
1. Wouldn't it make more sense to get the Z-values from either of the two geometries that are used for the intersection at that particular X,Y ordinate instead of taking an calculated guess? Albeit, I'm a novice in all of this, so I assume the current approach is the consensus within the community. I guess this is one of the issues of it being a 2.5D model.
2. With _"As the GeometryTransformer doesn't let me provide an additional argument to the Transform() method."_, I meant it won't allow me to add an additional parameter such as "myTransformer.Transform(geom, secondGeom)". As I need to original intersecting geometry on each Transform call to set the Z-values to NaN for all coordinates where there is no actual intersection in the 3D space on the geometry that I'm transforming.

Thank you for your time and effort. Is there anyway i can support you by buying a cup of coffee or donating some money?

**Comment by FObermaier** [comment]
OK, I see. Your solution is bound to be terribly slow. You can adjust the proposed `TwoDTransformer` like this:

```C#
internal class IntPtZToNaNTransformer : GeometryTransformer
{
    private readonly HashSet<Coordinate> _origCoordinates;

    public IntPtZToNaNTransformer(Geometry original)
    {
        _origCoordinates = new HashSet<Coordinate>(original.Coordinates);
    }

    protected override CoordinateSequence Copy(CoordinateSequence seq)
    {
        var res = seq.Copy();
        for (int i = 0; i <= res.Count; i++)
        {
            // leave original coordinates untouched
            if (_origCoordinates.Contains(res.GetCoordinate(i)))
                continue;
            // remove computed z-ordinate from intersection points
            res.SetZ(i, double.NaN);
        }
        return res;
    }
}

var t = new IntPtZToNaNTransformer(original);
var shape = t.Transform(shape);
```
>  Is there anyway i can support you by buying a cup of coffee or donating some money?

No.

**Comment by southernsun** [comment]
Thanks! I will make _origCoordinates accessible as a property, otherwise I will need to create an IntPtZToNaNTransformer instance every time i do a transform as the "original" is going to be different on each call to Transform.

Thanks again for your help and time.

**Comment by southernsun** [comment]
for completion, my Transformer:

```
        public class IntPtZToNaNTransformer : GeometryTransformer
        {
            private HashSet<Coordinate> _origCoordinates;

            public void SetOriginal(Geometry original)
            {
                _origCoordinates = [..original.Coordinates];
            }

            protected override CoordinateSequence Copy(CoordinateSequence coordinateSequence)
            {
                CoordinateSequence result = coordinateSequence.Copy();

                for (int i = 0; i < result.Count ; i++)
                {
                    // leave original coordinates untouched
                    if (_origCoordinates.Contains(result.GetCoordinate(i)))
                    {
                        continue;
                    }

                    // remove computed z-ordinate from intersection points
                    result.SetZ(i, double.NaN);
                }

                return result;
            }
        }
```
