### ISSUE TITLE
Consider Removing PowerCollections Dependency In .NET 2.0 and PCL

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#77]
This is a successor of #73, which identified what could be done with minimal rewrites in NTS and which resulted in #75.  Here are the things that are keeping the .NET 2.0 and PCL targets from dropping PowerCollections entirely:

1. (Both 2.0 and PCL) Need a hash-based set type.
    1. `HashSet<T>` can be emulated by wrapping a `Dictionary<T, bool>`.
2. (Both 2.0 and PCL) Need a way to do a stable-sort.
    1. One way to do it would be to add a utility method that wraps each element of an `IEnumerable<T>` in an `ItemWithIndex<T>` whose comparison implementation uses the original `T`'s comparison, and then uses the index from the original sequence as a tiebreaker, then sort it and select the `T` elements of the sorted set back out.
    2. Of course, another way would be to just go ahead and implement a stable sort within NTS, which is not very appealing either.
3. (PCL only) Need an ordered dictionary type.
    1. It's not actually all that easy to do this.  Even if it looks utterly obvious that [EdgeList](https://github.com/NetTopologySuite/NetTopologySuite/blob/0f56e478f91a0a40e4b75203ade55908990fc4ce/NetTopologySuite/GeometriesGraph/EdgeList.cs#L24), for example, **should** be OK with using a hash-based dictionary, it's not.  Because [OrientedCoordinateArray](https://github.com/NetTopologySuite/NetTopologySuite/blob/0f56e478f91a0a40e4b75203ade55908990fc4ce/NetTopologySuite/Noding/OrientedCoordinateArray.cs) does not have `Equals` / `GetHashCode` overrides that are consistent with its comparison behavior.
    2. The requirement to be able to use a hash-based dictionary in the first place is that either the key type defines its `Equals` and `GetHashCode` methods such that two "equal" objects return true from `Equals` and have the same hash codes from `GetHashCode`, or we implement an `IEqualityComparer<T>` with those semantics.
    3. Many `TKey` types in `SortedDictionary<TKey, TValue>` are like `OrientedCoordinateArray`: `CompareTo`, but no `Equals` / `GetHashCode`.

**Comment by FObermaier** [comment]
Here my suggestions/remarks

1. Possible solutions:
    1. Reference `System.Core` (works only for full .NET 20, not PCL)
    2. Use Mono's implementation of HashSet<T> internally. The license looks very permissive, the speed is comparable to the native one.
2. I'd go for ii. Sedgewick's Algorithm bible has some acceptable (stable) sorting algorithms, I'm sure. I'll look into adopting one for NTS.
3. Are you saying that SortedDictionary should do?

**Comment by FObermaier** [comment]
sorry for the noise

**Comment by airbreather** [comment]
1. I'm not sure if the "reference `System.Core`" solution is appropriate.  Wouldn't that mean that the .NET 2.0 build will only run on systems that have .NET 3.5 installed anyway (which upgrades the .NET 2.0 CLR in-place)?  Mono `HashSet<T>` could work, but then again, wouldn't it make just as much sense to copy [the implementation from .NET Core](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/HashSet.cs) now that it's [open-source (MIT)](https://github.com/dotnet/corefx/blob/master/LICENSE)?
2. No opinions here.
3. Well, `SortedDictionary<TKey, TValue>` is what the full .NET 2.0 target uses already.  The problem is that it's not available in PCL, at least the profile NTS uses.
    1. The reason I brought up the hash-based dictionary idea is that it seems hypothetically possible that, if all key types had acceptable `Equals` / `GetHashCode`, then most uses could be replaced with hash-based dictionaries which we only sort when the ordering is observed externally.
    2. Perhaps that's not a viable route for performance reasons (which would most likely be the case if something changes the dictionary after something else has already enumerated over it, but there may be other things I'm not thinking of right now).

**Comment by DGuidi** [comment]
> the .NET 2.0 build will only run on systems that have .NET 3.5 installed anyway  (which upgrades the .NET 2.0 CLR in-place)

As far as I know, .NET 3.5 it's _only_ new assemblies (i.e: LINQ), no new CLR (same as 2-0) stuff and no dll substitutions (like 4.5-4.6)

**Comment by xivk** [comment]
Any reason to hold on to.NET 2.0 support? In OsmSharp I also used Mono's HashSet implementation at some point. It's not perfect but better than keeping powercollections in my opinion.

**Comment by DGuidi** [comment]
> Any reason to hold on to.NET 2.0 support? 
> It's not perfect but better than keeping powercollections in my opinion.

+1 and this can "save" .NET 2.0 support, or I'm wrong?
I don't like to maintain powercollections __only__ to .NET 2.0 support. My2cents.

**Comment by airbreather** [comment]
> As far as I know, .NET 3.5 it's only new assemblies (i.e: LINQ), no new CLR (same as 2-0) stuff and no dll substitutions (like 4.5-4.6)

Hmm, well even so, my point is that if someone says "no, I can't use the .NET 3.5 release; I need the .NET 2.0 release", then wouldn't NTS need to distribute the .NET 3.5 version of System.Core.dll in order to actually serve those folks?

> [...] In OsmSharp I also used Mono's HashSet implementation at some point. It's not perfect but better than keeping powercollections in my opinion.
/
> I don't like to maintain powercollections **only** to .NET 2.0 support. My2cents.

The PCL target also has no easy replacement for the 3 things listed in the issue description.  I'm mainly looking at the `OrderedDictionary<TKey, TValue>` issue, in particular (since pulling in either Mono's or .NET Core's `HashSet<T>` would fix the first item, and sorting is one of the most solved problems in computer science).

**Comment by DGuidi** [comment]
> the .NET 3.5 version of System.Core.dll 

This Library actually don't exists, I think. System.core.dll it's the same lib (binary dll) in 2.0 and 3.5.

----- Messaggio originale -----
Da: "airbreather" <notifications@github.com>
Inviato: ‎26/‎01/‎2016 12:03
A: "NetTopologySuite/NetTopologySuite" <NetTopologySuite@noreply.github.com>
Cc: "Diego Guidi" <diegoguidi@gmail.com>
Oggetto: Re: [NetTopologySuite] Consider Removing PowerCollections DependencyIn .NET 2.0 and PCL (#77)

As far as I know, .NET 3.5 it's only new assemblies (i.e: LINQ), no new CLR (same as 2-0) stuff and no dll substitutions (like 4.5-4.6)
Hmm, well even so, my point is that if someone says "no, I can't use the .NET 3.5 release; I need the .NET 2.0 release", then wouldn't NTS need to distribute the .NET 3.5 version of System.Core.dll in order to actually serve those folks?
[...] In OsmSharp I also used Mono's HashSet implementation at some point. It's not perfect but better than keeping powercollections in my opinion.
/
I don't like to maintain powercollections only to .NET 2.0 support. My2cents.
The PCL target also has no easy replacement for the 3 things listed in the issue description. I'm mainly looking at the OrderedDictionary<TKey, TValue> issue, in particular (since pulling in either Mono's or .NET Core's HashSet<T> would fix the first item, and sorting is one of the most solved problems in computer science).

**Comment by airbreather** [comment]
> System.core.dll it's the same lib (binary dll) in 2.0 and 3.5.

Can systems that have **only** .NET 2.0 installed, and **not** .NET 3.5, and **cannot** install 3.5, use `HashSet<T>`?  Win2000 comes to mind.

If [this SO answer](http://stackoverflow.com/a/687042/1083771) and its comments are to be trusted, it sounds like the "reference System.Core" solution would not work for things that use the .NET 2.0 build and cannot use the .NET 3.5 build instead.

**Comment by DGuidi** [comment]
Ok maybe [I'm wrong](https://msdn.microsoft.com/en-us/library/bb359438(v=vs.90).aspx) 
Probably I made some confusion with .NET versions and Core CRL versions... or, maybe, __system.core.dll__ exists only in .NET 3.5 and not in previous versions, as stated[here](http://blogs.msdn.com/b/pedram/archive/2007/11/07/system-core-dll-of-net-framework-3-5.aspx)?

**Comment by FObermaier** [comment]
I agree we should go for a solution that is not only a fix for .NET 2.0.

I don't particulary care whether we take HashSet<T> from .NET core or from Mono, which ever way is easier, requires fewer additions to the codebase.

If we take HashSet<T> from either source, we might as well take SortedDictionary<TKey, TValue> from there.

Along with a stable sorting algorithm we have it all together, don't we?

**Comment by FObermaier** [comment]
For the record, I don't use the .NET 2.0 version of NTS either but I'm reluctant to removing it completly.

**Comment by DGuidi** [comment]
> I'm reluctant to removing it completly

I agree with you, I think 2.0 support can be an added value

**Comment by FObermaier** [comment]
I made an attempt to extract from .NET Core to have HashSet and SortedDictionary.
Could anyone take an attempt to bring that into NTS? Thanks
[Snipplets.zip](https://github.com/NetTopologySuite/NetTopologySuite/files/106438/Snipplets.zip)

**Comment by DGuidi** [comment]
@FObermaier I've take a look: there is a replacement for a 2.0 StableSort? I've not found something similar in code you've posted

**Comment by FObermaier** [comment]
No it is atm "just" HashSet and SortedDictionary

**Comment by DGuidi** [comment]
@FObermaier ah ok, so SortedSet looks the only thing missing. your code looks ok.
Anyway, hope to push a branch so anyone can take a look.

**Comment by FObermaier** [comment]
SortedSet is in the Zip file, too

**Comment by DGuidi** [comment]
@FObermaier ops, my bad. comment fixed.

**Comment by DGuidi** [comment]
Code posted as "snipplets" branch.
From the commit comment, here my thoughts:
>1. StableSort stuff not provided
>2. I'm unable to reference "replacements" code only for NTS project when built for .NET 2.0

Anyone feel free to fix things and add comments to branch.

P.S: : probably I've made some mistakes with submodules management, that looks not removed in branch... any help appreciated.

**Comment by DGuidi** [comment]
ops, troubles with [TravisCI](https://travis-ci.org/NetTopologySuite/NetTopologySuite)

**Comment by DGuidi** [comment]
>I'm unable to reference "replacements" code only for NTS project when built for .NET 2.0**
@FObermaier any idea about this?

**Comment by FObermaier** [comment]
I updated that branch.
No need to reference the `System.Core.Replacements` or `System.Core.Replacements.Pcl` libraries,
as I did a conditional include (`&lt;IncludeItems condition= " '$(TargetFrameworkVersion)' == 'v2.0' "&gt;`) of the files in the project for .NET 2.0 and an unconditional one for the PCL project.

I'm unhappy with the namespaces for the framework replacements. Shouldn't we indicate that we borrowed it from corefx? Additionally we should place a `ReadMe` file denoting where it comes from and which license applies...

An Update of the license file is necessary, too. Btw JTS has changed the license to BSD/EPL. But this is worth a different work item.


.

**Comment by airbreather** [comment]
And I submitted a PR for that branch (#79) which tops it off with a stable sort.

**Comment by DGuidi** [comment]
>Shouldn't we indicate that we borrowed it from corefx?

That was I did at first, but then I thinked that using same namespaces could avoid __using__ and macros.
Thanks to you and @airbreather for the revision.

**Comment by airbreather** [comment]
#80 deals with the remaining things I found during my own (informal) review of the branch that I could fix easily by myself.

Questions I still have:

1. Were the following four additional lines needed? [change1](https://github.com/NetTopologySuite/NetTopologySuite/commit/7ddffcf0ccb4bd6f85146491cd7a77c844aede84#diff-e28c61f7e411ff39aceb635509b5907fR630), [change2](https://github.com/NetTopologySuite/NetTopologySuite/commit/7ddffcf0ccb4bd6f85146491cd7a77c844aede84#diff-e28c61f7e411ff39aceb635509b5907fR632), [change3](https://github.com/NetTopologySuite/NetTopologySuite/commit/7ddffcf0ccb4bd6f85146491cd7a77c844aede84#diff-d6c9a31a3c4b0ec33b1e1bf09a80a7c0R1396), [change4](https://github.com/NetTopologySuite/NetTopologySuite/commit/7ddffcf0ccb4bd6f85146491cd7a77c844aede84#diff-d6c9a31a3c4b0ec33b1e1bf09a80a7c0R1398)
2. As has been mentioned above, the license file needs an update.
3. Is there still a need for the separate .csproj files and separate location for the replacements?  It seems like the replacement files could just sit in an actual folder under NetTopologySuite, such as NetTopologySuite/Utilities/FrameworkReplacements.

**Comment by DGuidi** [comment]
@airbreather 
1. I don't know, hope @FObermaier can help
2. yep
3. probably not

**Comment by FObermaier** [comment]
1. no they are not needed. They are added atomagically whenever I open the solution. I think it has to do with NuGet package restore option. Don't you see this behavior?
3. no need for separate projects.

**Comment by DGuidi** [comment]
branch __revsnipplets__ merged, hope I' haven't made any mistake
