### ISSUE TITLE
Changing the SRID doesn't change the coordinate data.

### ISSUE THREAD

**Issue by alex-smith-ai** [NetTopologySuite/NetTopologySuite#771]
### Description
I have a Geometry, say a Point at (1.57554173300002, 42.646007512) with an SRID of 4326. I would like to change the SRID to 3857, so a Point at (175388.50344111404, 5258244.862258436).

However, when I change the SRID to 3857, the new Point has the correct SRID but the Point hasn't changed. I have the same behavior with (Multi)Polygons as well.

Am I not creating/reassigning the SRID correctly? Does the GeometryFactory require a different/additional step to do this? I know many change the SRID for their Geometry objects so I expect many have solved this already. Thank you in advance.

### Steps to Reproduce
Example 1, changing SRID directly
```
const double inputX = 1.57554173300002;
const double inputY = 42.646007512;
var point = new Point(new Coordinate(inputX, inputY))
{
   SRID = 3857
};
Console.WriteLine($"x = {point.X}, y = {point.Y}");
// Prints "x = 1.57554173300002, y = 42.646007512"
```

Example 2, using GeometryFactory
```
const double inputX = 1.57554173300002;
const double inputY = 42.646007512;
var factory = new GeometryFactory(new PrecisionModel(), 3857);
var point = factory.CreatePoint(new Coordinate(inputX, inputY));
Console.WriteLine($"x = {point.X}, y = {point.Y}");
// Prints "x = 1.57554173300002, y = 42.646007512"
```

### System Configuration
Tell us about the environment where you are experiencing the bug:
- NetTopologySuite version: 2.5.0
- Other NetTopologySuite packages and versions:
- Environment (Operating system, version and so on): Mac OS 14.6.1
- .NET Framework version: 8.0

**Comment by FObermaier** [comment]
NetTopologySuite does not perform coordinate transformation on its own. You will have to use other libraries like
* [ProjNet](https://www.nuget.org/packages/ProjNet)
* [SharpProj](https://www.nuget.org/packages/SharpProj.NetTopologySuite)
* [DotSpatial.Projections](https://www.nuget.org/packages/DotSpatial.Projections)
* ...

to achieve that.

**Comment by alex-smith-ai** [comment]
Now I get. Thank you. Given that NTS doesn't perform coordinate transformation, how should you use the `geometry.SRID = 1234` or `GeometryFactory(1234)` functionality?

**Comment by FObermaier** [comment]
That is plain information. You might be able to use it in order to get a spatial reference system from the projection library. NTS itself does not do anything with it.
