### ISSUE TITLE
NetTopology .NET assemblies?

### ISSUE THREAD

**Issue by stgeorges** [NetTopologySuite/NetTopologySuite#78]
Hello,
By checking the NetTopologySuite repository, there's a large amount of c# file present.
I was wondering if a single (or a couple of those) NetTopologySuite .NET assembly (.dll) exists?
I am interested in using it/them to call NetTopologySuite function in ironpython.

Thank you for the reply.

**Comment by FObermaier** [comment]
You can install NetTopologySuite by using the binaries provided by [NuGet](https://www.nuget.org/packages/NetTopologySuite/)

**Comment by stgeorges** [comment]
Thank you @FObermaier ,
I have only found the [Nuget Package .nupkg file](https://www.nuget.org/api/v2/package/NetTopologySuite/1.14.0).
Is it possible to download the binaries directly (or in a .zip file) for users who do not have Visual Studio/Express?

**Comment by FObermaier** [comment]
Those are basically zip files that adhere to some internal directory layout.

**Comment by stgeorges** [comment]
Thank you @FObermaier .
Is there a C# example code on how .shp files' fields, values and feature points can be read from it, and printed to a console? 
I've seen the official [API section](http://nettopologysuite.github.io/html/namespace_net_topology_suite.html), but did not understand which functions to use in order to achieve the opening of .shp file, along with printing its features, values..

**Comment by DGuidi** [comment]
@stgeorges please post support questions in the [google group](http://code.google.com/p/nettopologysuite/), where you can find also some samples.

**Comment by stgeorges** [comment]
Hi @DGuidi ,
When I follow the [google group](http://code.google.com/p/nettopologysuite/) link, it takes me to this github repository:

nettopologysuite has Moved!

> This project has moved to a new location on the internet. Its new home is at: https://github.com/NetTopologySuite/NetTopologySuit

**Comment by DGuidi** [comment]
@stgeorges sorry, posted wrong link to past code repository. my bad.
here the [Google Group](https://groups.google.com/forum/#!forum/nettopologysuite) link.
