### ISSUE TITLE
Remove MSBuild based NuGet package restore

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite#81]
The method of restoring NuGet packages for build has changed for NuGet version 2.7+
https://docs.nuget.org/consume/package-restore/msbuild-integrated

The new approach is described in this document:
https://docs.nuget.org/Consume/Package-Restore

**Comment by DGuidi** [comment]
@FObermaier  fix was added to __RevSnipplets__ branch. do you plan to merge also this change after integration?

**Comment by FObermaier** [comment]
I think this branch is close to being merged

**Comment by FObermaier** [comment]
Fixed with 213696b0577621a238855a05591af36187e1e848
