### ISSUE TITLE
Add support for writing GeoJSON feature ID

### ISSUE THREAD

**Issue by atlefren** [NetTopologySuite/NetTopologySuite#83]
Ref the GeoJSON spec on Features: http://geojson.org/geojson-spec.html#feature-objects

    If a feature has a commonly used identifier, that identifier should be included as a member of the   feature object with the name "id".

This means that a valid GeoJSON feature response should support features on the form

    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [10, 60]
      },
      "id": 1,
      "properties": {
        "Name": "test"
      }
    }

And, in the GeoJSON feature converter the "id" property is supported on read:
https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite.IO/NetTopologySuite.IO.GeoJSON/Converters/FeatureConverter.cs#L67

Alas, there is no support  for this on write.

What needs to be done:
1. Add an Id-property to NetTopologySuite.Features.Feature
2. Add support for assigning the id read in FeatureConverter to the Id-property of the feature,  and not add it as an attribute
2. Add support for writing the id directly on the GeoJSON feature

If none of the "regular" contributors are interested / have time I might be able to devote some time to implement this, but I would like the developers to at least see the rationale before I start something

**Comment by FObermaier** [comment]
> Add an Id-property to NetTopologySuite.Features.Feature

Checking for `Feature.Attributes["id"]` is not sufficient? This could reduce the effort to special handling in the Feature- and AttributeTableConverter's WriteJson overloads.
The ID could then be gathered by e.g. an extension method:

```
public static class FeatureExtensions
{
    public static object ID(this IFeature feature)
    {
        return HasID(feature)
        ? feature.Attributes["id"] 
            : null;
    }

    public static bool HasID(this IFeature feature)
    {
        if (feature == null)
            throw new ArgumentNullException("feature");

        return feature.Attributes.Exists("id");
    }
}
```

**Comment by atlefren** [comment]
@FObermaier Good idea, that means that it's a much smaller patch, and it captures the essence of the spec, so I cannot see why this shouldn't work.

I'd be happy to use this approach if it's included!

**Comment by FObermaier** [comment]
@atlefren:
Could you please verify that the provided fix suits your needs and if so, close the issue? 
Thanks

**Comment by atlefren** [comment]
@FObermaier This looks great! Thanks for quick follow-up and solution!

**Comment by lorenh** [comment]
Is there a way to override this new "id" behavior when serializing?  This broke our code.  We actually have an intentional "id" parameter in our properties, and need it to stay there and not get promoted up to the feature.  Because of this we cannot upgrade to this latest version of NetTopologySuite unless we do some sort of override / disabling of this change.

**Comment by anujgoel73** [comment]
Was this request ever acknowledged? I am facing the same problem.
