### ISSUE TITLE
Incorrect looping in NetTopologySuite.IO.Converters.GeometryConverter

### ISSUE THREAD

**Issue by SharavananEswar** [NetTopologySuite/NetTopologySuite#88]
I have found one issue while parsing IGeometry data by NetTopologySuite.IO.Converters.GeometryConverter. We are using JSON.NET for serialize and de-serialize our own feature collection. Our feature model class looks like,
    public class Feature
    {
        public Guid Id { get; set; }
        public string Type { get { return "Feature"; } }
        public IGeometry Geometry { get; set; }
        public IDictionary<string, object> Properties { get; set; }
        /// <summary>
        /// User supplied and internal metadata
        /// </summary>
        public IDictionary<string, object> Metadata { get; set; }
    }

and JSON model looks like,

{
      "id": null,
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          99.404296899999963,
          40.7805414,
          0.0
        ]
      },
      "properties": {
        "text 1": "AsaSAS"
      },
      "metadata": {
        "collection_userinfo": "()",
        "collection_timestamp": "2016-02-23T16:21:47.2489582",
        "externalid": "00e7055f-c5e4-4ac5-b67a-4fc308416187",
        "collection_todoid": "",
        "collection_templateid": "3",
        "collection_layerid": "1"
      }
    }

Note: Geometry maybe null or have values.

If the Geometry is null, NetTopologySuite.IO.Converters.GeometryConverter.ParseGeometry() loops all json properties in JSON model as shown below,
private IGeometry ParseGeometry(JsonReader reader)
        {
            GeoJsonObjectType? geometryType = null;
            List<object> coords = null;
            while (reader.Read())
            {
                ...............
            }
      }

We're not getting Properties and Metadata object values if Geometry is null. I think the reason is because of reader cursor point ends in loops and not process other objects,

Right now I have added temporary fix like,
    public class CustomNetTopologySuiteGeometryConverter : NetTopologySuite.IO.Converters.GeometryConverter
    {
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            //There is one issue in deserializing IGeomertry object when it is null.
            //I have created issue ticket for tracking
            //Right now overridden ReadJson of NetTopologySuite.IO.Converters.GeometryConverter and fixed the issue
            if (reader.TokenType == JsonToken.Null) return null;

            return base.ReadJson(reader, objectType, existingValue, serializer);
        }
    }

Can you please check this one and fix it...

The same issue present in NetTopologySuite.IO.Converters.CoordinateConverter()

Thanks,
Sharavanan

**Comment by DGuidi** [comment]
can you post a GeoJSON sample with "null" geometry?

**Comment by SharavananEswar** [comment]
{
      "id": "00000000-0000-0000-0000-000000000000",
      "type": "Feature",
      "geometry": null,
      "properties": {
        "yesNo 1": false,
        "date 1": "2016-02-16T00:00:00"
      },
      "metadata": {
        "collection_userinfo": "()",
        "collection_timestamp": "2016-02-25T14:38:01.9087672",
        "collection_todoid": "",
        "collection_templateid": "nj7Glv-AqV0",
        "collection_layerid": "nj7Glv-AqV0"
      }
    }

I think we have to add below condition,
if (reader.TokenType == JsonToken.Null) return null;

Thanks,
Sharavanan

**Comment by DGuidi** [comment]
looks that GeoJSON specs allow [null geometry[(http://geojson.org/geojson-spec.html#feature-objects)

**Comment by SharavananEswar** [comment]
Yes you are correct. As per spec we have a null.

The issue is when geometry is null,

private IGeometry ParseGeometry(JsonReader reader)

        {

            GeoJsonObjectType? geometryType = null;

            List<object> coords = null;



            if (reader.Value == null)

                return null;



            while (reader.Read())

            {

                //This loop reads all json object

}

}

var feature =  JsonConvert.DeserializeObject(jsonFeatureString, new
NetTopologySuite.IO.Converters.GeometryConverter());
var jsonString = JsonConvert.SerializeObject(feature,new
NetTopologySuite.IO.Converters.GeometryConverter())

see the same json result after de-serialize and serialization. You can see
Properties and Metadata will be null.

**Comment by SharavananEswar** [comment]
Continuation to previous mail,

The issue is when geometry is null,

private IGeometry ParseGeometry(JsonReader reader)

        {

            GeoJsonObjectType? geometryType = null;

            List<object> coords = null;



            while (reader.Read())

            {

                //This loop reads all json object

}
}

so, we have to check value before while loop,

if (reader.TokenType == JsonToken.Null) return null;

**Comment by DGuidi** [comment]
code works well if you omut "metadata" stuff. so bug looks not related to null geometry, but instead to unexpected properties

**Comment by DGuidi** [comment]
@FObermaier can I push a fix? or are you working on it, too? :)

**Comment by DGuidi** [comment]
@SharavananEswar can you check?

**Comment by SharavananEswar** [comment]
Please push your changes. After that I will delete the temporary fix in my
code.

Thanks,
Sharavanan

**Comment by SharavananEswar** [comment]
Please don't push these changes to master branch. 

The mentioned Feature model followed in our product. Properties  and Metadata objects are specific to us and Don't add it in your Feature model until we get requirement for this.

I will clearly record my situation in video format and send it you. 

Thanks,
Sharavanan

**Comment by DGuidi** [comment]
"properties" are simply attributes, mapped to Feature.Attributes.
Other stuff, like "metadata" is simply ignored.

This email has been sent from a virus-free computer protected by Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>


Diego Guidi

**Comment by DGuidi** [comment]
looks ok to me
