### ISSUE TITLE
Clarify coding conventions

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite#89]
I think we should agree on some coding conventions as some commits are blown up with a change in e.g. variable declarations:
```var geom = geomFactory.CreatePoint(...);```
is changed to 
```IGeometry geom = geomFactory.CreatePoint(...);```
or vice versa. This makes it difficult to track the essential change.

Also, sometimes namespace declarations get moved from the header of the file to just below the namespace declaration of the class declared in the file.

Perhaps, not applying automatic reformating (e.g. ReSharper) is sufficient.

**Comment by DGuidi** [comment]
To me, automatic reformatting is the key to share same stile.
Hope to create a StyleSettings file soon.

**Comment by DGuidi** [comment]
@FObermaier added a stile to share with all developers, try to take a look and modify as you wish.
personally, I don't like "var" sintax, but I haven't found a way to force "explicit" declaration.
anyway: choosing a set of rules and [using this file](http://stackoverflow.com/a/14896788) can help us: I think that a codebase with the same style is a great added value.
As usual, feel free to add your thoughts and/or modify settings file.

**Comment by airbreather** [comment]
@DGuidi how would someone running just Visual Studio 2015 Community Edition, or MonoDevelop (i.e., no ReSharper) ensure compliance with this?

**Comment by DGuidi** [comment]
No way, actually. Actually, JetBrains offer free licenses for oss contributors. I've asked but no response at this time.
I see many oss projects use this system, but if you know other tools that can help with this, feel free to suggest. 

----- Messaggio originale -----
Da: "airbreather" <notifications@github.com>
Inviato: ‎28/‎02/‎2016 17:34
A: "NetTopologySuite/NetTopologySuite" <NetTopologySuite@noreply.github.com>
Cc: "Diego Guidi" <diegoguidi@gmail.com>
Oggetto: Re: [NetTopologySuite] Clarify coding conventions (#89)

@DGuidi how would someone running just Visual Studio 2015 Community Edition, or MonoDevelop (i.e., no ReSharper) ensure compliance with this?

**Comment by FObermaier** [comment]
@DGuidi, I'm an absolute fan of `var` declarations :).
Nonetheless, I go with whatever you say. @airbreather is right though, can't this be done with stylecop?

**Comment by DGuidi** [comment]
@FObermaier stylecop suggests things, while R# applies styles directly via code cleanup, as far as I know.

**Comment by Joeppie** [comment]
I've worked with a company in the past where the guideline was to only use var where the type of the variable in question was directly deducible from the line itself, without needing to rely on other information sources (such as Intellisense, debugging, etc.)

E.g.

```
     var x = (y) as string; //Would be fine; there is no question about the type.
     var geom = geomFactory.CreatePoint(...);  //Unless investigate/ use intellisense, you cannot determine the type; is geom a Point or an IGeom? Without looking it up or debugging I would not know for sure.
```

**Comment by DGuidi** [comment]
@Joeppie honestly, for the same reason you noticed I've stopped using var completely.

to me `var x = (y) as string` is readable exactly as  `string x = (y) as string`
and in **ALL** other cases is more readable to see directly the type.
my2cents.

**Comment by FObermaier** [comment]
For what it is worth, I'm a great fan of `var` declarations: If I have to write down what type it is, there is something wrong with the variable name in the first place.

So if I name a variable
* `geom` it is a geometry, I don't specifically care if it is a point, line, etc.
* `point`, `ptWhatever` I know it is a point
* `line` ... you get the idea.

But that is just my 2cts

**Comment by DGuidi** [comment]
> point, ptWhatever I know it is a point

but maybe you want a reference to `IPoint`m so, sometimes name isn't just enough
