### ISSUE TITLE
Stream Support for ShapefileDataReader using IStreamProviderRegistry

### ISSUE THREAD

**Issue by gprieck** [NetTopologySuite/NetTopologySuite#91]
This is my first post, hoping to start contributing to this project.
I would like support reading Streams.  The current options are from file and from cloud storage.

I created two classes that I think would support this.  I have attached the source.
public class MemoryStreamProvider : IStreamProvider
public class ShapefileMemoryStreamProviderRegistry : IStreamProviderRegistry

[MemoryStreamProvider.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/153211/MemoryStreamProvider.txt)
[ShapefileMemoryStreamProviderRegistry.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/153212/ShapefileMemoryStreamProviderRegistry.txt)

Test method is below.  The problem I am having is that the memorystream is disposed when it gets to this method in NetTopologySuite-master\NetTopologySuite.IO\NetTopologySuite.IO.GeoTools\Dbase\DbaseFileReader.FullFat.cs

public DbaseFileEnumerator(DbaseFileReader parent)
            {
                _parent = parent;
                Stream stream = parent._streamProvider.OpenRead();
                _dbfStream = new BinaryReader(stream, parent._header.Encoding);
                ReadHeader();
            }

public static void Test1()
        {
            byte[] shpBytes = File.ReadAllBytes(@"c:\temp\G.shp");
            byte[] shxBytes = File.ReadAllBytes(@"c:\temp\G.shx");
            byte[] dbfBytes = File.ReadAllBytes(@"c:\temp\G.dbf");

            MemoryStream shpStream = new MemoryStream(shpBytes);
            MemoryStream shxStream = new MemoryStream(shxBytes);
            MemoryStream dbfStream = new MemoryStream(dbfBytes);

            GeometryFactory factory = new GeometryFactory();

            NetTopologySuite.IO.Streams.ShapefileMemoryStreamProviderRegistry r =
                new NetTopologySuite.IO.Streams.ShapefileMemoryStreamProviderRegistry(shpStream, dbfStream, shxStream);

            ShapefileDataReader shapeFileDataReader = new ShapefileDataReader(r, factory);
            //Display the shapefile type
            ShapefileHeader shpHeader = shapeFileDataReader.ShapeHeader;
            //meta.ShpHeader = shapeFileDataReader.ShapeHeader;
            Console.Out.WriteLine(string.Format("Shape type: {0}", shpHeader.ShapeType));

            //Display the min and max bounds of the shapefile
            Envelope bounds = shpHeader.Bounds;
            Console.Out.WriteLine(string.Format("Min bounds: ({0},{1})", bounds.MinX, bounds.MinY));
            Console.Out.WriteLine(string.Format("Max bounds: ({0},{1})", bounds.MaxX, bounds.MaxY));

            //Display summary information about the Dbase file
            DbaseFileHeader header = shapeFileDataReader.DbaseHeader;
            //meta.DbfHeader = shapeFileDataReader.DbaseHeader;
            Console.Out.WriteLine("Dbase info");
            Console.Out.WriteLine(string.Format("{0} Columns, {1} Records", header.Fields.Length, header.NumRecords));

            for (int i = 0; i < header.NumFields; i++)
            {
                DbaseFieldDescriptor fldDescriptor = header.Fields[i];
                Console.Out.WriteLine(string.Format("   {0} {1}", fldDescriptor.Name, fldDescriptor.DbaseType));
            }

            //Reset the pointer to the start of the shapefile, just in case
            shapeFileDataReader.Reset();

            //Read through all records of the shapefile (geometry and attributes) into a feature collection 

            //ArrayList features = new ArrayList();
            //FeatureCollection features = new FeatureCollection();

            IList<IFeature> features = new List<IFeature>();

            while (shapeFileDataReader.Read())
            {
                Feature feature = new Feature();
                AttributesTable attributesTable = new AttributesTable();
                string[] keys = new string[header.NumFields];
                IGeometry geometry = shapeFileDataReader.Geometry;

                for (int i = 0; i < header.NumFields; i++)
                {
                    DbaseFieldDescriptor fldDescriptor = header.Fields[i];
                    keys[i] = fldDescriptor.Name;
                    attributesTable.AddAttribute(fldDescriptor.Name, shapeFileDataReader.GetValue(i));
                }
                feature.Geometry = geometry;
                feature.Attributes = attributesTable;
                features.Add(feature);
            }
            //Close and free up any resources
            shapeFileDataReader.Close();
            shapeFileDataReader.Dispose();

        }

**Comment by gprieck** [comment]
I changed how MemoryStreamProvider was storing the Stream in the constructor and returning the Stream in OpenRead method.  That eliminated the dispose issue.  I have not looked into yet, but probably not quite right for the OpenWrite method.  Revised files are attached.

[MemoryStreamProvider2.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/153399/MemoryStreamProvider2.txt)
[ShapefileMemoryStreamProviderRegistry2.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/153400/ShapefileMemoryStreamProviderRegistry2.txt)

**Comment by FObermaier** [comment]
@jaundice, could you please have a look at this.

**Comment by jaundice** [comment]
Will do.. May take a few days before I can though

@jaundice<https://github.com/jaundice>, could you please have a look at this.

-

**Comment by gprieck** [comment]
I made a few more changes and attached my files.  I switched it back to a Stream instead of a MemoryStream.  Thanks for looking into.
George

[MemoryStreamProvider.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/157720/MemoryStreamProvider.txt)

[ShapefileMemoryStreamProviderRegistry.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/157721/ShapefileMemoryStreamProviderRegistry.txt)

**Comment by jaundice** [comment]
@george any chance you can fork the repo and add your changes there?

I made a few more changes and attached my files. I switched it back to a Stream instead of a MemoryStream. Thanks for looking into.
George

MemoryStreamProvider.txt<https://github.com/NetTopologySuite/NetTopologySuite/files/157720/MemoryStreamProvider.txt>

ShapefileMemoryStreamProviderRegistry.txt<https://github.com/NetTopologySuite/NetTopologySuite/files/157721/ShapefileMemoryStreamProviderRegistry.txt>

-

**Comment by george** [comment]
I think @jaundice meant to mention @gprieck on that last comment. Cheers.

**Comment by gprieck** [comment]
Ok, I forked the master, uploaded my two source files, and created a Pull Request.  I have been reading and trying to follow the documentation, but please let me know if I am doing anything wrong

**Comment by jaundice** [comment]
@george sorry about that :)

@gprieck I have had a quick look, I will take a longer look soon. Initial impression is that it should work for a readonly provider, writable is much harder. 
A couple of thoughts: 
I am not sure you should dispose the stream that was passed in as a constructor argument in the dispose method, I would leave that up to calling code to manage that stream.

In the ReadFully method, I would store the stream position at the start of the method and reset that position before exiting the method.

iirc (I need to check) there are a few places in the various shapefile classes where there are multiple stream readers active at the same time. 
In your current code, writing is done on the passed in stream, whereas reading is done on a new memory stream initialized using a cached copy of the bytes as they were at initialization time, so readers will never see any changes to the data.

Thinking aloud, I would be tempted to change the constructor to take byte[] instead of Stream, this would indicate to the caller that we are not modifying that stream. Then copy the bytes into a bigger array (large enough to contain all modifications), the size would also be a constructor parameter. Reader streams and writer streams can then be created using the same array as the underlying buffer, but you would need to synchronize the Stream length across any readers and writers, note that you cannot set a length larger than the underlying buffer size, but you can set it shorter to only access real data. You could subclass MemoryStream and override Length to do this.

**Comment by gprieck** [comment]
I would like it to have the ability to write to Streams as well.  My use case is read the three shapefile streams (shp, shx, and dbf), convert to a List of IFeature objects, perform some interpolation on the List of IFeature objects, and then save them back to the shapefile streams.  So, what I have now supports the reading, but not the writing.  My initial version (See MemoryStreamProvider .txt in my first post) was having dispose issues in public DbaseFileEnumerator(DbaseFileReader parent).  That is why I converted to the byte array internally.  Any suggestions you have on how to fix the dispose issue and support writing would be great.
George

**Comment by jaundice** [comment]
@gprieck you could wrap the streams in another non disposing stream (e.g create a new subclass of Steam and forward all props and methods to the MemoryStream except Dispose), however you may still have issues where there are multiple readers open and only one "real" stream. 
Ultimately I think it will only really work reliably for writing if you use the byte[] buffer and provide new streams backed by that buffer. Once you have finished modifying you can call OpenRead on the stream provider which will return the stream containing the updated data and you can copy that stream over your initial file stream.

**Comment by gprieck** [comment]
I added two new classes to the fork based on everyone's comments.

ByteStreamProvider
ShapefileByteStreamProviderRegistry

George

**Comment by jaundice** [comment]
Sorry it has taken a while to get back to this @gprieck. Attached is a patch which should add a new project with a refactored set of ByteStream related classes. Unfortunately I haven't had a chance to write any tests for it. I'll try and schedule some time soon. Let me know if it works for you.

[0001-Refactored-ByteStream-related-classes.patch.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/175000/0001-Refactored-ByteStream-related-classes.patch.txt)

**Comment by gprieck** [comment]
I left a comment 7 days ago that I uploaded two new files to this pull request.
https://github.com/gprieck/NetTopologySuite/pull/1

ByteStreamProvider
ShapefileByteStreamProviderRegistry

Your patch is the first two files I uploaded 14 days ago (MemoryStreamProvider and
ShapefileMemoryStreamProviderRegistry).  Could you take a look at the two files I uploaded 7 days ago.  I think they correctly handle both reading and writing.

[ByteStreamProvider.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/175239/ByteStreamProvider.txt)
[ShapefileByteStreamProviderRegistry.txt](https://github.com/NetTopologySuite/NetTopologySuite/files/175240/ShapefileByteStreamProviderRegistry.txt)

**Comment by jaundice** [comment]
My patch removes the initial MemoryStreamProvider and adds a refactored ByteStreamProvider.

**Comment by FObermaier** [comment]
@gprieck, @jaundice: 
Could you please review the fix and then close the issue?

**Comment by gprieck** [comment]
I have not been able to get the patch to apply.

**Comment by DGuidi** [comment]
@gprieck you should checkout master branch

**Comment by FObermaier** [comment]
I think this is done.
