### ISSUE TITLE
Most of the NTS Nuget packages are out of date

### ISSUE THREAD

**Issue by ssram1603** [NetTopologySuite/NetTopologySuite#94]
Hi,

First of all I would like to thank you for such an amazing and useful library. But here are some things which I feel could be more useful.

I could see that most of the NTS Nuget packages are out of date because of which every time we have to pull the updated source from here and build. I understand that it won't be appropriate to publish package for each and every change but it's very complicated to follow the below process.

> 1. Check if any bug is already exists for the facing issue
> 2. If it's fixed then pull the source and build to get the updated assembly.
> 3. Update all assembly references in the solution.

Could anyone please let me know if there is any easy way to have updated assembly time to time else is it possible to update and publish the Nuget package for some essential functionality breakers like [#92](https://github.com/NetTopologySuite/NetTopologySuite/issues/92),  [#93](https://github.com/NetTopologySuite/NetTopologySuite/issues/93), [#69](https://github.com/NetTopologySuite/NetTopologySuite/issues/69)

Thanks
Sivaram K

**Comment by peetw** [comment]
I am also facing this problem - our project uses the lastest stable NuGet packages (1.14), but is affected by issue #100, which was fixed after the release. I see that there is a pre-release available (mainly due to the move to support .NET Standard), is there a plan to release a stable version in the near future?

**Comment by FObermaier** [comment]
You can consider the pre-release packages as stable, I'm only cleaning up the repositories and bring everything in line.
We won't be releasing a non-prerelease version until JTS 1.15 is out.

**Comment by xivk** [comment]
Discussion moved here: https://github.com/NetTopologySuite/NetTopologySuite/issues/179
