### ISSUE TITLE
GeoJsonReader is not working with GeoJson FeatureCollection having a "bbox" property

### ISSUE THREAD

**Issue by ssram1603** [NetTopologySuite/NetTopologySuite#95]
Hi,

I'm getting the below exception while trying to read a "GeoJson FeatureCollection" using the GeoJsonReader.

> Expected a property name. at NetTopologySuite.IO.Converters.FeatureCollectionConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

Here is my input GeoJson

`{  
   "type":"FeatureCollection",
   "features":[  
      {  
         "geometry":{  
            "type":"Point",
            "coordinates":[  
               -6.091861724853516,
               4.991835117340088
            ]
         },
         "type":"Feature",
         "properties":{  
            "prop1":[  
               "a",
               "b"
            ]
         },
         "id":1
      }
   ],
   "bbox":[  
      -8.599302291870117,
      4.357067108154297,
      -2.494896650314331,
      10.736641883850098
   ]
}`

I could see that "FeatureCollectionConverter" is not handling the "bbox"  property currently. Could anyone please let me know if this is as expected or an issue.

Thanks
Sivaram K

**Comment by ssram1603** [comment]
Thanks for the quick fix. I could be able to convert with out any exception. I have seen the below comment from the FeatureConverter.cs

>   case "bbox":
                        // Read, but can't do anything with it, assigning Envelopes is impossible without reflection
                        Envelope bbox = serializer.Deserialize<Envelope>(reader);
                        //Debug.WriteLine("BBOX: {0}", bbox.ToString());
                        break;

Why can't envelopes be added like Geometry, Id properties and will there be any future consideration as this will effect the round trip conversion between Geojson and NTS objects?

**Comment by DGuidi** [comment]
>why can't envelopes be added like Geometry,

NTS Feature doesn't have a `Envelope` property, but you can call `Geometry.Envelope`, so you strickly don't need to read JSON 'envelope', because NTS geometries can't use any information taken from it.
Maybe GeoJson serializer should serialize a NTS object to JSON adding (always?) an 'envelope' property: this can be helpful for external consumers.
My2Cents.

**Comment by FObermaier** [comment]
@DGuidi:
I'm looking into adding `BoundingBox` to both `Feature` and `FeatureCollection`. Those are assigned when present in the geojson definition, otherwise not.
`Feature` will have a static property that controls whether `BoundingBox` is computed upon access when not explicitly set.

**Comment by DGuidi** [comment]
@FObermaier ok. 
Only a suggestion: why not a readonly property `IFeature.Envelope` that returns  `Geometry.Envelope` or `Envelope.Empty`?  Do we really need to store envelope from a json? 
I'm not concerned about performances, but for data-consistency.
Anyway, feel free to change code as you wish.
