### ISSUE TITLE
WKBWriter.WriteHeader: Missing Case for LinearRing

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite#96]
[This block](https://github.com/NetTopologySuite/NetTopologySuite/blob/c1a1d4654aeba89ba7ce6c5678de006db3751aee/NetTopologySuite/IO/WKBWriter.cs#L118-L141) is missing a case for "[LinearRing](https://github.com/NetTopologySuite/NetTopologySuite/blob/c1a1d4654aeba89ba7ce6c5678de006db3751aee/NetTopologySuite/Geometries/LinearRing.cs#L89)", which causes WKBWriter to fail to write out a LinearRing geometry.

**Comment by DGuidi** [comment]
@airbreather @FObermaier fixed, but WKBReader now always reads "ring" geometries as linestrings (see test added with commit). Looks correct: I see that WKBGeometryTypes doesn't even have LinearRing type, so I suppose that maybe we can add a check (in WBBReader.ReadLineString) and build a LinearRing if the sequence is closed.

**Comment by DGuidi** [comment]
something like:
```
        protected IGeometry ReadLineString(BinaryReader reader, CoordinateSystem cs, int srid)
        {
            IGeometryFactory factory = _geometryServices.CreateGeometryFactory(_precisionModel, srid, _sequenceFactory);
            int numPoints = reader.ReadInt32();
            ICoordinateSequence sequence = ReadCoordinateSequenceLineString(reader, numPoints, cs);
            if (CoordinateSequences.IsRing(sequence))
                return factory.CreateLinearRing(sequence);
            return factory.CreateLineString(sequence);
        }

```
but I fear to introduce some performances penalties or side effects

**Comment by airbreather** [comment]
JTS [writes](https://github.com/dr-jts/jts/blob/f6187ee22aee29933c561284e1cb56df32fddcc0/modules/core/src/main/java/org/locationtech/jts/io/WKBWriter.java#L309-L311) LinearRings as LineStrings.

It [doesn't](https://github.com/dr-jts/jts/blob/f6187ee22aee29933c561284e1cb56df32fddcc0/modules/core/src/main/java/org/locationtech/jts/io/WKBReader.java#L197-L199) bother [doing](https://github.com/dr-jts/jts/blob/f6187ee22aee29933c561284e1cb56df32fddcc0/modules/core/src/main/java/org/locationtech/jts/io/WKBReader.java#L241-L246) anything special to read a LinearRing, and I don't think it really needs to -- from my understanding, the only reason someone would specifically need a LinearRing instead of a LineString is when it's a part of a Polygon, which NTS deals with just fine.

Other than the line in the test that I added a line comment for (which may be a nitpick), I think this is fine.  Closed.  Thank you.

**Comment by DGuidi** [comment]
ok, great. thanks to you for support.
