### ISSUE TITLE
Defect in KdTree.NearestNeighbor

### ISSUE THREAD

**Issue by ikolev21** [NetTopologySuite/NetTopologySuite#97]
Hello,

First of all, congratulations and best wishes for the great project.

I made some tests and found that `KdTree.NearestNeighbor` is not working correctly. I debugged the code, found the problem and fixed it, and also modified the algorithm a little to improve its performance.

Here's the unit test that I added to `KdTreeTest.cs`

        [Test]
        public void TestNearestNeighbor2()
        {
            var kd = new KdTree<string>();
            const int Count = 8;

            for (var row = 0; row < Count; ++row)
            {
                for (var column = 0; column < Count; ++column)
                {
                    kd.Insert(new Coordinate(column, row), (column * 100 + row).ToString());
                }
            }

            var testCoordinate = new Coordinate(Count / 2, Count / 2);
            var res = kd.NearestNeighbor(testCoordinate);

            Assert.AreEqual(testCoordinate, res.Coordinate);
        }

The returned result is 3,4 instead of the expected 4, 4.
I found that the smallest Count that exposes the problem is 8.
This was tested with the latest master branch.
I can provide a patch with my changes on request.

Best regards,
Ivan

**Comment by DGuidi** [comment]
@ikolev21 can you create a [pull request](https://help.github.com/articles/using-pull-requests/) with your changes? So we can check modifies and compare with jts code.

**Comment by ikolev21** [comment]
I don't have Git installed, I checked out the repository with TortoiseSvn. I don't want to install Git for now. So I suppose I cannot create a pull request. I can provide a patch.

For some reason attaching to this message wouldn't work, though I zipped the file as requested.
Here's a link to my Google drive:
https://drive.google.com/file/d/0B2MG4LKbRHikc215YWVHRXZtME0/view?usp=sharing

I couldn't figure out a better name for the test than TestNearestNeighbor2.

**Comment by DGuidi** [comment]
thanks hope to take a look soon

**Comment by DGuidi** [comment]
please can you check [revkdtree](https://github.com/NetTopologySuite/NetTopologySuite/compare/revkdtree) branch and validate my changes?
@FObermaier all tests are green, what do you think? Actually [i have no idea what i'm doing](https://goo.gl/rsLkGq)

**Comment by DGuidi** [comment]
moved to #105
